### ISSUE TITLE
qvm-block not recognizing that a certain VM is running

### ISSUE THREAD

**Issue by fowlslegs** [QubesOS/qubes-issues#1074]
I'm sometimes unable to attach block devices, at the end of this traceback it's being reported that the research VM is not running, however, it is and is being recognized as being started by qvm-ls as well.

    [ringminusone@dom0 ~]$ qvm-block -a research dom0:sdb1
    Traceback (most recent call last):
      File "/usr/bin/qvm-block", line 151, in <module>
        main()
      File "/usr/bin/qvm-block", line 105, in main
        block_attach(qvm_collection, vm, dev, **kwargs)
      File "/usr/lib64/python2.7/site-packages/qubes/qubesutils.py", line 408, in block_attach
        block_detach(attached_vm['vm'], attached_vm['frontend'])
      File "/usr/lib64/python2.7/site-packages/qubes/qubesutils.py", line 446, in block_detach
        vm.libvirt_domain.detachDevice(etree.tostring(disk, encoding='utf-8'))
      File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1095, in detachDevice
        if ret == -1: raise libvirtError ('virDomainDetachDevice() failed', dom=self)
    libvirt.libvirtError: Requested operation is not valid: Domain is not running

Edit: R3-rc1. I also tried formatting the USB and the error persisted.

**Comment by marmarek** [comment]
Already fixed in qubesos/qubes-core-admin@310ba9f1dfd0e70eeda01e6dcf740403bd722a13, package still in testing repo.
