### ISSUE TITLE
window errors because environment variable QT_X11_NO_MITSHM not set

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1172]
Environment variable `QT_X11_NO_MITSHM` is not set. This leads to severe issues. (Such as described in the commit message https://github.com/marmarek/qubes-gui-agent-linux/commit/a02e54b71a9ee17f4b10558065a8fc9deaf69984.) Commands such as `kdesudo kwrite` open only unusable windows (without visible content). Running `export QT_X11_NO_MITSHM=1` beforehand is a functional workaround.

Debug output...

-----

```
env
```

```
XDG_VTNR=7
SSH_AGENT_PID=1332
XDG_SESSION_ID=c2
GIO_LAUNCHED_DESKTOP_FILE_PID=3114
GPG_AGENT_INFO=/run/user/1000/keyring/gpg:0:1
SHELL=/bin/bash
TERM=xterm
H=768
KONSOLE_DBUS_SERVICE=:1.54
KONSOLE_PROFILE_NAME=Shell
QUBES_KEYMAP=xkb_keymap {
        xkb_keycodes { include "evdev+aliases(qwertz)"  };
        xkb_types { include "complete"  };
        xkb_compat { include "complete" };
        xkb_symbols { include "pc+de+inet(evdev)"       };
        xkb_geometry { include "pc(pc104)"      };
};
WINDOWID=10485782
QUBES_USER_KEYMAP=
SHELL_SESSION_ID=8d5cae7be789400095b9aef632333120
USER=user
LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.Z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.jpg=01;35:*.jpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.axv=01;35:*.anx=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.axa=00;36:*.oga=00;36:*.spx=00;36:*.xspf=00;36:
SSH_AUTH_SOCK=/run/user/1000/keyring/ssh
W=1280
GIO_LAUNCHED_DESKTOP_FILE=/usr/share/applications/kde4/konsole.desktop
MAIL=/var/mail/user
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/games:/usr/games
TORSOCKS_LOG_LEVEL=1
PWD=/home/user
UPDTYPE=UpdateableVM
KONSOLE_DBUS_WINDOW=/Windows/1
LANG=en_US.UTF-8
KDEDIRS=/usr/share/whonix-gw-kde-desktop-conf/:/usr/share/kde-dolphin-menubar-enable/:/usr/share/kde-sounds-off/:/usr/share/kde-privacy/:/usr/share/kde-no-move-max-win/:/usr/share/kde-mouse-doubleclick/:/usr/share/kde-lowfat/:/usr/share/kde-konsole-unlim-scrollback/:/usr/share/kde-kgpg-tweaks/:/usr/share/kde-common-resolution/:/usr/share/kde-apper-no-autoupdate/:/usr/share/anon-gw-kde-startmenu/:/usr/share/open-link-confirmation/:/usr/share/kde-power-savings-disable-in-vms/
QREXEC_AGENT_PID=3108
DEPTH=24
WHONIX=1
KONSOLE_DBUS_SESSION=/Sessions/2
HOME=/home/user
COLORFGBG=15;0
XDG_SEAT=seat0
SHLVL=4
LANGUAGE=
LOGNAME=user
DBUS_SESSION_BUS_ADDRESS=unix:abstract=/tmp/dbus-eKAvBE2Jvt,guid=0a9174836cb8120fa92d624955ec606e
VMTYPE=TemplateVM
BROWSER=/usr/lib/open_link_confirmation
WINDOWPATH=7
PROFILEHOME=
XDG_RUNTIME_DIR=/run/user/1000
DISPLAY=:0
MEM=3841
TOR_HIDE_BROWSER_LOGO=1
_=/usr/bin/env
OLDPWD=/etc/profile.d
```

-----

`/etc/X11/Xsession.d/20qt-x11-no-mitshm.sh` exists.
```
# Stops QT from using the MIT-SHM X11 Shared Memory Extension
export QT_X11_NO_MITSHM=1
```

-----

`/etc/profile.d/cat qt_x11_no_mitshm.sh` exists.
```
# Stops Qt form using the MIT-SHM X11 Shared Memory Extension
export QT_X11_NO_MITSHM=1
```

-----

`/etc/sudoers.d/qt_x11_no_mitshm` exists:
```
# Don't allow QT to used shared memory to prevent errors
Defaults env_keep += "QT_X11_NO_MITSHM"
```

-----

Why is the environment variable not set? Happens in a whonix-gw development version (that is build using no-recommends and minimal). Could it be because of some missing dependency?

**Comment by marmarek** [comment]
Just checked in standard Debian 7 and Debian 8 templates (updated to
current-testing) and `QT_X11_NO_MITSHM=1` is there. Anything interesting
in `~/.xsession-errors`?

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
Yes, looks like. I guess this is another manifestation of https://github.com/marmarek/qubes-core-agent-linux/pull/27. Trying reboot now.

```
user@host:~$ cat .xsession-errors 
```

```
X.Org X Server 1.16.4
Release Date: 2014-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux host 3.18.17-6.pvops.qubes.x86_64 #1 SMP Sat Aug 8 21:27:00 UTC 2015 x86_64
Kernel command line: root=/dev/mapper/dmroot ro nomodeset console=hvc0 rd_NO_PLYMOUTH 3 nopat
Build Date: 11 February 2015  12:32:02AM
xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.0.log", Time: Sun Sep  6 15:49:02 2015
(++) Using config file: "/etc/X11/xorg-qubes.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Xsession: X session started for user at Sun Sep  6 15:49:02 UTC 2015
xsettingsd: Loaded 17 settings from /home/user/.xsettingsd
xsettingsd: Created window 0x200001 on screen 0 with timestamp 221998
xsettingsd: Selection _XSETTINGS_S0 is owned by 0x0
xsettingsd: Took ownership of selection _XSETTINGS_S0
localuser:user being added to access control list
Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
                  Ignoring extra symbols
Warning:          Key <OUTP> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KITG> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KIDN> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KIUP> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <RO> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I192> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I193> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I194> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I195> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I196> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I255> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          No symbols defined for <AB11> (keycode 97)
Warning:          No symbols defined for <JPCM> (keycode 103)
Warning:          No symbols defined for <I120> (keycode 120)
Warning:          No symbols defined for <AE13> (keycode 132)
Warning:          No symbols defined for <I149> (keycode 149)
Warning:          No symbols defined for <I154> (keycode 154)
Warning:          No symbols defined for <I168> (keycode 168)
Warning:          No symbols defined for <I178> (keycode 178)
Warning:          No symbols defined for <I183> (keycode 183)
Warning:          No symbols defined for <I184> (keycode 184)
Warning:          No symbols defined for <FK19> (keycode 197)
Warning:          No symbols defined for <FK24> (keycode 202)
Warning:          No symbols defined for <I217> (keycode 217)
Warning:          No symbols defined for <I219> (keycode 219)
Warning:          No symbols defined for <I221> (keycode 221)
Warning:          No symbols defined for <I222> (keycode 222)
Warning:          No symbols defined for <I230> (keycode 230)
Warning:          No symbols defined for <I247> (keycode 247)
Warning:          No symbols defined for <I248> (keycode 248)
Warning:          No symbols defined for <I249> (keycode 249)
Warning:          No symbols defined for <I250> (keycode 250)
Warning:          No symbols defined for <I251> (keycode 251)
Warning:          No symbols defined for <I252> (keycode 252)
Warning:          No symbols defined for <I253> (keycode 253)
** Message: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory
Traceback (most recent call last):
  File "/usr/bin/qubes-session-autostart", line 28, in <module>
    from qubes.xdg import launch
  File "/usr/lib/python2.7/dist-packages/qubes/xdg.py", line 5, in <module>
    import dbus
ImportError: No module named dbus
Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
                  Ignoring extra symbols
Warning:          Key <OUTP> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KITG> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KIDN> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KIUP> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <RO> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I192> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I193> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I194> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I195> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I196> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I255> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          No symbols defined for <AB11> (keycode 97)
Warning:          No symbols defined for <JPCM> (keycode 103)
Warning:          No symbols defined for <I120> (keycode 120)
Warning:          No symbols defined for <AE13> (keycode 132)
Warning:          No symbols defined for <I149> (keycode 149)
Warning:          No symbols defined for <I154> (keycode 154)
Warning:          No symbols defined for <I168> (keycode 168)
Warning:          No symbols defined for <I178> (keycode 178)
Warning:          No symbols defined for <I183> (keycode 183)
Warning:          No symbols defined for <I184> (keycode 184)
Warning:          No symbols defined for <FK19> (keycode 197)
Warning:          No symbols defined for <FK24> (keycode 202)
Warning:          No symbols defined for <I217> (keycode 217)
Warning:          No symbols defined for <I219> (keycode 219)
Warning:          No symbols defined for <I221> (keycode 221)
Warning:          No symbols defined for <I222> (keycode 222)
Warning:          No symbols defined for <I230> (keycode 230)
Warning:          No symbols defined for <I247> (keycode 247)
Warning:          No symbols defined for <I248> (keycode 248)
Warning:          No symbols defined for <I249> (keycode 249)
Warning:          No symbols defined for <I250> (keycode 250)
Warning:          No symbols defined for <I251> (keycode 251)
Warning:          No symbols defined for <I252> (keycode 252)
Warning:          No symbols defined for <I253> (keycode 253)
executed (nowait) konsole pid 1372
send exit code 0
executed (nowait) konsole pid 1394
send exit code 0
executed (nowait) qubes-desktop-run /usr/share/applications/kde4/konsole.desktop pid 1422
send exit code 0
executed (nowait) qubes-desktop-run /usr/share/applications/kde4/konsole.desktop pid 1430
send exit code 0
executed qubes-desktop-run /usr/share/applications/kde4/konsole.desktop pid 1434
send exit code 1
pid 1434 exited with 1
executed qubes-desktop-run /usr/share/applications/kde4/konsole.desktop pid 2733
send exit code 0
pid 2733 exited with 0
executed (nowait) qubes-desktop-run /usr/share/applications/kde4/konsole.desktop pid 2807
send exit code 0
executed (nowait) qubes-desktop-run /usr/share/applications/gateway-torrc.desktop pid 2842
send exit code 0
executed (nowait) qubes-desktop-run /usr/share/applications/gateway-torrcexamples.desktop pid 2987
send exit code 0
executed (nowait) qubes-desktop-run /usr/share/applications/gpk-log.desktop pid 3001
send exit code 0
executed (nowait) qubes-desktop-run /usr/share/applications/gateway-firewall50user.desktop pid 3018
send exit code 0
executed (nowait) qubes-desktop-run /usr/share/applications/gateway-torrc.desktop pid 3041
send exit code 0
executed (nowait) qubes-desktop-run /usr/share/applications/gateway-torrc.desktop pid 3064
send exit code 0
executed qubes-desktop-run /usr/share/applications/gateway-torrc.desktop pid 3087
send exit code 0
pid 3087 exited with 0
executed (nowait) qubes-desktop-run /usr/share/applications/kde4/konsole.desktop pid 3110
send exit code 0
executed (nowait) qubes-desktop-run /usr/share/applications/gateway-firewall50user.desktop pid 4869
send exit code 0
executed kate pid 5122
send exit code 127
pid 5122 exited with 127
executed kwrite pid 5125
send exit code 0
pid 5125 exited with 0
executed qubes-desktop-run /usr/share/applications/gateway-torrc.desktop pid 5134
send exit code 0
pid 5134 exited with 0
executed qubes-desktop-run /usr/share/applications/gateway-torrc.desktop pid 5379
send exit code 0
pid 5379 exited with 0
executed (nowait) qubes-desktop-run /usr/share/applications/gateway-torrc.desktop pid 5709
send exit code 0
```

**Comment by adrelanos** [comment]
No, that wasn't it.

**Comment by marmarek** [comment]
Failure of `/usr/bin/qubes-session-autostart` shouldn't result in
missing environment variable - it is responsible only for loading apps
from /etc/xdg/autostart. `/etc/X11/Xsession.d/` is processed earlier.

-- 
Best Regards,
Marek Marczykowski-Górecki
Invisible Things Lab
A: Because it messes up the order in which people normally read text.
Q: Why is top-posting such a bad thing?

**Comment by adrelanos** [comment]
`/usr/bin/qubes-session-autostart` no longer fails after manually installing the python-dbus package.

Environment variable `QT_X11_NO_MITSHM` not set.

Here is a new `.xsession-errors`. Does it contain something related/problematic?

What about...

> ** Message: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory

Does it matter?

```
user@host:~$ cat .xsession-errors
```
```
X.Org X Server 1.16.4
Release Date: 2014-12-20
X Protocol Version 11, Revision 0
Build Operating System: Linux 3.16.0-4-amd64 x86_64 Debian
Current Operating System: Linux host 3.18.17-6.pvops.qubes.x86_64 #1 SMP Sat Aug 8 21:27:00 UTC 2015 x86_64
Kernel command line: root=/dev/mapper/dmroot ro nomodeset console=hvc0 rd_NO_PLYMOUTH 3 nopat
Build Date: 11 February 2015  12:32:02AM
xorg-server 2:1.16.4-1 (http://www.debian.org/support) 
Current version of pixman: 0.32.6
        Before reporting problems, check http://wiki.x.org
        to make sure that you have the latest version.
Markers: (--) probed, (**) from config file, (==) default setting,
        (++) from command line, (!!) notice, (II) informational,
        (WW) warning, (EE) error, (NI) not implemented, (??) unknown.
(++) Log file: "/tmp/Xorg.0.log", Time: Sun Sep  6 20:35:45 2015
(++) Using config file: "/etc/X11/xorg-qubes.conf"
(==) Using system config directory "/usr/share/X11/xorg.conf.d"
Xsession: X session started for user at Sun Sep  6 20:35:45 UTC 2015
xsettingsd: Loaded 17 settings from /home/user/.xsettingsd
xsettingsd: Created window 0x200001 on screen 0 with timestamp 3032
xsettingsd: Selection _XSETTINGS_S0 is owned by 0x0
xsettingsd: Took ownership of selection _XSETTINGS_S0
localuser:user being added to access control list
Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
                  Ignoring extra symbols
Warning:          Key <OUTP> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KITG> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KIDN> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KIUP> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <RO> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I192> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I193> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I194> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I195> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I196> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I255> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          No symbols defined for <AB11> (keycode 97)
Warning:          No symbols defined for <JPCM> (keycode 103)
Warning:          No symbols defined for <I120> (keycode 120)
Warning:          No symbols defined for <AE13> (keycode 132)
Warning:          No symbols defined for <I149> (keycode 149)
Warning:          No symbols defined for <I154> (keycode 154)
Warning:          No symbols defined for <I168> (keycode 168)
Warning:          No symbols defined for <I178> (keycode 178)
Warning:          No symbols defined for <I183> (keycode 183)
Warning:          No symbols defined for <I184> (keycode 184)
Warning:          No symbols defined for <FK19> (keycode 197)
Warning:          No symbols defined for <FK24> (keycode 202)
Warning:          No symbols defined for <I217> (keycode 217)
Warning:          No symbols defined for <I219> (keycode 219)
Warning:          No symbols defined for <I221> (keycode 221)
Warning:          No symbols defined for <I222> (keycode 222)
Warning:          No symbols defined for <I230> (keycode 230)
Warning:          No symbols defined for <I247> (keycode 247)
Warning:          No symbols defined for <I248> (keycode 248)
Warning:          No symbols defined for <I249> (keycode 249)
Warning:          No symbols defined for <I250> (keycode 250)
Warning:          No symbols defined for <I251> (keycode 251)
Warning:          No symbols defined for <I252> (keycode 252)
Warning:          No symbols defined for <I253> (keycode 253)
** Message: couldn't access control socket: /run/user/1000/keyring/control: No such file or directory

** (nm-applet:1164): WARNING **: Error retrieving accessibility bus address: org.freedesktop.DBus.Error.ServiceUnknown: The name org.a11y.Bus was not provided by any .service files
Warning:          Type "ONE_LEVEL" has 1 levels, but <RALT> has 2 symbols
                  Ignoring extra symbols
Warning:          Key <OUTP> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KITG> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KIDN> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <KIUP> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <RO> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I192> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I193> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I194> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I195> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I196> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          Key <I255> not found in evdev+aliases(qwertz) keycodes
                  Symbols ignored
Warning:          No symbols defined for <AB11> (keycode 97)
Warning:          No symbols defined for <JPCM> (keycode 103)
Warning:          No symbols defined for <I120> (keycode 120)
Warning:          No symbols defined for <AE13> (keycode 132)
Warning:          No symbols defined for <I149> (keycode 149)
Warning:          No symbols defined for <I154> (keycode 154)
Warning:          No symbols defined for <I168> (keycode 168)
Warning:          No symbols defined for <I178> (keycode 178)
Warning:          No symbols defined for <I183> (keycode 183)
Warning:          No symbols defined for <I184> (keycode 184)
Warning:          No symbols defined for <FK19> (keycode 197)
Warning:          No symbols defined for <FK24> (keycode 202)
Warning:          No symbols defined for <I217> (keycode 217)
Warning:          No symbols defined for <I219> (keycode 219)
Warning:          No symbols defined for <I221> (keycode 221)
Warning:          No symbols defined for <I222> (keycode 222)
Warning:          No symbols defined for <I230> (keycode 230)
Warning:          No symbols defined for <I247> (keycode 247)
Warning:          No symbols defined for <I248> (keycode 248)
Warning:          No symbols defined for <I249> (keycode 249)
Warning:          No symbols defined for <I250> (keycode 250)
Warning:          No symbols defined for <I251> (keycode 251)
Warning:          No symbols defined for <I252> (keycode 252)
Warning:          No symbols defined for <I253> (keycode 253)
Starting aa-notify
executed (nowait) konsole pid 1284
send exit code 0
```

**Comment by adrelanos** [comment]
The fact, that other environment variables configured in `/etc/X11/Xsession.d/` made be curious. After renaming the files, the issue was solved.

* `/etc/X11/Xsession.d/20qt-gnome-desktop-session-id.sh` -> `/etc/X11/Xsession.d/20qt-gnome-desktop-session-id`
* `/etc/X11/Xsession.d/qt-x11-no-mitshm.sh` -> `/etc/X11/Xsession.d/qt-x11-no-mitshm`

Looks like Debian doesn't like the `.sh` file extension. I assume Fedora also works without the `.sh` extension, because `90qubes-keymap` also does not use the `.sh` file extension.

**Comment by adrelanos** [comment]
@nrgaway
