### ISSUE TITLE
Unclear error message while creating HVM but without hardware support for it (VT-x)

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1198]
[The error is](https://groups.google.com/d/msgid/qubes-users/f3d81f15-da9d-46b7-ad1f-5f1871aba700%40googlegroups.com):
> [aaa@dom0 ~]$ qvm-create windows7 --hvm --label green
--> Creating directory: /var/lib/qubes/appvms/windows7
--> Creating volatile image: /var/lib/qubes/appvms/windows7/volatile.img...
--> Creating icon symlink: /var/lib/qubes/appvms/windows7/icon.png -> /usr/share
/icons/hicolor/128x128/devices/appvm-green.png
Traceback (most recent call last):
 File "/usr/bin/qvm-create", line 210, in <module>
   main()
 File "/usr/bin/qvm-create", line 188, in main
   vm.create_on_disk(verbose=options.verbose, source_template=template)
 File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 21
8, in create_on_disk
   self._update_libvirt_domain()
 File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 71
4, in _update_libvirt_domain
   self._libvirt_domain = vmm.libvirt_conn.defineXML(domain_config)
 File "/usr/lib64/python2.7/site-packages/libvirt.py", line 3541, in defineXML
   if ret is None:raise libvirtError('virDomainDefineXML() failed', conn=self)
libvirt.libvirtError: неизвестный тип ОС hvm
[aaa@dom0 ~]$
___________________________________________________________
Note: "неизвестный тип ОС hvm" - "unknown type of OS hvm"

**Comment by marmarek** [comment]
Additionally VM directory should be deleted after failed VM creation. Otherwise further attempts will fail.
