### ISSUE TITLE
tests: ERROR in tearDownClass crashes test runner

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1370]
```
Traceback (most recent call last):
  File "/usr/lib64/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/usr/lib64/python2.7/site-packages/qubes/tests/run.py", line 362, in <module>
    sys.exit(not main())
  File "/usr/lib64/python2.7/site-packages/qubes/tests/run.py", line 358, in main
    return runner.run(suite).wasSuccessful()
  File "/usr/lib64/python2.7/unittest/runner.py", line 151, in run
    test(result)
  File "/usr/lib64/python2.7/unittest/suite.py", line 70, in __call__
    return self.run(*args, **kwds)
  File "/usr/lib64/python2.7/unittest/suite.py", line 98, in run
    self._tearDownPreviousClass(test, result)
  File "/usr/lib64/python2.7/unittest/suite.py", line 247, in _tearDownPreviousClass
    self._addClassOrModuleLevelException(result, e, errorName)
  File "/usr/lib64/python2.7/unittest/suite.py", line 198, in _addClassOrModuleLevelException
    result.addError(error, sys.exc_info())
  File "/usr/lib64/python2.7/site-packages/qubes/tests/run.py", line 137, in addError
    test.log.critical('ERROR ({err[0].__name__}: {err[1]!r})'.format(err=err))
AttributeError: '_ErrorHolder' object has no attribute 'log'
```

**Comment by marmarek** [comment]
Fixed here: https://github.com/QubesOS/qubes-core-admin/commit/be00d15d99926e4ea1bfd32ad5b65556d1955893
