### ISSUE TITLE
icon-sender crash

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1497]
```
icon-sender:111:send_icon:IndexError: list index out of range

Traceback (most recent call last):
  File "/usr/lib/qubes/icon-sender", line 151, in <module>
    retriever.watch_and_send_icons()
  File "/usr/lib/qubes/icon-sender", line 146, in watch_and_send_icons
    self.send_icon(ev.window)
  File "/usr/lib/qubes/icon-sender", line 111, in send_icon
    1] < ICON_MAX_SIZE])[-1]
IndexError: list index out of range

Local variables in innermost frame:
k: (132, 185)
self: <__main__.IconRetriever object at 0x7fd2ee0e3510>
w: 33554440
```

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.3-1.fc21` has been pushed to the `r3.1` testing repository for the Fedora `fc21` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.3-1.fc22` has been pushed to the `r3.1` testing repository for the Fedora `fc22` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.3-1.fc23` has been pushed to the `r3.1` testing repository for the Fedora `fc23` template.
To test this update, please install it with the following command:
```
sudo yum update --enablerepo=qubes-vm-r3.1-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.3+deb8u1` has been pushed to the `r3.1` testing repository for the Debian `jessie` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `jessie-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/R3.1-rc1...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.3+deb9u1` has been pushed to the `r3.1` testing repository for the Debian `stretch` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `stretch-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.3+deb7u1` has been pushed to the `r3.1` testing repository for the Debian `wheezy` template.
To test this update, first enable the testing repository in `/etc/apt/sources.list.d/qubes-*.list` by uncommenting the line containing `wheezy-testing`, then use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...d2ce71b29ac19610acf1abed4dc7be03e69b4c66

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.4-1.fc21` has been pushed to the `r3.1` stable repository for the Fedora `fc21` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...f29a7925bbcc8797c480f59d19dca5f7061fab9b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.4-1.fc22` has been pushed to the `r3.1` stable repository for the Fedora `fc22` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...f29a7925bbcc8797c480f59d19dca5f7061fab9b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-vm-3.1.4-1.fc23` has been pushed to the `r3.1` stable repository for the Fedora `fc23` template.
To install this update, please use the standard update command:
```
sudo yum update
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/26587e3c82eb51c0193c7370ba1c933f99ef9364...f29a7925bbcc8797c480f59d19dca5f7061fab9b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.4+deb8u1` has been pushed to the `r3.1` stable repository for the Debian `jessie` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/R3.1-rc1...f29a7925bbcc8797c480f59d19dca5f7061fab9b

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-gui-agent_3.1.4+deb7u1` has been pushed to the `r3.1` stable repository for the Debian `wheezy` template.
To install this update, please use the standard update command:
```
sudo apt-get update && sudo apt-get dist-upgrade
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-gui-agent-linux/compare/R3.1-rc1...f29a7925bbcc8797c480f59d19dca5f7061fab9b
