### ISSUE TITLE
qvm-revert-template-changes fails for HVM template.

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1573]
https://groups.google.com/d/msgid/qubes-users/3e9bd2ab-aab8-407e-9e03-27bd48aa6c7a%40googlegroups.com
> Trying to revert a HVM template in Qubes R3.1 RC1 I get this error message:

> ```
[user@dom0 ~]$ sudo qvm-revert-template-changes winxp
Traceback (most recent call last):
  File "/bin/qvm-revert-template-changes", line 142, in <module>
    main()
  File "/bin/qvm-revert-template-changes", line 66, in main
    oldcow_img = vm.rootcow_img + '.old'
TypeError: unsupported operand type(s) for +: 'instancemethod' and 'str'

> 'vm.rootcow_image' is not a string but: <bound method QubesTemplateHVm.rootcow_img of
<QubesTemplateHVm at 0x181edd0 qid=36 name='winxp'>>, so string concatenation fails.
```

> I don't get this error if the vm is a normal PV template.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.9-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/ba0d60595eab2e348d296d20840e6d366c160d3b...301eed55b31714ea500de9eb4e5c2ee799b03bf4

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.10-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/36134c8c43c0ff8dd45d9cd29d0f4b0539352c18...46a338d0879410debda8e3e073024fefe87a4704
