### ISSUE TITLE
qmemman crash

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1601]
https://groups.google.com/d/msgid/qubes-users/07116d70-aca0-409d-9054-4c7ced9f462a%40googlegroups.com
> I did an update from qubes-dom0-current-testing. There seems to be a problem with HVMs. When
trying to start Windows I get this:

> ```
--> Loading the VM (type = TemplateHVM)...
Traceback (most recent call last):
  File "/usr/bin/qvm-start", line 131, in <module>
    main()
  File "/usr/bin/qvm-start", line 115, in main
    xid = vm.start(verbose=options.verbose, preparing_dvm=options.preparing_dvm, start_guid=not
options.noguid, notify_function=tray_notify_generic if options.tray else None)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/02QubesTemplateHVm.py", line 94, in sta
rt
    return super(QubesTemplateHVm, self).start(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/01QubesHVm.py", line 326, in start
    return super(QubesHVm, self).start(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1876, in start
    self.libvirt_domain.createWithFlags(libvirt.VIR_DOMAIN_START_PAUSED)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 1059, in createWithFlags
    if ret == -1: raise libvirtError ('virDomainCreateWithFlags() failed', dom=self)
libvirt.libvirtError: internal error: libxenlight failed to create new domain 'win7-x64'
```
> After that I can't start ANY VM without first rebooting Qubes:
Starting a HVM template:
```
--> Loading the VM (type = TemplateHVM)...
ERROR: ERROR: Failed to connect to qmemman: [Errno 111] Connection refused
```
> Starting a PV template:
```
--> Loading the VM (type = TemplateVM)...
ERROR: ERROR: Failed to connect to qmemman: [Errno 111] Connection refused
```
> Starting a normal VM:
```
--> Creating volatile image: /var/lib/qubes/appvms/untrusted/volatile.img...
--> Loading the VM (type = AppVM)...
ERROR: ERROR: Failed to connect to qmemman: [Errno 111] Connection refused
```

**Comment by marmarek** [comment]
For example #1602 trigger this issue.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.10-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/301eed55b31714ea500de9eb4e5c2ee799b03bf4...46a338d0879410debda8e3e073024fefe87a4704

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.10-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/36134c8c43c0ff8dd45d9cd29d0f4b0539352c18...46a338d0879410debda8e3e073024fefe87a4704
