### ISSUE TITLE
DispVM not cleaned up when it shutdown itself

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#1660]
https://groups.google.com/d/msgid/qubes-users/74e4778f-09b1-4f37-8cfc-e858538e0f85%40googlegroups.com
> This is how I can reliably reproduce the bug:
* Use a customized DVM.
* Start a DVM in dom0.
* qvm-run disp* poweroff

> Then the DVM remains among my appvms and following error gets logged in dom0,
~./xsession-errors:

> ```
Traceback (most recent call last):
  File "/usr/lib/qubes/qfile-daemon-dvm", line 185, in <module>
    main()
  File "/usr/lib/qubes/qfile-daemon-dvm", line 182, in main
    dispvm.force_shutdown()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 1987, in force_shu
tdown
    raise QubesException ("VM already stopped!")
qubes.qubes.QubesException: VM already stopped!
```
> Sometimes this happens without calling `poweroff` in disp* but I don't know why.

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.12-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/04415e13fed0e15539419ec930ae1046e4f2fcd7...ae848d536958b2064ec96f96ad96540162cb4683

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.12-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/04415e13fed0e15539419ec930ae1046e4f2fcd7...ae848d536958b2064ec96f96ad96540162cb4683

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.28-1.fc20` has been pushed to the `r3.0` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/b25c3f05c7c93e397cd2639e533c089bf5e140fb...d29c2889b0744d57c51ce9b14d87a411c3d84dfa

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.0.28-1.fc20` has been pushed to the `r3.0` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/444d602d88cc7e079a550ff8da18901fac472781...d29c2889b0744d57c51ce9b14d87a411c3d84dfa
