### ISSUE TITLE
qubes-builder ./setup fails - dialog

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#1920]
```
user@qubes-build:~/qubes-builder$ ./setup 




































Traceback (most recent call last):
  File "./setup", line 1919, in <module>
    main(sys.argv)
  File "./setup", line 1902, in main
    Wizard(DialogUI(), **args)()
  File "./setup", line 1194, in __call__
    self.set_release()
  File "./setup", line 1362, in set_release
    self.release = str(self.ui.release(**info))  # pylint: disable=W0201
  File "./setup", line 554, in release
    return cls.radiolist(**info)
  File "./setup", line 544, in radiolist
    code, tag = cls.dialog.radiolist(**default)
  File "/home/user/qubes-builder/libs/dialog.py", line 3267, in radiolist
    (code, output) = self._perform(cmd, **kwargs)
  File "/home/user/qubes-builder/libs/dialog.py", line 1757, in _perform
    child_output_rfd)
  File "/home/user/qubes-builder/libs/dialog.py", line 1702, in _wait_for_program_termination
    child_output.strip()))
dialog.DialogError
```

**Comment by adrelanos** [comment]
I could work around this bug by starting with a fresh qubes-builder source folder from a new git clone. make clean-all and switching to latest qubes-builder git master did not help. I still keep the old qubes-builder source folder in case you wish to debug this.

**Comment by unman** [comment]
@adrelanos @andrewdavidwong Is there any point in keeping this open after 3 years?

**Comment by andrewdavidwong** [comment]
Closing this for now due to the prolonged lack of activity. If you believe this is a mistake, or if anyone would like this issue to remain open, please leave a comment, and we'll be happy to reopen this. Thank you.
