### ISSUE TITLE
[R3.2-rc3] Removing templates does not remove them from /var/lib/qubes/qubes.xml

### ISSUE THREAD

**Issue by Chilinot** [QubesOS/qubes-issues#2290]
#### Qubes OS version (e.g., `R3.1`):
R3.2-rc3

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
All default.

---

### Expected behavior:
The entries for the templates to be removed from the "/var/lib/qubes/qubes.xml" file.

### Actual behavior:
The entries are still there forcing me to manually remove them in order to install my backup copies.

### Steps to reproduce the behavior:
My steps:
1. Clean install of R3.2-rc3.
2. Choose "configure nothing" at first boot.
3. Use "sudo yum remove qubes-template*" to remove all installed default templates.
4. Check qubes manager. The templates are still listed. This is persistent across reboots.

### General notes:
This blocks me from re-installing the templates from my backup because Qubes thinks they are already installed.

By manually removing the entries in the .xml file i was able to restore my backups.

I do not know if there are any other residual data still on the laptop that did not get removed when the templates where removed by command. I have not found any issues now, but there might be some.

---

**Comment by andrewdavidwong** [comment]
Does yum/dnf indicate that the packages were removed successfully, or not?

**Comment by Chilinot** [comment]
Yes, yum/dnf was successful in removing the packages. There were some
errors in the output for all packages though. I have a copy of all output
but am currently unable to access it. I will post the contents asap.

Den 4 sep. 2016 01:06 skrev "Andrew David Wong" <notifications@github.com>:

**Comment by Chilinot** [comment]
Output from removing the templates:
```
[lucas@dom0 ~]$ sudo yum search qubes-template*
Redirecting to '/usr/bin/dnf search qubes-template*' (see 'man yum2dnf')

Failed to synchronize cache for repo 'qubes-dom0-cached', disabling.
========================= N/S Matched: qubes-template* =========================
qubes-template-debian-8.noarch : Qubes template for debian-8
qubes-template-fedora-23.noarch : Qubes template for fedora-23
qubes-template-whonix-gw.noarch : Qubes template for whonix-gw
qubes-template-whonix-ws.noarch : Qubes template for whonix-ws
[lucas@dom0 ~]$ sudo yum remove qubes-template*
Redirecting to '/usr/bin/dnf remove qubes-template*' (see 'man yum2dnf')

Dependencies resolved.
================================================================================
 Package                     Arch      Version               Repository    Size
================================================================================
Removing:
 qubes-template-debian-8     noarch    3.0.6-201608090120    @anaconda    1.9 G
 qubes-template-fedora-23    noarch    3.0.6-201608081228    @anaconda    3.3 G
 qubes-template-whonix-gw    noarch    3.0.6-201608050041    @anaconda    1.9 G
 qubes-template-whonix-ws    noarch    3.0.6-201608050146    @anaconda    2.3 G

Transaction Summary
================================================================================
Remove  4 Packages

Installed size: 9.4 G
Is this ok [y/N]: y
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
A VM with the name 'whonix-ws-dvm' does not exist in the system.
Traceback (most recent call last):
  File "/bin/qvm-remove", line 107, in <module>
    main()
  File "/bin/qvm-remove", line 85, in main
    vm.libvirt_domain.undefine()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 764, in libvirt_domain
    self._libvirt_domain = vmm.libvirt_conn.lookupByName(self.name)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4066, in lookupByName
    if ret is None:raise libvirtError('virDomainLookupByName() failed', conn=self)
libvirt.libvirtError: Domain not found
error: %preun(qubes-template-whonix-ws-3.0.6-201608050146.noarch) scriptlet failed, exit status 1
Error in PREUN scriptlet in rpm package qubes-template-whonix-ws
Error in PREUN scriptlet in rpm package qubes-template-whonix-ws
  Erasing     : qubes-template-whonix-ws-3.0.6-201608050146.noarch          1/4 
warning: file /var/lib/qubes/vm-templates/whonix-ws/root.img.part.02: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/whonix-ws/root.img.part.01: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/whonix-ws/root.img.part.00: remove failed: No such file or directory
A VM with the name 'whonix-gw-dvm' does not exist in the system.
Traceback (most recent call last):
  File "/bin/qvm-remove", line 107, in <module>
    main()
  File "/bin/qvm-remove", line 85, in main
    vm.libvirt_domain.undefine()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 764, in libvirt_domain
    self._libvirt_domain = vmm.libvirt_conn.lookupByName(self.name)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4066, in lookupByName
    if ret is None:raise libvirtError('virDomainLookupByName() failed', conn=self)
libvirt.libvirtError: Domain not found
error: %preun(qubes-template-whonix-gw-3.0.6-201608050041.noarch) scriptlet failed, exit status 1
Error in PREUN scriptlet in rpm package qubes-template-whonix-gw
Error in PREUN scriptlet in rpm package qubes-template-whonix-gw
  Erasing     : qubes-template-whonix-gw-3.0.6-201608050041.noarch          2/4 
warning: file /var/lib/qubes/vm-templates/whonix-gw/root.img.part.01: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/whonix-gw/root.img.part.00: remove failed: No such file or directory
A VM with the name 'fedora-23-dvm' does not exist in the system.
Traceback (most recent call last):
  File "/bin/qvm-remove", line 107, in <module>
    main()
  File "/bin/qvm-remove", line 85, in main
    vm.libvirt_domain.undefine()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 764, in libvirt_domain
    self._libvirt_domain = vmm.libvirt_conn.lookupByName(self.name)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4066, in lookupByName
    if ret is None:raise libvirtError('virDomainLookupByName() failed', conn=self)
libvirt.libvirtError: Domain not found
error: %preun(qubes-template-fedora-23-3.0.6-201608081228.noarch) scriptlet failed, exit status 1
Error in PREUN scriptlet in rpm package qubes-template-fedora-23
Error in PREUN scriptlet in rpm package qubes-template-fedora-23
  Erasing     : qubes-template-fedora-23-3.0.6-201608081228.noarch          3/4 
warning: file /var/lib/qubes/vm-templates/fedora-23/root.img.part.03: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/fedora-23/root.img.part.02: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/fedora-23/root.img.part.01: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/fedora-23/root.img.part.00: remove failed: No such file or directory
A VM with the name 'debian-8-dvm' does not exist in the system.
Traceback (most recent call last):
  File "/bin/qvm-remove", line 107, in <module>
    main()
  File "/bin/qvm-remove", line 85, in main
    vm.libvirt_domain.undefine()
  File "/usr/lib64/python2.7/site-packages/qubes/modules/000QubesVm.py", line 764, in libvirt_domain
    self._libvirt_domain = vmm.libvirt_conn.lookupByName(self.name)
  File "/usr/lib64/python2.7/site-packages/libvirt.py", line 4066, in lookupByName
    if ret is None:raise libvirtError('virDomainLookupByName() failed', conn=self)
libvirt.libvirtError: Domain not found
error: %preun(qubes-template-debian-8-3.0.6-201608090120.noarch) scriptlet failed, exit status 1
Error in PREUN scriptlet in rpm package qubes-template-debian-8
Error in PREUN scriptlet in rpm package qubes-template-debian-8
  Erasing     : qubes-template-debian-8-3.0.6-201608090120.noarch           4/4 
warning: file /var/lib/qubes/vm-templates/debian-8/root.img.part.01: remove failed: No such file or directory
warning: file /var/lib/qubes/vm-templates/debian-8/root.img.part.00: remove failed: No such file or directory
  Verifying   : qubes-template-debian-8-3.0.6-201608090120.noarch           1/4 
  Verifying   : qubes-template-fedora-23-3.0.6-201608081228.noarch          2/4 
  Verifying   : qubes-template-whonix-gw-3.0.6-201608050041.noarch          3/4 
  Verifying   : qubes-template-whonix-ws-3.0.6-201608050146.noarch          4/4 

Removed:
  qubes-template-debian-8.noarch 3.0.6-201608090120                             
  qubes-template-fedora-23.noarch 3.0.6-201608081228                            
  qubes-template-whonix-gw.noarch 3.0.6-201608050041                            
  qubes-template-whonix-ws.noarch 3.0.6-201608050146                            

Complete!
[lucas@dom0 ~]$ 
```

**Comment by Chilinot** [comment]
And it appears i misspoke, there were some errors when restoring the backups. But the restored VM's appears to be working fine.

Errors after restoring backups:
```
Extracting data: 123.2 GiB to restore
-> Restoring QubesTemplateVm fedora-23...
*** Directory /var/lib/qubes/vm-templates/fedora-23 already exists! It has been moved to /var/lib/qubes/vm-templates/fedora-23FOI8_T
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesTemplateVm whonix-gw...
*** Directory /var/lib/qubes/vm-templates/whonix-gw already exists! It has been moved to /var/lib/qubes/vm-templates/whonix-gw9RhVL7
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesTemplateVm debian-8...
*** Directory /var/lib/qubes/vm-templates/debian-8 already exists! It has been moved to /var/lib/qubes/vm-templates/debian-8WPKCVu
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesTemplateVm kali...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesTemplateVm whonix-ws...
*** Directory /var/lib/qubes/vm-templates/whonix-ws already exists! It has been moved to /var/lib/qubes/vm-templates/whonix-wsBcTWUN
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesProxyVm sys-firewall...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesProxyVm sys-whonix...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesNetVm sys-net...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesHVm win7...
-> Restoring QubesAppVm git...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesAppVm spotify...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesAppVm personal...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesAppVm dev...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesAppVm haxxor...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesAppVm anon-whonix...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesAppVm web...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesAppVm vault...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesAppVm mail...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring QubesAppVm encore...
WARNING: Kernel 4.1.24-10 not installed, using default one
-> Restoring home of user 'lucas'...
--> Existing files/dirs backed up in 'home-pre-restore-2016-09-04-213512' dir
-> Done. Please install updates for all the restored templates.
Please unmount your backup volume and cancel the file selection dialog.
Finished with errors!
```

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.10-1.fc23` has been pushed to the `r3.2` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/0e24d803f5cdf563c2e9dd4b7280f9d3771ba45a...a4db742077add71221518dbb47853b44d414a173

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.2.10-1.fc23` has been pushed to the `r3.2` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/0e24d803f5cdf563c2e9dd4b7280f9d3771ba45a...a4db742077add71221518dbb47853b44d414a173

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` testing repository for dom0.
To test this update, please install it with the following command:
```
sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing
```
[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e

**Comment by marmarek** [comment]
**Automated announcement from [builder-github]**

The package `qubes-core-dom0-3.1.18-1.fc20` has been pushed to the `r3.1` stable repository for dom0.
To install this update, please use the standard update command:
```
sudo qubes-dom0-update
```
Or update dom0 via Qubes Manager.

[Changes included in this update][commits]

[builder-github]: https://github.com/QubesOS/qubes-builder-github
[commits]: https://github.com/QubesOS/qubes-core-admin/compare/d8093f38c428e4a9e7be421f2dc57e0a45a19477...d315daf86a97b8ec899df237fcd8af76e223b91e
