### ISSUE TITLE
qubesd crash on libvirt event

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2806]
```
Exception in callback None()
handle: <Handle cancelled>
Traceback (most recent call last):
  File "/usr/lib64/python3.5/asyncio/events.py", line 126, in _run
    self._callback(*self._args)
  File "/usr/lib64/python3.5/site-packages/libvirtaio.py", line 99, in _handle
    for callback in self.callbacks.values():
RuntimeError: dictionary changed size during iteration
```

**Comment by marmarek** [comment]
Duplicate of #2805
