### ISSUE TITLE
qubesadmin: app.add_new_vm fails with (..., template=qubesadmin.DEFAULT)

### ISSUE THREAD

**Issue by woju** [QubesOS/qubes-issues#2886]
```
Jul 06 14:04:22 dom0 qubesd[12586]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Create.AppVM' dest=b'dom0' arg=b'<o
Jul 06 14:04:22 dom0 qubesd[12586]: Traceback (most recent call last):
Jul 06 14:04:22 dom0 qubesd[12586]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 257, in respond
Jul 06 14:04:22 dom0 qubesd[12586]:     untrusted_payload=untrusted_payload)
Jul 06 14:04:22 dom0 qubesd[12586]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 380, in __iter__
Jul 06 14:04:22 dom0 qubesd[12586]:     yield self  # This tells Task to wait for completion.
Jul 06 14:04:22 dom0 qubesd[12586]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 304, in _wakeup
Jul 06 14:04:22 dom0 qubesd[12586]:     future.result()
Jul 06 14:04:22 dom0 qubesd[12586]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 293, in result
Jul 06 14:04:22 dom0 qubesd[12586]:     raise self._exception
Jul 06 14:04:22 dom0 qubesd[12586]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
Jul 06 14:04:22 dom0 qubesd[12586]:     result = coro.send(None)
Jul 06 14:04:22 dom0 qubesd[12586]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 213, in coro
Jul 06 14:04:22 dom0 qubesd[12586]:     res = yield from res
Jul 06 14:04:22 dom0 qubesd[12586]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 829, in _vm_create
Jul 06 14:04:22 dom0 qubesd[12586]:     assert self.arg in self.app.domains
Jul 06 14:04:22 dom0 qubesd[12586]: AssertionError
```

Cc: @marmarek

**Comment by marmarek** [comment]
Fixed in QubesOS/qubes-core-admin-client@e6149b09
