### ISSUE TITLE
Devices widget print errors when creating new VM

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#2893]
#### Qubes OS version (e.g., `R3.2`): R4.0

Creating new VM cause devices widget to print a lot of:
```
ERROR:dbus.connection:Exception in handler for D-Bus signal:
Traceback (most recent call last):
  File "/usr/lib64/python3.5/site-packages/dbus/connection.py", line 230, in maybe_handle_message
    self._handler(*args, **kwargs)
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 154, in add_vm
    self._add_vm(vm)
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 147, in _add_vm
    menu_item = DomainMenuItem(self.data, vm)
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 86, in __init__
    self._hbox = self._create_hbox()
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 93, in _create_hbox
    label = Gtk.Label(self.vm.name, xalign=0)
AttributeError: 'NoneType' object has no attribute 'name'
```
The widget seems to remain functional after that.

Command used to create VM:
```
qvm-create -t debian-8 -l red d8test
```

**Comment by kalkin** [comment]
will fix that

**Comment by kalkin** [comment]
I can't reproduce that. 😩 Is it still reproducable on your machine?

**Comment by marmarek** [comment]
No, I can't. Lets close it for now.
