### ISSUE TITLE
4.0rc1 qvm-run --dispvm non-graceful exiting in dom0

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#3016]
No graceful handling of non-dvms:

```
qvm-run --dispvm fedora-25 xterm
Running 'xterm' on $dispvm:fedora-25
$dispvm:fedora-25: Got empty response from qubesd
Traceback (most recent call last):
  File "/usr/bin/qvm-run", line 9, in <module>
    load_entry_point('qubesadmin==4.0.5', 'console_scripts', 'qvm-run')()
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_run.py", line 235, in main
    dispvm.cleanup()
  File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 376, in cleanup
    self.kill()
  File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 118, in kill
    self.qubesd_call(self._method_dest, 'admin.vm.Kill')
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 69, in qubesd_call
    payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 482, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 82, in _parse_qubesd_response
    'Got empty response from qubesd')
qubesadmin.exc.QubesDaemonNoResponseError: Got empty response from qubesd
```

No graceful handling of non-existing VMs:

```
qvm-run --dispvm foo xterm
Running 'xterm' on $dispvm:foo
$dispvm:foo: Got empty response from qubesd
Traceback (most recent call last):
  File "/usr/bin/qvm-run", line 9, in <module>
    load_entry_point('qubesadmin==4.0.5', 'console_scripts', 'qvm-run')()
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_run.py", line 235, in main
    dispvm.cleanup()
  File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 376, in cleanup
    self.kill()
  File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 118, in kill
    self.qubesd_call(self._method_dest, 'admin.vm.Kill')
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 69, in qubesd_call
    payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 482, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 82, in _parse_qubesd_response
    'Got empty response from qubesd')
qubesadmin.exc.QubesDaemonNoResponseError: Got empty response from qubesd
```

**Comment by marmarek** [comment]
More details are in qubesd log. qvm-run intentionally do not know more details (see https://github.com/QubesOS/qubes-core-admin/pull/113#discussion_r122654278). So, this is mostly about better error message here (and not printing traceback). What do you think about "Got empty response from qubesd. See journalctl in dom0 for details."?

**Comment by 3hhh** [comment]
I see.

Yes, if it's in the journal, it would definitely make sense highlighting that in the error message.
