### ISSUE TITLE
qvm-block attach dom0 XXX fails due to 'AdminVM' object has no attribute 'is_halted'

### ISSUE THREAD

**Issue by ctrlaltdel** [QubesOS/qubes-issues#3054]
#### Qubes OS version (e.g., `R3.2`):

R4-rc1

#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):

Dom0

---

### Expected behavior:

USB storage device available in dom0.

### Actual behavior:

`got empty response from qubesd`

### Steps to reproduce the behavior:

Run `qvm-block attach dom0 sys-usb:sda` from a dom0 terminal after attaching a USB storage device.

### General notes:

The following exception is logged in journald:

```
Aug 27 23:14:02 dom0 qubesd[2430]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.device.block.Attach' dest=b'dom0' arg=b'sys-usb+sda' len(untrusted_payload)=0
Aug 27 23:14:02 dom0 qubesd[2430]: Traceback (most recent call last):
Aug 27 23:14:02 dom0 qubesd[2430]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 262, in respond
Aug 27 23:14:02 dom0 qubesd[2430]:     untrusted_payload=untrusted_payload)
Aug 27 23:14:02 dom0 qubesd[2430]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 380, in __iter__
Aug 27 23:14:02 dom0 qubesd[2430]:     yield self  # This tells Task to wait for completion.
Aug 27 23:14:02 dom0 qubesd[2430]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 304, in _wakeup
Aug 27 23:14:02 dom0 qubesd[2430]:     future.result()
Aug 27 23:14:02 dom0 qubesd[2430]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 293, in result
Aug 27 23:14:02 dom0 qubesd[2430]:     raise self._exception
Aug 27 23:14:02 dom0 qubesd[2430]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 239, in _step
Aug 27 23:14:02 dom0 qubesd[2430]:     result = coro.send(None)
Aug 27 23:14:02 dom0 qubesd[2430]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1067, in vm_device_attach
Aug 27 23:14:02 dom0 qubesd[2430]:     yield from self.dest.devices[devclass].attach(assignment)
Aug 27 23:14:02 dom0 qubesd[2430]:   File "/usr/lib/python3.5/site-packages/qubes/devices.py", line 197, in attach
Aug 27 23:14:02 dom0 qubesd[2430]:     if not device_assignment.persistent and self._vm.is_halted():
Aug 27 23:14:02 dom0 qubesd[2430]: AttributeError: 'AdminVM' object has no attribute 'is_halted'
```

**Comment by kalkin** [comment]
AFAIK You shouldn't be able to attach usb devices from dom0. Still so a proper error message would be nice.
