### ISSUE TITLE
Missing steps while booting qube from cdrom

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3113]
#### Qubes OS version (e.g., `R3.2`): R4.0

New GUI for creating standalone qube and booting it from cdrom should set kernel to `None` (or empty string). Otherwise dom0-provided kernel will be used, instead of booting from provided cdrom.

Additionally, when one want to install Windows, some more steps are needed:

1. Set maxmem = memory = 1024 (or more)
2. Increase size of root volume - Windows 7 installer suggests at least 12GB, by default there is 10GB.

This probably should be covered in documentation: https://www.qubes-os.org/doc/windows-appvms/ (which currently link to https://www.qubes-os.org/doc/hvm/ for actual qube setup).

**Comment by 0spinboson** [comment]
Kernel can only be set to none using qvm-prefs --set name kernel ''; when I try this via the GUI, I get an error, namely "kernel '(none)' not installed".

Additionally, when I try to install w7 via 'qvm-start w7 --cdrom=dom0:/run/media/etc/etc/etc.iso', qubesd appears to crash ("got empty response from qubesd, see journalctl").

relevant bits: [w7iso.txt](https://github.com/QubesOS/qubes-issues/files/1338751/w7iso.txt)

**Comment by marmarek** [comment]
Relevant messages:
```
Sep 27 23:11:20 dom0 qubesdb-daemon[2895]: invalid message received from client 5
Sep 27 23:11:20 dom0 qubesd[13511]: python3: qdb-client.c:443: qdb_list: Assertion `hdr.type == QDB_RESP_LIST' failed.
```

Is it reproducible?

**Comment by 0spinboson** [comment]
Yes, this is the only thing it does -- it never works.

**Comment by 0spinboson** [comment]
additional info, no idea if it's useful: when I launch qubes-vm-boot-from-device from a shell, I get this:

Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qubesmanager/bootfromdevice.py", line 52, in save_and_apply
    cdrom_location = self.vm_list[self.fileVM.currentIndex()] + ":" + self.pathText.text()
TypeError: unsupported operand type(s) for +: 'StandaloneVM' and 'str'

**Comment by marmarek** [comment]
I've reproduced both errors, working on the fix.

**Comment by marmarek** [comment]
Relevant messages:
```
Sep 27 23:11:20 dom0 qubesdb-daemon[2895]: invalid message received from client 5
Sep 27 23:11:20 dom0 qubesd[13511]: python3: qdb-client.c:443: qdb_list: Assertion `hdr.type == QDB_RESP_LIST' failed.
```

Is it reproducible?

**Comment by 0spinboson** [comment]
I'm not getting the qubesd crash any more, but when I now try to mount an ISO file, I get the following warning:

traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qubesmanager/bootfromdevice.py", line 52, in save_and_apply
    cdrom_location = self.vm_list[self.fileVM.currentIndex()] + ":" + self.pathText.text()
TypeError: unsupported operand type(s) for +: 'AppVM' and 'str'

VM type was set to 'StandaloneVM without template', so something may be wrong with the detection.
Possibly related: Oct 08 14:35:14 dom0 qubesd[2962]: QubesNoSuchPropertyError("Invalid property 'template' of w7",) while calling src=b'dom0' meth=b'admin.vm.property.Get' dest=b'w7' arg=b'template' len(untrusted_payload)=0

**Comment by marmarek** [comment]
This one is already fixed in https://github.com/QubesOS/qubes-manager/pull/42. Updated package will be in repo today.

**Comment by 0spinboson** [comment]
did qubes-manager v4.0.6 get stuck in a pipe somewhere? :)

**Comment by marmarek** [comment]
> did qubes-manager v4.0.6 get stuck in a pipe somewhere? :)

Apparently, calling a plumber ;)

**Comment by 0spinboson** [comment]
Thanks. :)

fyi: qubes-vm-boot-from-device doesn't load a GUI selection window any more.

**Comment by 0spinboson** [comment]
also, when I try to attach a win7 installation image, libxenlight is unable to create a new domain. libxlDomainstart:1320: internal error: libxenlight failed to create new domain.

**Comment by marmarek** [comment]
Check `/var/log/libvirt/libxl/libxl-driver.log`

**Comment by 0spinboson** [comment]
2017-10-10 09:02:34.125+0000: libxl: libxl_dm.c:2103:stubdom_xswait_cb: Stubdom 38 for 37 startup: startup timed out
2017-10-10 09:02:34.125+0000: libxl: libxl_create.c:1541:domcreate_devmodel_started: device model did not start: -9
2017-10-10 09:02:34.235+0000: libxl: libxl_device.c:1074:device_backend_callback: unable to remove device with path /local/domain/8/backend/vbd/38/51840
2017-10-10 09:02:34.238+0000: libxl: libxl_device.c:1074:device_backend_callback: unable to remove device with path /local/domain/4/backend/vif/38/0
2017-10-10 09:02:34.276+0000: libxl: libxl_linux.c:155:libxl__loopdev_cleanup: unable to release device /dev/loop52: No such device or address
2017-10-10 09:02:34.281+0000: libxl: libxl_device.c:1074:device_backend_callback: unable to remove device with path /local/domain/8/backend/vbd/37/51840
2017-10-10 09:02:34.620+0000: libxl: libxl.c:1673:devices_destroy_cb: libxl__devices_destroy failed for 37
2017-10-10 09:02:34.663+0000: libxl: libxl.c:1673:devices_destroy_cb: libxl__devices_destroy failed for 38

**Comment by 0spinboson** [comment]
oh, it seems this only affects loading the ISO via a VM. dom0 as a backend works.

**Comment by marmarek** [comment]
> also, when I try to attach a win7 installation image, libxenlight is unable to create a new domain. libxlDomainstart:1320: internal error: libxenlight failed to create new domain.

This is #3172

**Comment by kalkin** [comment]
Sorry for closing this issue. It looks like my private repo where I merge changes closes an issue in another organization. Weird :-/

**Comment by donob4n** [comment]
Hi,

It seems that this issue stills in Qubes 4.0 rc4, at least in the part of:

@marmarek 
> New GUI for creating standalone qube and booting it from cdrom should set kernel to None (or empty string). Otherwise dom0-provided kernel will be used, instead of booting from provided cdrom.

**Comment by marmarek** [comment]
This should be already fixed by https://github.com/QubesOS/qubes-manager/pull/64, included in qubes-manager 4.0.14 package. What version do you have?

**Comment by donob4n** [comment]
Sorry @marmarek , I was running 4.0.13. After updating with testing repository and get 4.0.15 it works fine. Also I discovered Alpinelinux HVM works (without soft lockup due bochs_drm). I will investigate it in Qubes 3.2 (maybe dom0 kernel or xen version?).
