### ISSUE TITLE
qubes-builder setup python traceback

### ISSUE THREAD

**Issue by freddierice** [QubesOS/qubes-issues#3132]
#### Qubes OS version (e.g., `R3.2`):
n/a
#### Affected TemplateVMs (e.g., `fedora-23`, if applicable):
qubes-builder

---

### Steps to reproduce the behavior:
```
./setup
```
Click "Yes" for "Owner: Qubes Master Signing Key key does not exist."
### Expected behavior:
See a dialogue box with 
"Owner: Marek Marczykowski-Grecki (Qubes OS signing key) <..> key does not exist."

### Actual behavior:
Python Traceback:
```
Traceback (most recent call last):
  File "/build/qubes-builder/libs/dialog.py", line 1618, in _call_program
    os.execve(self._dialog_prg, arglist, new_environ)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xf3' in position 27: ordinal not in range(128)

Traceback (most recent call last):
  File "./setup", line 1919, in <module>
    main(sys.argv)
  File "./setup", line 1902, in main
    Wizard(DialogUI(), **args)()
  File "./setup", line 1190, in __call__
    self.verify_keys(self.keys, force=False)
  File "./setup", line 1291, in verify_keys
    if not self.ui.verify_keys(**info):
  File "./setup", line 598, in verify_keys
    return cls.yesno(**default)
  File "./setup", line 412, in yesno
    code = cls.dialog.yesno(**default)
  File "/build/qubes-builder/libs/dialog.py", line 3666, in yesno
    kwargs)
  File "/build/qubes-builder/libs/dialog.py", line 1970, in _widget_with_no_output
    code, output = self._perform(args, **kwargs)
  File "/build/qubes-builder/libs/dialog.py", line 1757, in _perform
    child_output_rfd)
  File "/build/qubes-builder/libs/dialog.py", line 1714, in _wait_for_program_termination
    more precisely what happened."""))
dialog.PythonDialogErrorBeforeExecInChildProcess
```

### General notes:
I tried this in a fedora 26 docker container (github.com/freddierice/dockerfile-qubes-builder). 

The error has to do with a unicode character being converted to ascii from the `arglist` during an `os.exec` call.

---

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/qubes-builder/pull/30, thanks @freddierice!
