### ISSUE TITLE
qrexec-core-agent eating all CPU in debian-9 template

### ISSUE THREAD

**Issue by ctrlaltdel** [QubesOS/qubes-issues#3433]
#### Qubes OS version:

R4

#### Affected TemplateVMs: 

debian-9

### Steps to reproduce the behavior:

Run `qvm-run -q -a --service -- debian-9 qubes.StartApp+terminator` two times rapidly from dom0 while domain is shutdown.

### Expected behavior:

Starts terminator two times.

### Actual behavior:

qrexec-core-agent eating all CPU Inside the VM and terminator not starting.

### General notes:

As discussed at 34C3:

```
root@debian-9:~# dpkg -l qubes-core-agent
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  qubes-core-age 4.0.13-1+deb amd64        Qubes core agent
root@debian-9:~# 

root@debian-9:~# gdb -p 617
GNU gdb (Debian 7.12-6) 7.12.0.20161007-git
Copyright (C) 2016 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
<http://www.gnu.org/software/gdb/documentation/>.
For help, type "help".
Type "apropos word" to search for commands related to "word".
Attaching to process 617
Reading symbols from /usr/lib/qubes/qrexec-agent...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libvchan-xen.so...(no debugging symbols found)...done.
Reading symbols from /usr/lib/libqrexec-utils.so.2...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libpam.so.0...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libc.so.6...Reading symbols from /usr/lib/debug/.build-id/79/450f6e36287865d093ea209b85a222209925ff.debug...done.
done.
Reading symbols from /usr/lib/x86_64-linux-gnu/libxenvchan.so.4.8...(no debugging symbols found)...done.
Reading symbols from /usr/lib/x86_64-linux-gnu/libxenctrl.so.4.8...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libaudit.so.1...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libdl.so.2...Reading symbols from /usr/lib/debug/.build-id/6a/5d98612129b8186f21e800afdfaaa627082f46.debug...done.
done.
Reading symbols from /lib64/ld-linux-x86-64.so.2...Reading symbols from /usr/lib/debug/.build-id/6f/150f33b150d6a81e26a425dd47d713d00f2d29.debug...done.
done.
Reading symbols from /usr/lib/x86_64-linux-gnu/libxenstore.so.3.0...(no debugging symbols found)...done.
Reading symbols from /usr/lib/x86_64-linux-gnu/libxengnttab.so.1...(no debugging symbols found)...done.
Reading symbols from /usr/lib/x86_64-linux-gnu/libxenevtchn.so.1...(no debugging symbols found)...done.
Reading symbols from /usr/lib/x86_64-linux-gnu/libxentoollog.so.1...(no debugging symbols found)...done.
Reading symbols from /usr/lib/x86_64-linux-gnu/libxencall.so.1...(no debugging symbols found)...done.
Reading symbols from /usr/lib/x86_64-linux-gnu/libxenforeignmemory.so.1...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libpthread.so.0...Reading symbols from /usr/lib/debug/.build-id/96/8df33f83963b559243653d74d27d89605bed02.debug...done.
done.
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Reading symbols from /lib/x86_64-linux-gnu/libcap-ng.so.0...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libsystemd.so.0...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libselinux.so.1...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/librt.so.1...Reading symbols from /usr/lib/debug/.build-id/fe/41526a83999f2fe9d0f8aadcd61d03a92cbb70.debug...done.
done.
Reading symbols from /lib/x86_64-linux-gnu/liblzma.so.5...(no debugging symbols found)...done.
Reading symbols from /usr/lib/x86_64-linux-gnu/liblz4.so.1...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libgcrypt.so.20...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libpcre.so.3...(no debugging symbols found)...done.
Reading symbols from /lib/x86_64-linux-gnu/libgpg-error.so.0...(no debugging symbols found)...done.
0x00005f829de354d8 in ?? ()
(gdb) bt
#0  0x00005f829de354d8 in ?? ()
#1  0x00005f829de3572f in ?? ()
#2  0x00005f829de343b7 in ?? ()
#3  0x00007129ab8892b1 in __libc_start_main (main=0x5f829de342c0, argc=1, 
    argv=0x7ffe172397a8, init=<optimized out>, fini=<optimized out>, 
    rtld_fini=<optimized out>, stack_end=0x7ffe17239798)
    at ../csu/libc-start.c:291
#4  0x00005f829de3444a in ?? ()
(gdb) w

```

**Comment by marmarek** [comment]
I can confirm the issue also on other templates (fedora-26 for example).

**Comment by ctrlaltdel** [comment]
Thanks @marmarek, good catch!
