### ISSUE TITLE
occasional "qvm-prefs: error: no such property: 'netvm'"

### ISSUE THREAD

**Issue by dncohen** [QubesOS/qubes-issues#3528]
#### Qubes OS version:

4.0-rc4

#### Affected TemplateVMs: 

fedora-26, I don't believe the problem is related to the template

---

### Steps to reproduce the behavior:

not sure.  

It happened to me after connecting a laptop to network in one location, closing the lid allowing laptop to sleep, open lid in another location.

Then, appvms are unable to connect to network, even though sys-net shows that it is connected.

### Expected behavior:

I would expect `qvm-prefs -s sys-firewall netvm sys-net` possibly to solve the problem.  Instead it gets an error...

### Actual behavior:

```
[dave@dom0 Desktop]$ qvm-prefs -s sys-firewall netvm sys-net
usage: qvm-prefs [-h] [--verbose] [--quiet] [--help-properties] [--get]
                 [--set] [--default]
                 VMNAME [PROPERTY] [VALUE]
qvm-prefs: error: no such property: 'netvm'
```

### General notes:

Under normal circumstances, I can run `qvm-prefs -s sys-firewall netvm sys-net` without errors.  This problem has happened only a couple of times.  When it does, I haven't found a way to recover short of rebooting.  (I haven't had 4.0 installed for long.  I expect this is a real bug)

Here are some things I've tried (without success):

```
[dave@dom0 Desktop]$ qvm-prefs -s sys-firewall netvm sys-net
usage: qvm-prefs [-h] [--verbose] [--quiet] [--help-properties] [--get]
                 [--set] [--default]
                 VMNAME [PROPERTY] [VALUE]
qvm-prefs: error: no such property: 'netvm'
[dave@dom0 Desktop]$ qvm-shutdown sys-net
sys-net: Shutdown error: There are other VMs connected to this VM: sys-firewall
[dave@dom0 Desktop]$ qvm-kill sys-net
[dave@dom0 Desktop]$ qvm-start sys-net
[dave@dom0 Desktop]$ qvm-prefs -s sys-firewall netvm sys-net
usage: qvm-prefs [-h] [--verbose] [--quiet] [--help-properties] [--get]
                 [--set] [--default]
                 VMNAME [PROPERTY] [VALUE]
qvm-prefs: error: no such property: 'netvm'
```
Note that `qvm-prefs -g sys-firewall` does show `netvm` in the output.

```
[dave@dom0 Desktop]$ qvm-prefs -g sys-firewall
autostart             -  True
backup_timestamp      U
debug                 D  False
default_dispvm        D  fedora-26-dvm
default_user          D  user
gateway               D  10.137.0.6
gateway6              D
include_in_backups    D  True
installed_by_rpm      D  False
ip                    D  10.137.0.6
ip6                   D
kernel                D  4.14.13-2
kernelopts            D  nopat
klass                 D  AppVM
label                 -  green
mac                   D  00:16:3E:5E:6C:00
maxmem                D  4000
memory                -  500
name                  -  sys-firewall
netvm                 -  sys-net
[snip]
```

---

**Comment by marmarek** [comment]
I can confirm that when setting netvm fails, sometimes it result in "no such property" error, instead of real reason.

**Comment by marmarek** [comment]
Actual message can be seen using `journalctl` in dom0.

**Comment by SaswatPadhi** [comment]
I ran into it recently. I see the following error in dom0's `journalctl`:

```
Dec 23 16:58:32 dom0 qubesd[16233]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.property.Set' dest=b'disp8439' arg=b'netvm' len(untrusted_payload)=17
Dec 23 16:58:32 dom0 qubesd[16233]: Traceback (most recent call last):
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 275, in respond
Dec 23 16:58:32 dom0 qubesd[16233]:     untrusted_payload=untrusted_payload)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Dec 23 16:58:32 dom0 qubesd[16233]:     yield self  # This tells Task to wait for completion.
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Dec 23 16:58:32 dom0 qubesd[16233]:     future.result()
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Dec 23 16:58:32 dom0 qubesd[16233]:     raise self._exception
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Dec 23 16:58:32 dom0 qubesd[16233]:     result = coro.send(None)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 210, in coro
Dec 23 16:58:32 dom0 qubesd[16233]:     res = func(*args, **kw)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 244, in vm_property_set
Dec 23 16:58:32 dom0 qubesd[16233]:     untrusted_payload=untrusted_payload)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 264, in _property_set
Dec 23 16:58:32 dom0 qubesd[16233]:     setattr(dest, self.arg, newvalue)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/vm/__init__.py", line 479, in __set__
Dec 23 16:58:32 dom0 qubesd[16233]:     super(VMProperty, self).__set__(instance, vm)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/__init__.py", line 261, in __set__
Dec 23 16:58:32 dom0 qubesd[16233]:     name=self.__name__, newvalue=value, oldvalue=oldvalue)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 198, in fire_event
Dec 23 16:58:32 dom0 qubesd[16233]:     pre_event=pre_event)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 166, in _fire_event
Dec 23 16:58:32 dom0 qubesd[16233]:     effect = func(self, event, **kwargs)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/vm/mix/net.py", line 430, in on_property_pre_set_netvm
Dec 23 16:58:32 dom0 qubesd[16233]:     self.detach_network()
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/vm/mix/net.py", line 338, in detach_network
Dec 23 16:58:32 dom0 qubesd[16233]:     vm=self))
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 101, in wrapper
Dec 23 16:58:32 dom0 qubesd[16233]:     return attr(*args, **kwargs)
Dec 23 16:58:32 dom0 qubesd[16233]:   File "/usr/lib64/python3.5/site-packages/libvirt.py", line 1170, in detachDevice
Dec 23 16:58:32 dom0 qubesd[16233]:     if ret == -1: raise libvirtError ('virDomainDetachDevice() failed', dom=self)
Dec 23 16:58:32 dom0 qubesd[16233]: libvirt.libvirtError: operation failed: no device matching mac address 00:16:3e:5e:6c:00 found
```
