### ISSUE TITLE
Too much debugged error messages for some console commands

### ISSUE THREAD

**Issue by schnurentwickler** [QubesOS/qubes-issues#3610]
#### Qubes OS version:
R4.0 rc4

#### Affected TemplateVMs: 
dom0
---

### Steps to reproduce the behavior:
`qvm-prefs --set sys-firewall netvm sys-net` (while sys-net is offline and sys-firewall running)

### Expected behavior:
```
[user@dom0 ~]$ qvm-prefs --set sys-firewall netvm sys-wifi
(Output message i.e.:) qvm-prefs: error: invalid: Cannot dynamically attach to stopped NetVM.
[user@dom0 ~]$
```

### Actual behavior:
```
[user@dom0 ~]$ qvm-prefs --set sys-firewall netvm sys-wifi
Traceback (most recent call last):
  File "/usr/bin/qvm-prefs", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_prefs.py", line 140, in main
    return process_actions(parser, args, target)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_prefs.py", line 116, in process_actions
    setattr(target, args.property, args.value)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 283, in __setattr__
    str(value).encode('utf-8'))
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 68, in qubesd_call
    payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 483, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 102, in _parse_qubesd_response
    raise exc_class(format_string, *args)
qubesadmin.exc.QubesVMNotStartedError: Cannot dynamically attach to stopped NetVM: <AppVM at 0x7d3f213e9898 name='sys-wifi' qid=16 autostart=False backup_timestamp=None debug=False default_user=user gateway=10.137.0.16 gateway6=None include_in_backups=True installed_by_rpm=False ip=10.137.0.16 ip6=None kernel=4.14.13-3 klass=AppVM label=red mac=00:16:3E:5E:6C:00 maxmem=4000 memory=400 provides_network=True qrexec_timeout=60 start_time=None stubdom_mem=None stubdom_xid=-1 template_for_dispvms=False updateable=False uuid=750b3824-237e-4805-b5a4-ee4a102e6da7 vcpus=2 virt_mode=hvm visible_gateway=None visible_gateway6=None visible_ip=10.137.0.16 visible_ip6=None visible_netmask=None xid=-1 default_dispvm=None kernelopts=nopat iommu=soft swiotlb=8192 netvm=None template=fedora-26>
[user@dom0 ~]$ 
```

### General notes:
It is - especially for new qubes user (in R4.0 rc3 for example) - too difficult to understand on first view.
And this is a quite often used command.

Also other non clean error messages (probably already as an issue postet):
```
[user@dom0 ~]$ qvm-create --class DispVM --template fedora-26 --label red test-dvm
app: Error creating VM: Got empty response from qubesd. See journalctl in dom0 for details.
[user@dom0 ~]$
```

journalctl:
```
-- Logs begin at Thu 2018-02-08 19:08:59 CET, end at Mon 2018-02-19 17:04:40 CET. --
Feb 19 17:04:40 dom0 qubesd[9181]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Create.DispVM' dest=b'dom0' arg=b'fedora-26' len(untrusted_payload)=23
Feb 19 17:04:40 dom0 qubesd[9181]: Traceback (most recent call last):
Feb 19 17:04:40 dom0 qubesd[9181]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 262, in respond
Feb 19 17:04:40 dom0 qubesd[9181]:     untrusted_payload=untrusted_payload)
Feb 19 17:04:40 dom0 qubesd[9181]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Feb 19 17:04:40 dom0 qubesd[9181]:     yield self  # This tells Task to wait for completion.
Feb 19 17:04:40 dom0 qubesd[9181]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Feb 19 17:04:40 dom0 qubesd[9181]:     future.result()
Feb 19 17:04:40 dom0 qubesd[9181]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Feb 19 17:04:40 dom0 qubesd[9181]:     raise self._exception
Feb 19 17:04:40 dom0 qubesd[9181]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Feb 19 17:04:40 dom0 qubesd[9181]:     result = coro.send(None)
Feb 19 17:04:40 dom0 qubesd[9181]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 213, in coro
Feb 19 17:04:40 dom0 qubesd[9181]:     res = yield from res
Feb 19 17:04:40 dom0 qubesd[9181]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1015, in _vm_create
Feb 19 17:04:40 dom0 qubesd[9181]:     vm = self.app.add_new_vm(vm_class, **kwargs)
Feb 19 17:04:40 dom0 qubesd[9181]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 1196, in add_new_vm
Feb 19 17:04:40 dom0 qubesd[9181]:     return self.domains.add(cls(self, None, qid=qid, **kwargs))
Feb 19 17:04:40 dom0 qubesd[9181]:   File "/usr/lib/python3.5/site-packages/qubes/vm/dispvm.py", line 81, in __init__
Feb 19 17:04:40 dom0 qubesd[9181]:     if not template.template_for_dispvms:
Feb 19 17:04:40 dom0 qubesd[9181]: AttributeError: 'TemplateVM' object has no attribute 'template_for_dispvms'
```

```
[user@dom0 ~]$ qvm-move-to-vm Bereich-Qubes command 
A file named command already exists in QubesIncoming dir
Gtk-Message: GtkDialog mapped without a transient parent. This is discouraged.
[user@dom0 ~]$
```

#### Related issues:
Here and there probably, but so far only a few adressed the overloaded error messages.

**Comment by marmarek** [comment]
For console tools, I definitely agree. But IMO log file should contain as much details as possible, to ease diagnosing and fixing the issue.
