### ISSUE TITLE
sys-usb attach usb printer to vm just hangs after recent update

### ISSUE THREAD

**Issue by qubesuser12** [QubesOS/qubes-issues#3654]
#### Qubes OS version:

4.0 rc4

#### Affected component(s): 

USB printer

---

### Steps to reproduce the behavior:

Setup sys-usb per docs

perform recent update of dom0 via:
`sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing`

`qvm-usb` -> shows usb printer
`qvm-usb attach <VM> sys-usb:3-1`

### Expected behavior:

connects USB printer to VM so i can print

### Actual behavior:

just hangs, hitting control - c returns:

```
^CTraceback (most recent call last):
  File "/usr/bin/qvm-usb", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_device.py", line 263, in main
    args.func(args)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_device.py", line 126, in attach_device
    vm.devices[args.devclass].attach(device_assignment)
  File "/usr/lib/python3.5/site-packages/qubesadmin/devices.py", line 157, in attach
    options_str.encode('utf-8'))
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 68, in qubesd_call
    payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 481, in qubesd_call
    return_data = client_socket.makefile('rb').read()
  File "/usr/lib64/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt

```

### General notes:

I was able to print using sys-usb to attach this printer prior to updates applied on or around 3 March 2018.

---

#### Related issues:

usb mouse was setup to ask permission to access dom0, but is not currently working either. But this was hit or miss before recent update as well.

**Comment by qubesuser12** [comment]
This issue was solved after most recent updates from 7 March 2018.
