### ISSUE TITLE
Provide qubesctl switch to limit concurrent jobs

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#3655]
#### Qubes OS version:

R4.0

#### Affected component(s): 

salt

---

### Steps to reproduce the behavior:

Launch `qubesctl --all state.highstate`

### Expected behavior:

An option to limit/increase number of parallel VMs being configured.

### Actual behavior:

A hardcoded value of `4` is used.
Especially annoying on limited memory or slow disk.

### General notes:

Discussion: https://groups.google.com/d/msgid/qubes-users/20170117032920.GC3974%40mail-itl

**Comment by GAhlekzis** [comment]
I installed the new fix by the advertised command: `sudo qubes-dom0-update --enablerepo=qubes-dom0-current-testing`
When I try it, it looks like this:
```
$ sudo qubesctl --max-concurrency 1 --templates state.highstate

Traceback (most recent call last):
  File "/bin/qubesctl", line 102, in <module>
    main()
  File "/bin/qubesctl", line 80, in main
    runner.run()
  File "/usr/lib/python2.7/site-packages/qubessalt/__init__.py", line 228, in run
    pool = multiprocessing.Pool(self.max_concurrency)
  File "/usr/lib64/python2.7/multiprocessing/__init__.py", line 232, in Pool
    return Pool(processes, initializer, initargs, maxtasksperchild)
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 159, in __init__
    self._repopulate_pool()
  File "/usr/lib64/python2.7/multiprocessing/pool.py", line 214, in _repopulate_pool
    for i in range(self._processes - len(self._pool)):
TypeError: unsupported operand type(s) for -: 'str' and 'int'
```
I'm on a fresh Qubes 4.0 Installation and I'm having issues detailed in #3768. 
I don't know what to do now.
