### ISSUE TITLE
R4.0 qvm-clone breaks when setting a secondary pool

### ISSUE THREAD

**Issue by yonjah** [QubesOS/qubes-issues#3776]
On R4.0  when cloning an existing VM to a pool on a secondary drive.
The following error is thrown -
```
$ qvm-clone -v -P storage appVM appVM-clone
2018-04-01 00:20:36,421 [MainProcess app.clone_vm:390] appVM-clone: Cloning private volume
Traceback (most recent call last):
  File "/usr/bin/qvm-clone", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_clone.py", line 73, in main
    app.clone_vm(src_vm, new_name, new_cls=args.cls, pool=pool, pools=pools)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 391, in clone_vm
    dst_volume.clone(src_volume)
  File "/usr/lib/python3.5/site-packages/qubesadmin/storage.py", line 229, in clone
    self._qubesd_call('CloneTo', payload=token)
  File "/usr/lib/python3.5/site-packages/qubesadmin/storage.py", line 76, in _qubesd_call
    payload_stream=payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 483, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 102, in _parse_qubesd_response
    raise exc_class(format_string, *args)
qubesadmin.exc.StoragePoolException: b'  Please use a single volume group name ("qubes_root0" or "qubes_storage0").\n  Run `lvcreate --help\' for more information.\n'
```

qubes_root0 is the volume group where appVM sits on (default pool)
qubes_storage0 is the volum group on the secondery drive where the clone should be created

**Comment by brendanhoar** [comment]
@yonjah - did  you register the additional pool first via qvm-pool? Also, there have been significant improvement in qvm-clone over the last year, just FYI.
@andrewdavidwong - is there a reason it's qvm-pool and not qubes-pool? :)

**Comment by andrewdavidwong** [comment]
> is there a reason it's qvm-pool and not qubes-pool? :)

This is a question for @marmarek. Possibly an oversight.

**Comment by yonjah** [comment]
@brendanhoar Yes I did register the additional pool.
As a workaround at the time I temporarily used qvm-perf to change the default pool to the secondary one and restored the AppVM from backup.
But since this issue was created I changed several drives and setups and never had to use more than one pool so I haven't tried it recently
