### ISSUE TITLE
Critical dnf errors while upgrading packages of fedora-26 template (qubes-core-agent-networking, qubes-core-agent-qrexec)

### ISSUE THREAD

**Issue by heinrich-ulbricht** [QubesOS/qubes-issues#4051]
### Qubes OS version:

R4.0

### Affected component(s): 

Template VM _fedora 26_

---

### Steps to reproduce the behavior:

`sudo dnf upgrade` (can only be used once to trigger the error)
`sudo dnf remove qubes-core-agent-networking --duplicates` (triggers the error again, every time)

### Expected behavior:

`dnf upgrade` should correctly upgrade the package _qubes-core-agent-networking_

### Actual behavior:

What follows are the _dnf.log_ entries for `dnf upgrade`. Note the failed transaction and these two errors:
```
2018-07-04T07:19:32Z CRITICAL qubes-core-agent-networking-4.0.28-1.fc26.x86_64 was supposed to be removed but is not!
2018-07-04T07:19:32Z CRITICAL qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64 was supposed to be removed but is not!
```
Full log for the command:
```
2018-07-04T07:16:12Z INFO --- logging initialized ---
2018-07-04T07:16:12Z DDEBUG timer: config: 3 ms
2018-07-04T07:16:12Z DEBUG Loaded plugins: builddep, config-manager, copr, debug, debuginfo-install, download, generate_completion_cache, needs-restarting, playground, qubes-hooks, repoclosure, repograph, repomanage, reposync
2018-07-04T07:16:12Z DEBUG DNF version: 2.7.5
2018-07-04T07:16:12Z DDEBUG Command: dnf upgrade 
2018-07-04T07:16:12Z DDEBUG Installroot: /
2018-07-04T07:16:12Z DDEBUG Releasever: 26
2018-07-04T07:16:12Z DEBUG cachedir: /var/cache/dnf
2018-07-04T07:16:12Z DDEBUG Base command: upgrade
2018-07-04T07:16:12Z DDEBUG Extra commands: ['upgrade']
2018-07-04T07:16:13Z DEBUG repo: using cache for: updates
2018-07-04T07:16:13Z DEBUG updates: using metadata from Tue May 29 13:05:48 2018.
2018-07-04T07:16:13Z DEBUG repo: using cache for: fedora
2018-07-04T07:16:13Z DEBUG not found deltainfo for: Fedora 26 - x86_64
2018-07-04T07:16:13Z DEBUG not found updateinfo for: Fedora 26 - x86_64
2018-07-04T07:16:13Z DEBUG fedora: using metadata from Wed Jul  5 22:31:38 2017.
2018-07-04T07:16:13Z DEBUG repo: using cache for: qubes-vm-r4.0-current
2018-07-04T07:16:13Z DEBUG not found deltainfo for: Qubes OS Repository for VM (updates)
2018-07-04T07:16:13Z DEBUG not found updateinfo for: Qubes OS Repository for VM (updates)
2018-07-04T07:16:13Z DEBUG qubes-vm-r4.0-current: using metadata from Tue Jul  3 22:14:54 2018.
2018-07-04T07:16:13Z INFO Last metadata expiration check: 0:00:37 ago on Wed Jul  4 09:15:36 2018.
2018-07-04T07:16:13Z DDEBUG timer: sack setup: 782 ms
2018-07-04T07:16:13Z DEBUG --> Starting dependency resolution
2018-07-04T07:16:15Z DEBUG ---> Package kernel.x86_64 4.16.11-100.fc26 will be installed
2018-07-04T07:16:15Z DEBUG ---> Package kernel-core.x86_64 4.16.11-100.fc26 will be installed
2018-07-04T07:16:15Z DEBUG ---> Package kernel-modules.x86_64 4.16.11-100.fc26 will be installed
2018-07-04T07:16:15Z DEBUG ---> Package kernel-devel.x86_64 4.16.11-100.fc26 will be installed
2018-07-04T07:16:15Z DEBUG ---> Package kernel-headers.x86_64 4.16.7-100.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package kernel-headers.x86_64 4.16.11-100.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package osinfo-db.noarch 20180502-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package osinfo-db.noarch 20180514-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package python3-dnf-plugins-qubes-hooks.x86_64 4.0.28-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package python3-dnf-plugins-qubes-hooks.x86_64 4.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent.x86_64 4.0.28-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent.x86_64 4.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-dom0-updates.x86_64 4.0.28-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-dom0-updates.x86_64 4.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-nautilus.x86_64 4.0.28-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-nautilus.x86_64 4.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-network-manager.x86_64 4.0.28-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-network-manager.x86_64 4.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-networking.x86_64 4.0.28-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-networking.x86_64 4.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-passwordless-root.x86_64 4.0.28-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-passwordless-root.x86_64 4.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-qrexec.x86_64 4.0.28-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-qrexec.x86_64 4.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-systemd.x86_64 4.0.28-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-core-agent-systemd.x86_64 4.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-gpg-split.x86_64 2.0.30-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-gpg-split.x86_64 2.0.31-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package qubes-input-proxy-sender.x86_64 1.0.11-1.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package qubes-input-proxy-sender.x86_64 1.0.12-1.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package xen-libs.x86_64 2001:4.8.3-7.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package xen-libs.x86_64 2001:4.8.3-8.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package xen-qubes-vm.x86_64 2001:4.8.3-7.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package xen-qubes-vm.x86_64 2001:4.8.3-8.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG ---> Package xen-licenses.x86_64 2001:4.8.3-7.fc26 will be upgraded
2018-07-04T07:16:15Z DEBUG ---> Package xen-licenses.x86_64 2001:4.8.3-8.fc26 will be an upgrade
2018-07-04T07:16:15Z DEBUG --> Finished dependency resolution
2018-07-04T07:16:15Z DDEBUG timer: depsolve: 1665 ms
2018-07-04T07:16:15Z INFO Dependencies resolved.
2018-07-04T07:16:16Z INFO ===================================================================================================================================================================================================================
 Package                                                          Arch                                 Version                                           Repository                                           Size
===================================================================================================================================================================================================================
Upgrading:
 kernel-headers                                                   x86_64                               4.16.11-100.fc26                                  updates                                             1.2 M
 osinfo-db                                                        noarch                               20180514-1.fc26                                   updates                                             149 k
 python3-dnf-plugins-qubes-hooks                                  x86_64                               4.0.31-1.fc26                                     qubes-vm-r4.0-current                               8.8 k
 qubes-core-agent                                                 x86_64                               4.0.31-1.fc26                                     qubes-vm-r4.0-current                               110 k
 qubes-core-agent-dom0-updates                                    x86_64                               4.0.31-1.fc26                                     qubes-vm-r4.0-current                               8.5 k
 qubes-core-agent-nautilus                                        x86_64                               4.0.31-1.fc26                                     qubes-vm-r4.0-current                                11 k
 qubes-core-agent-network-manager                                 x86_64                               4.0.31-1.fc26                                     qubes-vm-r4.0-current                               9.5 k
 qubes-core-agent-networking                                      x86_64                               4.0.31-1.fc26                                     qubes-vm-r4.0-current                                18 k
 qubes-core-agent-passwordless-root                               x86_64                               4.0.31-1.fc26                                     qubes-vm-r4.0-current                               8.5 k
 qubes-core-agent-qrexec                                          x86_64                               4.0.31-1.fc26                                     qubes-vm-r4.0-current                                31 k
 qubes-core-agent-systemd                                         x86_64                               4.0.31-1.fc26                                     qubes-vm-r4.0-current                                22 k
 qubes-gpg-split                                                  x86_64                               2.0.31-1.fc26                                     qubes-vm-r4.0-current                                26 k
 qubes-input-proxy-sender                                         x86_64                               1.0.12-1.fc26                                     qubes-vm-r4.0-current                                15 k
 xen-libs                                                         x86_64                               2001:4.8.3-8.fc26                                 qubes-vm-r4.0-current                               559 k
 xen-licenses                                                     x86_64                               2001:4.8.3-8.fc26                                 qubes-vm-r4.0-current                                46 k
 xen-qubes-vm                                                     x86_64                               2001:4.8.3-8.fc26                                 qubes-vm-r4.0-current                               138 k
Installing dependencies:
 kernel                                                           x86_64                               4.16.11-100.fc26                                  updates                                              74 k
 kernel-core                                                      x86_64                               4.16.11-100.fc26                                  updates                                              23 M
 kernel-devel                                                     x86_64                               4.16.11-100.fc26                                  updates                                              12 M
 kernel-modules                                                   x86_64                               4.16.11-100.fc26                                  updates                                              27 M

Transaction Summary
===================================================================================================================================================================================================================
Install   4 Packages
Upgrade  16 Packages

2018-07-04T07:16:16Z INFO Total download size: 65 M
2018-07-04T07:16:33Z INFO Downloading Packages:
2018-07-04T07:16:36Z SUBDEBUG Call: DeltaPayload._end_cb: (<dnf.drpm.DeltaPayload object at 0x7cbb1d5ab080>, 0, None), {}
2018-07-04T07:16:36Z SUBDEBUG drpm: spawned 1935: /usr/bin/applydeltarpm -a noarch /var/cache/dnf/updates-2854b3113b7a3c6c/packages/osinfo-db-20180502-1.fc26_20180514-1.fc26.noarch.drpm /var/cache/dnf/updates-2854b3113b7a3c6c/packages/osinfo-db-20180514-1.fc26.noarch.rpm
2018-07-04T07:16:36Z SUBDEBUG Call: DeltaPayload._end_cb: (<dnf.drpm.DeltaPayload object at 0x7cbb2c2ae2b0>, 0, None), {}
2018-07-04T07:16:36Z SUBDEBUG drpm: 1935: return code: 0, 0
2018-07-04T07:16:36Z SUBDEBUG drpm: spawned 1937: /usr/bin/applydeltarpm -a x86_64 /var/cache/dnf/updates-2854b3113b7a3c6c/packages/kernel-headers-4.16.7-100.fc26_4.16.11-100.fc26.x86_64.drpm /var/cache/dnf/updates-2854b3113b7a3c6c/packages/kernel-headers-4.16.11-100.fc26.x86_64.rpm
2018-07-04T07:16:36Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d569198>, 0, None), {}
2018-07-04T07:16:52Z SUBDEBUG Call: DeltaPayload._end_cb: (<dnf.drpm.DeltaPayload object at 0x7cbb1d5b8cf8>, 0, None), {}
2018-07-04T07:16:52Z SUBDEBUG drpm: 1937: return code: 0, 0
2018-07-04T07:16:52Z SUBDEBUG drpm: spawned 1939: /usr/bin/applydeltarpm -a x86_64 /var/cache/dnf/updates-2854b3113b7a3c6c/packages/kernel-devel-4.16.7-100.fc26_4.16.11-100.fc26.x86_64.drpm /var/cache/dnf/updates-2854b3113b7a3c6c/packages/kernel-devel-4.16.11-100.fc26.x86_64.rpm
2018-07-04T07:16:55Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d5c8dd8>, 0, None), {}
2018-07-04T07:16:56Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d5662b0>, 0, None), {}
2018-07-04T07:16:57Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d566240>, 0, None), {}
2018-07-04T07:16:58Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb2c2ae630>, 0, None), {}
2018-07-04T07:16:59Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb2c2aee48>, 0, None), {}
2018-07-04T07:17:00Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d56d9e8>, 0, None), {}
2018-07-04T07:17:01Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d56d908>, 0, None), {}
2018-07-04T07:17:02Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d56d0b8>, 0, None), {}
2018-07-04T07:17:03Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d56d128>, 0, None), {}
2018-07-04T07:17:04Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d56d198>, 0, None), {}
2018-07-04T07:17:04Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d56d400>, 0, None), {}
2018-07-04T07:17:08Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d56d1d0>, 0, None), {}
2018-07-04T07:17:09Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d56d470>, 0, None), {}
2018-07-04T07:17:10Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d56d3c8>, 0, None), {}
2018-07-04T07:18:13Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d569fd0>, 0, None), {}
2018-07-04T07:18:19Z SUBDEBUG Call: RPMPayload._end_cb: (<dnf.repo.RPMPayload object at 0x7cbb1d5b8d68>, 0, None), {}
2018-07-04T07:18:19Z SUBDEBUG drpm: 1939: return code: 0, 0
2018-07-04T07:18:19Z INFO -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
2018-07-04T07:18:19Z INFO Total                                                                                                                                                                              531 kB/s |  55 MB     01:46     
2018-07-04T07:18:19Z INFO Delta RPMs reduced 65.1 MB of updates to 55.1 MB (15.1% saved)
2018-07-04T07:18:19Z INFO Running transaction check
2018-07-04T07:18:19Z INFO Transaction check succeeded.
2018-07-04T07:18:19Z INFO Running transaction test
2018-07-04T07:18:20Z INFO Transaction test succeeded.
2018-07-04T07:18:20Z DDEBUG timer: transaction test: 1378 ms
2018-07-04T07:18:20Z INFO Running transaction
2018-07-04T07:18:21Z DDEBUG RPM transaction start.
2018-07-04T07:19:31Z DDEBUG RPM transaction over.
2018-07-04T07:19:31Z DEBUG Errors occurred during transaction.
2018-07-04T07:19:32Z CRITICAL qubes-core-agent-networking-4.0.28-1.fc26.x86_64 was supposed to be removed but is not!
2018-07-04T07:19:32Z CRITICAL qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64 was supposed to be removed but is not!
2018-07-04T07:19:32Z DDEBUG timer: verify transaction: 608 ms
2018-07-04T07:19:32Z DDEBUG timer: transaction: 71473 ms
2018-07-04T07:19:33Z INFO Notifying dom0 about installed applications
2018-07-04T07:19:48Z DEBUG Completion plugin: Generating completion cache...
2018-07-04T07:19:48Z INFO 
Installed:
  kernel.x86_64 4.16.11-100.fc26                 kernel-core.x86_64 4.16.11-100.fc26                 kernel-devel.x86_64 4.16.11-100.fc26                 kernel-modules.x86_64 4.16.11-100.fc26                

Upgraded:
  kernel-headers.x86_64 4.16.11-100.fc26             osinfo-db.noarch 20180514-1.fc26               python3-dnf-plugins-qubes-hooks.x86_64 4.0.31-1.fc26  qubes-core-agent.x86_64 4.0.31-1.fc26                  
  qubes-core-agent-dom0-updates.x86_64 4.0.31-1.fc26 qubes-core-agent-nautilus.x86_64 4.0.31-1.fc26 qubes-core-agent-network-manager.x86_64 4.0.31-1.fc26 qubes-core-agent-passwordless-root.x86_64 4.0.31-1.fc26
  qubes-core-agent-systemd.x86_64 4.0.31-1.fc26      qubes-gpg-split.x86_64 2.0.31-1.fc26           qubes-input-proxy-sender.x86_64 1.0.12-1.fc26         xen-libs.x86_64 2001:4.8.3-8.fc26                      
  xen-licenses.x86_64 2001:4.8.3-8.fc26              xen-qubes-vm.x86_64 2001:4.8.3-8.fc26         

Failed:
  qubes-core-agent-networking.x86_64 4.0.31-1.fc26                                                           qubes-core-agent-qrexec.x86_64 4.0.31-1.fc26                                                          

2018-07-04T07:19:48Z DDEBUG Cleaning up.
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/updates-2854b3113b7a3c6c/packages/kernel-devel-4.16.11-100.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-core-agent-networking-4.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-core-agent-systemd-4.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/xen-licenses-4.8.3-8.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/updates-2854b3113b7a3c6c/packages/osinfo-db-20180514-1.fc26.noarch.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/updates-2854b3113b7a3c6c/packages/kernel-headers-4.16.11-100.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-core-agent-nautilus-4.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/python3-dnf-plugins-qubes-hooks-4.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/xen-libs-4.8.3-8.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-core-agent-network-manager-4.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-core-agent-qrexec-4.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/updates-2854b3113b7a3c6c/packages/kernel-modules-4.16.11-100.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-gpg-split-2.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/updates-2854b3113b7a3c6c/packages/kernel-4.16.11-100.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-input-proxy-sender-1.0.12-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/xen-qubes-vm-4.8.3-8.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-core-agent-dom0-updates-4.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-core-agent-passwordless-root-4.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/updates-2854b3113b7a3c6c/packages/kernel-core-4.16.11-100.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z DDEBUG /var/cache/dnf/qubes-vm-r4.0-current-eab4eb96ce983546/packages/qubes-core-agent-4.0.31-1.fc26.x86_64.rpm removed
2018-07-04T07:19:48Z SUBDEBUG 
Traceback (most recent call last):
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 123, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.6/site-packages/dnf/cli/main.py", line 154, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.6/site-packages/dnf/cli/cli.py", line 244, in do_transaction
    raise dnf.exceptions.Error(_('Transaction failed'))
dnf.exceptions.Error: Transaction failed
2018-07-04T07:19:48Z CRITICAL Error: Transaction failed
```

**Comment by andrewdavidwong** [comment]
> ### Steps to reproduce the behavior:
> `sudo dnf upgrade` (can only be used once to trigger the error)
> `sudo dnf remove qubes-core-agent-networking --duplicates` (triggers the error again, every time)

Are you trying to upgrade from Fedora 26 to 27 or 28? If so, please follow the appropriate guide:

- https://www.qubes-os.org/doc/template/fedora/upgrade-26-to-27/
- https://www.qubes-os.org/doc/template/fedora/upgrade-27-to-28/

**Comment by heinrich-ulbricht** [comment]
@andrewdavidwong No, I'm not upgrading Fedora. I just wanted to update packages that had an update available. If `sudo dnf upgrade` is not the right way to do this, how can I keep my system up-to-date?

**Comment by marmarek** [comment]
Looks like a duplicate of #3926, especially see https://github.com/QubesOS/qubes-issues/issues/3926#issuecomment-391938122 for solution.

**Comment by heinrich-ulbricht** [comment]
@marmarek It seems so! The commands from the comment you linked to solved my issue:

```
sudo rpm -e --noscripts qubes-core-agent-networking-4.0.28-1.fc26.x86_64 qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64
sudo dnf reinstall qubes-core-agent-networking qubes-core-agent-qrexec
```

For sake of completeness the command line output:
```
[user@fedora-26 ~]$ sudo rpm -e --noscripts qubes-core-agent-networking-4.0.28-1.fc26.x86_64 qubes-core-agent-qrexec-4.0.28-1.fc26.x86_64
[user@fedora-26 ~]$ sudo dnf reinstall qubes-core-agent-networking qubes-core-agent-qrexec
Last metadata expiration check: 5:29:28 ago on Wed Jul  4 09:15:36 2018.
Dependencies resolved.
================================================================================
 Package                     Arch   Version         Repository             Size
================================================================================
Reinstalling:
 qubes-core-agent-networking x86_64 4.0.31-1.fc26   qubes-vm-r4.0-current  18 k
 qubes-core-agent-qrexec     x86_64 4.0.31-1.fc26   qubes-vm-r4.0-current  31 k

Transaction Summary
================================================================================

Total download size: 48 k
Is this ok [y/N]: y
Downloading Packages:
(1/2): qubes-core-agent-networking-4.0.31-1.fc26.x86_64.rpm                                                                                                                        2.5 kB/s |  18 kB     00:07    
(2/2): qubes-core-agent-qrexec-4.0.31-1.fc26.x86_64.rpm                                                                                                                            4.2 kB/s |  31 kB     00:07    
-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------
Total                                                                                                                                                                              6.6 kB/s |  48 kB     00:07     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                                                           1/1 
  Reinstalling     : qubes-core-agent-qrexec-4.0.31-1.fc26.x86_64                                                                                                                                              1/4 
  Running scriptlet: qubes-core-agent-qrexec-4.0.31-1.fc26.x86_64                                                                                                                                              1/4 
  Reinstalling     : qubes-core-agent-networking-4.0.31-1.fc26.x86_64                                                                                                                                          2/4 
  Running scriptlet: qubes-core-agent-networking-4.0.31-1.fc26.x86_64                                                                                                                                          2/4 
  Running scriptlet: qubes-core-agent-networking-4.0.31-1.fc26.x86_64                                                                                                                                          3/4 
  Erasing          : qubes-core-agent-networking-4.0.31-1.fc26.x86_64                                                                                                                                          3/4 
  Running scriptlet: qubes-core-agent-qrexec-4.0.31-1.fc26.x86_64                                                                                                                                              4/4 
  Erasing          : qubes-core-agent-qrexec-4.0.31-1.fc26.x86_64                                                                                                                                              4/4 
  Running scriptlet: qubes-core-agent-qrexec-4.0.31-1.fc26.x86_64                                                                                                                                              4/4 
Running as unit: run-r21efd1e0e5cc42be9bf0f069f3c3f367.service
Running as unit: run-rc82404315ce54b79ab47360bd3454bae.service
  Verifying        : qubes-core-agent-networking-4.0.31-1.fc26.x86_64                                                                                                                                          1/4 
  Verifying        : qubes-core-agent-qrexec-4.0.31-1.fc26.x86_64                                                                                                                                              2/4 
  Verifying        : qubes-core-agent-networking-4.0.31-1.fc26.x86_64                                                                                                                                          3/4 
  Verifying        : qubes-core-agent-qrexec-4.0.31-1.fc26.x86_64                                                                                                                                              4/4 
Notifying dom0 about installed applications

Reinstalled:
  qubes-core-agent-networking.x86_64 4.0.31-1.fc26                                                           qubes-core-agent-qrexec.x86_64 4.0.31-1.fc26                                                          

Complete!

```

Thank you!

**Comment by andrewdavidwong** [comment]
Duplicate of #3926
