### ISSUE TITLE
Microphone stuck & undetachable (GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown)

### ISSUE THREAD

**Issue by nil0x42** [QubesOS/qubes-issues#4054]
### Qubes OS version:

R4.0

### Affected component(s): 

microphone
qvm-device

---

### Steps to reproduce the behavior:

My initial goal was to attach microphone automatically to 'videochat' qube, so i did the following: 
```
[user@dom0 ~]$ qvm-shutdown videochat
[user@dom0 ~]$ qvm-device mic attach --persistent videochat dom0:mic
[user@dom0 ~]$ qvm-start videochat
```

No error, here i was thinking that everything was OK, because `qvm-device mic list` showed that my microphone was used by 'videochat', and sys-usb's tray icon said the same:
```
[user@dom0 ~]$ qvm-device mic list
BACKEND:DEVID  DESCRIPTION  USED BY
dom0:mic       Microphone   videochat
```

After starting 'videochat' qube, my microphone was NOT detected.
I then rebooted my machine in order to see if it resolves the issue, and after that, the mic was shown as attached to videochat as expected, but still not working.
So i resolved to undo the persistent attach as shown here:
```
[user@dom0 ~]$ qvm-device mic detach videochat dom0:mic
Can not remove a persistent attachment from a non halted vm

[user@dom0 ~]$ qvm-shutdown videochat

[user@dom0 ~]$ qvm-device mic detach videochat dom0:mic
Failed to attach microphone: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name org.qubesos.Audio.videochat was not provided by any .service files (2)

[user@dom0 ~]$ qvm-device mic list
BACKEND:DEVID  DESCRIPTION  USED BY
dom0:mic       Microphone   videochat
```

Now, i am totally stuck in that situation, the microphone is stuck in videochat, i cannot detach it, and even in videochat qube it doesn't works.

### Expected behavior:

The microphone works when attached with '--persistent' argument, and can then be detached.

### Actual behavior:

The micropohone is stuck as 'persistently attached', and doesn't work.

### General notes:

I think it's a minor issue that persistent attach didn't worked as expected. For me, the real issue is being stuck in a state where my microphone is 100% unusable.

Note: before trying to to 'persistent attach' of my microphone, it worked fine by manually attaching it to any qube from sys-usb tray icon.

---

**Comment by nil0x42** [comment]
Update: i just resolved my issue with a dirty hack, manually edited `/var/lib/qubes/qubes.xml`, and set mic device to null (`<devices class="mic"/>`) in videochat qube.
After a reboot, everything seems OK, `qvm-device mic list`'s output shows that mic is not in use, and a can attach and detach my microphone manually again.

**Comment by hbswn** [comment]
@ nil0x42

Thanks for this solution !

Apparently the issue still persists.
Maybe difficult to get rid of `--persistent` options ;-)

Anyway, not a big deal if you know what to edit.

Hans

**Comment by SaswatPadhi** [comment]
This issue still persists in R4.1

**Comment by ambdroid** [comment]
Affects 4.1.2. The error is different, though: `Failed to detach audio input from {!s} to {!s}: pulseaudio agent not running`. (The error while running was the same.)
I should note that the domain in question had qubes-gui disabled (via replacing the binary with `false`, being unsure of a more graceful way) and I was using `qvm-start-gui --force-stubdomain` to interact with it.

**Comment by ben-grande** [comment]
Affects R4.2 with the same error message from Dom0.
I am using a custom debian-12-minimal based disposable sys-audio and trying to attach the microphone to the audio client personal-signal.

I have turned off the client domain with the microphone attached and I believe this is causing the error, although I couldn't get the mic to work before anyway, so not sure.

- sys-audio user journal:
```
sys-audio qubes.AudioInputEnable+personal-signal-dom0[953]: socat[955] E connect(, AF=1 "/var/run/qubes/audio-control.personal-signal", 46): Connection refused
```

- dom0 user journarl when using qui-devices:
```
dom0 widget-wrapper[4109]: Traceback (most recent call last):
dom0 widget-wrapper[4109]:   File "/usr/lib/python3.11/site-packages/qui/tray/devices.py", line 89, in attach_item
dom0 widget-wrapper[4109]:     vm_to_attach.devices[menu_item.device.devclass].attach(assignment)
dom0 widget-wrapper[4109]:   File "/usr/lib/python3.11/site-packages/qubesadmin/devices.py", line 158, in attach
dom0 widget-wrapper[4109]:     self._vm.qubesd_call(None,
dom0 widget-wrapper[4109]:   File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 76, in qubesd_call
dom0 widget-wrapper[4109]:     return self.app.qubesd_call(dest, method, arg, payload,
dom0 widget-wrapper[4109]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dom0 widget-wrapper[4109]:   File "/usr/lib/python3.11/site-packages/qubesadmin/app.py", line 770, in qubesd_call
dom0 widget-wrapper[4109]:     return self._parse_qubesd_response(return_data)
dom0 widget-wrapper[4109]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
dom0 widget-wrapper[4109]:   File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 111, in _parse_qubesd_response
dom0 widget-wrapper[4109]:     raise exc_class(format_string, *args)
dom0 widget-wrapper[4109]: qubesadmin.exc.QubesVMError: Failed to attach audio input from sys-audio to personal-signal: pulseaudio agent not running
```

- dom0 `qvm-device mic attach personal-signal dom0:mic` output:
```
Failed to detach audio input from dom0 to personal-signal: pulseaudio agent not running
```

------

After restarting `sys-audio` and the audio client, the device can be attached again, although mic is not working. Audio client journal when trying to record audio with Signal Desktop:
```
pipewire[569]: mod.qubes-audio: Underrun: asked to read 940 bytes but only 0 available
```

Volume output works, but input doesn't.
