### ISSUE TITLE
Qubes Firewall - Got empty response from qubesd.

### ISSUE THREAD

**Issue by fabiogermann** [QubesOS/qubes-issues#4228]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

`qvm-firewall`

---

### Steps to reproduce the behavior:

1. Create list of IP you which to block/allow in firewall (~500 IPs) at /home/user/blockList.sh
2. Run `cat /home/user/blockList.sh  | xargs -I {} qvm-firewall sys-firewall add action=drop dsthost={} expire="+300" comment="blocklist"`

### Expected behavior:

All IPs are blocked/allowed by firewall

### Actual behavior:

After a few successful additions to the firewall rules (~60-100) every following command keeps failing with `Got empty response from qubesd. See journalctl in dom0 for details.`.
When consulting `journalctl` I see:
```
Aug 20 14:10:39 dom0 qubesd[9028]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.firewall.Set' dest=b'sys-firewall' arg=b'' len(untrusted_payload)
Aug 20 14:10:39 dom0 qubesd[9028]: Traceback (most recent call last):
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 262, in respond
Aug 20 14:10:39 dom0 qubesd[9028]:     untrusted_payload=untrusted_payload)
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Aug 20 14:10:39 dom0 qubesd[9028]:     yield self  # This tells Task to wait for completion.
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Aug 20 14:10:39 dom0 qubesd[9028]:     future.result()
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Aug 20 14:10:39 dom0 qubesd[9028]:     raise self._exception
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Aug 20 14:10:39 dom0 qubesd[9028]:     result = coro.send(None)
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 210, in coro
Aug 20 14:10:39 dom0 qubesd[9028]:     res = func(*args, **kw)
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 1303, in vm_firewall_set
Aug 20 14:10:39 dom0 qubesd[9028]:     self.dest.firewall.save()
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/firewall.py", line 588, in save
Aug 20 14:10:39 dom0 qubesd[9028]:     self.vm.fire_event('firewall-changed')
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 198, in fire_event
Aug 20 14:10:39 dom0 qubesd[9028]:     pre_event=pre_event)
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 166, in _fire_event
Aug 20 14:10:39 dom0 qubesd[9028]:     effect = func(self, event, **kwargs)
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/ext/r3compatibility.py", line 79, in on_firewall_changed
Aug 20 14:10:39 dom0 qubesd[9028]:     self.write_iptables_qubesdb_entry(vm.netvm)
Aug 20 14:10:39 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/ext/r3compatibility.py", line 158, in write_iptables_qubesdb_entry
Aug 20 14:10:39 dom0 qubesd[9028]:     iptables)
Aug 20 14:10:39 dom0 qubesd[9028]: qubesdb.Error: (0, 'Error')
```

After a while (when the rules expire) I see the following in the `journalctl`:
```
Aug 20 14:15:34 dom0 qubesd[9028]: Exception in callback Firewall._expire_rules()
Aug 20 14:15:34 dom0 qubesd[9028]: handle: <TimerHandle when=8882.646979272999 Firewall._expire_rules()>
Aug 20 14:15:34 dom0 qubesd[9028]: Traceback (most recent call last):
Aug 20 14:15:34 dom0 qubesd[9028]:   File "/usr/lib64/python3.5/asyncio/events.py", line 127, in _run
Aug 20 14:15:34 dom0 qubesd[9028]:     self._callback(*self._args)
Aug 20 14:15:34 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/firewall.py", line 552, in _expire_rules
Aug 20 14:15:34 dom0 qubesd[9028]:     self.save()
Aug 20 14:15:34 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/firewall.py", line 588, in save
Aug 20 14:15:34 dom0 qubesd[9028]:     self.vm.fire_event('firewall-changed')
Aug 20 14:15:34 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 198, in fire_event
Aug 20 14:15:34 dom0 qubesd[9028]:     pre_event=pre_event)
Aug 20 14:15:34 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/events.py", line 166, in _fire_event
Aug 20 14:15:34 dom0 qubesd[9028]:     effect = func(self, event, **kwargs)
Aug 20 14:15:34 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/ext/r3compatibility.py", line 79, in on_firewall_changed
Aug 20 14:15:34 dom0 qubesd[9028]:     self.write_iptables_qubesdb_entry(vm.netvm)
Aug 20 14:15:34 dom0 qubesd[9028]:   File "/usr/lib/python3.5/site-packages/qubes/ext/r3compatibility.py", line 158, in write_iptables_qubesdb_entry
Aug 20 14:15:34 dom0 qubesd[9028]:     iptables)
Aug 20 14:15:34 dom0 qubesd[9028]: qubesdb.Error: (0, 'Error')
```

### General notes:

Qubes install is up-to-date with current/stable repository (2018-08-20 07:00 CEST).

---

### Related issues:

On qubes-issues i found https://github.com/QubesOS/qubes-issues/issues/3661 which describes a similar issue, but as it is declared as resolved I have to assume it's not the same.

**Comment by andrewdavidwong** [comment]
Possibly related to #1570.

**Comment by fabiogermann** [comment]
Maybe also related to https://github.com/QubesOS/qubes-issues/issues/1570 or https://github.com/QubesOS/qubes-issues/issues/4018
- am I getting this right that it should have been fixed for 4.0 (no limit on rules) and for 3.2 there is a limit? 
To clarify: I created the VMs in 4.0 - no import from 3.2.

**Comment by andrewdavidwong** [comment]
> am I getting this right that it should have been fixed for 4.0 (no limit on rules) and for 3.2 there is a limit?

I think so, based on https://github.com/QubesOS/qubes-issues/issues/1570#issuecomment-261677217.

**Comment by fabiogermann** [comment]
@andrewdavidwong I retested this with the latest Qubes R4.0 (latest patches installed), and I still get the same error. The only difference is that the limit is now approx. 900 to 950. Is there still a known limit?

**Comment by marmarek** [comment]
Does your template on which sys-firewall is based has `qubes-firewall` feature? Check `qvm-features TEMPLATE_NAME`, it should be listed with value `1`.

**Comment by fabiogermann** [comment]
My sys-firewall is based on the fedora-29 template (installed from qubes repo). This template has feature qubes-firewall set to 1.
