### ISSUE TITLE
qui-devices (Qubes Device Widget) failed to start

### ISSUE THREAD

**Issue by wynn1212** [QubesOS/qubes-issues#4386]
### Qubes OS version:

Qubes release 4.0 (R4.0)

### Affected component(s): 

qui-devices (Qubes Device Widget)

---

### Steps to reproduce the behavior:

After update dom0 and reboot
When I entered to my desktop.

### Expected behavior:

qui-devices should start in tray icon and displaying which devices is available to use

### Actual behavior:

qui-devices failed to start.
when I try to run "qui-devices" in terminal, it shows the following error.
```
ERROR:dbus.proxies:Introspect error on org.qubes.Devices1:/org/qubes/Devices1: dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
Traceback (most recent call last):
  File "/usr/bin/qui-devices", line 9, in <module>
    load_entry_point('qui==0.1', 'gui_scripts', 'qui-devices')()
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 363, in main
    app = DevicesTray()
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 344, in __init__
    self.device_manager = qui.models.qubes.DevicesManager()
  File "/usr/lib/python3.5/site-packages/qui/models/qubes.py", line 134, in __init__
    super().__init__(proxy, cls=Device)
  File "/usr/lib/python3.5/site-packages/qui/models/dbus.py", line 168, in __init__
    super(ObjectManager, self).__init__(proxy)
  File "/usr/lib/python3.5/site-packages/qui/models/dbus.py", line 63, in __init__
    super(Model, self).__init__(self._init_interfaces())
  File "/usr/lib/python3.5/site-packages/qui/models/dbus.py", line 74, in _init_interfaces
    xml_str = str(self.proxy.Introspect())
  File "/usr/lib64/python3.5/site-packages/dbus/proxies.py", line 70, in __call__
    return self._proxy_method(*args, **keywords)
  File "/usr/lib64/python3.5/site-packages/dbus/proxies.py", line 145, in __call__
    **keywords)
  File "/usr/lib64/python3.5/site-packages/dbus/connection.py", line 651, in call_blocking
    message, timeout)
dbus.exceptions.DBusException: org.freedesktop.DBus.Error.NoReply: Message recipient disconnected from message bus without replying
```

### General notes:

---

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/updates-status/issues/741 (by not using that dbus service at all).

**Comment by canary5** [comment]
Hi, after todays update, devixe widget gone again

**Comment by andrewdavidwong** [comment]
@canary5, can you provide the names and version numbers of the packages you updated today?

**Comment by canary5** [comment]
Later yesterday i have installed another update (4.0.11-1) of linux managet which fixed it again. 
It was 20 packages installed, please tell which package responsible for device widget, i will look

**Comment by wynn1212** [comment]
desktop-linux-manager responsible for device widget

**Comment by canary5** [comment]
Ok, so 4.0.11-1 fixed it again for me. In previuos update there was no desktop-linux-manager for me
