### ISSUE TITLE
devices widget crashes with AttributeError: 'NoneType' oject has no attribute 'icon'

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4391]
### Qubes OS version:

R4.0

### Affected component(s): 

desktop-linux-manager

---

### Steps to reproduce the behavior:

Unsure, ran system tests for some time.

### Expected behavior:

No crash.

### Actual behavior:

```
Traceback (most recent call last):
  File "/usr/bin/qui-devices", line 9, in <module>
    load_entry_point('qui==0.1', 'gui_scripts', 'qui-devices')()
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 412, in main
    dispatcher.listen_for_events()))
  File "/usr/lib/python3.5/site-packages/gbulb/glib_events.py", line 736, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py", line 126, in listen_for_events
    yield from self._listen_for_events(vm)
  File "/usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py", line 186, in _listen_for_events
    self.handle(subject, event, **kwargs)
  File "/usr/lib/python3.5/site-packages/qubesadmin/events/__init__.py", line 220, in handle
    handler(subject, event, **kwargs)
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 86, in add_vm
    menu_item = DomainMenuItem(self.device, vm, vm in self.frontend_domains)
  File "/usr/lib/python3.5/site-packages/qui/tray/devices.py", line 37, in __init__
    icon = self.vm.label.icon
AttributeError: 'NoneType' object has no attribute 'icon'
```

**Comment by marmarta** [comment]
How did you manage to get a VM with a None label?
