### ISSUE TITLE
qrexec-client hang and prevent dead domain cleanup

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4433]
### Qubes OS version:

R4.0

### Affected component(s): 

core-admin-linux

---

### Steps to reproduce the behavior:

Kill domain when qrexec connection is still establishing. Happens during automated tests.

### Expected behavior:

Domain is cleaned up.

### Actual behavior:

Domain remains visible on `xl list`, without a name:
```
$ xl list
Name                                        ID   Mem VCPUs	State	Time(s)
...
(null)                                    2496     0     2     --p--d      10.7
```

There are few related processes, but the one responsible for this is qrexec-client (killing it cause domain cleanup). Backtrace of hung process:
```
(gdb) bt
#0  0x000075f158071b0d in read () from /lib64/libc.so.6
#1  0x000075f157337d16 in xenevtchn_pending () from /lib64/libxenevtchn.so.1
#2  0x000075f157d7809d in libxenvchan_wait () from /lib64/libxenvchan.so.4.8
#3  0x000075f157d785bb in libxenvchan_read () from /lib64/libxenvchan.so.4.8
#4  0x000075f15834249c in read_vchan_all () from /lib64/libqrexec-utils.so.2
#5  0x00005d71513dd054 in handle_agent_handshake ()
#6  0x00005d71513dcb0c in main ()
```

**Comment by ben-grande** [comment]
Closing as duplicate of:

- https://github.com/qubesos/qubes-issues/issues/9884

Although this issue is older, the other one is linked recently to some issues we had.
