### ISSUE TITLE
command 'qubes-change-keyboard-layout' return non-zero exit status 1

### ISSUE THREAD

**Issue by TNTBOMBOM** [QubesOS/qubes-issues#4434]
### Qubes OS version:

R 4

### Affected component(s): 

Qubes Manager

---

### Steps to reproduce the behavior:

open Qubes Manager , click on the white top keyboard button icon

### Expected behavior:

to change the keyboard layout per VM? (not sure about it)

### Actual behavior:

![keyboardissuequbes](https://user-images.githubusercontent.com/11895339/47542961-6e96b300-d8cf-11e8-81ed-ed92e45d6327.png)

```
----
line: raise exc
func: run_service_for_stdio
line no.: 282
file: /usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py
----
line: input=self.prepare_input_for_vmshell(command, input), **kwargs)
func: run
line no.: 303
file: /usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py
----
line: raise e
func: run
line no.: 306
file: /usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py
----
line: vm.run('qubes-change-keyboard-layout')
func: action_set_keyboard_layout_triggered
line no.: 1111
file: /usr/lib/python3.5/site-packages/qubesmanager/qube_manager.py
```

**Comment by donob4n** [comment]
Could you detail the steps for reproduce it? I tried but it seems working fine for me.

It seems that the problem is outside manager although it could catch the error. Do you see something relevant on journald?

**Comment by TNTBOMBOM** [comment]
> Could you detail the steps for reproduce it? I tried but it seems working fine for me.

actually nothing more simple than what i have mentioned.

**Comment by donob4n** [comment]
Ok, so I can't reproduce it.

**Comment by sptankard** [comment]
This is easily reproducible on my computer. From dom0 qubes manager, I got the same error and trace as @TNTBOMBOM. 

Additionally, if i try to run the utility from inside a qube, i get the following error:

``` shell
user@personal ~> sudo qubes-change-keyboard-layout --layout=us
Traceback (most recent call last):
  File "/usr/bin/qubes-change-keyboard-layout", line 65, in <module>
    apply_choice(cmd_param_layout)
  File "/usr/bin/qubes-change-keyboard-layout", line 31, in apply_choice
    subprocess.check_call(['/etc/X11/xinit/xinitrc.d/qubes-keymap.sh'])
  File "/usr/lib64/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
user@personal ~> 
```

**Comment by sptankard** [comment]
@marmarek I'm not sure that your commit is enough to fix the entire problem. :( After i `chmod 0755` the file, i get a different error: `OSError: [Errno 8] Exec format error`

```shell
user@personal ~> ls -l /etc/X11/xinit/xinitrc.d/qubes-keymap.sh
-rw-r--r-- 1 root root 700 Oct  8 22:06 /etc/X11/xinit/xinitrc.d/qubes-keymap.sh
user@personal ~> sudo qubes-change-keyboard-layout --layout=us
Traceback (most recent call last):
  File "/usr/bin/qubes-change-keyboard-layout", line 65, in <module>
    apply_choice(cmd_param_layout)
  File "/usr/bin/qubes-change-keyboard-layout", line 31, in apply_choice
    subprocess.check_call(['/etc/X11/xinit/xinitrc.d/qubes-keymap.sh'])
  File "/usr/lib64/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 13] Permission denied
user@personal ~> sudo chmod 0755 /etc/X11/xinit/xinitrc.d/qubes-keymap.sh
user@personal ~> ls -l /etc/X11/xinit/xinitrc.d/qubes-keymap.sh
-rwxr-xr-x 1 root root 700 Oct  8 22:06 /etc/X11/xinit/xinitrc.d/qubes-keymap.sh*
user@personal ~> sudo qubes-change-keyboard-layout --layout=us
Traceback (most recent call last):
  File "/usr/bin/qubes-change-keyboard-layout", line 65, in <module>
    apply_choice(cmd_param_layout)
  File "/usr/bin/qubes-change-keyboard-layout", line 31, in apply_choice
    subprocess.check_call(['/etc/X11/xinit/xinitrc.d/qubes-keymap.sh'])
  File "/usr/lib64/python2.7/subprocess.py", line 185, in check_call
    retcode = call(*popenargs, **kwargs)
  File "/usr/lib64/python2.7/subprocess.py", line 172, in call
    return Popen(*popenargs, **kwargs).wait()
  File "/usr/lib64/python2.7/subprocess.py", line 394, in __init__
    errread, errwrite)
  File "/usr/lib64/python2.7/subprocess.py", line 1047, in _execute_child
    raise child_exception
OSError: [Errno 8] Exec format error
user@personal ~> 
```

But much thanks for such a quick fix on the permissions problem!

**Comment by sptankard** [comment]
Oh! Excuse me, please disregard prior comment. Your commit does fix the whole problem. 

(I was getting that error because I didn't add `#!/bin/sh` to my `qubes-keymap.sh`, but your commit takes care of this.)

**Comment by sptankard** [comment]
For those wanting an immediate fix to the problem before the update ships out, open up your template VMs and something like this should work:

```shell
# For FEDORA
# Make a backup
sudo cp /etc/X11/xinit/xinitrc.d/qubes-keymap.sh /etc/X11/xinit/xinitrc.d/qubes-keymap.sh.bak
# Change the permissions to make it executable
sudo chmod 0755 /etc/X11/xinit/xinitrc.d/qubes-keymap.sh

# This next line should add #!/bin/sh to the beginning of the file
sudo echo -e '#!/bin/sh' "\n$(cat /etc/X11/xinit/xinitrc.d/qubes-keymap.sh)" > /etc/X11/xinit/xinitrc.d/qubes-keymap.sh

# Or, you can also just use a text editor to add it :)
sudo gedit /etc/X11/xinit/xinitrc.d/qubes-keymap.sh
```

For Debian the filename is different: `/etc/X11/Xsession.d/90qubes-keymap`, otherwise same commands should work.
