### ISSUE TITLE
Prevent removing storage pool if any VM is using it

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#4454]
### Qubes OS version:

R4.0

### Affected component(s): 

core-admin

---

### Steps to reproduce the behavior:

`qvm-pool --add new-pool ...`
`qvm-create -P new-pool ...`
`qvm-pool --remove new-pool`

### Expected behavior:

`qvm-pool --remove` fails  because is used by a VM

### Actual behavior:

`qvm-pool --remove` actually removes the pool. Everything works until `qubesd` service restart. But the service doesn't start anymore - fails on loading `qubes.xml`:
```
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qubes/app.py", line 1234, in get_pool
    return self.pools[pool]
KeyError: 'new-pool'
During handling of the above exception, another exception occurred:
Traceback (most recent call last):
  File "/usr/bin/qubesd", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubes/tools/qubesd.py", line 33, in main
    args = parser.parse_args(args)
  File "/usr/lib/python3.5/site-packages/qubes/tools/__init__.py", line 362, in parse_args
    offline_mode=namespace.offline_mode)
  File "/usr/lib/python3.5/site-packages/qubes/app.py", line 794, in __init__
    self.load(lock=lock)
  File "/usr/lib/python3.5/site-packages/qubes/app.py", line 903, in load
    vm.fire_event('domain-load')
  File "/usr/lib/python3.5/site-packages/qubes/events.py", line 198, in fire_event
    pre_event=pre_event)
  File "/usr/lib/python3.5/site-packages/qubes/events.py", line 166, in _fire_event
    effect = func(self, event, **kwargs)
  File "/usr/lib/python3.5/site-packages/qubes/vm/qubesvm.py", line 806, in on_domain_init_loaded
    self.storage = qubes.storage.Storage(self)
  File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 362, in __init__
    self.init_volume(name, conf)
  File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 404, in init_volume
    pool = self.vm.app.get_pool(volume_config['pool'])
  File "/usr/lib/python3.5/site-packages/qubes/app.py", line 1236, in get_pool
    raise qubes.exc.QubesException('Unknown storage pool ' + pool)
qubes.exc.QubesException: Unknown storage pool new-pool
```

### General notes:

---

**Comment by GammaSQ** [comment]
I just ran into this issue and fixed it by editing `/var/lib/qubes/qubes.xml`, replacing any occurrence of the deleted group with an existing one. However, now removing the offending VM doesn't work, I get the error `VM default-mgmt-dvm cannot be removed. It is in use as:`

**Comment by marmarek** [comment]
I think your problem is unrelated to this ticket. The default-mgmt-dvm VM is in use because it's set to `management_dispvm` global property. The problem is `qvm-remove` doesn't list it.
