### ISSUE TITLE
Nautilus (Gnome File Manager a.k.a Files) Does Not Show Up in Qubes-related Menus From Fedora 29

### ISSUE THREAD

**Issue by wynn1212** [QubesOS/qubes-issues#4460]
### Qubes OS version:

Qubes Release 4.0 (R4.0)

### Affected component(s): 

Fedora 29 TemplateVM

---

### Steps to reproduce the behavior:

Installing Fedora-29 Templates from templates-itl-testing repo.
Running `nautilus` form Terminal via Fedora-29 Template.

### Expected behavior:

Nautilus opens up and when right click on any file/folder it shows Qubes-related Menus like:Move To Other AppVM..., Edit In DisposableVM, View In DisposableVM, Copy To Other AppVM...

### Actual behavior:

The terminal show the following error:
```
(nautilus:1309): Nautilus-Python-WARNING **: 13:33:00.837: g_module_open libpython failed: /usr/lib64/libpython3.7.so.1.0: cannot open shared object file: No such file or directory
ImportError: could not import gobject (error was: ImportError('/usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError'))

(nautilus:1309): Nautilus-Python-WARNING **: 13:33:00.850: pygobject initialization failed

(nautilus:1309): Nautilus-Python-WARNING **: 13:33:00.850: nautilus_python_init_python failed
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/qvm_convert_img_nautilus.py", line 4, in <module>
    from gi.repository import Nautilus, GObject
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/qvm_copy_nautilus.py", line 3, in <module>
    from gi.repository import Nautilus, GObject
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/qvm_convert_pdf_nautilus.py", line 4, in <module>
    from gi.repository import Nautilus, GObject
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/qvm_dvm_nautilus.py", line 4, in <module>
    from gi.repository import Nautilus, GObject
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError
Traceback (most recent call last):
  File "/usr/share/nautilus-python/extensions/qvm_move_nautilus.py", line 3, in <module>
    from gi.repository import Nautilus, GObject
  File "/usr/lib64/python3.7/site-packages/gi/__init__.py", line 42, in <module>
    from . import _gi
ImportError: /usr/lib64/python3.7/site-packages/gi/_gi.cpython-37m-x86_64-linux-gnu.so: undefined symbol: PyExc_NotImplementedError
```
And Qubes-related menus doesn't show up when right clicking on any file/folder.

### General notes:

The Fedora 29 Template rpm is:`qubes-template-fedora-29-4.0.1-201810300018.noarch.rpm`

---

**Comment by marmarek** [comment]
Related upstream bug report: https://bugzilla.redhat.com/show_bug.cgi?id=1636626, the fix is pending: https://bodhi.fedoraproject.org/updates/FEDORA-2018-068061b361

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.
