### ISSUE TITLE
qvm-create fails to create a TemplateVM

### ISSUE THREAD

**Issue by lynxis** [QubesOS/qubes-issues#4463]
### Qubes OS version:
R4.0

### Affected component(s): 

---

### Steps to reproduce the behavior:
```qvm-create -l blue -t debian-9 -C TemplateVM debian-dev```

**app: Error creating VM: Got empty response from qubesd. See jouirnalctl in dom0 for details.**

```
Nov 02 01:31:31 dom0 qubesd[1831]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Create.TemplateVM' dest=b'dom0' arg=b'debian-9' len(untrusted_payload)=26
Nov 02 01:31:31 dom0 qubesd[1831]: Traceback (most recent call last):
Nov 02 01:31:31 dom0 qubesd[1831]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 262, in respond
Nov 02 01:31:31 dom0 qubesd[1831]:     untrusted_payload=untrusted_payload)
Nov 02 01:31:31 dom0 qubesd[1831]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
Nov 02 01:31:31 dom0 qubesd[1831]:     yield self  # This tells Task to wait for completion.
Nov 02 01:31:31 dom0 qubesd[1831]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
Nov 02 01:31:31 dom0 qubesd[1831]:     future.result()
Nov 02 01:31:31 dom0 qubesd[1831]:   File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
Nov 02 01:31:31 dom0 qubesd[1831]:     raise self._exception
Nov 02 01:31:31 dom0 qubesd[1831]:   File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
Nov 02 01:31:31 dom0 qubesd[1831]:     result = coro.send(None)
Nov 02 01:31:31 dom0 qubesd[1831]:   File "/usr/lib64/python3.5/asyncio/coroutines.py", line 213, in coro
Nov 02 01:31:31 dom0 qubesd[1831]:     res = yield from res
Nov 02 01:31:31 dom0 qubesd[1831]:   File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 998, in _vm_create
Nov 02 01:31:31 dom0 qubesd[1831]:     assert not self.arg
Nov 02 01:31:31 dom0 qubesd[1831]: AssertionError
```

### Expected behavior:
Create the template VM *debian-dev*

### Actual behavior:
fails doing so

**Comment by marmarek** [comment]
Oh, this error message is really wrong.
The problem is that TemplateVM cannot be based on another template (there is no template chaining). But you can clone existing template using qvm-clone tool.

**Comment by lynxis** [comment]
@marmarek How about adding a helpful error message "Use qvm-clone instead."
Is it documented somewhere? (I'ven't found it, but maybe there is one ;)
