### ISSUE TITLE
qubes-core-agent qvm-features-request failing during template build in chroot since qubesdb is not running - Failed connect to local daemon

### ISSUE THREAD

**Issue by adrelanos** [QubesOS/qubes-issues#4469]
Saw this in Debian build log.

https://github.com/QubesOS/updates-status/issues/763

(Whonix is equally affected.)

```
2018-10-30 11:31:39.360767 +0000 build-fedora4: Setting up libmailtools-perl (2.18-1) ...
2018-10-30 11:31:39.460607 +0000 build-fedora4: Setting up qubes-mgmt-salt-vm-connector (4.0.11-1+deb9u1) ...
2018-10-30 11:31:39.591110 +0000 build-fedora4: Setting up qubes-core-agent (4.0.38-1+deb9u1) ...
2018-10-30 11:31:39.854794 +0000 build-fedora4: 
2018-10-30 11:31:39.854836 +0000 build-fedora4: Configuration file '/etc/fstab'
2018-10-30 11:31:39.854856 +0000 build-fedora4:  ==> File on system created by you or by a script.
2018-10-30 11:31:39.854887 +0000 build-fedora4:  ==> File also in package provided by package maintainer.
2018-10-30 11:31:39.854903 +0000 build-fedora4:  ==> Using new file as you requested.
2018-10-30 11:31:39.854926 +0000 build-fedora4: Installing new version of config file /etc/fstab ...
2018-10-30 11:31:43.214081 +0000 build-fedora4: Running in chroot, ignoring request.
2018-10-30 11:31:43.220152 +0000 build-fedora4: Removed /etc/systemd/system/multi-user.target.wants/haveged.service.
2018-10-30 11:31:43.220191 +0000 build-fedora4: Removed /etc/systemd/system/default.target.wants/haveged.service.
2018-10-30 11:31:43.220211 +0000 build-fedora4: Created symlink /etc/systemd/system/multi-user.target.wants/haveged.service -> /etc/systemd/system/haveged.service.
2018-10-30 11:31:43.242018 +0000 build-fedora4: Adding 'diversion of /etc/init/plymouth-shutdown.conf to /etc/init/plymouth-shutdown.conf.qubes-disabled by qubes-core-agent'
2018-10-30 11:31:43.277630 +0000 build-fedora4: Adding 'diversion of /etc/init/prefdm.conf to /etc/init/prefdm.conf.qubes-disabled by qubes-core-agent'
2018-10-30 11:31:43.311067 +0000 build-fedora4: Adding 'diversion of /etc/init/splash-manager.conf to /etc/init/splash-manager.conf.qubes-disabled by qubes-core-agent'
2018-10-30 11:31:43.344785 +0000 build-fedora4: Adding 'diversion of /etc/init/start-ttys.conf to /etc/init/start-ttys.conf.qubes-disabled by qubes-core-agent'
2018-10-30 11:31:43.378808 +0000 build-fedora4: Adding 'diversion of /etc/init/tty.conf to /etc/init/tty.conf.qubes-disabled by qubes-core-agent'
2018-10-30 11:31:43.413195 +0000 build-fedora4: Adding 'diversion of /etc/init/serial.conf to /etc/init/serial.conf.qubes-orig by qubes-core-agent'
2018-10-30 11:31:43.533983 +0000 build-fedora4: Failed connect to local daemon
2018-10-30 11:31:43.563526 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.563569 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.563585 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.563601 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.563613 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.563806 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.589017 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.589060 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.589344 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.589369 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.589382 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.589396 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.619085 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.619127 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.619358 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.619382 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.619395 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.619409 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.644615 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.644658 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.644891 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.644915 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.644928 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.644942 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.674693 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.674745 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.675027 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.675059 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.675076 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.675091 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.704603 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.704644 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.704911 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.704935 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.704949 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.704962 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.734603 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.734644 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.735108 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.735137 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.735151 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.735165 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.774022 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.774064 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.774080 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.774095 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.774107 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.774121 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.808485 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.808526 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.808541 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.808556 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.808568 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.808582 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.846701 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.846743 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.847008 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.847032 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.847046 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.847228 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.876524 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.876565 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.876831 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.876855 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.876868 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.877051 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.920356 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.920397 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.920745 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.920771 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.920785 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.921040 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.950540 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.950582 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.950850 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.950875 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.950888 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.951073 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:43.980701 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:43.980742 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:43.980758 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:43.980773 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:43.980786 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:43.981021 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:44.010851 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:44.010902 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:44.011229 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:44.011263 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:44.011279 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:44.011481 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:44.041092 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:44.041136 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:44.041152 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:44.041168 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:44.041180 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:44.041194 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:44.068085 +0000 build-fedora4: Traceback (most recent call last):
2018-10-30 11:31:44.068127 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 81, in <module>
2018-10-30 11:31:44.068324 +0000 build-fedora4:     sys.exit(main())
2018-10-30 11:31:44.068348 +0000 build-fedora4:   File "/usr/bin/qvm-features-request", line 70, in main
2018-10-30 11:31:44.068361 +0000 build-fedora4:     qdb = qubesdb.QubesDB()
2018-10-30 11:31:44.068374 +0000 build-fedora4: qubesdb.Error: (2, 'No such file or directory')
2018-10-30 11:31:45.295392 +0000 build-fedora4: Setting up qubes-input-proxy-sender (1.0.13-1+deb9u1) ...
2018-10-30 11:31:45.446943 +0000 build-fedora4: Setting up qubes-usb-proxy (1.0.19+deb9u1) ...
2018-10-30 11:31:45.628627 +0000 build-fedora4: Setting up xserver-xorg-video-all (1:7.7+19) ...
2018-10-30 11:31:45.716225 +0000 build-fedora4: Setting up cups (2.2.1-8+deb9u2) ...
```

**Comment by marmarek** [comment]
Safe to ignore, as qvm-features-request (and other related) are called also at template installation time by `qubes.PostInstall` service - specifically for the reason it couldn't do anything during template build.
I don't want `2>/dev/null` in all the cases, to see the messages during package updates etc. Maybe qvm-features-request should detect chroot and don't do anything in that case?
