### ISSUE TITLE
Can start any application

### ISSUE THREAD

**Issue by imestin** [QubesOS/qubes-issues#4471]
### Qubes OS version:
R4.0

### Affected component(s): 
All VMs

### Steps to reproduce the behavior:
I try to start any VM, any application, like Terminal, Thunar, etc.

### Expected behavior:
X11 window appears

### Actual behavior:
Nothing happens

### General notes:

XIO: fatal IO error 11 (Resource temporarly unavailabl) on X server
":0.0" after 1462 request (1462 known processed) with 0 events
remaining.

//Can't start any program, no window will show. other vm:

invalid PMaxSize for 0x4a00041 (587/32767)

//same problem. other vm:

open /var/run/qubes/qubes-clipboard.bin.xevent: No such file or
directory
XIO: fatal IO error 4 (Interupted system call) on X server ":0.0" after
4350 requests (4350 known processed) with 0 events remaining.

//I tried to update dom0 previously, but failed and I killed the process with CTRL+ALT+ESC

**Comment by marmarek** [comment]
What happen if you start from dom0 terminal:
```
qvm-run -p sys-firewall xterm
```
(choose a VM with which you have a problem, instead of sys-firewall)

**Comment by imestin** [comment]
@marmarek nothing, if I press CTRL+C it writes:
Traceback (most recent call last):
File "/use/bin/qvm-run", line 5, in <module>
   sys.exit(main))
File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_run.py", line 205, in main
wait_session.communicate(vm.default_user.encode())
File "/usr/lib64/python3.5/subprocess.py", line 795, in communicate self.wait()
File /usr/lib64/python3.5/subprocess.py, line 1399, in wait (pid, sts) = self._try_wait()
File "/usr/lib64/python3.5/subprocess.py", line 1349, in _try_wait (pid, sts) = os.waitpid(self.pid, wait_flags)
KeyboardInterupt

**Comment by marmarek** [comment]
Interrupted update may be the reason - try to restart the update.

If that doesn't help, choose one VM, start it (qvm-start or try any application), then call `qvm-start-gui VMNAME` and see what happens. Normally it should do nothing (as gui daemon should be already started automatically). If that helps for that VM, then something is wrong with automatically starting gui daemon - see if there is `qvm-start-gui --all --watch` process running, maybe restart the system and see again. If applications still doesn't start, see if you get any new details - either on qvm-start-gui output, or in `/var/log/qubes/guid.VMNAME.log` (replace VMNAME with actual VM name).

Does it happen to all templates, or just VMs based on one single template?

**Comment by imestin** [comment]
I updated dom0 from command line. First it prompted an error but after it completed the update.
VM guis still don´t start. 
I restarted system, afterwards there were problems with UEFI boot "no boot media found"
I need to alter boot options in BIOS, after I got to drive encryption screen, the system were loading for like 2 minutes, then i got to Dracut Emergency Shell

_Could not boot
/dev/mapper/qubes_dom0-root does not exist
/dev/qubes_dom0/root does not exist
/dev/qubes_dom0/swap does not exist
Starting Dracut Emergency Shell
Generating "/run/initramfs/dsosreport.txt"Entering emergency mode. Exit the shell to continoue._

**Comment by imestin** [comment]
The keyboard layout changed and it did´t accept my password. Now I got to login

**Comment by imestin** [comment]
/var/log/qubes/guid.VM.log:
_Icon size: 128x128
invalid PMaxSize for 0x4a00041 (587/32767)
invalid PMaxSize for 0x4a00041 (587/32767_

**Comment by imestin** [comment]
Okay... it seems the problem was that, in /etc/qubes/guid.conf, instead of writing a new block in VM: {}
I created a new VM: {} block in the end of file (for enabling full screen)

"Critical: error reading config (/etc/qubes/guid.conf:25): duplicate setting name

Now X server is working.

That was a good learning experience. I could´t imagine that I will get my system working again ever.

Thanks for the help!
