### ISSUE TITLE
gnome-tweaks cannot run on fedora-29 template

### ISSUE THREAD

**Issue by tquest1** [QubesOS/qubes-issues#4575]
### Qubes OS version:

R4.0

### Affected component(s): 

qubes-template-fedora-29 from templates-itl-testing

---

### Steps to reproduce the behavior:

Install and try to start gnome-tweaks

### Expected behavior:

start successfully

### Actual behavior:

```
$ gnome-tweaks
WARNING : Shell not installed or running
WARNING : Error detecting shell
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gtweak/tweaks/tweak_group_shell_extensions.py", line 217, in __init__
    raise Exception("Shell not running or DBus service not available")
Exception: Shell not running or DBus service not available
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/gtweak/app.py", line 30, in do_activate
    self.win = Window(self, model)
  File "/usr/lib/python3.7/site-packages/gtweak/tweakview.py", line 38, in __init__
    self._model.load_tweaks(self)
  File "/usr/lib/python3.7/site-packages/gtweak/tweakmodel.py", line 104, in load_tweaks
    mods = __import__("gtweak.tweaks", globals(), locals(), tweak_files, 0)
  File "/usr/lib/python3.7/site-packages/gtweak/tweaks/tweak_group_general.py", line 14, in <module>
    _shell_not_ubuntu = _shell.mode != 'ubuntu'
AttributeError: 'NoneType' object has no attribute 'mode'
```

### General notes:

gnome-tweaks (or the previous gnome-tweak-tool) has successfully installed & run on previous recent versions of Qubes fedora templates without any problems.
It makes it much easier to install or tryout different gtk / icon themes & fonts & font-aliasing.

As a workaround I run this from the terminal:

```
gsettings set org.gnome.desktop.interface gtk-theme Arc && gsettings set org.gnome.desktop.interface icon-theme Papirus && gsettings set org.gnome.settings-daemon.plugins.xsettings antialiasing 'rgba' && gsettings set org.gnome.settings-daemon.plugins.xsettings hinting 'slight' && gsettings set org.gnome.desktop.interface font-name 'Noto Sans 11' && gsettings set org.gnome.desktop.interface document-font-name 'Noto Sans Regular 11' && gsettings set org.gnome.desktop.interface monospace-font-name 'Source Code Pro Medium 13'
```

---

**Comment by andrewdavidwong** [comment]
Not sure if this is actually a Qubes issue.

**Comment by marmarek** [comment]
Looks like `gnome-tweaks` doesn't like to be started outside of GNOME. But according to [project page](https://gitlab.gnome.org/GNOME/gnome-tweaks#supported-desktops) it should be supported:
```
Tweaks is designed for GNOME Shell but can be used in other desktops. A few features will be missing when Tweaks is run on a different desktop.
```
Reported upstream: https://gitlab.gnome.org/GNOME/gnome-tweaks/issues/192
