### ISSUE TITLE
Qubes dnf hooks in the Fedora template breakage

### ISSUE THREAD

**Issue by noseshimself** [QubesOS/qubes-issues#4592]
### Qubes OS version:

4.0

### Affected component(s): 

---

### Steps to reproduce the behavior:

Update a Fedora (29) template to 20181209's state.
Reboot the template.
Install something else.

### Expected behavior:

Installation being executed

### Actual behavior:

```
# dnf install qubes-u2f
Fedora Modular 29 - x86_64 - Updates             14 kB/s |  24 kB     00:01    
Fedora 29 - x86_64 - Updates                     33 kB/s |  24 kB     00:00    
Dependencies resolved.
================================================================================
 Package             Arch   Version                 Repository             Size
================================================================================
Installing:
 qubes-u2f           noarch 1.2.3-1.fc29            qubes-vm-r4.0-current 265 k
Installing dependencies:
 hidapi              x86_64 0.8.0-0.10.d17db57.fc29 fedora                 43 k
 python3-hidapi      x86_64 0.7.99.post20-10.fc29   fedora                 52 k
 python3-u2flib-host noarch 3.0.3-2.fc29            qubes-vm-r4.0-current  48 k

Transaction Summary
================================================================================
Install  4 Packages

Total download size: 409 k
Installed size: 616 k
Is this ok [y/N]: y
Downloading Packages:
(1/4): hidapi-0.8.0-0.10.d17db57.fc29.x86_64.rp 170 kB/s |  43 kB     00:00    
(2/4): python3-hidapi-0.7.99.post20-10.fc29.x86 129 kB/s |  52 kB     00:00    
(3/4): python3-u2flib-host-3.0.3-2.fc29.noarch.  77 kB/s |  48 kB     00:00    
(4/4): qubes-u2f-1.2.3-1.fc29.noarch.rpm        610 kB/s | 265 kB     00:00    
--------------------------------------------------------------------------------
Total                                           230 kB/s | 409 kB     00:01     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Installing       : hidapi-0.8.0-0.10.d17db57.fc29.x86_64                  1/4 
  Installing       : python3-hidapi-0.7.99.post20-10.fc29.x86_64            2/4 
  Installing       : python3-u2flib-host-3.0.3-2.fc29.noarch                3/4 
  Installing       : qubes-u2f-1.2.3-1.fc29.noarch                          4/4 
  Running scriptlet: qubes-u2f-1.2.3-1.fc29.noarch                          4/4 
  Verifying        : hidapi-0.8.0-0.10.d17db57.fc29.x86_64                  1/4 
  Verifying        : python3-hidapi-0.7.99.post20-10.fc29.x86_64            2/4 
  Verifying        : python3-u2flib-host-3.0.3-2.fc29.noarch                3/4 
  Verifying        : qubes-u2f-1.2.3-1.fc29.noarch                          4/4 
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 123, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 154, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.7/site-packages/dnf/cli/cli.py", line 237, in do_transaction
    tid = super(BaseCli, self).do_transaction(display)
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 862, in do_transaction
    self._plugins.run_transaction()
  File "/usr/lib/python3.7/site-packages/dnf/plugin.py", line 100, in fn
    dnf.util.mapall(operator.methodcaller(method), self.plugins)
  File "/usr/lib/python3.7/site-packages/dnf/util.py", line 264, in mapall
    return list(map(fn, *seq))
  File "/usr/lib/python3.7/site-packages/dnf-plugins/qubes-hooks.py", line 54, in transaction
    for pkg in item.installs():
AttributeError: 'RPMTransactionItemWrapper' object has no attribute 'installs'
```

### General notes:

---

**Comment by mossy-nw** [comment]
I also experience this error whenever updating or installing new packages to the fedora-29 template (and derivatives) that ship with Qubes 4.0.1_rc1

**Comment by marmarek** [comment]
Update in current-testing already fix this: https://github.com/QubesOS/updates-status/issues/827 (specifically this commit: https://github.com/QubesOS/qubes-core-agent-linux/commit/8d7313b)

**Comment by mossy-nw** [comment]
thank you!

**Comment by mossy-nw** [comment]
Sorry to reopen this, but unforunately in fedora-29 templates I run `sudo dnf update --enablerepo=qubes-vm-r4.0-current-testing` and indeed it installs new packages but I get what looks to be the identical error:

~~~
Traceback (most recent call last):
  File "/usr/bin/dnf", line 58, in <module>
    main.user_main(sys.argv[1:], exit_code=True)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 179, in user_main
    errcode = main(args)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 64, in main
    return _main(base, args, cli_class, option_parser_class)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 99, in _main
    return cli_run(cli, base)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 123, in cli_run
    ret = resolving(cli, base)
  File "/usr/lib/python3.7/site-packages/dnf/cli/main.py", line 154, in resolving
    base.do_transaction(display=displays)
  File "/usr/lib/python3.7/site-packages/dnf/cli/cli.py", line 237, in do_transaction
    tid = super(BaseCli, self).do_transaction(display)
  File "/usr/lib/python3.7/site-packages/dnf/base.py", line 862, in do_transaction
    self._plugins.run_transaction()
  File "/usr/lib/python3.7/site-packages/dnf/plugin.py", line 100, in fn
    dnf.util.mapall(operator.methodcaller(method), self.plugins)
  File "/usr/lib/python3.7/site-packages/dnf/util.py", line 264, in mapall
    return list(map(fn, *seq))
  File "/usr/lib/python3.7/site-packages/dnf-plugins/qubes-hooks.py", line 54, in transaction
    query = base.sack.query()
AttributeError: 'RPMTransactionItemWrapper' object has no attribute 'installs'
~~~

**Comment by marmarek** [comment]
dnf loads plugins on startup, so the run during which update is installed still use the old one.
