### ISSUE TITLE
qvm-backup traceback when backup list includes nonexistent VMs

### ISSUE THREAD

**Issue by andrewdavidwong** [QubesOS/qubes-issues#4654]
### Qubes OS version:

`R3.2`

### Affected component(s): 

`qvm-backup`

---

### Steps to reproduce the behavior:

Attempt to use `qvm-backup` on a nonexistent VM. For example, delete `oldappvm`, then do:

```
$ qvm-backup --encrypt --compress --dest-vm=backupvm /home/user/ oldappvm
```

### Expected behavior:

An error message that explains why the backup cannot proceed:
```
$ qvm-backup --encrypt --compress --dest-vm=backupvm /home/user/ oldappvm
Error: No qube named 'oldappvm' was found.
```

### Actual behavior:

Traceback:
```
$ qvm-backup --encrypt --compress --dest-vm=backupvm /home/user/ oldappvm
Traceback (most recent call last):
  File "/usr/bin/qvm-backup", line 218, in <module>
    main()
  File "/usr/bin/qvm-backup", line 127, in main
    hide_vm_names=options.encrypt)
  File "/usr/lib64/python2.7/site-packages/qubes/backup.py", line 154, in backup_prepare
    vms_for_backup = [vm for vm in vms_list if vm.name not in exclude_list]
AttributeError: 'NoneType' object has no attribute 'name'
```

### General notes:

A more informative error message would be especially helpful when passing a list of VMs, e.g.:
```
$ qvm-backup --encrypt --compress --dest-vm=backupvm /home/user/ `cat vm-list.txt`
```
In this case, it may be difficult to know which VMs in `vm-list.txt` were not found. An error message that includes the names of the VMs that were not found would help the user to know which names should be removed from `vm-list.txt`.

---

**Comment by andrewdavidwong** [comment]
This issue is being closed because:

 - This issue has the "Release 3.2 updates" milestone.
 - [Qubes OS 3.2 has reached end-of-life (EOL).](https://www.qubes-os.org/news/2019/03/28/qubes-3-2-has-reached-eol/)
 - This issue has not been updated in over a year.

If anyone believes that this issue should be reopened, please let us know in a comment here.
