### ISSUE TITLE
qubes-core-admin-client - missing dependency python3-yaml

### ISSUE THREAD

**Issue by heinrich-ulbricht** [QubesOS/qubes-issues#4666]
### Qubes OS version:

Qubes 4

### Affected component(s): 

qubes-core-admin-client in AppVM

---

### Steps to reproduce the behavior:

Install qubes-core-admin-client in a Fedora 28-based AppVM. Run qvm-backup.

An error is shown: 

```
Traceback (most recent call last):
  File "/usr/bin/qvm-backup", line 2, in <module>
    from qubesadmin.tools.qvm_backup import main
  File "/usr/lib/python3.6/site-packages/qubesadmin/tools/qvm_backup.py", line 29, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'
```

**Solution**: `sudo dnf install python3-yaml`

### Expected behavior:

I expected qvm-backup to work after installing qubes-core-admin-client.

### Actual behavior:

I had to dnf install python3-yaml to get qvm-backup running.

**Comment by marmarek** [comment]
Oh, I didn't noticed you assigned it to yourself @fepitre and already and made a PR already.

**Comment by fepitre** [comment]
I was about to modify also the rpm macro

**Comment by fepitre** [comment]
I had not the time to open the PR :) . Use your one.
