### ISSUE TITLE
Fedora 29 selinux-policy-minimum fails update

### ISSUE THREAD

**Issue by chillingfx** [QubesOS/qubes-issues#4699]
### Qubes OS version:

R4.0

### Affected component(s): 

fedora-29-template

---

### Steps to reproduce the behavior:

`sudo dnf update` on freshly installed fedora-29-template from the qubes repo

### Expected behavior:

update run without problems

### Actual behavior:

the result shows this error:
```bash
  Running scriptlet: selinux-policy-minimum-3.14.2-44.fc29.noarch        77/256 
Traceback (most recent call last):
  File "/usr/sbin/semanage", line 28, in <module>
    import seobject
  File "/usr/lib/python3.7/site-packages/seobject.py", line 1039, in <module>
    class portRecords(semanageRecords):
  File "/usr/lib/python3.7/site-packages/seobject.py", line 1041, in portRecords
    valid_types = list(list(sepolicy.info(sepolicy.ATTRIBUTE, "port_type"))[0]["types"])
  File "/usr/lib/python3.7/site-packages/sepolicy/__init__.py", line 197, in <genexpr>
    return ({
  File "/usr/lib64/python3.7/site-packages/setools/typeattrquery.py", line 65, in results
    for attr in self.policy.typeattributes():
AttributeError: 'NoneType' object has no attribute 'typeattributes'

  Running scriptlet: tpm2-abrmd-selinux-2.0.0-2.fc29.noarch              78/256 
  Installing       : tpm2-abrmd-selinux-2.0.0-2.fc29.noarch              78/256 
  Running scriptlet: tpm2-abrmd-selinux-2.0.0-2.fc29.noarch              78/256 
Failed to resolve roletype statement at /var/lib/selinux/targeted/tmp/modules/200/tabrmd/cil:2
/usr/sbin/semodule:  Failed!
```

### General notes:

none

---

### Related issues:

none found

**Comment by marmarek** [comment]
Fedora upstream issue, details here: https://bugzilla.redhat.com/show_bug.cgi?id=1558861

**Comment by andrewdavidwong** [comment]
Closing as "not our bug." If you believe this is a mistake, please leave a comment, and we'll be happy to take another look. Thank you.

**Comment by marmarek** [comment]
According to the upstream bug tracker, the fix is in Fedora 29 stable.
