### ISSUE TITLE
Cannot Update debian-9 and fedora-29 on Qubes 4.0.1

### ISSUE THREAD

**Issue by scoobyscrappy** [QubesOS/qubes-issues#4714]
### Qubes OS version:

4.0.1 (clean install)

### Affected component(s): 

Debian-9 and Fedora-29 Template Updates

---

### Steps to reproduce the behavior:

Start Qube Manager
Right-click debian-9 and select Update Qube
Right-click fedora-29 and select Update Qube

Select debian-9 template terminal: sudo apt-get update
Select fedora-29 template terminal: sudo dnf update

### Expected behavior:

Update debian-9 and fedora-29 templates and remove pending updates from Qube Manager.

### Actual behavior:

I got the same errors when I terminal into the debian-9 and fedora-29 templates.  

Here is the errors I got from the debian-9 update:

Jan 13 09:30:09 localhost systemd[1]: Started Forward connection to updates prox
y over Qubes RPC (127.0.0.1:59084).
Jan 13 09:30:09 localhost systemd[1]: Started Forward connection to updates prox
y over Qubes RPC (127.0.0.1:59086).
Jan 13 09:30:09 localhost systemd[1]: qubes-updates-proxy-forwarder@0-127.0.0.1:
8082-127.0.0.1:59082.service: Main process exited, code=exited, status=1/FAILURE
Jan 13 09:30:09 localhost systemd[1]: qubes-updates-proxy-forwarder@0-127.0.0.1:
8082-127.0.0.1:59082.service: Unit entered failed state.
Jan 13 09:30:09 localhost systemd[1]: qubes-updates-proxy-forwarder@0-127.0.0.1:
8082-127.0.0.1:59082.service: Failed with result 'exit-code'.

Here is the errors I get from fedora-29:

2019-01-13T17:34:39Z DEBUG Unknown configuration value: failovermethod=priority
in /etc/yum.repos.d/fedora.repo; Configuration: OptionBinding with id "failoverm
ethod" does not exist
2019-01-13T17:34:39Z DEBUG repo: downloading from remote: fedora-modular
2019-01-13T17:34:39Z DEBUG error: Curl error (56): Failure when receiving data f
rom the peer for https://mirrors.fedoraproject.org/metalink?repo=fedora-modular-
29&arch=x86_64 [Received HTTP code 500 from proxy after CONNECT] (https://mirror
s.fedoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64).
2019-01-13T17:34:39Z DEBUG Cannot download 'https://mirrors.fedoraproject.org/me
talink?repo=fedora-modular-29&arch=x86_64': Cannot prepare internal mirrorlist:
Curl error (56): Failure when receiving data from the peer for https://mirrors.f
edoraproject.org/metalink?repo=fedora-modular-29&arch=x86_64 [Received HTTP code
 500 from proxy after CONNECT].
2019-01-13T17:34:39Z DDEBUG Cleaning up.
2019-01-13T17:34:39Z SUBDEBUG
Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/dnf/repo.py", line 566, in load
    ret = self._repo.load()
  File "/usr/lib64/python3.7/site-packages/libdnf/repo.py", line 503, in load
    return _repo.Repo_load(self)
RuntimeError: Failed to synchronize cache for repo 'fedora-modular'

### General notes:

---

**Comment by ArjTP** [comment]
How to solve this issue?

**Comment by 0spinboson** [comment]
it reads like a connectivity issue. Both update fine here.

**Comment by marmarek** [comment]
Looks like updates proxy doesn't work. See what VM you have set for those templates in `/etc/qubes-rpc/policy/qubes.UpdatesProxy` (see [documentation](https://www.qubes-os.org/doc/software-update-vm/#technical-details-r40)) - the line with `target=...`. Check if that VM exists and can be started.
