### ISSUE TITLE
Race condition in qubesd on VM removal: qvm-ls & qvm-block ls

### ISSUE THREAD

**Issue by 3hhh** [QubesOS/qubes-issues#5105]
### Qubes OS version:

4.0

### Affected component(s) or functionality:
qubesd

---

### Steps to reproduce the behavior:
Shut down a disposable VM while `qvm-ls` is running.

### Expected or desired behavior:

`qvm-ls` prints a list of VMs.

### Actual behavior:

`qvm-ls` errors out (I guess only sometimes).

### General notes:

```
Jun 18 09:41:33 dom0 qubesd[1684]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.List' dest=b'disp2932' arg=b'' len(untrusted_payload)=0
Jun 18 09:41:33 dom0 qubesd[1684]: Traceback (most recent call last):
Jun 18 09:41:33 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 264, in respond
Jun 18 09:41:33 dom0 qubesd[1684]:     self.send_event)
Jun 18 09:41:33 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 125, in __init__
Jun 18 09:41:33 dom0 qubesd[1684]:     self.dest = self.app.domains[dest.decode('ascii')]
Jun 18 09:41:33 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 467, in __getitem__
Jun 18 09:41:33 dom0 qubesd[1684]:     raise KeyError(key)
Jun 18 09:41:33 dom0 qubesd[1684]: KeyError: 'disp2932'
Jun 18 09:41:33 dom0 qubesd[1684]: Removing volume root: appvms/disp2932/root
Jun 18 09:41:33 dom0 qubesd[1684]: Removing volume private: appvms/disp2932/private
Jun 18 09:41:33 dom0 qubesd[1684]: Removing volume volatile: appvms/disp2932/volatile
Jun 18 09:41:33 dom0 qubesd[1684]: Removing volume kernel: 4.19.43-1
Jun 18 09:41:34 dom0 qubesd[1684]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.property.Get' dest=b'disp2932' arg=b'template' len(untrusted_payload)=0
Jun 18 09:41:34 dom0 qubesd[1684]: Traceback (most recent call last):
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 264, in respond
Jun 18 09:41:34 dom0 qubesd[1684]:     self.send_event)
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 125, in __init__
Jun 18 09:41:34 dom0 qubesd[1684]:     self.dest = self.app.domains[dest.decode('ascii')]
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 467, in __getitem__
Jun 18 09:41:34 dom0 qubesd[1684]:     raise KeyError(key)
Jun 18 09:41:34 dom0 qubesd[1684]: KeyError: 'disp2932'
Jun 18 09:41:34 dom0 qubesd[1684]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.property.Get' dest=b'disp2932' arg=b'netvm' len(untrusted_payload)=0
Jun 18 09:41:34 dom0 qubesd[1684]: Traceback (most recent call last):
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 264, in respond
Jun 18 09:41:34 dom0 qubesd[1684]:     self.send_event)
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 125, in __init__
Jun 18 09:41:34 dom0 qubesd[1684]:     self.dest = self.app.domains[dest.decode('ascii')]
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 467, in __getitem__
Jun 18 09:41:34 dom0 qubesd[1684]:     raise KeyError(key)
Jun 18 09:41:34 dom0 qubesd[1684]: KeyError: 'disp2932'
Jun 18 09:41:34 dom0 qubesd[1684]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.property.Get' dest=b'disp2932' arg=b'ip' len(untrusted_payload)=0
Jun 18 09:41:34 dom0 qubesd[1684]: Traceback (most recent call last):
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 264, in respond
Jun 18 09:41:34 dom0 qubesd[1684]:     self.send_event)
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 125, in __init__
Jun 18 09:41:34 dom0 qubesd[1684]:     self.dest = self.app.domains[dest.decode('ascii')]
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 467, in __getitem__
Jun 18 09:41:34 dom0 qubesd[1684]:     raise KeyError(key)
Jun 18 09:41:34 dom0 qubesd[1684]: KeyError: 'disp2932'
Jun 18 09:41:34 dom0 qubesd[1684]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.volume.List' dest=b'disp2932' arg=b'' len(untrusted_payload)=0
Jun 18 09:41:34 dom0 qubesd[1684]: Traceback (most recent call last):
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 264, in respond
Jun 18 09:41:34 dom0 qubesd[1684]:     self.send_event)
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 125, in __init__
Jun 18 09:41:34 dom0 qubesd[1684]:     self.dest = self.app.domains[dest.decode('ascii')]
Jun 18 09:41:34 dom0 qubesd[1684]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 467, in __getitem__
Jun 18 09:41:34 dom0 qubesd[1684]:     raise KeyError(key)
Jun 18 09:41:34 dom0 qubesd[1684]: KeyError: 'disp2932'
```

---

### I have consulted the following relevant [documentation](https://www.qubes-os.org/doc/):
none

### I am aware of the following related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues:
none

**Comment by 3hhh** [comment]
Unfortunately this one is not fixed yet.

Moreover I noticed that it also happens for `qvm-block ls`.

To reproduce:
1. Start multiple disposable VMs.
2. Run the following dom0 script:
```{.bash}
#!/bin/bash
while : ; do
	qvm-block ls > /dev/null
	#qvm-ls --no-spinner -O NAME,TEMPLATE,NETVM,IP,PRIV-USED,ROOT-USED,CLASS,LABEL,STATE > /dev/null
	echo -n $?
done
```
3. Close the disposable VM windows.

Multiple errors will occur for `qvm-block ls` (reproducible on every close for me) and after a while you'll also get some for `qvm-ls` (took me a few tries & multiple disposable VMs). The journal will not show any error message anymore - I guess that message was removed.

Examples:

`qvm-block ls`:
```
./testbug 
00000000000000Got empty response from qubesd. See journalctl in dom0 for details.
1Got empty response from qubesd. See journalctl in dom0 for details.
10Got empty response from qubesd. See journalctl in dom0 for details.
```

`qvm-ls`:
```
./testbug 
0000000000Traceback (most recent call last):
  File "/usr/bin/qvm-ls", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 649, in main
    table.write_table(sys.stdout)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 421, in write_table
    table_data.append(self.get_row(vm))
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 405, in get_row
    ret.append(col.cell(vm))
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 85, in cell
    value = self.format(vm) or '-'
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 106, in format
    ret = self._attr(vm)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 364, in <lambda>
    attr=(lambda vm: calc_used(vm, 'private')),
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 324, in calc_used
    size = calc_size(vm, volume_name)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 311, in calc_size
    return vm.volumes[volume_name].size // 1024 // 1024
  File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 245, in volumes
    self._method_dest, 'admin.vm.volume.List')
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 68, in qubesd_call
    payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 597, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 81, in _parse_qubesd_response
    'Got empty response from qubesd. See journalctl in dom0 for '
qubesadmin.exc.QubesDaemonNoResponseError: Got empty response from qubesd. See journalctl in dom0 for details.
100000000000000Killed
```

Side note: I didn't manage to break `qvm-run` that way.

@marmarek: fyi
@andrewdavidwong: Please re-open.

**Comment by 3hhh** [comment]
I randomly hit into this one again while removing a shut down non-disposable VM via `qvm-remove`.

So there is a high likelihood that the removal of VMs is still causing this bug.

**Comment by 3hhh** [comment]
Still observing this one almost every day.

**Comment by 3hhh** [comment]
After testing it again and reviewing @marmarek 's [fix](https://github.com/QubesOS/qubes-core-admin/commit/370cfb5d822bebb740ff50dddc9109b3d11e90d3) I can confirm that the fix works on the server side (permission denied errors come up in `journalctl`).

However it doesn't help on the client side (`qvm-ls` & `qvm-block ls`) as the exception cannot be handled by the client (generic "empty response in qubesd" exception).
Ideally the client should e.g. be able to remove invalid data from its result or at least try again at a later point in time when qubesd can provide valid results.

The way it is now I'll probably write a wrapper that continuously retries qvm-ls & qvm-block ls whenever they return a non-zero exit code. Obviously that includes other errors as well and might just result in pointless endless loops. Alternatively i could check journalctl from my app whether it actually hits into this one (ofc only works for dom0 adminVM).

--------------------------------------------------------------
Latest test results:

qvm-block ls:
```
0Got empty response from qubesd. See journalctl in dom0 for details.
10Got empty response from qubesd. See journalctl in dom0 for details.
1Failed to list 'block' devices, this device type either does not exist or you do not have access to it.
100000^


Apr 07 20:20:34 dom0 qubesd[2169]: permission denied for call b'admin.vm.device.block.Available'+b'' (b'dom0' → b'disp5738') with payload of 0 bytes
Apr 07 20:20:34 dom0 qubesd[2169]: permission denied for call b'admin.vm.device.block.List'+b'' (b'dom0' → b'disp5738') with payload of 0 bytes
```

qvm-ls:
```
00Traceback (most recent call last):
  File "/usr/bin/qvm-ls", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 649, in main
    table.write_table(sys.stdout)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 421, in write_table
    table_data.append(self.get_row(vm))
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 405, in get_row
    ret.append(col.cell(vm))
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 85, in cell
    value = self.format(vm) or '-'
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 106, in format
    ret = self._attr(vm)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 364, in <lambda>
    attr=(lambda vm: calc_used(vm, 'private')),
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 324, in calc_used
    size = calc_size(vm, volume_name)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 311, in calc_size
    return vm.volumes[volume_name].size // 1024 // 1024
  File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 245, in volumes
    self._method_dest, 'admin.vm.volume.List')
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 68, in qubesd_call
    payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 597, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 81, in _parse_qubesd_response
    'Got empty response from qubesd. See journalctl in dom0 for '
qubesadmin.exc.QubesDaemonNoResponseError: Got empty response from qubesd. See journalctl in dom0 for details.
100000Traceback (most recent call last):
  File "/usr/bin/qvm-ls", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 649, in main
    table.write_table(sys.stdout)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 421, in write_table
    table_data.append(self.get_row(vm))
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 405, in get_row
    ret.append(col.cell(vm))
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 85, in cell
    value = self.format(vm) or '-'
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 106, in format
    ret = self._attr(vm)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 364, in <lambda>
    attr=(lambda vm: calc_used(vm, 'private')),
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 324, in calc_used
    size = calc_size(vm, volume_name)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_ls.py", line 311, in calc_size
    return vm.volumes[volume_name].size // 1024 // 1024
  File "/usr/lib/python3.5/site-packages/qubesadmin/vm/__init__.py", line 245, in volumes
    self._method_dest, 'admin.vm.volume.List')
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 68, in qubesd_call
    payload_stream)
  File "/usr/lib/python3.5/site-packages/qubesadmin/app.py", line 597, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.5/site-packages/qubesadmin/base.py", line 81, in _parse_qubesd_response
    'Got empty response from qubesd. See journalctl in dom0 for '
qubesadmin.exc.QubesDaemonNoResponseError: Got empty response from qubesd. See journalctl in dom0 for details.
10000Killed

Apr 07 20:30:00 dom0 qrexec[9582]: qubes.WindowIconUpdater: disp2636 -> dom0: denied: qrexec-client failed
Apr 07 20:30:01 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'klass' (b'dom0' → b'disp5666') with payload of 0 bytes
Apr 07 20:30:01 dom0 qrexec[28141]: qubes.WindowIconUpdater: disp5376 -> dom0: denied: qrexec-client failed
Apr 07 20:30:01 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'klass' (b'dom0' → b'disp2636') with payload of 0 bytes
Apr 07 20:30:08 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'template' (b'dom0' → b'disp2636') with payload of 0 bytes
Apr 07 20:30:08 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'netvm' (b'dom0' → b'disp2636') with payload of 0 bytes
Apr 07 20:30:08 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'ip' (b'dom0' → b'disp2636') with payload of 0 bytes
Apr 07 20:30:08 dom0 qubesd[2169]: permission denied for call b'admin.vm.volume.List'+b'' (b'dom0' → b'disp2636') with payload of 0 bytes
Apr 07 20:30:21 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'template' (b'dom0' → b'disp1041') with payload of 0 bytes
Apr 07 20:30:21 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'netvm' (b'dom0' → b'disp1041') with payload of 0 bytes
Apr 07 20:30:21 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'ip' (b'dom0' → b'disp1041') with payload of 0 bytes
Apr 07 20:30:21 dom0 qubesd[2169]: permission denied for call b'admin.vm.volume.List'+b'' (b'dom0' → b'disp1041') with payload of 0 bytes
Apr 07 20:30:21 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'template' (b'dom0' → b'disp1041') with payload of 0 bytes
Apr 07 20:30:21 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'netvm' (b'dom0' → b'disp1041') with payload of 0 bytes
Apr 07 20:30:21 dom0 qubesd[2169]: permission denied for call b'admin.vm.property.Get'+b'ip' (b'dom0' → b'disp1041') with payload of 0 bytes
Apr 07 20:30:21 dom0 qubesd[2169]: permission denied for call b'admin.vm.volume.List'+b'' (b'dom0' → b'disp1041') with payload of 0 bytes
Apr 07 20:30:27 dom0 qrexec[30287]: qubes.WindowIconUpdater: disp1041 -> dom0: denied: qrexec-client failed
```
