### ISSUE TITLE
Qubes Disk Space widget went missing, python module throws error

### ISSUE THREAD

**Issue by heinrich-ulbricht** [QubesOS/qubes-issues#5145]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
Qubes disk space widget

**Brief summary**
The disk space widget is missing. My assumption is that this widget should be displayed.

Some time long ago it was there. Then, also long ago, it disappeared. I never thought about this but now I need it back. 

**To Reproduce**
Since the widget just disappeared long time ago I have no repro.

**Expected behavior**
The widget should display disk size information.

**Actual behavior**
Widget is missing.

**Solutions you've tried**
I found [a case where the device widget disappeared](https://groups.google.com/forum/#!topic/qubes-users/7pKRr4E7h40) for a user after updating Qubes. There I read how to start those tray widgets via python. For the disk space widget I assume the command would be this: `python3 -mqui.tray.disk_space`

When trying this (assuming disk_space is the module I need) I get this error:

```
[user@dom0 tray]$ python3 -mqui.tray.disk_space
Traceback (most recent call last):
  File "/usr/lib64/python3.5/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/lib/python3.5/site-packages/qui/tray/disk_space.py", line 211, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qui/tray/disk_space.py", line 206, in main
    app = DiskSpace()
  File "/usr/lib/python3.5/site-packages/qui/tray/disk_space.py", line 99, in __init__
    self.refresh_icon()
  File "/usr/lib/python3.5/site-packages/qui/tray/disk_space.py", line 106, in refresh_icon
    pool_data = PoolUsageData()
  File "/usr/lib/python3.5/site-packages/qui/tray/disk_space.py", line 23, in __init__
    self.__populate_pools()
  File "/usr/lib/python3.5/site-packages/qui/tray/disk_space.py", line 32, in __populate_pools
    if pool.usage/pool.size >= URGENT_WARN_LEVEL:
ZeroDivisionError: division by zero

```
This does not look good, right?

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
https://groups.google.com/forum/#!topic/qubes-users/7pKRr4E7h40 ??

**Comment by marmarta** [comment]
Definitely not good. Hopefully we have not created any black holes through dividing by zero. I'll make a fix promptly :)

**Comment by heinrich-ulbricht** [comment]
Wow, this was quick - thank you :D

(This also makes my question here obsolete, but at first I wasn't sure I was looking in the right place: https://github.com/QubesOS/qubes-issues/issues/693#issuecomment-508952293)

**Comment by heinrich-ulbricht** [comment]
@marmarta To test this I changed the code according to your commit. Now the widget appears. But when clicking the disk icon in the tray nothing happens and another error appears:

```
[user@dom0 tray]$ python3 -mqui.tray.disk_space
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qui/tray/disk_space.py", line 150, in make_menu
    for (label1, label2, label3) in pool_data.get_pools_widgets():
  File "/usr/lib/python3.5/site-packages/qui/tray/disk_space.py", line 39, in get_pools_widgets
    yield self.__create_box(p)
  File "/usr/lib/python3.5/site-packages/qui/tray/disk_space.py", line 56, in __create_box
    percentage = pool.usage/pool.size
ZeroDivisionError: division by zero
```
Another use of pool.size, which is zero.

**Comment by brendanhoar** [comment]
I ran into this when I had a temporary (ephemerally encrypted) pool and had a hard shutdown. The widget wouldn't run until I removed qubes' record of the no longer existing pool via qvm-pool. 

I'll test the scenario as soon as this is pushed into current-test.
