### ISSUE TITLE
BrokenPipeError when running qubes-dom0-update

### ISSUE THREAD

**Issue by n0sign4l** [QubesOS/qubes-issues#5153]
**Qubes OS version**
R 4.0

**Affected component(s) or functionality**
Qubes update

**Brief summary**
if I run `sudo qubes-dom0-update` I get this:

```
sudo qubes-dom0-update
Using sys-whonix as UpdateVM to download updates for Dom0; this may take some time...
Traceback (most recent call last):
  File "/bin/qvm-run", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_run.py", line 263, in main
    proc, copy_proc, local_proc = run_command_single(args, vm)
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_run.py", line 180, in run_command_single
    proc.stdin.flush()
BrokenPipeError: [Errno 32] Broken pipe
```

**To Reproduce**
_Steps to reproduce the behavior:_
_1. update qube sand get that error

**Expected behavior**
should update

**Actual behavior**
OS doesn't update

**Comment by andrewdavidwong** [comment]
Possibly related: #5121
