### ISSUE TITLE
Resizing DispVM private volume stack traces 

### ISSUE THREAD

**Issue by jpouellet** [QubesOS/qubes-issues#5219]
**Qubes OS version**

R4.0.2-rc1

```
[user@dom0 ~]$ rpm -qf `which qubesd`
qubes-core-dom0-4.0.45-1.fc25.x86_64
```

**Affected component(s) or functionality**

qubesd

**Brief summary**

Resizing a currently-running DispVM's private volume results in stack traces like the following from qubesd:

```
unhandled exception while calling src=b'dom0' meth=b'admin.vm.volume.Resize' dest=b'disp6416' arg=b'private' len(untrusted_payload)=10
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 266, in respond
    untrusted_payload=untrusted_payload)
  File "/usr/lib64/python3.5/asyncio/futures.py", line 381, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 310, in _wakeup
    future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/qubes/api/admin.py", line 461, in vm_volume_resize
    yield from self.dest.storage.resize(self.arg, size)
  File "/usr/lib/python3.5/site-packages/qubes/storage/__init__.py", line 494, in resize
    yield from ret
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 285, in wrapper
    return (yield from method(self, *args, **kwargs))
  File "/usr/lib/python3.5/site-packages/qubes/storage/lvm.py", line 625, in resize
    if size < self.size:
TypeError: unorderable types: int() < str()
```

**To Reproduce**

This can be triggered via both the `qubes-vm-settings` GUI, or `qvm-volume resize ...`, e.g.:

```
[user@dom0 ~]$ qvm-volume resize disp6416:private $(($(qvm-volume info disp6416:private size) + 1024 * 1024 ))
Got empty response from qubesd. See journalctl in dom0 for details.
```

**Expected behavior**

When resizing currently running non-DispVMs, things work fine:

```
[user@dom0 ~]$ qvm-volume resize testvm:private $(($(qvm-volume info testvm:private size) + 1024 * 1024 ))
```

with journalctl output:
```
No longer monitoring thin pool qubes_dom0-pool00-tpool.
Monitoring thin pool qubes_dom0-pool00-tpool.
xen-blkback: VBD Resize: Domid: 32, Device: (253, 49)
xen-blkback: VBD Resize: new size 20979712
```

**Actual behavior**

DispVM private volumes fail to resize, with details as above.

**Comment by iprid23** [comment]
Confirming this on R4.0.1 as well.
