### ISSUE TITLE
qrexec: AttributeError: 'DBusAskResolution' object has no attribute 'target'

### ISSUE THREAD

**Issue by marmarta** [QubesOS/qubes-issues#5228]
**Qubes OS version**
4.0

**Affected component(s) or functionality**
core-qrexec

**Brief summary**
```
Traceback (most recent call last):
  File "/home/user/qrexec/qubes-core-qrexec-4.1.1-1.fc29.x86_64/usr/lib/python3.7/site-packages/qrexec/tools/qrexec_policy_daemon.py", line 93, in handle_client_connection
    result = handle_request(**args, log=log, path=policy_path)
  File "/home/user/qrexec/qubes-core-qrexec-4.1.1-1.fc29.x86_64/usr/lib/python3.7/site-packages/qrexec/tools/qrexec_policy_exec.py", line 164, in handle_request
    log.info('%s allowed to %s', log_prefix, resolution.target)
AttributeError: 'DBusAskResolution' object has no attribute 'target'
```

**To Reproduce**
policy call that asks (with an accept)

**Comment by marmarek** [comment]
Fixed in https://github.com/QubesOS/qubes-core-qrexec/commit/bd2c5813
