### ISSUE TITLE
qvm-console-dispvm doesn’t work at all

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#5362]
**Qubes OS version**
`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**
`qvm-console-dispvm`

**Brief summary**
`qvm-console-dispvm` doesn’t work at all.

**To Reproduce**
Run `qvm-console-dispvm` with any VM as the target.

**Expected behavior**
A console window pops up.

**Actual behavior**
The DispVM launches and then immediately exits.  The dom0 terminal shows a Python exception.

**Screenshots**
_If applicable, add screenshots to help explain your problem._

**Additional context**
The `qvm-console` solution I came up with on my own does work.

**Solutions you've tried**
Use my own scripts, which predate `qvm-console-dispvm`.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by fepitre** [comment]
Something like this ?:
Traceback (most recent call last):
  File "/bin/qubesd-query", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.5/site-packages/qubes/tools/qubesd_query.py", line 94, in main
    returncode = loop.run_until_complete(coro)
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 467, in run_until_complete
    return future.result()
  File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
    raise self._exception
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
    result = coro.send(None)
  File "/usr/lib/python3.5/site-packages/qubes/tools/qubesd_query.py", line 66, in qubesd_client
    returncode = int(header_data)
ValueError: invalid literal for int() with base 10: b''

**Comment by DemiMarie** [comment]
@fepitre Correct.

**Comment by DemiMarie** [comment]
@marmarek @marmarta I am hesitant (for security reasons) to use my personal solution on an untrusted VM.

**Comment by fepitre** [comment]
I got this in journalctl:
```
Sep 30 15:07:08 dom0 qubesd[29466]: unhandled exception while calling src=b'' meth=b'admin.vm.Console' dest=b'sys-net' arg=b'' len(untrusted_payload)=0
Sep 30 15:07:08 dom0 qubesd[29466]: Traceback (most recent call last):
Sep 30 15:07:08 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 264, in respond
Sep 30 15:07:08 dom0 qubesd[29466]:     self.send_event)
Sep 30 15:07:08 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 122, in __init__
Sep 30 15:07:08 dom0 qubesd[29466]:     self.src = self.app.domains[src.decode('ascii')]
Sep 30 15:07:08 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 470, in __getitem__
Sep 30 15:07:08 dom0 qubesd[29466]:     raise KeyError(key)
Sep 30 15:07:08 dom0 qubesd[29466]: KeyError: ''
Sep 30 15:07:11 dom0 qubesd[29466]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.device.block.Available' dest=b'disp4414' arg=b'' len(untrusted_payload)=0
Sep 30 15:07:11 dom0 qubesd[29466]: Traceback (most recent call last):
Sep 30 15:07:11 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 264, in respond
Sep 30 15:07:11 dom0 qubesd[29466]:     self.send_event)
Sep 30 15:07:11 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 125, in __init__
Sep 30 15:07:11 dom0 qubesd[29466]:     self.dest = self.app.domains[dest.decode('ascii')]
Sep 30 15:07:11 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 470, in __getitem__
Sep 30 15:07:11 dom0 qubesd[29466]:     raise KeyError(key)
Sep 30 15:07:11 dom0 qubesd[29466]: KeyError: 'disp4414'
Sep 30 15:07:11 dom0 qubesd[29466]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.List' dest=b'disp4414' arg=b'' len(untrusted_payload)=0
Sep 30 15:07:11 dom0 qubesd[29466]: Traceback (most recent call last):
Sep 30 15:07:11 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 264, in respond
Sep 30 15:07:11 dom0 qubesd[29466]:     self.send_event)
Sep 30 15:07:11 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 125, in __init__
Sep 30 15:07:11 dom0 qubesd[29466]:     self.dest = self.app.domains[dest.decode('ascii')]
Sep 30 15:07:11 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 470, in __getitem__
Sep 30 15:07:11 dom0 qubesd[29466]:     raise KeyError(key)
Sep 30 15:07:11 dom0 qubesd[29466]: KeyError: 'disp4414'
Sep 30 15:07:11 dom0 qubesd[29466]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.volume.Info' dest=b'disp4414' arg=b'root' len(untrusted_payload)=0
Sep 30 15:07:11 dom0 qubesd[29466]: Traceback (most recent call last):
Sep 30 15:07:11 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 264, in respond
Sep 30 15:07:11 dom0 qubesd[29466]:     self.send_event)
Sep 30 15:07:11 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/api/__init__.py", line 125, in __init__
Sep 30 15:07:11 dom0 qubesd[29466]:     self.dest = self.app.domains[dest.decode('ascii')]
Sep 30 15:07:11 dom0 qubesd[29466]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 470, in __getitem__
Sep 30 15:07:11 dom0 qubesd[29466]:     raise KeyError(key)
Sep 30 15:07:11 dom0 qubesd[29466]: KeyError: 'disp4414'
```

**Comment by fepitre** [comment]
Don't worry, it's not a big deal. It's just related to qubesdb.

(Sorry I edited your comment by error)

**Comment by fepitre** [comment]
@marmarek: it's related to https://github.com/QubesOS/qubes-issues/issues/5030
