### ISSUE TITLE
Use backup files as an optional format of built templates

### ISSUE THREAD

**Issue by zaoqi** [QubesOS/qubes-issues#5467]
**The problem you're addressing (if any)**
worried that the generated rpm will do something to dom0.

**Describe the solution you'd like**
Use backup files as an optional format of built templates

**Where is the value to a user, and who might that user be?**

**Describe alternatives you've considered**

**Additional context**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/building-archlinux-template/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by marmarek** [comment]
>  worried that the generated rpm will do something to dom0.

This is valid point, but we plan to solve it differently: https://github.com/QubesOS/qubes-issues/issues/2534
Specifically, if you install `qubes-core-admin-client` package in a VM, and setup qrexec policy according to [this post](https://www.qubes-os.org/news/2017/06/27/qubes-admin-api/#simple-management-vm-demo) (and allow `admin.vm.Create.TemplateVM` too), it's already possible to install template rpm in a VM. The package installation will use Admin API to create the actual template in dom0, while the whole rpm parsing will be nicely sandboxed in a VM. There are few catches (like, menu entries won't be automatically created - you need to press "Refresh Applications" button in a vm settings), but generally this is one of the solutions we're going to do. The setup procedure (qrexec policy etc) will be automated of course.

**Comment by zaoqi** [comment]
I've add these 2 lines to `/etc/qubes-rpc/policy/admin.vm.Create.TemplateVM`
```
Q-admin-T-installer @anyvm allow,target=dom0
Q-admin-T-installer dom0 allow,target=dom0
```
but it doesn't work
```
[user@Q-admin-T-installer ~]$ sudo dnf reinstall QubesIncoming/Q-arch-T-builder/qubes-template-archlinux-4.0.1-202001190008.noarch.rpm 
Last metadata expiration check: 0:32:21 ago on Sun Jan 19 08:54:02 2020.
Dependencies resolved.
=========================================================================================================================================================================
 Package                                          Architecture                   Version                                      Repository                            Size
=========================================================================================================================================================================
Reinstalling:
 qubes-template-archlinux                         noarch                         4.0.1-202001190008                           @commandline                         625 M

Transaction Summary
=========================================================================================================================================================================

Total size: 625 M
Installed size: 2.7 G
Is this ok [y/N]: y
Downloading Packages:
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                                                                                                                 1/1 
  Running scriptlet: qubes-template-archlinux-4.0.1-202001190008.noarch                                                                                              1/2 
  Reinstalling     : qubes-template-archlinux-4.0.1-202001190008.noarch                                                                                              1/2 
  Running scriptlet: qubes-template-archlinux-4.0.1-202001190008.noarch                                                                                              1/2 
Traceback (most recent call last):
  File "/bin/qvm-template-postprocess", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.7/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 310, in main
    loop.run_until_complete(post_install(args))
  File "/usr/lib64/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "/usr/lib/python3.7/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 212, in post_install
    vm = app.domains[args.name]
  File "/usr/lib/python3.7/site-packages/qubesadmin/app.py", line 90, in __getitem__
    if not self.app.blind_mode and item not in self:
  File "/usr/lib/python3.7/site-packages/qubesadmin/app.py", line 113, in __contains__
    self.refresh_cache()
  File "/usr/lib/python3.7/site-packages/qubesadmin/app.py", line 62, in refresh_cache
    'admin.vm.List'
  File "/usr/lib/python3.7/site-packages/qubesadmin/app.py", line 668, in qubesd_call
    'Service call error: %s', stderr.decode())
qubesadmin.exc.QubesDaemonNoResponseError: Service call error: Request refused

warning: %post(qubes-template-archlinux-4.0.1-202001190008.noarch) scriptlet failed, exit status 1

Error in POSTIN scriptlet in rpm package qubes-template-archlinux
  Running scriptlet: qubes-template-archlinux-4.0.1-202001190008.noarch                                                                                              2/2 
  Cleanup          : qubes-template-archlinux-4.0.1-202001190008.noarch                                                                                              2/2 
  Verifying        : qubes-template-archlinux-4.0.1-202001190008.noarch                                                                                              1/2 
  Verifying        : qubes-template-archlinux-4.0.1-202001190008.noarch                                                                                              2/2 
Last metadata expiration check: 0:38:40 ago on Sun Jan 19 08:54:02 2020.
Notifying dom0 about installed applications

Reinstalled:
  qubes-template-archlinux-4.0.1-202001190008.noarch                                                                                                                     

Complete!
```

**Comment by marmarek** [comment]
> I've add these 2 lines to `/etc/qubes-rpc/policy/admin.vm.Create.TemplateVM`

This is not enough, you need also give permission to configure the VM and check its state. See linked post - the thing I've mentioned is needed _in addition_ to what is described there.
