### ISSUE TITLE
qubes.StartApp fails to start Kate

### ISSUE THREAD

**Issue by Rudd-O** [QubesOS/qubes-issues#5559]
Qubes 4.0.

Qubes-core-agent 4.0.50-1.fc30.

Launching Kate from the menu does not produce anything — the app won't start.

VM where Kate is supposed to launch shows this in the journal log:

```
Jan 05 17:36:01 myvm qubes.StartApp+org.kde.kate-dom0[2008]: Traceback (most recent call last):
Jan 05 17:36:01 myvm qubes.StartApp+org.kde.kate-dom0[2008]:   File "/usr/bin/qubes-desktop-run", line 7, in <module>
Jan 05 17:36:01 myvm qubes.StartApp+org.kde.kate-dom0[2008]:     launch(*sys.argv[1:])
Jan 05 17:36:01 -myvm qubes.StartApp+org.kde.kate-dom0[2008]:   File "/usr/lib/python2.7/site-packages/qubesagent/xdg.py", line 17, in launch
Jan 05 17:36:01 myvm qubes.StartApp+org.kde.kate-dom0[2008]:     launcher = Gio.DesktopAppInfo.new_from_filename(desktop)
Jan 05 17:36:01 myvm qubes.StartApp+org.kde.kate-dom0[2008]: TypeError: constructor returned NULL
```
The contents of the Kate desktop file:

```
[Desktop Entry]
GenericName=Advanced Text Editor
GenericName[ar]=محرّر نصوص متقدّم
GenericName[ast]=Editor avanzáu de testu
GenericName[bg]=Усъвършенстван текстов редактор
GenericName[bs]=Napredni uređivač teksta
GenericName[ca]=Editor de text avançat
GenericName[ca@valencia]=Editor de text avançat
GenericName[cs]=Pokročilý textový editor
GenericName[da]=Avanceret teksteditor
GenericName[de]=Erweiterter Texteditor
GenericName[el]=Προχωρημένος επεξεργαστής κειμένου
GenericName[en_GB]=Advanced Text Editor
GenericName[es]=Editor de texto avanzado
GenericName[et]=Täiustatud tekstiredaktor
GenericName[eu]=Testu-editore aurreratua
GenericName[fi]=Kehittynyt tekstimuokkain
GenericName[fr]=Éditeur de texte avancé
GenericName[ga]=Ardeagarthóir Téacs
GenericName[gl]=Editor avanzado de textos
GenericName[he]=עורך טקסט מתקדם
GenericName[hr]=Napredni uređivač teksta
GenericName[hu]=Speciális szövegszerkesztő
GenericName[ia]=Editor avantiate de texto
GenericName[id]=Pengedit Teks Canggih
GenericName[is]=Þróaður textaritill
GenericName[it]=Editor di testi avanzato
GenericName[ja]=高度なテキストエディタ
GenericName[kk]=здік мтін редакторы
GenericName[km]=កម្មវិធី​និពន្ធ​អត្ថបទ​កម្រិត​ខ្ពស់
GenericName[ko]=고급 텍스트 편집기
GenericName[lt]=Sudėtingesnis teksto redaktorius
GenericName[lv]=Jaudīgs teksta redaktors
GenericName[mr]=प्रगत पाठ्य संपादक
GenericName[nb]=Avansert skriveprogram
GenericName[nds]=Verwiedert Texteditor
GenericName[ne]=उन्नत पाठ सम्पादक
GenericName[nl]=Geavanceerde teksteditor
GenericName[nn]=Avansert skriveprogram
GenericName[pa]=ਤਕਨੀਕੀ ਟੈਕਸਟ ਐਡੀਟਰ
GenericName[pl]=Zaawansowany edytor tekstu
GenericName[pt]=Editor de Texto Avançado
GenericName[pt_BR]=Editor de textos avançado
GenericName[ro]=Redactor de text avansat
GenericName[ru]=Улучшенный текстовый редактор
GenericName[si]=උසස් පෙළ සකසනය
GenericName[sk]=Pokročilý textový editor
GenericName[sl]=Napreden urejevalnik besedil
GenericName[sr]=Напредни уређивач текста
GenericName[sr@ijekavian]=Напредни уређивач текста
GenericName[sr@ijekavianlatin]=Napredni uređivač teksta
GenericName[sr@latin]=Napredni uređivač teksta
GenericName[sv]=Avancerad texteditor
GenericName[tg]=Тариргари матнии бетаршуда
GenericName[tr]=Gelişmiş Metin Düzenleyici
GenericName[ug]=ئالىي تېكىست تەرىرلىۈ
GenericName[uk]=Потужний текстовий редактор
GenericName[vi]=Trình biên tp văn bn nâng cao
GenericName[x-test]=xxAdvanced Text Editorxx
GenericName[zh_CN]=高级文本编辑器
GenericName[zh_TW]=進階文字編輯器
Name=Kate
Name[ar]=كيت
Name[ast]=Kate
Name[be]=Kate
Name[bg]=Kate
Name[bs]=Kate
Name[ca]=Kate
Name[ca@valencia]=Kate
Name[cs]=Kate
Name[da]=Kate
Name[de]=Kate
Name[el]=Kate
Name[en_GB]=Kate
Name[eo]=Kate
Name[es]=Kate
Name[et]=Kate
Name[eu]=Kate
Name[fi]=Kate
Name[fr]=Kate
Name[ga]=Kate
Name[gl]=Kate
Name[he]=Kate
Name[hu]=Kate
Name[ia]=Kate
Name[id]=Kate
Name[it]=Kate
Name[ja]=Kate
Name[kk]=Kate
Name[km]=Kate
Name[ko]=Kate
Name[lt]=Kate
Name[lv]=Kate
Name[mr]=केट
Name[ms]=Kate
Name[nb]=Kate
Name[nds]=Kate
Name[ne]=केट
Name[nl]=Kate
Name[nn]=Kate
Name[pa]=ਕੇਟ
Name[pl]=Kate
Name[pt]=Kate
Name[pt_BR]=Kate
Name[ro]=Kate
Name[ru]=Kate
Name[si]=Kate
Name[sk]=Kate
Name[sl]=Kate
Name[sr]=Кејт
Name[sr@ijekavian]=Кејт
Name[sr@ijekavianlatin]=Kate
Name[sr@latin]=Kate
Name[sv]=Kate
Name[tg]=Кейт
Name[tr]=Kate
Name[ug]=Kate
Name[uk]=Kate
Name[vi]=Kate
Name[wa]=Kate
Name[x-test]=xxKatexx
Name[zh_CN]=Kate
Name[zh_TW]=Kate
Comment=KDE Advanced Text Editor
Comment[ar]=كيت محرّر النّصوص المتقدّم
Comment[ast]=Editor avanzáu de testu de KDE
Comment[ca]=Editor avançat de text pel KDE
Comment[ca@valencia]=Editor avançat de text pel KDE
Comment[cs]=Pokročilý textový editor pro KDE
Comment[da]=KDE Avanceret Tekst Editor
Comment[de]=Erweiterter Texteditor für KDE
Comment[el]=Προχωρημένος επεξεργαστής κειμένου για το KDE
Comment[en_GB]=KDE Advanced Text Editor
Comment[es]=Editor de texto avanzado de KDE
Comment[et]=KDE täiustatud tekstiredaktor
Comment[eu]=KDE testu-editore aurreratua
Comment[fi]=KDE:n kehittynyt tekstimuokkain
Comment[fr]=Éditeur de texte avancé de KDE
Comment[gl]=Editor avanzado de textos de KDE
Comment[he]=עורך טקסט מתקדם של KDE
Comment[hu]=Speciális szövegszerkesztő
Comment[ia]=KDE Advanced Text Editor, i.e. Editor avantiate de texto de KDE
Comment[id]=Pengedit Teks Canggih KDE
Comment[it]=Editor di testi avanzato di KDE
Comment[ko]=KDE 고급 텍스트 편집기
Comment[lt]=Sudėtingesnė KDE rašyklė
Comment[nb]=Avansert skriveprogram for KDE
Comment[nl]=KDE geavanceerde tekstbewerker
Comment[nn]=Avansert skriveprogram for KDE
Comment[pa]=KDE ਤਕਨੀਕੀ ਟੈਕਸਟ ਐਡੀਟਰ
Comment[pl]=Zaawansowany edytor tekstu KDE
Comment[pt]=Editor de Texto Avançado do KDE
Comment[pt_BR]=Editor de texto avançado do KDE
Comment[ru]=Улучшенный текстовый редактор от KDE
Comment[sk]=KDE pokročilý textový editor
Comment[sl]=Napreden urejevalnik besedil za KDE
Comment[sr]=КДЕ‑ов напредни уређивач текста
Comment[sr@ijekavian]=КДЕ‑ов напредни уређивач текста
Comment[sr@ijekavianlatin]=KDE‑ov napredni uređivač teksta
Comment[sr@latin]=KDE‑ov napredni uređivač teksta
Comment[sv]=KDE avancerad texteditor
Comment[tr]=KDE Gelişmiş Metin Düzenleyici
Comment[uk]=Потужний текстовий редактор KDE
Comment[x-test]=xxKDE Advanced Text Editorxx
Comment[zh_CN]=KDE 高级文本编辑器
Comment[zh_TW]=KDE 進階文字編輯器
MimeType=text/plain;
Exec=kate -b %U
StartupNotify=true
X-KDE-HasTempFileOption=true
Icon=kate
X-DocPath=kate/index.html
Type=Application
Terminal=false
InitialPreference=9
X-DBUS-StartupType=Multi
X-DBUS-ServiceName=org.kde.kate
Categories=Qt;KDE;Utility;TextEditor;
```

To reproduce the issue, all you have to do is have a Fedora 30 AppVM whose template has Kate installed, add the icon to the menu of the AppVM, and then attempt to launch it from `dom0`.  (All the icon does is launch the following command: `qvm-run -q -a --service -- yourvm qubes.StartApp+org.kde.kate`)

**Comment by Rudd-O** [comment]
I have managed to work around the issue by deleting the `~/.local/share/applications/org.kde.kate.desktop` file that my AppVM has.  It looks as if, when I run the StartApp command, that file gets recreated, then when the file already exists, if I run the StartApp command once again, I get that traceback again.  Something is funky about that.

Let me investigate a bit more.

**Comment by Rudd-O** [comment]
Aha!

1. Delete file `myvm@~/.local/share/applications/org.kde.kate.desktop`.
2. Run `dom0@qubes.StartApp+org.kde.kate`.
3. Kate launches well, `desktop` parameter to `launch()` function in `xdg.py` contains `/usr/share/applications/org.kde.kate.desktop`.
4. Due to something mysterious I haven't quite figured out, the file `myvm@~/.local/share/applications/org.kde.kate.desktop` gets recreated.
5. Run `dom0@qubes.StartApp+org.kde.kate`.
6. Kate won't launch anymore.
7. Removing the file `myvm@~/.local/share/applications/org.kde.kate.desktop` causes Kate to start again once more, but the file gets recreated.

Something is really weird there!

**Comment by Rudd-O** [comment]
Found the problematic code that creates the `.local` version of `org.kde.kate.desktop`, in `xdg.py`:

```
...
...
    except ImportError:
        pass
    if wait:
        pid_list = []
        flags = GLib.SpawnFlags.SEARCH_PATH | GLib.SpawnFlags.DO_NOT_REAP_CHILD
        launcher.launch_uris_as_manager(files, None, flags, None, None,
                pid_callback, pid_list) # <<< THIS LINE creates the problematic desktop file
        for pid in pid_list:
            os.waitpid(pid, 0)
    else:
        launcher.launch(files, None)
...
...
```

**Comment by marmarek** [comment]
Interesting. I've tried and it works for me - kate starts each time and no desktop file is created in `.local`. I suspect it may depend on some other packages installed.
Anyway, the line you've found should not create any desktop file. I think that's kate itself. Try starting it directly and see if the file is created. Try also `kate -b` as in the desktop file.

**Comment by Rudd-O** [comment]
Will try it right away.

**Comment by Rudd-O** [comment]
Yeah it's Kate.

I think I know what is going on.

Kate is I think creating the desktop file to remember its session, which is a legitimate use of desktop files.  (My use case has a saved session, and Kate uses it to restore the session via the menu:

```
[user@ring2-financial ~]$ cat ./.local/share/applications/org.kde.kate.desktop
[Desktop Action Session d4c143f004d88b7286e6f999dea9d0d7]
Exec=kate -s accounting
Name=accounting
```

Kate is not the only application that does this.  So the code that the Qubes automation is calling needs to be fixed, specifically the code invoked by `Gio.DesktopAppInfo.new_from_filename(desktop)`.

**Comment by Rudd-O** [comment]
https://github.com/frida/glib/blob/master/gio/gdesktopappinfo.c

```
/**
 * g_desktop_app_info_new_from_filename:
 * @filename: (type filename): the path of a desktop file, in the GLib
 *      filename encoding
 *
 * Creates a new #GDesktopAppInfo.
 *
 * Returns: (nullable): a new #GDesktopAppInfo or %NULL on error.
 **/
GDesktopAppInfo *
g_desktop_app_info_new_from_filename (const char *filename)
{
  GDesktopAppInfo *info = NULL;

  info = g_object_new (G_TYPE_DESKTOP_APP_INFO, "filename", filename, NULL);
  if (!g_desktop_app_info_load_file (info))
    {
      g_object_unref (info);
      return NULL;
    }
  return info;
}
```

Imma try something, stand by...

**Comment by Rudd-O** [comment]
EXTRA EXTRA EXTRA interesting, my man.  (To replicate the following, install `gtk3-devel` on a disposable VM).

If the desktop file does not have the infamous `[Desktop action ....]` section, it works!

```
[user@disp9884 ~]$ cat dai.c ; echo --------------- ; gcc dai.c -o dai `pkg-config --cflags --libs gio-unix-2.0` && ./dai ; echo -------------- ; cat .local/share/applications/org.kde.kate.desktop 
#include <stdio.h>
#include <gio/gdesktopappinfo.h>


int main() {

void * appinfo = g_desktop_app_info_new_from_filename ("/home/user/.local/share/applications/org.kde.kate.desktop");
printf("Pointer: %d\n", appinfo);

void * appinfo2 = g_desktop_app_info_new_from_filename ("/usr/share/applications/org.kde.kate.desktop");
printf("Pointer: %d\n", appinfo2);

}
---------------
Pointer: 13879408
Pointer: 13879616
--------------
[Desktop Entry]
Categories=Qt;KDE;Utility;TextEditor;
Comment=KDE Advanced Text Editor
Exec=kate -b %U
GenericName=Advanced Text Editor
Icon=kate
InitialPreference=9
MimeType=text/plain;
Name=Kate
StartupNotify=true
Terminal=false
Type=Application
X-DBUS-ServiceName=org.kde.kate
X-DBUS-StartupType=Multi
X-DocPath=kate/index.html
X-KDE-HasTempFileOption=true
```

BUT, if I add the section:

```
[user@disp9884 ~]$ cat dai.c ; echo --------------- ; gcc dai.c -o dai `pkg-config --cflags --libs gio-unix-2.0` && ./dai ; echo -------------- ; cat .local/share/applications/org.kde.kate.desktop 
#include <stdio.h>
#include <gio/gdesktopappinfo.h>


int main() {

void * appinfo = g_desktop_app_info_new_from_filename ("/home/user/.local/share/applications/org.kde.kate.desktop");
printf("Pointer: %d\n", appinfo);

void * appinfo2 = g_desktop_app_info_new_from_filename ("/usr/share/applications/org.kde.kate.desktop");
printf("Pointer: %d\n", appinfo2);

}
---------------
Pointer: 0
Pointer: 35592512
--------------
[Desktop Action Session d4c143f004d88b7286e6f999dea9d0d7]
Exec=kate -s accounting
Name=accounting

[Desktop Entry]
Actions=Session d4c143f004d88b7286e6f999dea9d0d7;
Categories=Qt;KDE;Utility;TextEditor;
Comment=KDE Advanced Text Editor
Exec=kate -b %U
GenericName=Advanced Text Editor
Icon=kate
InitialPreference=9
MimeType=text/plain;
Name=Kate
StartupNotify=true
Terminal=false
Type=Application
X-DBUS-ServiceName=org.kde.kate
X-DBUS-StartupType=Multi
X-DocPath=kate/index.html
X-KDE-HasTempFileOption=true
```

BOOM, NULL pointer!

God dammit, I hate C!

Yeah this looks like a bug in the Gio library.  I will route to them.

**Comment by Rudd-O** [comment]
I've upstreamed this.  Can we please track the closing of this bug over there before closing here?  They may take a while, and the Qubes OS project may just have to find a workaround for this issue (even if it means munging the desktop file into a temporary file instead).

https://gitlab.gnome.org/GNOME/glib/issues/1987

**Comment by Rudd-O** [comment]
I closed the GNOME bug, it's not their bug, it's a KDE problem.

https://bugs.kde.org/show_bug.cgi?id=415948
