### ISSUE TITLE
Qubes 4.0.3 sometimes stuck/freeze on execution post-install scripts

### ISSUE THREAD

**Issue by ghost** [QubesOS/qubes-issues#5636]
**Qubes OS version**
4.0.3
**Affected templates**
Debian-10, Fedora-30, Whonix-ws-15, Whonix-gw-15
**To Reproduce**
1. download iso from ftp
https://ftp.qubes-os.org/iso/Qubes-R4.0.3-x86_64.iso
2. check xfce4 + debian10 and whonix 15 templates
3. check update qubes via whonix

Here is a journalctl output

```
`Feb 08 21:36:55 dom0 anaconda[1900]: Executing org_qubes_os_initial_setup addon
Feb 08 21:36:55 dom0 program[1900]: Running... /usr/bin/qubes-prefs default-kernel 4.19.94-1
Feb 08 21:36:55 dom0 program[1900]: Running... qvm-template-postprocess --really post-install whonix-gw-15 /var/lib/qubes/vm-templates
Feb 08 21:36:56 dom0 anaconda[1900]: ['qvm-template-postprocess', '--really', 'post-install', 'whonix-gw-15', '/var/lib/qubes/vm-templ
                                     stdout: ""
                                     stderr: "whonix-gw-15: Importing data
                                     Traceback (most recent call last):
                                       File "/usr/bin/qvm-template-postprocess", line 5, in <module>
                                         sys.exit(main())
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 310,
                                         loop.run_until_complete(post_install(args))
                                       File "/usr/lib64/python3.5/asyncio/base_events.py", line 467, in run_until_complete
                                         return future.result()
                                       File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
                                         raise self._exception
                                       File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
                                         result = coro.send(None)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 235,
                                         import_root_img(vm, args.dir)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 83, 
                                         root_size = get_root_img_size(source_dir)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 73, 
                                         raise qubesadmin.exc.QubesException('root.img not found')
                                     qubesadmin.exc.QubesException: root.img not found
                                     "
Feb 08 21:36:56 dom0 program[1900]: Running... qvm-template-postprocess --really post-install fedora-30 /var/lib/qubes/vm-templates/fe
Feb 08 21:36:56 dom0 anaconda[1900]: ['qvm-template-postprocess', '--really', 'post-install', 'fedora-30', '/var/lib/qubes/vm-template
                                     stdout: ""
                                     stderr: "fedora-30: Importing data
                                     Traceback (most recent call last):
                                       File "/usr/bin/qvm-template-postprocess", line 5, in <module>
                                         sys.exit(main())
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 310,
                                         loop.run_until_complete(post_install(args))
                                       File "/usr/lib64/python3.5/asyncio/base_events.py", line 467, in run_until_complete
                                         return future.result()
                                       File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
                                         raise self._exception
                                       File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
                                         result = coro.send(None)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 235,
                                         import_root_img(vm, args.dir)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 83, 
                                         root_size = get_root_img_size(source_dir)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 73, 
                                         raise qubesadmin.exc.QubesException('root.img not found')
                                     qubesadmin.exc.QubesException: root.img not found
                                     "
Feb 08 21:36:56 dom0 program[1900]: Running... qvm-template-postprocess --really post-install whonix-ws-15 /var/lib/qubes/vm-templates
Feb 08 21:36:56 dom0 anaconda[1900]: ['qvm-template-postprocess', '--really', 'post-install', 'whonix-ws-15', '/var/lib/qubes/vm-templ
                                     stdout: ""
                                     stderr: "whonix-ws-15: Importing data
                                     Traceback (most recent call last):
                                       File "/usr/bin/qvm-template-postprocess", line 5, in <module>
                                         sys.exit(main())
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 310,
                                         loop.run_until_complete(post_install(args))
                                       File "/usr/lib64/python3.5/asyncio/base_events.py", line 467, in run_until_complete
                                         return future.result()
                                       File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
                                         raise self._exception
                                       File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
                                         result = coro.send(None)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 235,
                                         import_root_img(vm, args.dir)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 83, 
                                         root_size = get_root_img_size(source_dir)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 73, 
                                         raise qubesadmin.exc.QubesException('root.img not found')
                                     qubesadmin.exc.QubesException: root.img not found
                                     "
Feb 08 21:36:56 dom0 program[1900]: Running... qvm-template-postprocess --really post-install debian-10 /var/lib/qubes/vm-templates/de
Feb 08 21:36:56 dom0 anaconda[1900]: ['qvm-template-postprocess', '--really', 'post-install', 'debian-10', '/var/lib/qubes/vm-template
                                     stdout: ""
                                     stderr: "debian-10: Importing data
                                     Traceback (most recent call last):
                                       File "/usr/bin/qvm-template-postprocess", line 5, in <module>
                                         sys.exit(main())
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 310,
                                         loop.run_until_complete(post_install(args))
                                       File "/usr/lib64/python3.5/asyncio/base_events.py", line 467, in run_until_complete
                                         return future.result()
                                       File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result
                                         raise self._exception
                                       File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step
                                         result = coro.send(None)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 235,
                                         import_root_img(vm, args.dir)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 83, 
                                         root_size = get_root_img_size(source_dir)
                                       File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 73, 
                                         raise qubesadmin.exc.QubesException('root.img not found')
                                     qubesadmin.exc.QubesException: root.img not found
                                     "
Feb 08 21:36:56 dom0 program[1900]: Running... systemctl disable rdisc.service
Feb 08 21:36:56 dom0 systemd[1]: Reloading.
Feb 08 21:36:56 dom0 program[1900]: Running... systemctl stop rdisc.service
Feb 08 21:36:56 dom0 program[1900]: Running... systemctl disable kdump.service
Feb 08 21:36:56 dom0 program[1900]: Running... systemctl stop kdump.service
Feb 08 21:36:56 dom0 program[1900]: Running... systemctl disable libvirt-guests.service
Feb 08 21:36:56 dom0 systemd[1]: Reloading.
Feb 08 21:36:57 dom0 program[1900]: Running... systemctl stop libvirt-guests.service
Feb 08 21:36:57 dom0 program[1900]: Running... systemctl disable salt-minion.service
Feb 08 21:36:57 dom0 systemd[1]: Reloading.
Feb 08 21:36:57 dom0 program[1900]: Running... systemctl stop salt-minion.service
Feb 08 21:36:57 dom0 program[1900]: Running... /usr/bin/qubes-prefs default-template fedora-30
Feb 08 21:36:57 dom0 program[1900]: Running... qubesctl saltutil.clear_cache
```

**Comment by marmarek** [comment]
The fact that all root.img are missing suggests you've completed initial setup already. Did it crashed the first time?

**Comment by 0rb677** [comment]
@marmarek 7-8/10 installs pass successfully, but sometimes...Do you need any other logs? I use only old thinkpads.

**Comment by raf-ets-github** [comment]
Similar issue here, same version.
I have tried:
#1 ensuring no USB storage devices are plugged in
#2 reinstalling, then shutting down and starting from a cold boot
#3 disable creation of VMs personal, work, etc

Often my hardware hard locks up at the "setting up administration VM (dom0)" stage.

I have been doing a clean install each time.

**Comment by raf-ets-github** [comment]
Console:

```
EXT4-fs error (device dm-4): ext4_journal_check_start:61: Detected aborted journal
EXT4-fs (dm-4): Remounting filesystem read-only
/usr/libexec/initial-setup/firstboot-windowmanager: line 22: 2811 Bus error $BINARY "$@"
```

Then the usual error messages you'd expect when a live fs was switched to ro, e.g. from systemd-cat, firstboot-windowmanager, run-initial-setup.

**Comment by marmarek** [comment]
Any errors earlier? Maybe too little space on the disk?

**Comment by raf-ets-github** [comment]
Hello @marmarek - no errors earlier, I'm using the whole of a 240GB SSD.
I have just had the same error again with a clean install.

**Comment by raf-ets-github** [comment]
Let me change the SATA port before taking any more of your time.

**Comment by raf-ets-github** [comment]
Changed the SATA port and cable, now getting "delayed block allocation failed for inode "
Clearly not a Qubes issue, sorry.

**Comment by raf-ets-github** [comment]
@marmarek surprisingly I'm having the same issue on a new hard drive, different cable and port.
This USB image of Qubes has been verified at boot time and has installed correctly on another machine yesterday.
What would be next steps to investigate? The aborted journal error upstream with Redhat?

**Comment by raf-ets-github** [comment]
On a different hard drive and port, with no other drives connected, I have selected custom partitioning and chosen xfs rather than ext4. At the post install configuration my machine hard locks up when preparing the fedora-30 template.

**Comment by raf-ets-github** [comment]
If I reboot and try the post install stage again, I get (with xfs)
```qubes-prefs: error: Failed to connect to qubesd service [errno 2] no such file or directory```

**Comment by raf-ets-github** [comment]
systemctl status qubesd.service reports
start request repeated too quickly / failed with result 'start-limit-hit'
