### ISSUE TITLE
[Build 2020021223-4.1-fedora-31] Updates proxy issue on fedora-31

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5654]
## Observation

openQA test in scenario qubesos-4.1-templates-x86_64-system_tests_network@64bit fails in
[VmUpdates_fedora-31](https://openqa.qubes-os.org/tests/6192/modules/VmUpdates_fedora-31/steps/2)

```
# test_010_update_via_proxy
# failure: 

Traceback (most recent call last):
  File "/usr/lib/python3.7/site-packages/qubes/tests/integ/network.py", line 1534, in test_010_update_via_proxy
    self.install_cmd.format('test-pkg'), self.exit_code_ok)
  File "/usr/lib/python3.7/site-packages/qubes/tests/integ/network.py", line 1311, in assertRunCommandReturnCode
    '{}: {}\n{}'.format(cmd, stdout, stderr))
AssertionError: 1 not found in [0, 100] : dnf install -y test-pkg: b'Test repo                                       132  B/s | 547  B     00:04    \nNo match for argument: test-pkg\n'
b"Errors during downloading metadata for repository 'test':\n  - Status code: 500 for http://localhost:8080/repodata/repomd.xml (IP: 127.0.0.1)\nError: Failed to download metadata for repo 'test': Cannot download repomd.xml: Cannot download repodata/repomd.xml: All mirrors were tried\nIgnoring repositories: test\nError: Unable to find a match: test-pkg\n"

# system-out: 



```

## Test suite description

The test setups a local repository then enable updates proxy and try to install updates.

## Reproducible

Fails since (at least) Build [2020021223-4.1-fedora-31](https://openqa.qubes-os.org/tests/6192) (current job)

## Expected result

Last good: (unknown) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=templates&machine=64bit&test=system_tests_network&version=4.1)

**Comment by marmarek** [comment]
Fixed here: https://github.com/QubesOS/qubes-core-admin/commit/4e6472b018a466740d729c696fb4de0754f328d9#diff-1a16e68b9478e729548746cafaec17f7
