### ISSUE TITLE
qui-domains widget doesn't start if VM icon is missing

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#5854]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
widgets

**Brief summary**
If a vm icon is missing in the current icon theme, qui-domain doesn't start at all. I believe the same applies to qui-devices.

**Comment by marmarek** [comment]
Also, it fails to get `system-file-manager` from icon cache - it's not added there at all.

**Comment by marmarek** [comment]
> Also, it fails to get `system-file-manager` from icon cache - it's not added there at all.

This is still an issue. The exact error is:
```
May 28 20:41:34 dom0 widget-wrapper[5288]: Traceback (most recent call last):
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/bin/qui-domains", line 11, in <module>
May 28 20:41:34 dom0 widget-wrapper[5288]:     load_entry_point('qui==0.1', 'gui_scripts', 'qui-domains')()
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 782, in main
May 28 20:41:34 dom0 widget-wrapper[5288]:     app.run()
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 722, in run
May 28 20:41:34 dom0 widget-wrapper[5288]:     self.initialize_menu()
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 707, in initialize_menu
May 28 20:41:34 dom0 widget-wrapper[5288]:     self.add_domain_item(None, None, vm)
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 595, in add_domain_item
May 28 20:41:34 dom0 widget-wrapper[5288]:     domain_item = DomainMenuItem(vm, self, self.icon_cache, state=state)
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 360, in __init__
May 28 20:41:34 dom0 widget-wrapper[5288]:     self.update_state(state)
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 424, in update_state
May 28 20:41:34 dom0 widget-wrapper[5288]:     self._set_submenu(state)
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 368, in _set_submenu
May 28 20:41:34 dom0 widget-wrapper[5288]:     submenu = StartedMenu(self.vm, self.app, self.icon_cache)
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 252, in __init__
May 28 20:41:34 dom0 widget-wrapper[5288]:     self.add(OpenFileManagerItem(self.vm, icon_cache))
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 228, in __init__
May 28 20:41:34 dom0 widget-wrapper[5288]:     icon_cache.get_icon('system-file-manager'))
May 28 20:41:34 dom0 widget-wrapper[5288]:   File "/usr/lib/python3.8/site-packages/qui/tray/domains.py", line 57, in get_icon
May 28 20:41:34 dom0 widget-wrapper[5288]:     self.icon_files[icon_name], 16, 0)
May 28 20:41:34 dom0 widget-wrapper[5288]: KeyError: 'system-file-manager'
May 28 20:41:34 dom0 widget-wrapper[5287]: exiting with 1
```

**Comment by jpds** [comment]
I'm seeing a similar issue with my fresh r4.1 install, but my error is:

```
gi.repository.GLib.Error: gtk-icon-theme-error-quark: Icon 'templatevm-black' not present in theme Adwaita (0)
```

**Comment by marmarek** [comment]
Yes, this is exactly the same. A fix is on its way (see linked pull request).
