### ISSUE TITLE
Qube Settings not working with dom0 using Fedora 32

### ISSUE THREAD

**Issue by LaurianeMorgue** [QubesOS/qubes-issues#5963]
**Qubes OS version**
R4.1

**Affected component(s) or functionality**
Qube Settings

**Brief summary**
I've updated my Dom0 to Fedora32 with fepitre's help. Everything went on smoothly, but we cannot access the Qube Settings of any Qube using the Qube Manager. However, it works when trying to access the settings with the VM list.

The following Python traceback is obtained:

Traceback (most recent call last):
                                      File "/usr/lib/python3.8/site-packages/qubesmanager/qube_manager.py", line 1082, in action_settings_triggered
                                        self.open_settings(vm, "basic")
                                      File "/usr/lib/python3.8/site-packages/qubesmanager/qube_manager.py", line 1048, in open_settings
                                        settings_window = settings.VMSettingsWindow(
                                      File "/usr/lib/python3.8/site-packages/qubesmanager/settings.py", line 161, in __init__
                                        self.__init_basic_tab__()
                                      File "/usr/lib/python3.8/site-packages/qubesmanager/settings.py", line 373, in __init_basic_tab__
                                        utils.initialize_widget_with_labels(
                                      File "/usr/lib/python3.8/site-packages/qubesmanager/utils.py", line 333, in initialize_widget_with_labels
                                        labels = sorted(qubes_app.labels.values(), key=lambda l: l.index)
                                    AttributeError: 'NoneType' object has no attribute 'labels'

**Comment by marmarta** [comment]
Will be fixed by https://github.com/QubesOS/qubes-manager/pull/245
