### ISSUE TITLE
Survey website throws exception without cookies

### ISSUE THREAD

**Issue by dduenker** [QubesOS/qubes-issues#6136]
**Qubes OS version**
-

**Affected component(s) or functionality**
https://survey.qubes-os.org/

**Brief summary**
The survey website throws an exception with a bunch of php code, when visiting with cookies disabled in firefox via umatrix plugin.

**To Reproduce**

1. Install umatrix plugin in firefox browser
2. disable cookies
3. visit survey
4. click next

**Expected behavior**
The user should be told to enable cookies.

**Actual behavior**
Crash

**Screenshots**
```
CHttpException

The CSRF token could not be verified.

/www/framework/web/CHttpRequest.php(1378)

1366 
1367             if (!empty($maskedUserToken) && $cookies->contains($this->csrfTokenName))
1368             {
1369                 $securityManager=Yii::app()->getSecurityManager();
1370                 $maskedCookieToken=$cookies->itemAt($this->csrfTokenName)->value;
1371                 $cookieToken=$securityManager->unmaskToken($maskedCookieToken);
1372                 $userToken=$securityManager->unmaskToken($maskedUserToken);
1373                 $valid=$cookieToken===$userToken;
1374             }
1375             else
1376                 $valid = false;
1377             if (!$valid)
1378                 throw new CHttpException(400,Yii::t('yii','The CSRF token could not be verified.'));
1379         }
1380     }
1381 
1382 
1383     /**
1384      * Returns the version of the HTTP protocol used by client.
1385      *
1386      * @return string the version of the HTTP protocol.
1387      * @since 1.1.16
1388      */
1389     public function getHttpVersion()
1390     {


	
Stack Trace

#0 | – 										 /www/framework/base/CComponent.php(561): CHttpRequest->validateCsrfToken(CEvent)
-- | --


556                         // an array: 0 - object, 1 - method name
557                         list($object,$method)=$handler;
558                         if(is_string($object))    // static method call
559                             call_user_func($handler,$event);
560                         elseif(method_exists($object,$method))
561                             $object->$method($event);
562                         else
563                             throw new CException(Yii::t('yii','Event "{class}.{event}" is attached with an invalid handler "{handler}".',
564                                 array('{class}'=>get_class($this), '{event}'=>$name, '{handler}'=>$handler[1])));
565                     }
566                     else // PHP 5.3: anonymous function

 
--
#1 | – 										 /www/framework/base/CApplication.php(212): CComponent->raiseEvent("onbeginrequest", CEvent)

207      * Raised right BEFORE the application processes the request.
208      * @param CEvent $event the event parameter
209      */
210     public function onBeginRequest($event)
211     {
212         $this->raiseEvent('onBeginRequest',$event);
213     }
214 
215     /**
216      * Raised right AFTER the application processes the request.
217      * @param CEvent $event the event parameter



 
--
#2 | – 										 /www/framework/base/CApplication.php(183): CApplication->onBeginRequest(CEvent)



178      * Remember to call the parent implementation so that static application components are loaded.
179      */
180     public function run()
181     {
182         if($this->hasEventHandler('onBeginRequest'))
183             $this->onBeginRequest(new CEvent($this));
184         register_shutdown_function(array($this,'end'),0,false);
185         $this->processRequest();
186         if($this->hasEventHandler('onEndRequest'))
187             $this->onEndRequest(new CEvent($this));
188     }

 
--
#3 | – 										 /www/index.php(194): CApplication->run()



189 require_once APPPATH . 'core/LSYii_Application' . EXT;
190 
191 $config = require_once(APPPATH . 'config/internal' . EXT);
192 
193 Yii::$enableIncludePath = false;
194 Yii::createApplication('LSYii_Application', $config)->run();
195 
196 /* End of file index.php */
197 /* Location: ./index.php */



```

**Solutions you've tried**
enabled cookies, which worked, but a good message to the user would be really helpful

**Comment by marmarta** [comment]
@marmarek , can we fix this? Reassigning this to you, as website stuff is the Necronomicon for me.

**Comment by marmarek** [comment]
I fixed it to have nice message instead of a PHP dump. But for some the message may still be not clear that cookies are needed:
```

400: Bad Request
The CSRF token could not be verified.

The request could not be understood by the server due to malformed syntax.Please do not repeat the request without modifications.

If you think this is a server error, please contact Qubes OS surveys admin.
```
