### ISSUE TITLE
qubes-dom0-update broken - bad repomd.xml.metalink?

### ISSUE THREAD

**Issue by icequbes1** [QubesOS/qubes-issues#6342]
**Qubes OS version**
R4.0

**Affected component(s) or functionality**
qubes-dom0-update, current repos (current-testing not affected)

**Brief summary**
yum is throwing an exception downloading the metalink files for Qubes R4.0, this causes dom0 updates to fail altogether.

**How Reproducible**
Unless I have done something bad to my system, very.

**To Reproduce**

1. Run `qubes-dom0-update` from dom0, ensure the `current` repository is in-use

**Expected behavior**
Updates downloaded

**Actual behavior**

Updates fail during downloading of repo metadata, ultimately killing the whole process.

UpdateVM output (red text):

```
$ sudo qubes-dom0-update
...using sys-whonix....
...
qubes-dom0-current/metalink                                 | 1.8 kB  00:00     
Traceback (most recent call last):
  File "/usr/bin/yumdownloader.anondist-orig", line 327, in <module>
    util = YumDownloader()
...
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 738, in _getMetalink
    self._metalink = metalink.MetaLinkRepoMD(result)
  File "/usr/lib/python2.7/dist-packages/yum/metalink.py", line 210, in __init__
    max_connections = int(celem.get("maxconnections"))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Screenshots**

Full output from `/usr/lib/qubes/qubes-download-dom0-update.sh` in UpdateVM:

```
...
+ YUM_COMMAND='yumdownloader --destdir=/var/lib/qubes/dom0-updates/packages --resolve'
+ mkdir -p /var/lib/qubes/dom0-updates/packages
+ set -e
+ '[' 0 = 1 ']'
+ yumdownloader --destdir=/var/lib/qubes/dom0-updates/packages --resolve --installroot /var/lib/qubes/dom0-updates --config=/var/lib/qubes/dom0-updates/etc/yum.conf --setopt=reposdir=/var/lib/qubes/dom0-updates/etc/yum.repos.d --exclude=qubes-template-whonix-ws-15,qubes-template-archlinux,qubes-template-fedora-32-minimal,qubes-template-whonix-gw-15,qubes-template-fedora-32,qubes-template-debian-10 
qubes-dom0-current/metalink                                 | 1.8 kB  00:00     
Traceback (most recent call last):
  File "/usr/bin/yumdownloader.anondist-orig", line 327, in <module>
    util = YumDownloader()
  File "/usr/bin/yumdownloader.anondist-orig", line 71, in __init__
    self.main()
  File "/usr/bin/yumdownloader.anondist-orig", line 94, in main
    self.doUtilYumSetup(opts)
  File "/usr/bin/yumdownloader.anondist-orig", line 296, in doUtilYumSetup
    self._getSacks(archlist=archlist)
  File "/usr/lib/python2.7/dist-packages/yum/__init__.py", line 673, in _getSacks
    self.repos.populateSack(which=repos)
  File "/usr/lib/python2.7/dist-packages/yum/repos.py", line 294, in populateSack
    sack.populate(repo, mdtype, callback, cacheonly)
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 168, in populate
    if self._check_db_version(repo, mydbtype):
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 226, in _check_db_version
    return repo._check_db_version(mdtype)
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 1268, in _check_db_version
    repoXML = self.repoXML
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 1467, in <lambda>
    repoXML = property(fget=lambda self: self._getRepoXML(),
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 1459, in _getRepoXML
    self._loadRepoXML(text=self)
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 1449, in _loadRepoXML
    return self._groupLoadRepoXML(text, self._mdpolicy2mdtypes())
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 1424, in _groupLoadRepoXML
    if self._commonLoadRepoXML(text):
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 1242, in _commonLoadRepoXML
    result = self._getFileRepoXML(local, text)
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 1020, in _getFileRepoXML
    size=102400) # setting max size as 100K
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 835, in _getFile
    result = self.grab.urlgrab(misc.to_utf8(relative), local,
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 531, in <lambda>
    grab = property(lambda self: self._getgrab())
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 526, in _getgrab
    self._setupGrab()
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 496, in _setupGrab
    self._grab = mgclass(self._grabfunc, self.urls,
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 711, in <lambda>
    urls = property(fget=lambda self: self._geturls(),
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 708, in _geturls
    self._baseurlSetup()
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 654, in _baseurlSetup
    mirrorurls.extend(list(self.metalink_data.urls()))
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 751, in <lambda>
    metalink_data = property(fget=lambda self: self._getMetalink(),
  File "/usr/lib/python2.7/dist-packages/yum/yumRepo.py", line 738, in _getMetalink
    self._metalink = metalink.MetaLinkRepoMD(result)
  File "/usr/lib/python2.7/dist-packages/yum/metalink.py", line 210, in __init__
    max_connections = int(celem.get("maxconnections"))
TypeError: int() argument must be a string or a number, not 'NoneType'
```

**Additional context**

Looks like the "maxconnections" attribute in the metalink files is missing causing the exception:

https://yum.qubes-os.org/r4.0/current/dom0/fc25/repodata/repomd.xml.metalink

```
...
            <resources>
                <url>https://yum.qubes-os.org/r4.0/current/dom0/fc25/repodata/repomd.xml</url>
                ...
           </resources>
```

Compared to R4.0 current-testing:

https://yum.qubes-os.org/r4.0/current-testing/dom0/fc25/repodata/repomd.xml.metalink

```
...
            <resources maxconnections="1">
                <url>https://mirrors.edge.kernel.org/qubes/repo/yum/r4.0/current-testing/dom0/fc25/repodata/repomd.xml</url>
                <url>https://yum.qubes-os.org/r4.0/current-testing/dom0/fc25/repodata/repomd.xml</url>
...
```

What confuses me is that the date on the repomd.xml.metalink says 18-Apr-2018, as if it's always been this way?

**Solutions you've tried**

Use `baseurl` instead of `metalink` in /etc/yum/repos.d/qubes-dom0.repo

current-testing works, as it does have a `maxconnections` attribute.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/software-update-dom0/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

None found dealing with metalink issues.

**Comment by marmarek** [comment]
Looks like I had old metalink lying around when uploading packages. Fixed.
