### ISSUE TITLE
Qubes R4 salt changing managment-dispvm fails (Invalid property 'template_for_dispvms')

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6410]
**Qubes OS version**

Latest R4

**Affected component(s) or functionality**

https://github.com/QubesOS/qubes-mgmt-salt-dom0-qvm

**Brief summary**

Changing the `management-dispvm` via saltstack's `qvm.prefs` fails. Doing it through the  `qvm-prefs` tool succeeds.

**How Reproducible**

Always happens

**To Reproduce**

1. In dom0: `qvm-clone default-mgmt-dvm non-default-mgmt-dvm`
2. Create a salt state with the following:

    ```yaml
    qvm-prefs-template:
      qvm.prefs:
        - name: debian-10
        - netvm: none
        - management-dispvm: non-default-mgmt-dvm
    ```
3. Run the state

**Expected behavior**

The state is successfully applied:

```
----------
          ID: qvm-prefs-template
    Function: qvm.prefs
        Name: debian-10
      Result: true
     Comment:
     Started: 04:51:12.213636
    Duration: 83.758 ms
     Changes:   
----------
```

**Actual behavior**

The state fails:

```

----------
          ID: qvm-prefs-template
    Function: qvm.prefs
        Name: debian-10
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 300, in prefs
                  return _state_action('qvm.prefs', name, *varargs, **kwargs)
                File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 144, in _state_action
                  status = __salt__[_action](*varargs, **kwargs)
                File "/var/cache/salt/minion/extmods/modules/ext_module_qvm.py", line 869, in prefs
                  elif args.vm.property_is_default(dest):
                File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 148, in property_is_default
                  None)
                File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 68, in qubesd_call
                  payload_stream)
                File "/usr/lib/python2.7/site-packages/qubesadmin/app.py", line 597, in qubesd_call
                  return self._parse_qubesd_response(return_data)
                File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 102, in _parse_qubesd_response
                  raise exc_class(format_string, *args)
              QubesNoSuchPropertyError: Invalid property 'template_for_dispvms' of debian-10
     Started: 04:51:12.213636
    Duration: 83.758 ms
     Changes:   
----------
```

**Screenshots**

none.

**Additional context**

* [commit](https://github.com/QubesOS/qubes-mgmt-salt-dom0-qvm/commit/9d264668d80670ea7f77b7a0a4a2e2758aca360b) that supposedly added support for this property
* although it should be implemented in code, the [README](https://github.com/QubesOS/qubes-mgmt-salt-dom0-qvm#qvm-prefs) doesn't mention it.

**Solutions you've tried**

The temporary solution is to run the command instead:

```yaml
template-non-default-mgmt-vm:
  cmd.run:
    - name: 'qvm-prefs debian-10 management-dispvm "non-default-mgmt-dvm"'
```

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

* https://github.com/QubesOS/qubes-mgmt-salt-dom0-qvm#qvm-prefs
* https://www.qubes-os.org/doc/salt/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

Didn't find.

**Comment by unman** [comment]
If you look in the docs you'll see that this preference is not (yet)
supported by salt in Qubes.
The error message is bogus, of course - interesting, but bogus.

**Comment by marmarek** [comment]
What works is a legacy name for this property: `dispvm-allowed`...

**Comment by deeplow** [comment]
> If you look in the docs you'll see that this preference is not (yet) supported by salt in Qubes.

**Comment by marmarek** [comment]
Wait, may comment was to another property, please ignore (removed now)

The issue with this error:

>               QubesNoSuchPropertyError: Invalid property 'template_for_dispvms' of debian-10

is setting 'template_for_dispvms' on a TemplateVM (debian-10 here), instead of AppVM (non-default-mgmt-dvm). Is that something you set in your formula?

**Comment by deeplow** [comment]
> is setting 'template_for_dispvms' on a TemplateVM (debian-10 here), instead of AppVM (non-default-mgmt-dvm). Is that something you set in your formula?

I'm still new with salt, but I've now reproduced it with the following steps:

Contents of `/srv/salt/state.sls`:
```
qvm-clone-id:
  qvm.clone:
    - name: non-default-mgmt-dvm
    - source: default-mgmt-dvm

qvm-prefs-template:
  qvm.prefs:
    - name: debian-10
    - management-dispvm: non-default-mgmt-dvm
```

Then I ran it with `sudo qubesctl --show-output state.apply state`

The following is the output:

```shell_session
[user@dom0 ~]$ sudo qubesctl --show-output state.apply state
[ERROR   ] An exception occurred in this state: Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
    **cdata['kwargs'])
  File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
    return f(*args, **kwargs)
  File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 300, in prefs
    return _state_action('qvm.prefs', name, *varargs, **kwargs)
  File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 144, in _state_action
    status = __salt__[_action](*varargs, **kwargs)
  File "/var/cache/salt/minion/extmods/modules/ext_module_qvm.py", line 869, in prefs
    elif args.vm.property_is_default(dest):
  File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 148, in property_is_default
    None)
  File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 68, in qubesd_call
    payload_stream)
  File "/usr/lib/python2.7/site-packages/qubesadmin/app.py", line 597, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 102, in _parse_qubesd_response
    raise exc_class(format_string, *args)
QubesNoSuchPropertyError: Invalid property 'template_for_dispvms' of debian-10

local:
----------
          ID: qvm-clone-id
    Function: qvm.clone
        Name: non-default-mgmt-dvm
      Result: True
     Comment: [SKIP] A VM with the name 'non-default-mgmt-dvm' already exists. None
     Started: 11:08:03.789537
    Duration: 347.553 ms
     Changes:   
----------
          ID: qvm-prefs-template
    Function: qvm.prefs
        Name: debian-10
      Result: False
     Comment: An exception occurred in this state: Traceback (most recent call last):
                File "/usr/lib/python2.7/site-packages/salt/state.py", line 1837, in call
                  **cdata['kwargs'])
                File "/usr/lib/python2.7/site-packages/salt/loader.py", line 1794, in wrapper
                  return f(*args, **kwargs)
                File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 300, in prefs
                  return _state_action('qvm.prefs', name, *varargs, **kwargs)
                File "/var/cache/salt/minion/extmods/states/ext_state_qvm.py", line 144, in _state_action
                  status = __salt__[_action](*varargs, **kwargs)
                File "/var/cache/salt/minion/extmods/modules/ext_module_qvm.py", line 869, in prefs
                  elif args.vm.property_is_default(dest):
                File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 148, in property_is_default
                  None)
                File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 68, in qubesd_call
                  payload_stream)
                File "/usr/lib/python2.7/site-packages/qubesadmin/app.py", line 597, in qubesd_call
                  return self._parse_qubesd_response(return_data)
                File "/usr/lib/python2.7/site-packages/qubesadmin/base.py", line 102, in _parse_qubesd_response
                  raise exc_class(format_string, *args)
              QubesNoSuchPropertyError: Invalid property 'template_for_dispvms' of debian-10
     Started: 11:08:04.139632
    Duration: 97.844 ms
     Changes:   

Summary for local
------------
Succeeded: 1
Failed:    1
------------
Total states run:     2
Total run time: 445.397 ms
DOM0 configuration failed, not continuing
```
