### ISSUE TITLE
No VMs can start due to qmemman.service not starting after latest testing update

### ISSUE THREAD

**Issue by tquest1** [QubesOS/qubes-issues#6427]
### Qubes OS version:
R4.1

### Affected component(s) or functionality:
No VMs can start.
qubes-qmemman.service cannot start

---

### Steps to reproduce the behavior:

Happens on every boot. Tried to restart qmemman -  following error:
```
[user@dom0 ~]$ sudo systemctl status qubes-qmemman.service
● qubes-qmemman.service - Qubes memory management daemon
     Loaded: loaded (/usr/lib/systemd/system/qubes-qmemman.service; enabled; vendor preset: enabled)
     Active: failed (Result: exit-code) since Thu 2021-02-25 22:03:48 EET; 8s ago
    Process: 3897 ExecStart=/usr/bin/qmemmand (code=exited, status=1/FAILURE)
   Main PID: 3897 (code=exited, status=1/FAILURE)
        CPU: 978ms

Feb 25 22:03:48 dom0 qmemmand[3897]:   File "/usr/lib64/python3.8/configparser.py", line 808, in _get_conv
Feb 25 22:03:48 dom0 qmemmand[3897]:     return self._get(section, conv, option, raw=raw, vars=vars,
Feb 25 22:03:48 dom0 qmemmand[3897]:   File "/usr/lib64/python3.8/configparser.py", line 803, in _get
Feb 25 22:03:48 dom0 qmemmand[3897]:     return conv(self.get(section, option, **kwargs))
Feb 25 22:03:48 dom0 qmemmand[3897]:   File "/usr/lib64/python3.8/configparser.py", line 792, in get
Feb 25 22:03:48 dom0 qmemmand[3897]:     raise NoOptionError(option, section)
Feb 25 22:03:48 dom0 qmemmand[3897]: configparser.NoOptionError: No option 'log-level' in section: 'global'
Feb 25 22:03:48 dom0 systemd[1]: qubes-qmemman.service: Main process exited, code=exited, status=1/FAILURE
Feb 25 22:03:48 dom0 systemd[1]: qubes-qmemman.service: Failed with result 'exit-code'.
Feb 25 22:03:48 dom0 systemd[1]: Failed to start Qubes memory management daemon.



[user@dom0 ~]$ sudo journalctl -xe
-- The unit qubes-qmemman.service has entered the 'failed' state with result 'exit-code'.
Feb 25 22:06:57 dom0 systemd[1]: Failed to start Qubes memory management daemon.
-- Subject: A start job for unit qubes-qmemman.service has failed
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- A start job for unit qubes-qmemman.service has finished with a failure.
-- 
-- The job identifier is 1850 and the job result is failed.

```

### Expected or desired behavior:

VMs to start as per usual

### General notes:

Problem started on latest  dom0 testing repo update:

Upgraded:
  qubes-core-dom0-4.1.19-1.fc32.noarch                                          
  qubes-manager-4.1.15-1.fc32.noarch                                            
  qubes-mgmt-salt-dom0-update-4.1.5-1.fc32.noarch                               
  qubes-mgmt-salt-dom0-virtual-machines-4.1.10-1.fc32.noarch           

I am not able to downgrade due to no update vm available.

This is the qmemman.conf after editing it as I noticed that the Qubes Manager introduces the size with Mib instead of M - but I tried both anyway:

```
cat /etc/qubes/qmemman.conf
# The only section in this file
[global]
# vm-min-mem - give at least this amount of RAM for dynamically managed VM
#  Default: 200M
vm-min-mem = 200M

# dom0-mem-boost - additional memory given to dom0 for disk caches etc
#  Default: 350M
dom0-mem-boost = 350M

# cache-margin-factor - calculate VM preferred memory as (used memory)*cache-margin-factor
#  Default: 1.3
cache-margin-factor = 1.3

```

---

**Comment by marmarek** [comment]
Add `log-level` entry - you should get `.rpmnew` file there with example.

**Comment by 92VV3M42d3v8** [comment]
Not able to start any VM. 
Error is - Got empty response from qubesd. See journalctl for details.

**Comment by tquest1** [comment]
Can confirm that after

sudo cp qmemman.conf.rpmnew qmemman.conf
sudo systemctl start qubes-qmemman.service

everything works,

thanks for the prompt fix.

**Comment by dylangerdaly** [comment]
I just got this as well, ended up commending out the logging lines.
Once everything came back up I undid that and copied the rpmnew conf and restarted successfully

**Comment by KnightWhoSaysNeeeowWumPing** [comment]
I seem to have a similar problem, but adding the `log-level` entry to my `/etc/qubes/qmemman.conf` file does not change anything.
There is no `/etc/qubes/qmemman.conf.rpmnew` file I could use as backup.

When trying to start the qmemman service I get the following error (in journalctl):
```
Mar 03 10:21:22 dom0 qmemmand[28972]: Traceback (most recent call last):
Mar 03 10:21:22 dom0 qmemmand[28972]:   File "/usr/lib64/python3.5/site-packages/libvirt.py", line 24, in <module>
Mar 03 10:21:22 dom0 qmemmand[28972]:     import cygvirtmod as libvirtmod
Mar 03 10:21:22 dom0 qmemmand[28972]: ImportError: No module named 'cygvirtmod'
Mar 03 10:21:22 dom0 qmemmand[28972]: During handling of the above exception, another exception occurred:
Mar 03 10:21:22 dom0 qmemmand[28972]: Traceback (most recent call last):
Mar 03 10:21:22 dom0 qmemmand[28972]:   File "/usr/bin/qmemmand", line 2, in <module>
Mar 03 10:21:22 dom0 qmemmand[28972]:     from qubes.tools.qmemmand import main
Mar 03 10:21:22 dom0 qmemmand[28972]:   File "/usr/lib/python3.5/site-packages/qubes/__init__.py, line 759, in <module>
Mar 03 10:21:22 dom0 qmemmand[28972]:     from qubes.app import Qubes
Mar 03 10:21:22 dom0 qmemmand[28972]:   File "/usr/lib/python3.5/site-packages/qubes/app.py", line 39, in <module>
Mar 03 10:21:22 dom0 qmemmand[28972]:     import libvirt
Mar 03 10:21:22 dom0 qmemmand[28972]:   File "/usr/lib64/python3.5/site-packages/libvirt.py", line 28, in <module>
Mar 03 10:21:22 dom0 qmemmand[28972]:     raise lib_e
Mar 03 10:21:22 dom0 qmemmand[28972]:   File "/usr/lib64/python3.5/site-packages/libvirt.py", line 20, in <module>
Mar 03 10:21:22 dom0 qmemmand[28972]:     import libvirtmod
Mar 03 10:21:22 dom0 qmemmand[28972]: ImportError: libpsl.so.5: cannot open shared object file: No such file or directory
Mar 03 10:21:22 dom0 systemd[1]: qubes-qmemman.service: Main process exited, code=exited, status=1/FAILURE
Mar 03 10:21:22 dom0 systemd[1]: Failed to start Qubes memory management daemon.
```
I cannot remember doing a dom0 update since the last successfull boot.
