### ISSUE TITLE
Cannot create qube named a_cmeta

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6475]
**Qubes OS version**

`Qubes release 4.0 (R4.0)`

**Affected component(s) or functionality**

`qubes-core-admin`, VM creation

**Brief summary**

Creating a qube named `a_cmeta` fails if it is to be placed on an LVM pool.

**How Reproducible**

100%

**To Reproduce**

1. Try to create a qube named `a_cmeta` on an LVM pool

**Expected behavior**

QubesOS escapes the name to make LVM happy

**Actual behavior**

An exception occurs indicating a failure in qubesd.  This is due to the name being reserved in LVM.

**Screenshots**

**Additional context**

**Solutions you've tried**

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**

**Comment by DemiMarie** [comment]
Changing milestone as this will require non-trivial changes to the LVM pool to fix, and is only a problem in (rare) corner-cases.

**Comment by DemiMarie** [comment]
Not fixed.

**Comment by ben-grande** [comment]
Just to show the exception, which doesn't show on qubesd:

```
Jan 19 17:43:22 dom0 qubesd[1937]: INFO: vm.a_cmeta: Creating directory: /var/lib/qubes/appvms/a_cmeta
Jan 19 17:43:22 dom0 qubesd[1937]: INFO: vm.a_cmeta: Removing volume root: qubes_dom0/vm-a_cmeta-root
Jan 19 17:43:22 dom0 qubesd[1937]: INFO: vm.a_cmeta: Removing volume private: qubes_dom0/vm-a_cmeta-private
Jan 19 17:43:22 dom0 qubesd[1937]: INFO: vm.a_cmeta: Removing volume volatile: qubes_dom0/vm-a_cmeta-volatile
Jan 19 17:43:22 dom0 qubesd[1937]: INFO: vm.a_cmeta: Removing volume kernel: 6.18.4-1.fc41
Jan 19 17:43:22 dom0 qubes-app-menu[7054]: Failed to handle event: None, domain-delete, {'vm': 'a_cmeta'}
Jan 19 17:43:22 dom0 qubes-app-menu[7054]: Traceback (most recent call last):
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:   File "/usr/lib/python3.13/site-packages/qubesadmin/events/__init__.py", line 306, in handle
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:     handler(subject, event, **kwargs)
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:     ~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:   File "/usr/lib/python3.13/site-packages/qubesmanager/qube_manager.py", line 1208, in on_domain_removed
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:     self.qubes_cache.remove_vm(name=kwargs['vm'])
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:     ~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:   File "/usr/lib/python3.13/site-packages/qubesmanager/qube_manager.py", line 388, in remove_vm
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:     vm_info = self.get_vm(name=name)
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:   File "/usr/lib/python3.13/site-packages/qubesmanager/qube_manager.py", line 397, in get_vm
Jan 19 17:43:22 dom0 qubes-app-menu[7054]:     return next(x for x in self._info_list if x.name == name)
Jan 19 17:43:22 dom0 qubes-app-menu[7054]: StopIteration
```

**Comment by DemiMarie** [comment]
Affects R4.3
