### ISSUE TITLE
Fedora 33 template install fails

### ISSUE THREAD

**Issue by anthonyjmartinez** [QubesOS/qubes-issues#6575]
**Qubes OS version**
Qubes release 4.0 (R4.0)

**Affected component(s) or functionality**
Template installation

**Brief summary**
qubes-dom0-update qubes-template-fedora-33 fails with root.img extraction failed.

**How Reproducible**
100% (4/4 attempts)

**To Reproduce**

1. Boot
2. Open dom0 terminal
3. sudo qubes-dom0-update qubes-template-fedora-33

**Expected behavior**
Template VM installation succeeds, and fedora-33 is available from Qube Manager

**Actual behavior**

```
Running transaction
  Installing  : qubes-template-fedora-33-4.0.6-202102262008.noarch          1/1 
fedora-33: Importing data
tar: Skipping to next header
cat: write error: Broken pipe
tar: Exiting with failure status due to previous errors
Traceback (most recent call last):
  File "/bin/qvm-template-postprocess", line 5, in <module>
    sys.exit(main())                                                                                                                                                        
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 310, in main                                                                   
    loop.run_until_complete(post_install(args))                                                                                                                             
  File "/usr/lib64/python3.5/asyncio/base_events.py", line 467, in run_until_complete                                                                                       
    return future.result()                                                                                                                                                  
  File "/usr/lib64/python3.5/asyncio/futures.py", line 294, in result                                                                                                       
    raise self._exception                                                                                                                                                   
  File "/usr/lib64/python3.5/asyncio/tasks.py", line 240, in _step                                                                                                          
    result = coro.send(None)                                                                                                                                                
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 235, in post_install                                                           
    import_root_img(vm, args.dir)                                                                                                                                           
  File "/usr/lib/python3.5/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 98, in import_root_img                                                                                                                 
    raise qubesadmin.exc.QubesException('root.img extraction failed')                                             
qubesadmin.exc.QubesException: root.img extraction failed                                                         
warning: %post(qubes-template-fedora-33-4.0.6-202102262008.noarch) scriptlet failed, exit status 1                
Non-fatal POSTIN scriptlet failure in rpm package qubes-template-fedora-33                                        
Non-fatal POSTIN scriptlet failure in rpm package qubes-template-fedora-33
  Verifying   : qubes-template-fedora-33-4.0.6-202102262008.noarch          1/1 

Installed:
  qubes-template-fedora-33.noarch 4.0.6-202102262008                            

Complete!

[amartinez@dom0 ~]$ sudo dnf list installed | grep fedora-33
qubes-template-fedora-33.noarch        4.0.6-202102262008     @qubes-dom0-cached
```

At this stage DNF sees an installed package, but this is not in a usable state and does not appear in Qubes Manager.

Removal of the package with `sudo dnf -y remove qubes-template-fedora-33` results in:

```
Running transaction
usage: qvm-template-postprocess [--verbose] [--quiet] [--help] [--really]
                                [--skip-start] [--keep-source]
                                {post-install,pre-remove} name dir
qvm-template-postprocess: error: No Qube with this name exists
error: %preun(qubes-template-fedora-33-4.0.6-202102262008.noarch) scriptlet failed, exit status 2
Error in PREUN scriptlet in rpm package qubes-template-fedora-33
Error in PREUN scriptlet in rpm package qubes-template-fedora-33
qubes-template-fedora-33-4.0.6-202102262008.noarch was supposed to be removed but is not!
  Verifying   : qubes-template-fedora-33-4.0.6-202102262008.noarch          1/1 

Removed:
  qubes-template-fedora-33.noarch 4.0.6-202102262008                            

Complete!
```

**Screenshots**
N/A

**Additional context**
dom0 has > 300G of free space.

**Solutions you've tried**
Doing an in-place upgrade as detailed [here](https://www.qubes-os.org/doc/template/fedora/upgrade/) works fine, but the direct installation should work.

**Relevant [documentation](https://www.qubes-os.org/doc/) you've consulted**
https://www.qubes-os.org/doc/templates/fedora/

**Related, [non-duplicate](https://www.qubes-os.org/doc/reporting-bugs/#new-issues-should-not-be-duplicates-of-existing-issues) issues**
N/A

**Comment by fepitre** [comment]
I would suggest you to:

```
$ qubes-dom0-update --clean
$ qubes-dom0-update qubes-template-fedora-33
```

What Qubes setup do you use in terms of partitioning ? You say that you have 300 GB free on dom0 but this is not necessary what's important. In case of LVM, what is your LVM pool remaining size?

**Comment by anthonyjmartinez** [comment]
I’ll try the clean and install again. For now all my templates were manually updated and a backup is under way.

Next week I will have a clean install I can test on as well.

> 300GB is free in the LVM mapper for / in dom0

**Comment by ctrlaltf24** [comment]
qubes-template-fedora-33-4.0.6-202102262008.noarch installed fine on my machine.

**Comment by TNTBOMBOM** [comment]
Installed smoothly from my side fedora-33 & fedora-33-minimal

**Comment by anthonyjmartinez** [comment]
I will clean install and restore my custom templates and AppVMs from backup. Seems like something may be broken in my dom0, which is disconcerting but not impossible.

Close the issue since it appears to only be reproduced on this specific machine.
