### ISSUE TITLE
[Build 2021072816-4.1] openQA test fails in TC_10_Thunderbird_fedora-34

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6806]
## Observation

openQA test in scenario qubesos-4.1-pull-requests-x86_64-system_tests_splitgpg@64bit fails in
[TC_10_Thunderbird_fedora-34](https://openqa.qubes-os.org/tests/19982/modules/TC_10_Thunderbird_fedora-34/steps/1)

Fails in this frame (see `test-inst-backend` halting in mid-testing)
![Screenshot 2021-07-29 at 08-11-20 Qubes OS openQA Video](https://user-images.githubusercontent.com/47065258/127489876-06800549-48f0-4565-a759-2e5e4c7a79d0.png)

```
[...]

press on [push button | OpenPGP Key Manager]
click on [menu | File]
click on [menu item | Import Public Key(s) From File]
Mouse button 1 click at (16,85)
Traceback (most recent call last):
  File "/usr/lib/qubes-gpg-split/test_thunderbird.py", line 914, in <module>
    main()
  File "/usr/lib/qubes-gpg-split/test_thunderbird.py", line 893, in main
    configure_openpgp_account(tb)
  File "/usr/lib/qubes-gpg-split/test_thunderbird.py", line 529, in configure_openpgp_account
    click(*file_chooser.childNamed('pub.asc').position)
  File "/home/user/dogtail/dogtail/tree.py", line 1089, in childNamed
    return self.findChild(predicate.IsNamed(childName), recursive, showingOnly=showingOnly)
  File "/home/user/dogtail/dogtail/tree.py", line 923, in findChild
    result = self._fastFindChild(compare_func, recursive, showingOnly=showingOnly)
  File "/home/user/dogtail/dogtail/tree.py", line 881, in _fastFindChild
    return pyatspi.utils.findDescendant(self, pred)
  File "/usr/lib/python3.9/site-packages/pyatspi/utils.py", line 190, in findDescendant
    for child in acc:
  File "/usr/lib/python3.9/site-packages/pyatspi/Accessibility.py", line 41, in Accessible_getitem
    len=self.get_child_count()
gi.repository.GLib.GError: atspi_error: Method "Get" with signature "ss" on interface "org.freedesktop.DBus.Properties" could not be processed as object /org/a11y/atspi/accessible/543 does not exist
 (1)
```

## Reproducible

- Fails since (at least) : Build [2021070613-4.1](https://openqa.qubes-os.org/tests/19392#step/TC_10_Thunderbird_fedora-34/2)
- unable to reproduce on local test-bench

## Expected result

Last good: [2021053004-4.1](https://openqa.qubes-os.org/tests/18065) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=pull-requests&machine=64bit&test=system_tests_splitgpg&version=4.1)

There is little historical data on this. The following are all the events of this particular error (`gi.repository.GLib.GError: atspi_error: Method "Get" with signature "ss"`)

| Test run               | Template                    | Test Title    |
|--------------------|-----------------------------|----------|
| 19392 (2021-07-07) | TC_10_Thunderbird_fedora-34 | test_010 |
| 19392 (2021-07-07) | TC_10_Thunderbird_fedora-34 | test_020 |
| 19954 (2021-07-26) | TC_10_Thunderbird_fedora-34 | test_000 |
| 19954 (2021-07-26) | TC_10_Thunderbird_fedora-34 | test_010 |

**Comment by deeplow** [comment]
No longer an issue as can been seen here:

![Figure222](https://user-images.githubusercontent.com/47065258/147874670-417fec3d-42a6-45b2-b0a1-9b7e71e3d383.png)
