### ISSUE TITLE
openQA test fails: "nm-applet window not found" (test_020_simple_proxyvm_nm)

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6879]
## Observation

openQA test in scenarios:
  - qubesos-4.1-pull-requests-x86_64-4.1-system_tests_network_ipv6@64bit
[VmIPv6Networking_fedora-34-xfce](https://openqa.qubes-os.org/tests/20183/modules/VmIPv6Networking_fedora-34-xfce/steps/3)
  -  qubesos-4.1-pull-requests-x86_64-4.1-system_tests_network@64bit [VmNetworking_fedora-34-xfce](https://openqa.qubes-os.org/tests/20431#step/VmNetworking_fedora-34-xfce/3)

Both fail mostly in `test_020_simple_proxyvm_nm` as you can see. And the error happens across Debian and Fedora templates. This can be seen in the following graphs (produced with [this script](https://github.com/deeplow/openqa-tests-qubesos/blob/stability-utils/utils/openqa_investigator.py)).

| GroupBy| ipv4 tests | ipv6 tests |
|-----|------|-----------|
| Test | ![Figure_1](https://user-images.githubusercontent.com/47065258/132383051-278808cd-cf79-484d-98a3-2ca60edc4f37.png) | ![Figure_2](https://user-images.githubusercontent.com/47065258/132383069-955d8873-c34e-4e3e-abf2-b90431c8d727.png) |
| Template | ![Figure_3](https://user-images.githubusercontent.com/47065258/132383140-9e73e916-42ee-41cd-be91-fd7b49581f54.png) |  ![Figure_4](https://user-images.githubusercontent.com/47065258/132383149-6aaa8ec8-3b63-4aae-a1be-036e70f5bcf9.png) |

Traceback: (fails on [this line](https://github.com/QubesOS/qubes-core-admin/blob/df6407f50811573760879a7a48b9243ea31e504a/qubes/tests/integ/network.py#L228))
```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubes/tests/__init__.py", line 221, in wrapper
    func(self, *args, **kwargs)
  File "/usr/lib/python3.8/site-packages/qubes/tests/integ/network.py", line 228, in test_020_simple_proxyvm_nm
    self.assertEqual(subprocess.call([
AssertionError: 1 != 0 : nm-applet window not found
```

xdotool error (as printed in terminal via the video):
```
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  15 (X_QueryTree)
  Resource id in failed request:  0x49001eb
  Serial number of failed request: 861
  Current serial number in output stream: 861
```
> **note:** only one video was available (others had been garbage collected), so I haven't been able to confirm all tests had failed with this exact error message.

## Test suite description
N/A

## Reproducible

- Fails since [Build2020092217-4.1](https://openqa.qubes-os.org/tests/12048#step/VmIPv6Networking_fedora-32/3) (2020-09-23) - about the time the test was introduced.

## Expected result

Last good: [2021080103-4.1](https://openqa.qubes-os.org/tests/20153) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=pull-requests&machine=64bit&test=system_tests_network_ipv6&version=4.1)

**Comment by marmarek** [comment]
>   Major opcode of failed request:  15 (X_QueryTree)

I'm very interested if this still happens, after https://github.com/QubesOS/updates-status/issues/2592. This xdotool update should (theoretically) fix the issue.

BTW those graphs are **really cool**!

**Comment by andrewdavidwong** [comment]
> BTW those graphs are **really cool**!

I think they have potential, but the current implementation leaves me puzzled:

- Why are there decimals on the Y-axis? A test can't fail 0.2 times. It either fails or it doesn't. And, in fact, all the data points are either 0 or 1, making the middle rather pointless. (This suggests that perhaps this kind of graph is not the best way to represent this particular data set visually.)
- What is the X-axis? The tags are overlapping, but I can make out that they're numbers. I'm guessing it's time, but those don't look like normal timestamps.

**Comment by deeplow** [comment]
> BTW those graphs are **really cool**!

Thanks :slightly_smiling_face:

Thanks for the feedback @andrewdavidwong.  Small note: these graphs are pretty much the simplest of the graphs. I can make them more fancy. But since they already do the job I haven't invested more time looking into that unless it significantly improves my work (avoiding gold-plating dev-oriented tools).

>  * Why are there decimals on the Y-axis?

I wanna make these discrete numbers. This is the default behavior of the graphing tool. It's something I'll look into in the future but not very pressing since they do their purpose already.

>  * And, in fact, all the data points are either 0 or 1, making the middle rather pointless.

It's here because there are times where a test fails on the same job multiple times. For example it would be useful in identifying if all tests fail on a particular test and in a particular template. The following image is network tests that fail with the error message `systemctl is-system-running`

![fedora](https://user-images.githubusercontent.com/47065258/132473458-3898d681-ff91-4f5c-939c-c0cc86667d01.png)


>  * (This suggests that perhaps this kind of graph is not the best way to represent this particular data set visually.)

Open to suggestions from the `matplotlib` python package (or alternatives)! I tried making little dots, but when there are many tests it's just chaotic and one can't see which one is which.

> * What is the X-axis? The tags are overlapping, but I can make out that they're numbers. I'm guessing it's time, but those don't look like normal timestamps.

Oh. It's the test's number (e.g. [20431](https://openqa.qubes-os.org/tests/20431)). They go get a bit overlapping. I've already made them show diagonally, but that's clearly not enough.

**Comment by andrewdavidwong** [comment]
> Small note: these graphs are pretty much the simplest of the graphs. I can make them more fancy. But since they already do the job I haven't invested more time looking into that unless it significantly improves my work (avoiding gold-plating dev-oriented tools).

Yep, makes sense. Please don't let my nitpicks divert time from more important work. 🙂

**Comment by deeplow** [comment]
> > Small note: these graphs are pretty much the simplest of the graphs. I can make them more fancy. But since they already do the job I haven't invested more time looking into that unless it significantly improves my work (avoiding gold-plating dev-oriented tools).
> 
> Yep, makes sense. Please don't let my nitpicks divert time from more important work. slightly_smiling_face

:+1: but I appreciate them, nonetheless :)

**Comment by deeplow** [comment]
> > 
> 
> I'm very interested if this still happens, after [QubesOS/updates-status#2592](https://github.com/QubesOS/updates-status/issues/2592). This xdotool update should (theoretically) fix the issue.

It did :raised_hands:, apparently :)

To test it, I ran in dom0 in a loop the command `while true; do xdotool search --class test-inst-proxy:nm-applet; sleep 0.1;  done`. The latest fail like this on openQA is [from 2021-08-14](https://openqa.qubes-os.org/tests/20431#step/VmNetworking_fedora-34-xfce/3), back when this was not on stable.

@marmarek should we close this now or wait a bit to see if there are indeed no new reports of this on openQA?

**Comment by deeplow** [comment]
@andrewdavidwong this seems to be diagnosed
