### ISSUE TITLE
Trying to run `--` with `qvm-run` crashes `qvm-run`

### ISSUE THREAD

**Issue by DemiMarie** [QubesOS/qubes-issues#6892]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
R4.1

### Brief summary
If I try to use `qvm-run` to run the literal command `--`, `qvm-run` crashes.

### Steps to reproduce
Run `qvm-run -- someqube -- /bin/true`

### Expected behavior
`/bin/true` is run

### Actual behavior

Crash:

```
Running '[]' on someqube
Traceback (most recent call last):
  File "/bin/qvm-run", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_run.py", line 308, in main
    proc, copy_proc, local_proc = run_command_single(args, vm)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_run.py", line 188, in run_command_single
    service += '+' + qubesadmin.utils.encode_for_vmexec(all_args)
  File "/usr/lib/python3.8/site-packages/qubesadmin/utils.py", line 171, in encode_for_vmexec
    part = re.sub(br'[^a-zA-Z0-9_.]', encode, arg.encode('utf-8'))
AttributeError: 'list' object has no attribute 'encode'
```

**Comment by DemiMarie** [comment]
Fixed.
