### ISSUE TITLE
`qvm-run-vm --dispvm` causing `QubesMgmtException`

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#6902]
While trying to build a qubes kernel from a pristine `qubes-builder` tree (something which did work a few days ago in the same VM), I get a failure to use a dispvm for kernel source decompression (see https://github.com/QubesOS/qubes-issues/issues/6901).

`qubes- dom0-update` does not report anything to update.

In build VM:

```
[user@fedora32-qubes-build linux-kernel]$ qvm-run-vm --dispvm xzcat <linux-5.10.61.tar.xz.UNTRUSTED > /dev/null
Request refused
```

in `qrexec.$VM.log`:
```
2021-09-15 23:13:50.733 qrexec-daemon[16282]: qrexec-daemon.c:815:connect_daemon_socket: invalid response: 
2021-09-15 23:13:50.733 qrexec-daemon[16282]: qrexec-daemon.c:865:handle_execute_service: couldn't invoke qrexec-policy-daemon, using qrexec-policy-exec
WARNING:root:warning: !compat-4.0 directive in file /etc/qubes/policy.d/35-compat.policy line 16 is transitional and will be deprecated
INFO:policy:qrexec: qubes.VMShell+WaitForSession: fedora32-qubes-build -> @dispvm: allowed to @dispvm:dom0
Traceback (most recent call last):
  File "/usr/bin/qrexec-policy-exec", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 221, in main
    return asyncio.run(handle_request(
  File "/usr/lib64/python3.8/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 274, in handle_request
    await resolution.execute(caller_ident)
  File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 169, in execute
    await super().execute(caller_ident)
  File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 133, in execute
    await super().execute(caller_ident)
  File "/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 535, in execute
    target = self.spawn_dispvm()
  File "/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 564, in spawn_dispvm
    dispvm_name = utils.qubesd_call(base_appvm, 'admin.vm.CreateDisposable')
  File "/usr/lib/python3.8/site-packages/qrexec/utils.py", line 94, in qubesd_call
    raise QubesMgmtException(exc_type.decode('ascii'))
qrexec.exc.QubesMgmtException
```

**Comment by marmarek** [comment]
Did you get any more details in `journalctl`?

**Comment by ydirson** [comment]
Not much more:

```
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]: qrexec: qubes.VMShell+WaitForSession: fedora32-qubes-build -> @dispvm: allowed to @dispvm:dom0
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]: Task exception was never retrieved
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]: future: <Task finished name='Task-316' coro=<handle_client_connection() done, defined at /usr/lib/python3.8/site-packages/qrexec/tools/qrexe>
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]: Traceback (most recent call last):
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:   File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_daemon.py", line 100, in handle_client_connection
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:     result = await handle_request(**args, log=log,
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:   File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 274, in handle_request
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:     await resolution.execute(caller_ident)
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:   File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 169, in execute
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:     await super().execute(caller_ident)
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:   File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 133, in execute
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:     await super().execute(caller_ident)
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:   File "/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 535, in execute
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:     target = self.spawn_dispvm()
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:   File "/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 564, in spawn_dispvm
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:     dispvm_name = utils.qubesd_call(base_appvm, 'admin.vm.CreateDisposable')
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:   File "/usr/lib/python3.8/site-packages/qrexec/utils.py", line 94, in qubesd_call
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]:     raise QubesMgmtException(exc_type.decode('ascii'))
Sep 15 23:31:27 dom0 qrexec-policy-daemon[2366]: qrexec.exc.QubesMgmtException
Sep 15 23:31:27 dom0 qrexec[16458]: qubes.VMShell+WaitForSession: fedora32-qubes-build -> @dispvm: allowed to @dispvm:dom0
```

**Comment by marmarek** [comment]
Nothing from `qubesd` service at this time?

**Comment by ydirson** [comment]
The only thing reported from qubesd, by both `journalctl -u qubesd` and `systemctl status qubesd` is the `qrexec` line: 
```
Sep 15 23:31:27 dom0 qrexec[16458]: qubes.VMShell+WaitForSession: fedora32-qubes-build -> @dispvm: allowed to @dispvm:dom0
```

**Comment by marmarek** [comment]
That's interesting, I would have expected some scary exception there. That's because `@dispvm:dom0` is a non-sense, you can't have DispVM using dom0 as a template!

**Comment by ydirson** [comment]
Interesting indeed, where does it come from...

**Comment by DemiMarie** [comment]
> Ah, my bad, I must have used `qubes-prefs default_dispvm` where I meant `qubes-prefs default_guivm`. I always have to read twice not not take "disp" for "display"...

Even if this is user error, Qubes OS should give a better error message!  At a minimum, `qubes-prefs default_dispvm 'NotADisposableVMTemplate'` should fail.

> Spelling things in full is nice :)

That is is, which is why the use of “disp” for “disposable” is deprecated.  Changing it will be quite a bit of work, though.

**Comment by andrewdavidwong** [comment]
You didn't specify which Qubes OS release this affects, so I took a guess at 4.0.

**Comment by ydirson** [comment]
I have it on 4.1, but I guess it can affect 4.0 as well.

**Comment by ydirson** [comment]
This was reported on 4.1 not 4.0, the tag was wrong - and it seems devs agreed the behaviour could be improved
