### ISSUE TITLE
qubes management frozen after qemu segfault, then `virDomainShutdown() failed` while shutting down hvm

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#6910]
### Qubes OS release

4.1beta

### Brief summary

Trying to run a non-qubes-aware VM with a custom rootfs, on shutdown request the panel widget does not popup qubes menu, an open Qubes Manager window freezes, and `qvm-ls` blocks.

### Steps to reproduce

* created VM with:
  ```
  $ qvm-create --property virt_mode=hvm --property memory=4096 --standalone --label red --root-move-from isar-buster.img test-isar2
  app: Error importing root volume (but VM created): Data import failed: not enough data (copied 791280640 bytes, expected 10737418240 bytes)
  ```
* start VM (qemu window briefly appears then goes away)
* setup inter-vm firewall rule and attempt ssh access (without any answer)
* stop VM from panel widget

### Expected behavior

Still being able to interact with the system while the VM is shut down, specifically being able to Kill it since it has no agent to do normal shutdown.

### Actual behavior

When interrupting stuck `qvm-ls`:
```
[root@dom0 ~]# qvm-ls 
^CTraceback (most recent call last):
  File "/usr/bin/qvm-ls", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_ls.py", line 715, in main
    domains = [d for d in domains
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_ls.py", line 715, in <listcomp>
    domains = [d for d in domains
  File "/usr/lib/python3.8/site-packages/qubesadmin/app.py", line 131, in __iter__
    self.refresh_cache()
  File "/usr/lib/python3.8/site-packages/qubesadmin/app.py", line 61, in refresh_cache
    vm_list_data = self.app.qubesd_call(
  File "/usr/lib/python3.8/site-packages/qubesadmin/app.py", line 717, in qubesd_call
    return_data = client_socket.makefile('rb').read()
  File "/usr/lib64/python3.8/socket.py", line 669, in readinto
    return self._sock.recv_into(b)
KeyboardInterrupt
```

After a delay I'm getting notifications of the failed attempt to shutdown, reporting `Got empty response from qubesd` including a hint to look at `journalctl`, which reports:
```
Sep 18 11:43:20 dom0 libvirtd[2049]: libvirt version: 6.6.0, package: 4.fc32 (Unknown, 2021-06-21-13:23:11, )
Sep 18 11:43:20 dom0 libvirtd[2049]: hostname: dom0
Sep 18 11:43:20 dom0 libvirtd[2049]: internal error: Failed to shutdown domain '21' with libxenlight
Sep 18 11:43:20 dom0 qubesd[2046]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Shutdown' dest=b'test-isar2' arg=b'' len(untrusted_payload)=0
Sep 18 11:43:20 dom0 qubesd[2046]: Traceback (most recent call last):
Sep 18 11:43:20 dom0 qubesd[2046]:   File "/usr/lib/python3.8/site-packages/qubes/api/__init__.py", line 287, in respond
Sep 18 11:43:20 dom0 qubesd[2046]:     response = yield from self.mgmt.execute(
Sep 18 11:43:20 dom0 qubesd[2046]:   File "/usr/lib/python3.8/site-packages/qubes/api/admin.py", line 910, in vm_shutdown
Sep 18 11:43:20 dom0 qubesd[2046]:     yield from self.dest.shutdown(force=force, wait=wait)
Sep 18 11:43:20 dom0 qubesd[2046]:   File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 1319, in shutdown
Sep 18 11:43:20 dom0 qubesd[2046]:     self.libvirt_domain.shutdown()
Sep 18 11:43:20 dom0 qubesd[2046]:   File "/usr/lib/python3.8/site-packages/qubes/app.py", line 104, in wrapper
Sep 18 11:43:20 dom0 qubesd[2046]:     return attr(*args, **kwargs)
Sep 18 11:43:20 dom0 qubesd[2046]:   File "/usr/lib64/python3.8/site-packages/libvirt.py", line 2672, in shutdown
Sep 18 11:43:20 dom0 qubesd[2046]:     if ret == -1: raise libvirtError ('virDomainShutdown() failed', dom=self)
Sep 18 11:43:20 dom0 qubesd[2046]: libvirt.libvirtError: internal error: Failed to shutdown domain '21' with libxenlight
```

The panel VM menu gives again me the ability to Shutdown the VM, not to Kill it.  The same happens again if I request a shutdown.

xen console logs show the kernel panic'd for a wrong `root=` setting; `-dm.log` shows a qemu segfault:

```
[2021-09-18 11:17:24] device eth0 left promiscuous mode
[2021-09-18 11:17:24] br0: port 1(eth0) entered disabled state
[2021-09-18 11:17:25] qemu[235]: segfault at 0 ip 00005c79d57a5240 sp 00007fff62699488 error 4 in qemu[5c79d552a000+3e9000]
[2021-09-18 11:17:25] Code: 48 8b 4c 24 20 e8 e0 3b 0f 00 48 83 c4 20 e9 a4 fe ff ff 0f 1f 80 00 00 00 00 48 8b 07 48 8b 00 48 8b 00 c3 66 0f 1f 44 00 00 <48> 8b 07 c3 66 66 2e 0f 1f 84 00 00 00 00 00 90 48 8b 07 0f b6 40
```

There is actually no qemu process left out there, but Qubes seems not to have noticed.

I can get rid of the remainders of the failed qube with `qvm-kill`.

**Comment by ydirson** [comment]
The trigger of the qemu segfault is likely the system volume full of zeroes (see https://forum.qubes-os.org/t/qvm-create-root-copy-from-vs-root-move-from/6436).

**Comment by Narvey** [comment]
I also had very similar symptoms, but with a Windows qube. My -dm.log doesn't have segfault in it.
