### ISSUE TITLE
Listing PCI devices breaks when there is some with non-0000 PCI domain

### ISSUE THREAD

**Issue by MarioSDR93** [QubesOS/qubes-issues#6932]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

All actions related to PCI devices fail with the following error in journalctl:

```
unhandled exception while calling src=b'dome' meth=b'admin.vm.device.pci. Available' dest=b'dome' arg-b' len (untrusted_payload)=0
Traceback (most recent call last):
	File "/usr/lib/python3.8/site-packages/qubes/api/__init__.py", line 287, in respond
		response = yield from self.mgmt.execute(
	File "/usr/lib64/python3.8/asyncio/coroutines.py", line 124, in coro
		res = func(*args, **kw)
	File "/usr/lib/python3.8/site-packages/qubes/api/admin.py", line 1242, in vm_device_available
		devices = self.dest.devices [devclass].available()
	File "/usr/lib/python3.8/site-packages/qubes/devices.py", line 380, in available
		devices = self._vm.fire_event ('device-list:' + self._bus)
	File "/usr/lib/python3.8/site-packages/qubes/events.py", line 197, in fire_event
		sync_effects, async_effects= self._fire_event (event, kwargs,
	File "/usr/lib/python3.8/site-packages/qubes/events.py", line 170, in fire_event
		effects.extend (effect)
	File "/usr/lib/python3.8/site-packages/qubes/ext/pci.py", line 191, in on_device_list_pci
		yield PCIDevice (vm, None, libvirt_name=libvirt_name)
	File "/usr/lib/python3.8/site-packages/qubes/ext/pci.py", line 140, in _init_
		assert dev_match
AssertionError
```

### Steps to reproduce

Install Qubes 4.1 on Dell Latitude 5520
11th Gen Intel i7-1185G7

Error occurs on initial setup, when configuring sys-net/sys-usb

### Expected behavior

PCI devices are usable. no errors occur

### Actual behavior

PCI devices are not usable
Devices Tab in Qubes Manager is greyed out
sys-net does not start
qvm-devices pci does show nothing

**Comment by Shoko-Asahara** [comment]
Unfortunately I am also experiencing this same issue on:

 
```
Device: MSI GE66 RAIDER 11UH

 CPU - Intel® Core™ i9-11980HK
 CHIPSET - HM570 
 GRAPHICS - NVIDIA® GeForce RTX™ 3080 Laptop GPU 16GB GDDR6
 NOTE: Attempted installation was on an m.2 ssd connected via USB-C
```
Tried using 4.1 rc3 and 4.1 rc2  rc2

There is a related post on the qubes forum [here](https://forum.qubes-os.org/t/major-problem-with-qvm-pci-and-devices-in-general/8359/3). I believe it is just myself and the OP here on that post as well but it seems one thing we have in common is the 11th gen intel processor. 

So when I do qvm-pci i get an error that says there is no permission to view pci devices, I can give a better more detailed explanation when I get on that device again but essentially the devices tab is greyed out in the settings for any vm. on the other hand, lspci and lsusb populate just fine. 

The only thing I havent yet tried is putting the ssd in my computer and installing it without using a usb cord and enabling sys-usb during the installation. I will attempt to do so soon though and report back also. 

Note: 
Actually for me sys-net does start, and it has the ethernet card attached to it somehow and if i use an ethernet cable I can get internet but beyond that nothing. For example I tried attaching a usb wifi dongle which I couldnt get attached to sys-net due to there being no use of the qvm-pci command or the devices tab. I havent looked too far into xen's commands but I will do that also later today, any guidance would also be appreciated.

**Comment by RaspyVotan** [comment]
I have similar issues, adding just to help debugging this:

**Qubes OS release**

R4.1


**Brief Summary:**
PCI devices cannot be used adequately


My device:

Dell XPS 9510
Core i7-11800H
64 GB RAM
NVIDIO GeForce RTX 3050 TI

**Steps to re-produce:**
New install of Qubes OS on laptop
sys-net, sys-usb and sys-firewall created during setup process

**Expected behaviour:**
- See all devices that are attached to the Thunderbolt Hub in sys-usb
- Be able to attach PCI devices via the GUI under "VM Settings" - "Devices"
- See all the PCI devices using "qvm-pci" without an error message

**Actual behaviour:**
- Thunderbolt hub is not recognized
- qvm-pci not usable - gives an error: "Failed to list PCI devices"
- tab "device" is greyed out on the VM settings window

**Comment by xunillen** [comment]
Same issue after replacing my old thinkpad with 11th gen intel cpu laptop. Everything works, except _qvm-pci_ command and _Device_ tab which is greyed out in AppVM settings window (because of broken qvm-pci command).
Initial Qubes OS setup successfully assigns PCI devices to sys-*  AppVMs, after that PCI devices are not attachable or detachable. 

Device specs (Asus ExpertBook):

- Intel i5-1135g7
- 16GB of ram
- Intel Iris Xe graphics

Result of qvm-pci while trying to attach pci device to AppVM
```
command - qvm-pci attach test-vm dom0:00_1f.3
test-vm - HVM model vm
dom0:00_1f.3 - Multimedia audio controller: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20)

result of command:
Traceback (most recent call last):
  File "/usr/bin/qvm-pci", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_device.py", line 291, in main
    args = parser.parse_args(args, app=app)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/__init__.py", line 409, in parse_args
    subaction.parse_qubes_app(self, namespace)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_device.py", line 200, in parse_qubes_app
    dev = vm.devices[devclass][device_id]
  File "/usr/lib/python3.8/site-packages/qubesadmin/devices.py", line 282, in __getitem__
    for dev in self.available():
  File "/usr/lib/python3.8/site-packages/qubesadmin/devices.py", line 235, in available
    self._vm.qubesd_call(None,
  File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 74, in qubesd_call
    return self.app.qubesd_call(dest, method, arg, payload,
  File "/usr/lib/python3.8/site-packages/qubesadmin/app.py", line 748, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 87, in _parse_qubesd_response
    raise qubesadmin.exc.QubesDaemonAccessError(
qubesadmin.exc.QubesDaemonAccessError: Got empty response from qubesd. See journalctl in dom0 for details.
```

Image of greyed out Device tab in AppVM settings window.
![Device_error](https://user-images.githubusercontent.com/81808352/160616436-0d9302db-8c8f-4d79-86f3-5138f8d0c0f8.png)

**Comment by DemiMarie** [comment]
@xunillen Can you post the output of `journalctl -b -u qubesd.service`?  Feel free to redact anything sensitive.

**Comment by xunillen** [comment]
Yes, of course. Hope it helps

Output of "journalctl -b -u qubesd.service":
```
-- Logs begin at Sun 2022-03-27 17:54:14 CEST, end at Wed 2022-03-30 09:15:00 CEST. --
Mar 30 08:39:41 dom0 systemd[1]: Starting Qubes OS daemon...
Mar 30 08:39:51 dom0 systemd[1]: Started Qubes OS daemon.
Mar 30 08:39:51 dom0 qubesd[2008]: vm.sys-net: Starting sys-net
Mar 30 08:39:52 dom0 qubesd[2008]: vm.sys-firewall: Starting sys-firewall
Mar 30 08:39:52 dom0 qubesd[2008]: vm.sys-usb: Starting sys-usb
Mar 30 08:39:52 dom0 qubesd[2008]: vm.sys-whonix: Starting sys-whonix
Mar 30 08:39:56 dom0 qubesd[2008]: vm.sys-net: Setting Qubes DB info for the VM
Mar 30 08:39:56 dom0 qubesd[2008]: vm.sys-net: Starting Qubes DB
Mar 30 08:39:56 dom0 runuser[4313]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:39:56 dom0 runuser[4313]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:39:56 dom0 qubesd[2008]: vm.sys-net: Activating the sys-net VM
Mar 30 08:39:56 dom0 runuser[4324]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:40:00 dom0 qubesd[2008]: vm.sys-usb: Setting Qubes DB info for the VM
Mar 30 08:40:00 dom0 qubesd[2008]: vm.sys-usb: Starting Qubes DB
Mar 30 08:40:00 dom0 runuser[5222]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:40:00 dom0 runuser[5222]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:40:00 dom0 qubesd[2008]: vm.sys-usb: Activating the sys-usb VM
Mar 30 08:40:00 dom0 runuser[5227]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:40:02 dom0 runuser[4324]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:40:05 dom0 qubesd[2008]: vm.sys-firewall: Setting Qubes DB info for the VM
Mar 30 08:40:05 dom0 qubesd[2008]: vm.sys-firewall: Starting Qubes DB
Mar 30 08:40:05 dom0 runuser[5756]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:40:05 dom0 runuser[5756]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:40:05 dom0 qubesd[2008]: vm.sys-firewall: Activating the sys-firewall VM
Mar 30 08:40:05 dom0 runuser[5760]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:40:09 dom0 runuser[5227]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:40:11 dom0 runuser[5760]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:40:14 dom0 qubesd[2008]: vm.sys-whonix: Setting Qubes DB info for the VM
Mar 30 08:40:14 dom0 qubesd[2008]: vm.sys-whonix: Starting Qubes DB
Mar 30 08:40:14 dom0 runuser[6408]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:40:14 dom0 runuser[6408]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:40:14 dom0 qubesd[2008]: vm.sys-whonix: Activating the sys-whonix VM
Mar 30 08:40:14 dom0 runuser[6412]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:40:18 dom0 runuser[6412]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:40:53 dom0 qubesd[2008]: vm.faks: Starting faks
Mar 30 08:40:56 dom0 qubesd[2008]: vm.faks: Setting Qubes DB info for the VM
Mar 30 08:40:56 dom0 qubesd[2008]: vm.faks: Starting Qubes DB
Mar 30 08:40:56 dom0 runuser[7430]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:40:56 dom0 runuser[7430]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:40:56 dom0 qubesd[2008]: vm.faks: Activating the faks VM
Mar 30 08:40:56 dom0 runuser[7434]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:41:01 dom0 runuser[7434]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:55:02 dom0 qubesd[2008]: vm.untrusted: Starting untrusted
Mar 30 08:55:06 dom0 qubesd[2008]: vm.untrusted: Setting Qubes DB info for the VM
Mar 30 08:55:06 dom0 qubesd[2008]: vm.untrusted: Starting Qubes DB
Mar 30 08:55:06 dom0 runuser[8361]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:55:06 dom0 runuser[8361]: pam_unix(runuser:session): session closed for user xuni
Mar 30 08:55:06 dom0 qubesd[2008]: vm.untrusted: Activating the untrusted VM
Mar 30 08:55:06 dom0 runuser[8365]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 08:55:10 dom0 runuser[8365]: pam_unix(runuser:session): session closed for user xuni
Mar 30 09:06:57 dom0 qubesd[2008]: vm.vault: Starting vault
Mar 30 09:07:00 dom0 qubesd[2008]: vm.vault: Setting Qubes DB info for the VM
Mar 30 09:07:00 dom0 qubesd[2008]: vm.vault: Starting Qubes DB
Mar 30 09:07:00 dom0 runuser[9794]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 09:07:00 dom0 runuser[9794]: pam_unix(runuser:session): session closed for user xuni
Mar 30 09:07:00 dom0 qubesd[2008]: vm.vault: Activating the vault VM
Mar 30 09:07:00 dom0 runuser[9798]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 09:07:04 dom0 runuser[9798]: pam_unix(runuser:session): session closed for user xuni
Mar 30 09:11:45 dom0 qubesd[2008]: vm.windows10: Starting windows10
Mar 30 09:11:52 dom0 qubesd[2008]: vm.windows10: Setting Qubes DB info for the VM
Mar 30 09:11:52 dom0 qubesd[2008]: vm.windows10: Starting Qubes DB
Mar 30 09:11:52 dom0 runuser[11279]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 09:11:52 dom0 runuser[11279]: pam_unix(runuser:session): session closed for user xuni
Mar 30 09:11:52 dom0 qubesd[2008]: vm.windows10: Activating the windows10 VM
Mar 30 09:11:52 dom0 runuser[11287]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 09:11:52 dom0 runuser[11287]: pam_unix(runuser:session): session closed for user xuni
Mar 30 09:11:52 dom0 runuser[11295]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 09:12:10 dom0 runuser[11295]: pam_unix(runuser:session): session closed for user xuni
Mar 30 09:13:24 dom0 qubesd[2008]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.device.pci.Available' dest=b'dom0' arg=b'' len(untrusted_payload)=0    -> Error while running just 'qvm-pci' command without any parameters
Mar 30 09:13:24 dom0 qubesd[2008]: Traceback (most recent call last):
Mar 30 09:13:24 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/api/__init__.py", line 286, in respond
Mar 30 09:13:24 dom0 qubesd[2008]:     response = await self.mgmt.execute(
Mar 30 09:13:24 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/api/admin.py", line 1217, in vm_device_available
Mar 30 09:13:24 dom0 qubesd[2008]:     devices = self.dest.devices[devclass].available()
Mar 30 09:13:24 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/devices.py", line 376, in available
Mar 30 09:13:24 dom0 qubesd[2008]:     devices = self._vm.fire_event('device-list:' + self._bus)
Mar 30 09:13:24 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/events.py", line 195, in fire_event
Mar 30 09:13:24 dom0 qubesd[2008]:     sync_effects, async_effects = self._fire_event(event, kwargs,
Mar 30 09:13:24 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/events.py", line 168, in _fire_event
Mar 30 09:13:24 dom0 qubesd[2008]:     effects.extend(effect)
Mar 30 09:13:24 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/ext/pci.py", line 191, in on_device_list_pci
Mar 30 09:13:24 dom0 qubesd[2008]:     yield PCIDevice(vm, None, libvirt_name=libvirt_name)
Mar 30 09:13:24 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/ext/pci.py", line 140, in __init__
Mar 30 09:13:24 dom0 qubesd[2008]:     assert dev_match
Mar 30 09:13:24 dom0 qubesd[2008]: AssertionError
Mar 30 09:14:10 dom0 qubesd[2008]: vm.work: Starting work
Mar 30 09:14:14 dom0 qubesd[2008]: vm.work: Setting Qubes DB info for the VM
Mar 30 09:14:14 dom0 qubesd[2008]: vm.work: Starting Qubes DB
Mar 30 09:14:14 dom0 runuser[12708]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 09:14:14 dom0 runuser[12708]: pam_unix(runuser:session): session closed for user xuni
Mar 30 09:14:14 dom0 qubesd[2008]: vm.work: Activating the work VM
Mar 30 09:14:14 dom0 runuser[12712]: pam_unix(runuser:session): session opened for user xuni by (uid=0)
Mar 30 09:14:18 dom0 runuser[12712]: pam_unix(runuser:session): session closed for user xuni
Mar 30 09:15:00 dom0 qubesd[2008]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.device.pci.Available' dest=b'dom0' arg=b'' len(untrusted_payload)=0    -> Error while running 'qvm-pci attach test-vm dom0:00_1f.3'. Command with test AppVM with test PCI device.
Mar 30 09:15:00 dom0 qubesd[2008]: Traceback (most recent call last):
Mar 30 09:15:00 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/api/__init__.py", line 286, in respond
Mar 30 09:15:00 dom0 qubesd[2008]:     response = await self.mgmt.execute(
Mar 30 09:15:00 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/api/admin.py", line 1217, in vm_device_available
Mar 30 09:15:00 dom0 qubesd[2008]:     devices = self.dest.devices[devclass].available()
Mar 30 09:15:00 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/devices.py", line 376, in available
Mar 30 09:15:00 dom0 qubesd[2008]:     devices = self._vm.fire_event('device-list:' + self._bus)
Mar 30 09:15:00 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/events.py", line 195, in fire_event
Mar 30 09:15:00 dom0 qubesd[2008]:     sync_effects, async_effects = self._fire_event(event, kwargs,
Mar 30 09:15:00 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/events.py", line 168, in _fire_event
Mar 30 09:15:00 dom0 qubesd[2008]:     effects.extend(effect)
Mar 30 09:15:00 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/ext/pci.py", line 191, in on_device_list_pci
Mar 30 09:15:00 dom0 qubesd[2008]:     yield PCIDevice(vm, None, libvirt_name=libvirt_name)
Mar 30 09:15:00 dom0 qubesd[2008]:   File "/usr/lib/python3.8/site-packages/qubes/ext/pci.py", line 140, in __init__
Mar 30 09:15:00 dom0 qubesd[2008]:     assert dev_match
Mar 30 09:15:00 dom0 qubesd[2008]: AssertionError
```

**Comment by marmarek** [comment]
Can you show output of `virsh -c xen nodedev-list`?

**Comment by xunillen** [comment]
Here you go.

output of `virsh -c xen nodedev-list`:
```
computer
drm_card0
drm_renderD128
net_lo_00_00_00_00_00_00
pci_0000_00_00_0
pci_0000_00_02_0
pci_0000_00_04_0
pci_0000_00_06_0
pci_0000_00_08_0
pci_0000_00_0a_0
pci_0000_00_0d_0
pci_0000_00_0e_0
pci_0000_00_14_0
pci_0000_00_14_2
pci_0000_00_14_3
pci_0000_00_15_0
pci_0000_00_15_1
pci_0000_00_16_0
pci_0000_00_17_0
pci_0000_00_1f_0
pci_0000_00_1f_3
pci_0000_00_1f_4
pci_0000_00_1f_5
pci_10000_e0_06_0
pci_10000_e0_17_0
pci_10000_e1_00_0
scsi_host0
```

**Comment by DemiMarie** [comment]
Thanks!  Obviously `pci_10000_e0_06_0` does not match qubesd’s regex and will trip that assertion.  It almost looks like your system has more than one PCIe root complex or something else strange.  What happens if you unplug the Thunderbolt cable?

**Comment by xunillen** [comment]
Here's the problem, nothing is connected to the ThunderBolt port. And i forgot to say, this laptop has Intel Volume Management Device (VMD) technology enabled. Can that cause such issues?

Here is the output of _lspci_ command, if it helps in any way:

```
0000:00:00.0 Host bridge: Intel Corporation 11th Gen Core Processor Host Bridge/DRAM Registers (rev 01)
0000:00:02.0 VGA compatible controller: Intel Corporation TigerLake-LP GT2 [Iris Xe Graphics] (rev 01)
0000:00:04.0 Signal processing controller: Intel Corporation TigerLake-LP Dynamic Tuning Processor Participant (rev 01)
0000:00:06.0 System peripheral: Intel Corporation Device 09ab
0000:00:08.0 System peripheral: Intel Corporation GNA Scoring Accelerator module (rev 01)
0000:00:0a.0 Signal processing controller: Intel Corporation Tigerlake Telemetry Aggregator Driver (rev 01)
0000:00:0d.0 USB controller: Intel Corporation Tiger Lake-LP Thunderbolt 4 USB Controller (rev 01)
0000:00:0e.0 RAID bus controller: Intel Corporation Volume Management Device NVMe RAID Controller
0000:00:14.0 USB controller: Intel Corporation Tiger Lake-LP USB 3.2 Gen 2x1 xHCI Host Controller (rev 20)
0000:00:14.2 RAM memory: Intel Corporation Tiger Lake-LP Shared SRAM (rev 20)
0000:00:14.3 Network controller: Intel Corporation Wi-Fi 6 AX201 (rev 20)
0000:00:15.0 Serial bus controller [0c80]: Intel Corporation Tiger Lake-LP Serial IO I2C Controller #0 (rev 20)
0000:00:15.1 Serial bus controller [0c80]: Intel Corporation Tiger Lake-LP Serial IO I2C Controller #1 (rev 20)
0000:00:16.0 Communication controller: Intel Corporation Tiger Lake-LP Management Engine Interface (rev 20)
0000:00:17.0 System peripheral: Intel Corporation Device 09ab
0000:00:1f.0 ISA bridge: Intel Corporation Tiger Lake-LP LPC Controller (rev 20)
0000:00:1f.3 Multimedia audio controller: Intel Corporation Tiger Lake-LP Smart Sound Technology Audio Controller (rev 20)
0000:00:1f.4 SMBus: Intel Corporation Tiger Lake-LP SMBus Controller (rev 20)
0000:00:1f.5 Serial bus controller [0c80]: Intel Corporation Tiger Lake-LP SPI Controller (rev 20)
10000:e0:06.0 PCI bridge: Intel Corporation 11th Gen Core Processor PCIe Controller (rev 01)
10000:e0:17.0 SATA controller: Intel Corporation Device a0d3 (rev 20)
10000:e1:00.0 Non-Volatile memory controller: Sandisk Corp WD Blue SN550 NVMe SSD (rev 01)
```

**Comment by DemiMarie** [comment]
> Intel Volume Management Device (VMD) technology enabled. Can that cause such issues?

That is probably the culprit, but I have no idea how dom0 should handle it.

> Here is the output of `lspci` command, if it helps in any way:

It does, and is about what I would expect for VMD given what I have just seen on Intel’s website.

**Comment by brendanhoar** [comment]
Perhaps Intel Volume Management Device can be disabled in bios?

B

**Comment by RaspyVotan** [comment]
The proposed solution to de-activate VMD worked for me: I de-activated 
it in BIOS, and after re-booting the laptop

- I can run "qvm-pci" and get a list of devices

- The tab "Devices" under "Settings" is not greyed out anymore.


Thanks for all your help!

**Comment by DemiMarie** [comment]
@marmarek @HW42: is it safe to just loosen the assertion?

**Comment by xunillen** [comment]
I can confirm what RaspyVotan says. I disabled the VMD in the BIOS and everything is working fine now. `qvm-pci` command works, and 'Device' tab is not greyed out anymore.
