### ISSUE TITLE
Qubes 4.1-RC1 fails to install fedora-34 template

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#6975]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Installed R4.1-RC1 from the provided ISO

### Brief summary

![error](https://user-images.githubusercontent.com/47065258/137458354-d9fab907-1b78-420a-82a7-e44188027d8e.jpeg)

I chose the defaults in the initial setup. After clicking OK it did show up the usual qubes UI but only fedora-34 was installed. No sys-net, no sys-vpn, etc.

### Steps to reproduce
1. Installed R4.1-RC1 from the provided ISO with the default setup

### Expected behavior
Installs correctly

### Actual behavior
Install fails with error as in screenshot above.

### Reproducible?
Afterwards I repeated the whole process from the RC1 ISO and the same exact issue happened.

So I may be able to get some extra debug logs if someone tells me which ones to get and how to get them.

### Related issues
- https://github.com/QubesOS/qubes-issues/issues/5636
- https://github.com/QubesOS/qubes-issues/issues/3122

- started discussing originally on the forum but with no replies: https://forum.qubes-os.org/t/rc1-failed-in-initial-setup-qvm-template-install-fedora-34/6888

**Comment by deeplow** [comment]
@fepitre here are some logs. qubesd logs

```
-- Logs begin at Tue 2021-10-12 10:42:46 EDT, end at Fri 2021-10-15 16:25:20 EDT. --
Oct 12 14:42:54 dom0 systemd[1]: Starting Qubes OS daemon...
Oct 12 14:42:55 dom0 qubesd[1447]: Required property 'default_template' not set on <qubes.app.Qubes object at 0x7b2467ce2d90>
Oct 12 14:42:55 dom0 systemd[1]: Started Qubes OS daemon.
Oct 12 14:50:58 dom0 qubesd[1447]: vm.fedora-34: Creating directory: /var/lib/qubes/vm-templates/fedora-34
Oct 12 14:50:59 dom0 runuser[2294]: pam_unix(runuser:session): session opened for user user by (uid=0)
Oct 12 14:50:59 dom0 runuser[2294]: pam_unix(runuser:session): session closed for user user
Oct 12 14:52:34 dom0 qubesd[1447]: vm.fedora-34: Starting fedora-34
Oct 12 14:52:36 dom0 qubesd[1447]: vm.fedora-34: Setting Qubes DB info for the VM
Oct 12 14:52:36 dom0 qubesd[1447]: vm.fedora-34: Starting Qubes DB
Oct 12 14:52:37 dom0 runuser[3017]: pam_unix(runuser:session): session opened for user user by (uid=0)
Oct 12 14:52:37 dom0 runuser[3017]: pam_unix(runuser:session): session closed for user user
Oct 12 14:52:37 dom0 qubesd[1447]: vm.fedora-34: Activating the fedora-34 VM
Oct 12 14:52:37 dom0 runuser[3021]: pam_unix(runuser:session): session opened for user user by (uid=0)
Oct 12 14:52:43 dom0 runuser[3021]: pam_unix(runuser:session): session closed for user user
Oct 12 15:09:36 dom0 qubesd[1447]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Create.AppVM' dest=b'dom0' arg=b'' len(untrusted_payload)=22
Oct 12 15:09:36 dom0 qubesd[1447]: Traceback (most recent call last):
Oct 12 15:09:36 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
Oct 12 15:09:36 dom0 qubesd[1447]:     return getattr(instance, self._attr_name)
Oct 12 15:09:36 dom0 qubesd[1447]: AttributeError: 'Qubes' object has no attribute '_qubesprop_default_template'
Oct 12 15:09:36 dom0 qubesd[1447]: During handling of the above exception, another exception occurred:
Oct 12 15:09:36 dom0 qubesd[1447]: Traceback (most recent call last):
Oct 12 15:09:36 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/api/__init__.py", line 286, in respond
Oct 12 15:09:36 dom0 qubesd[1447]:     response = await self.mgmt.execute(
Oct 12 15:09:36 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/api/admin.py", line 1128, in _vm_create
Oct 12 15:09:36 dom0 qubesd[1447]:     vm = self.app.add_new_vm(vm_class, **kwargs)
Oct 12 15:09:36 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/app.py", line 1302, in add_new_vm
Oct 12 15:09:36 dom0 qubesd[1447]:     kwargs['template'] = self.default_template
Oct 12 15:09:36 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 230, in __get__
Oct 12 15:09:36 dom0 qubesd[1447]:     return self.get_default(instance)
Oct 12 15:09:36 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 234, in get_default
Oct 12 15:09:36 dom0 qubesd[1447]:     raise AttributeError(
Oct 12 15:09:36 dom0 qubesd[1447]: AttributeError: property 'default_template' have no default
Oct 12 15:09:54 dom0 qubesd[1447]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Create.AppVM' dest=b'dom0' arg=b'' len(untrusted_payload)=22
Oct 12 15:09:54 dom0 qubesd[1447]: Traceback (most recent call last):
Oct 12 15:09:54 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 227, in __get__
Oct 12 15:09:54 dom0 qubesd[1447]:     return getattr(instance, self._attr_name)
Oct 12 15:09:54 dom0 qubesd[1447]: AttributeError: 'Qubes' object has no attribute '_qubesprop_default_template'
Oct 12 15:09:54 dom0 qubesd[1447]: During handling of the above exception, another exception occurred:
Oct 12 15:09:54 dom0 qubesd[1447]: Traceback (most recent call last):
Oct 12 15:09:54 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/api/__init__.py", line 286, in respond
Oct 12 15:09:54 dom0 qubesd[1447]:     response = await self.mgmt.execute(
Oct 12 15:09:54 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/api/admin.py", line 1128, in _vm_create
Oct 12 15:09:54 dom0 qubesd[1447]:     vm = self.app.add_new_vm(vm_class, **kwargs)
Oct 12 15:09:54 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/app.py", line 1302, in add_new_vm
Oct 12 15:09:54 dom0 qubesd[1447]:     kwargs['template'] = self.default_template
Oct 12 15:09:54 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 230, in __get__
Oct 12 15:09:54 dom0 qubesd[1447]:     return self.get_default(instance)
Oct 12 15:09:54 dom0 qubesd[1447]:   File "/usr/lib/python3.8/site-packages/qubes/__init__.py", line 234, in get_default
Oct 12 15:09:54 dom0 qubesd[1447]:     raise AttributeError(
Oct 12 15:09:54 dom0 qubesd[1447]: AttributeError: property 'default_template' have no default
Oct 12 15:13:11 dom0 qubesd[1447]: socket.send() raised exception.
Oct 12 15:13:11 dom0 qubesd[1447]: socket.send() raised exception.
Oct 12 15:13:11 dom0 qubesd[1447]: socket.send() raised exception.
Oct 12 15:13:11 dom0 qubesd[1447]: socket.send() raised exception.
Oct 12 15:13:16 dom0 systemd[1]: Stopping Qubes OS daemon...
Oct 12 15:13:16 dom0 qubesd[1447]: caught SIGTERM, exiting
Oct 12 15:13:16 dom0 systemd[1]: qubesd.service: Succeeded.
Oct 12 15:13:16 dom0 systemd[1]: Stopped Qubes OS daemon.
Oct 12 15:13:16 dom0 systemd[1]: qubesd.service: Consumed 5.236s CPU time.
-- Reboot --
Oct 15 16:19:28 dom0 systemd[1]: Starting Qubes OS daemon...
Oct 15 16:19:28 dom0 qubesd[1278]: Required property 'default_template' not set on <qubes.app.Qubes object at 0x7f0738586d60>
Oct 15 16:19:28 dom0 systemd[1]: Started Qubes OS daemon.
-- Reboot --
Oct 15 16:24:07 dom0 systemd[1]: Starting Qubes OS daemon...
Oct 15 16:24:07 dom0 qubesd[1279]: Required property 'default_template' not set on <qubes.app.Qubes object at 0x7fa3c13f1d60>
Oct 15 16:24:07 dom0 systemd[1]: Started Qubes OS daemon.
```

**Comment by deeplow** [comment]
Oddly enough I reinstalled the system twice now and this issue didn't happen.

**Comment by deeplow** [comment]
Closing until I can make it reproducible.

**Comment by deeplow** [comment]
@fepitre another user experiencing this: https://forum.qubes-os.org/t/post-instalation-fail-to-install-basic-template-and-qube/6996

**Comment by fepitre** [comment]
Ok something really needs to be done here.
