### ISSUE TITLE
menu: exception when adding the first favorite entry

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7068]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

New app menu: adding the first ever favorite entry fails.

### Steps to reproduce

1. Start the new menu
2. Try to add the first ever favorite entry

### Expected behavior

Entry added.

### Actual behavior

```
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubes_menu/app_widgets.py", line 161, in _add_to_favorites
    current_feature = target_vm.features.get(constants.FAVORITES_FEATURE)
  File "/usr/lib/python3.8/site-packages/qubesadmin/features.py", line 74, in get
    return self[item]
  File "/usr/lib/python3.8/site-packages/qubesadmin/features.py", line 54, in __getitem__
    return self.vm.qubesd_call(
  File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 74, in qubesd_call
    return self.app.qubesd_call(dest, method, arg, payload,
  File "/usr/lib/python3.8/site-packages/qubesadmin/app.py", line 748, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 109, in _parse_qubesd_response
    raise exc_class(format_string, *args)
qubesadmin.exc.QubesFeatureNotFoundError: Feature not set for domain dom0: menu-favorites
```

**Comment by andrewdavidwong** [comment]
Reported against 4.1 but milestone set to 4.2. Was this intentional, @marmarek?
