### ISSUE TITLE
[4.1] qvm-shutdown –wait causes QubesVMNotFoundError

### ISSUE THREAD

**Issue by anybody-01** [QubesOS/qubes-issues#7108]
### Qubes OS release
4.1 RC2 (most recent updates)

### Brief summary
See https://forum.qubes-os.org/t/4-1-qvm-shutdown-wait-with-disposables-is-buggy/8014

`qvm-shutdown --wait dispxxxx` results in an error, while shuting down the disposable.
The command does work properly with Qubes OS 4.0.

### Steps to reproduce
Start any non-named disposable. Then invoke (substitute `1234` by given id):
```
qvm-shutdown --wait disp1234
```

### Expected behavior
No provoked errors, same behavior as Qubes OS 4.0 

### Actual behavior
```
[user@dom0 ~]$ qvm-shutdown --wait disp1234
Traceback (most recent call last):
  File "/usr/bin/qvm-shutdown", line 5, in <module>
    sys.exit(main())
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_shutdown.py", line 139, in main
    power_state = vm.get_power_state()
  File "/usr/lib/python3.8/site-packages/qubesadmin/vm/__init__.py", line 188, in get_power_state
    power_state = self._get_current_state()['power_state']
  File "/usr/lib/python3.8/site-packages/qubesadmin/vm/__init__.py", line 204, in _get_current_state
    response = self.qubesd_call(self._method_dest, 'admin.vm.CurrentState')
  File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 74, in qubesd_call
    return self.app.qubesd_call(dest, method, arg, payload,
  File "/usr/lib/python3.8/site-packages/qubesadmin/app.py", line 748, in qubesd_call
    return self._parse_qubesd_response(return_data)
  File "/usr/lib/python3.8/site-packages/qubesadmin/base.py", line 109, in _parse_qubesd_response
    raise exc_class(format_string, *args)
qubesadmin.exc.QubesVMNotFoundError: No such domain: 'disp1234'
```

There might be race conditions, as `disp1234` properly gets shut down, but still raises the error
> No such domain: ‘disp1234’

**Comment by lubellier** [comment]
Tests results:

- works without `--wait` 
- works with `--wait` if you wait ~2mn after the dispVM start
- fails with `--wait` if you wait less than ~2mn after the dispVM start

Failure reason:
```
  File "/usr/lib/python3.8/site-packages/qubesadmin/vm/__init__.py", line 188, in get_power_state
    power_state = self._get_current_state()['power_state']
```
--> fails to get the power_state of the dispVM
