### ISSUE TITLE
python exception printed out, while running 'dnf update'

### ISSUE THREAD

**Issue by iggi42** [QubesOS/qubes-issues#7109]
### Qubes OS release
Qubes release 4.0 (R4.0)

### Brief summary
While running `dnf update` in a minimal fedora-33 template vm, a python exception is printed to the terminal.
This exception:
```
Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf/plugin.py", line 104, in _caller
    getattr(plugin, method)()
  File "/usr/lib/python3.9/site-packages/dnf-plugins/qubes-hooks.py", line 78, in transaction
    updates.discard(item.pkg)
  File "/usr/lib/python3.9/site-packages/dnf/db/history.py", line 157, in pkg
    return self._swdb.rpm._swdb_ti_pkg[self._item]
KeyError: <libdnf.transaction.TransactionItem; proxy of <Swig Object of type 'libdnf::TransactionItemPtr *' at 0x700bdfaef750> >
```

### Steps to reproduce
Frankly, no idea. 
I can reproduce it with a `qvm-volume revert` and then calling `dnf update` again.
It doesn't show up again. Any ideas what information about the template vm I should provide additionally?

### Expected behavior
not printing out a python exception.

### Actual behavior
showing said python exception.

Here is the full output of the `dnf update`:
```
Last metadata expiration check: 0:01:59 ago on Thu Dec  9 16:21:58 2021.
Dendencies resolved.
================================================================================
 Package                       Arch      Version              Repository   Size
================================================================================
Upgrading:
 ethtool                       x86_64    2:5.15-1.fc33        updates     219 k
 hwdata                        noarch    0.353-1.fc33         updates     1.5 M
 libseccomp                    x86_64    2.5.3-1.fc33         updates      72 k
 libusb                        x86_64    1:0.1.7-6.fc33       updates      29 k
 python-unversioned-command    noarch    3.9.9-2.fc33         updates      12 k
 python3                       x86_64    3.9.9-2.fc33         updates      28 k
 python3-libs                  x86_64    3.9.9-2.fc33         updates     7.3 M
 python3-tkinter               x86_64    3.9.9-2.fc33         updates     311 k
 vim-minimal                   x86_64    2:8.2.3582-1.fc33    updates     702 k
Installing dependencies:
 kernel-debug-core             x86_64    5.14.18-100.fc33     updates      37 M
 kernel-debug-modules          x86_64    5.14.18-100.fc33     updates      33 M
Removing:
 kernel-debug-core             x86_64    5.14.13-100.fc33     @updates     79 M
 kernel-debug-modules          x86_64    5.14.13-100.fc33     @updates     32 M

Transaction Summary
================================================================================
Install  2 Packages
Upgrade  9 Packages
Remove   2 Packages

Total download size: 79 M
Is this ok [y/N]: Downloading Packages:
(1/11): ethtool-5.15-1.fc33.x86_64.rpm           68 kB/s | 219 kB     00:03    
(2/11): hwdata-0.353-1.fc33.noarch.rpm          102 kB/s | 1.5 MB     00:14    
(3/11): libseccomp-2.5.3-1.fc33.x86_64.rpm       18 kB/s |  72 kB     00:03    
(4/11): libusb-0.1.7-6.fc33.x86_64.rpm           11 kB/s |  29 kB     00:02    
(5/11): python-unversioned-command-3.9.9-2.fc33 5.1 kB/s |  12 kB     00:02    
(6/11): python3-3.9.9-2.fc33.x86_64.rpm          12 kB/s |  28 kB     00:02    
(7/11): python3-libs-3.9.9-2.fc33.x86_64.rpm    121 kB/s | 7.3 MB     01:01    
(8/11): python3-tkinter-3.9.9-2.fc33.x86_64.rpm  71 kB/s | 311 kB     00:04    
(9/11): vim-minimal-8.2.3582-1.fc33.x86_64.rpm  178 kB/s | 702 kB     00:03    
(10/11): kernel-debug-modules-5.14.18-100.fc33. 270 kB/s |  33 MB     02:03    
(11/11): kernel-debug-core-5.14.18-100.fc33.x86 296 kB/s |  37 MB     02:06    
--------------------------------------------------------------------------------
Total                                           636 kB/s |  79 MB     02:07     
Running transaction check
Transaction check succeeded.
Running transaction test
Transaction test succeeded.
Running transaction
  Preparing        :                                                        1/1 
  Upgrading        : python3-libs-3.9.9-2.fc33.x86_64                      1/22 
  Upgrading        : python3-tkinter-3.9.9-2.fc33.x86_64                   2/22 
  Upgrading        : python3-3.9.9-2.fc33.x86_64                           3/22 
  Upgrading        : python-unversioned-command-3.9.9-2.fc33.noarch        4/22 
  Installing       : kernel-debug-core-5.14.18-100.fc33.x86_64             5/22 
  Running scriptlet: kernel-debug-core-5.14.18-100.fc33.x86_64             5/22 
  Installing       : kernel-debug-modules-5.14.18-100.fc33.x86_64          6/22 
  Running scriptlet: kernel-debug-modules-5.14.18-100.fc33.x86_64          6/22 
  Upgrading        : vim-minimal-2:8.2.3582-1.fc33.x86_64                  7/22 
  Upgrading        : libusb-1:0.1.7-6.fc33.x86_64                          8/22 
  Upgrading        : libseccomp-2.5.3-1.fc33.x86_64                        9/22 
  Upgrading        : hwdata-0.353-1.fc33.noarch                           10/22 
  Upgrading        : ethtool-2:5.15-1.fc33.x86_64                         11/22 
  Erasing          : kernel-debug-modules-5.14.13-100.fc33.x86_64         12/22 
  Running scriptlet: kernel-debug-modules-5.14.13-100.fc33.x86_64         12/22 
  Cleanup          : python-unversioned-command-3.9.7-1.fc33.noarch       13/22 
  Running scriptlet: kernel-debug-core-5.14.13-100.fc33.x86_64            14/22 
  Erasing          : kernel-debug-core-5.14.13-100.fc33.x86_64            14/22 
  Cleanup          : hwdata-0.352-1.fc33.noarch                           15/22 
  Cleanup          : python3-tkinter-3.9.7-1.fc33.x86_64                  16/22 
  Cleanup          : python3-3.9.7-1.fc33.x86_64                          17/22 
  Cleanup          : python3-libs-3.9.7-1.fc33.x86_64                     18/22 
  Cleanup          : vim-minimal-2:8.2.3568-1.fc33.x86_64                 19/22 
  Cleanup          : libusb-1:0.1.7-2.fc33.x86_64                         20/22 
  Cleanup          : libseccomp-2.5.0-3.fc33.x86_64                       21/22 
  Cleanup          : ethtool-2:5.14-1.fc33.x86_64                         22/22 
  Running scriptlet: kernel-debug-core-5.14.18-100.fc33.x86_64            22/22 
  Running scriptlet: ethtool-2:5.14-1.fc33.x86_64                         22/22 
  Verifying        : kernel-debug-core-5.14.18-100.fc33.x86_64             1/22 
  Verifying        : kernel-debug-modules-5.14.18-100.fc33.x86_64          2/22 
  Verifying        : ethtool-2:5.15-1.fc33.x86_64                          3/22 
  Verifying        : ethtool-2:5.14-1.fc33.x86_64                          4/22 
  Verifying        : hwdata-0.353-1.fc33.noarch                            5/22 
  Verifying        : hwdata-0.352-1.fc33.noarch                            6/22 
  Verifying        : libseccomp-2.5.3-1.fc33.x86_64                        7/22 
  Verifying        : libseccomp-2.5.0-3.fc33.x86_64                        8/22 
  Verifying        : libusb-1:0.1.7-6.fc33.x86_64                          9/22 
  Verifying        : libusb-1:0.1.7-2.fc33.x86_64                         10/22 
  Verifying        : python-unversioned-command-3.9.9-2.fc33.noarch       11/22 
  Verifying        : python-unversioned-command-3.9.7-1.fc33.noarch       12/22 
  Verifying        : python3-3.9.9-2.fc33.x86_64                          13/22 
  Verifying        : python3-3.9.7-1.fc33.x86_64                          14/22 
  Verifying        : python3-libs-3.9.9-2.fc33.x86_64                     15/22 
  Verifying        : python3-libs-3.9.7-1.fc33.x86_64                     16/22 
  Verifying        : python3-tkinter-3.9.9-2.fc33.x86_64                  17/22 
  Verifying        : python3-tkinter-3.9.7-1.fc33.x86_64                  18/22 
  Verifying        : vim-minimal-2:8.2.3582-1.fc33.x86_64                 19/22 
  Verifying        : vim-minimal-2:8.2.3568-1.fc33.x86_64                 20/22 
  Verifying        : kernel-debug-core-5.14.13-100.fc33.x86_64            21/22 
  Verifying        : kernel-debug-modules-5.14.13-100.fc33.x86_64         22/22Traceback (most recent call last):
  File "/usr/lib/python3.9/site-packages/dnf/plugin.py", line 104, in _caller
    getattr(plugin, method)()
  File "/usr/lib/python3.9/site-packages/dnf-plugins/qubes-hooks.py", line 78, in transaction
    updates.discard(item.pkg)
  File "/usr/lib/python3.9/site-packages/dnf/db/history.py", line 157, in pkg
    return self._swdb.rpm._swdb_ti_pkg[self._item]
KeyError: <libdnf.transaction.TransactionItem; proxy of <Swig Object of type 'libdnf::TransactionItemPtr *' at 0x700bdfaef750> >

 

Upgraded:
  ethtool-2:5.15-1.fc33.x86_64                                                  
  hwdata-0.353-1.fc33.noarch                                                    
  libseccomp-2.5.3-1.fc33.x86_64                                                
  libusb-1:0.1.7-6.fc33.x86_64                                                  
  python-unversioned-command-3.9.9-2.fc33.noarch                                
  python3-3.9.9-2.fc33.x86_64                                                   
  python3-libs-3.9.9-2.fc33.x86_64                                              
  python3-tkinter-3.9.9-2.fc33.x86_64                                           
  vim-minimal-2:8.2.3582-1.fc33.x86_64                                          
Installed:
  kernel-debug-core-5.14.18-100.fc33.x86_64                                     
  kernel-debug-modules-5.14.18-100.fc33.x86_64                                  
Removed:
  kernel-debug-core-5.14.13-100.fc33.x86_64                                     
  kernel-debug-modules-5.14.13-100.fc33.x86_64                                  

Complete!
```

**Comment by DemiMarie** [comment]
Following.  I believe I have the same problem but didn’t think to report it.
