### ISSUE TITLE
Proper salt updates in archlinux templates

### ISSUE THREAD

**Issue by k4z4n0v4** [QubesOS/qubes-issues#7155]
### The problem you're addressing (if any)
Upgrading archlinux templates through saltstack ( Qubes Update widget) will never complete successfully. The upgrades-installed-check script that is run after the pkg.uptodate looks like this on archlinux's part:
```bash
elif [ -e /etc/arch-release ]; then
    ## Archlinux
    checkupdates >/dev/null 2>&1
    exit_code="$?"
    [ "$exit_code" -eq 2 ] && echo "true" && exit 0
    [ "$exit_code" -eq 0 ] && echo "false"
```
The issue resides in calling the checkupdates script. On archlinux templates the proxying of pacman is done by using a different pacman in `/run/qubes/bin/pacman`. When running this update through salt, the PATH variable is not set properly, hence the  `/run/qubes/bin/pacman` is not called by `upgrades-installed-check`, resulting in an exit code of 1, which is then not handled properly. 

### The solution you'd like
Initializing the proper PATH somewhere during the execution would fix this issue. For example by setting it in the upgrades-installed-check itself like so:
```bash
elif [ -e /etc/arch-release ]; then
    ## Archlinux
    export PATH=/run/qubes/bin:$PATH
    checkupdates >/dev/null 2>&1
    exit_code="$?"
    [ "$exit_code" -eq 2 ] && echo "true" && exit 0
    [ "$exit_code" -eq 0 ] && echo "false"
```

### The value to a user, and who that user might be
Correctly reporting the update state of archlinux templates for people who use the templates.

**Comment by techge** [comment]
This issue is not valid anymore as far as I can see, since https://github.com/QubesOS/qubes-core-agent-linux/pull/391 was merged. I suggest to close the issue.

**Comment by unman** [comment]
There's still an issue with Arch salt updates - they report as failures even
when the update is successful.
I would keep this open until updates work fully.

**Comment by techge** [comment]
Do you mean this kind of error?

```
Error on updating arch: Command '['sudo', 'qubesctl', '--skip-dom0', '--targets=arch', '--show-output', 'state.sls', 'update.qubes-vm']' returned non-zero exit status 20.
arch:
      ----------
      _error:
          Failed to return clean data
      retcode:
          64
      stderr:
          /usr/lib/python3.10/site-packages/_distutils_hack/__init__.py:33: UserWarning: Setuptools is replacing distutils.
            warnings.warn("Setuptools is replacing distutils.")
          Usage: salt-call [options] <function> [arguments]
          
          salt-call: error: Error while processing <function LogLevelMixIn.__setup_logging at 0x766641bda4d0>: Traceback (most recent call last):
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/parsers.py", line 212, in parse_args
              mixin_after_parsed_func(self)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/parsers.py", line 905, in __setup_logging
              salt._logging.setup_logging()
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/_logging/impl.py", line 971, in setup_logging
              setup_extended_logging(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/_logging/impl.py", line 878, in setup_extended_logging
              providers = salt.loader.log_handlers(opts)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/__init__.py", line 857, in log_handlers
              _module_dirs(
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/loader/__init__.py", line 153, in _module_dirs
              for entry_point in entrypoints.iter_entry_points("salt.loader"):
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/entrypoints.py", line 29, in _wrapped
              return f(*args, **kwargs)
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/entrypoints.py", line 41, in iter_entry_points
              for entry_point_group, entry_points_list in entry_points.items():
          AttributeError: 'EntryPoints' object has no attribute 'items'
      stdout:
```

While this is still an annoying problem, it seems to me to be a totally unlreated one, isn't it? We might open another issue for this? 

I wanted to look into it for a long time, but just did not find the time for it. Otherwise, which exact problem do you mean?

**Comment by ben-grande** [comment]
Please retest on R4.3.

**Comment by techge** [comment]
Could update without any issues (at least those described above).

Though archlinux is always a bit of a pain for the qubes updater anyway. There are issues when archlinux is bumping python versions, there are issues if the keyring is too old and so on. Therefore, I stopped using the qubes updater for archlinux and only update the other templates with it.

**Comment by ben-grande** [comment]
> Could update without any issues (at least those described above).

Closing as resolved because of this.

> Though archlinux is always a bit of a pain for the qubes updater anyway. There are issues when archlinux is bumping python versions, there are issues if the keyring is too old and so on. Therefore, I stopped using the qubes updater for archlinux and only update the other templates with it.

Yes. The current state is contributors make a PR to bump the python version as it is "fixed" to a less than current version. `x <= 3.14` for example. This workflow is not so nice because well, for a moment, all Archlinux users will have a broken update.
