### ISSUE TITLE
[Build 2022050209-4.1] openQA test fails in TC_00_AppVM_fedora-35 test_223_audio_play_hvm

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7485]
## Observation

openQA test in scenario qubesos-4.1-pull-requests-x86_64-system_tests_basic_vm_qrexec_gui@64bit fails in
[TC_00_AppVM_fedora-35](https://openqa.qubes-os.org/tests/39051/modules/TC_00_AppVM_fedora-35/steps/17)

```
# test_223_audio_play_hvm
# failure: 

# timestamp 2022-05-02T13:57:41.322085
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 484, in common_audio_playback
    self.loop.run_until_complete(
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
subprocess.CalledProcessError: Command 'paplay --format=float32le --rate=44100                             --channels=1 --raw audio_in.raw' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 605, in test_223_audio_play_hvm
    self.common_audio_playback()
  File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 489, in common_audio_playback
    self.fail('{} stderr: {}'.format(str(err), err.stderr))
AssertionError: Command 'paplay --format=float32le --rate=44100                             --channels=1 --raw audio_in.raw' returned non-zero exit status 1. stderr: b'Failed to drain stream: Timeout\n'

# system-out: 


```

## Test suite description

Play audio over qemu-emulated sound card.

## Reproducible

Fails since (at least) Build [2022050102-4.1](https://openqa.qubes-os.org/tests/38998)

## Expected result

Last good: [2022042005-4.1](https://openqa.qubes-os.org/tests/38592) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=pull-requests&machine=64bit&test=system_tests_basic_vm_qrexec_gui&version=4.1)

This fails in fedora-35 only, so it's unlikely to be a kernel or stubdom issue. While using qemu-emulated sound card in fedora-35 specifically is not very useful thing (there is native PA module which works much better), the issue may be more general about pulseaudio in fedora-35 and may affect sys-audio too.

**Comment by marmarek** [comment]
This is a conflict with pipewire. Until #6358 is fixed, pipewire needs to be disabled.
