### ISSUE TITLE
qvm-template: "No such file or directory" while installing template

### ISSUE THREAD

**Issue by Minimalist73** [QubesOS/qubes-issues#7529]
### Qubes OS release
4.1

### Brief summary
While using `qvm-template` to install a new template, the execution fails at the beginning with "No such file or directory"

Interesting error line: `Error canonicalizing file: not an RPM package`

I tested fedora-33 and fedora-34-xfce and it works correctly.

### Steps to reproduce
- Execute following command in dom0 `qvm-template install fedora-36 --enablerepo='qubes-templates-itl-testing' --verbose`

### Expected behavior
Download fedora-36 template

### Actual behavior
Say that the "qubes-template-fedora-36-0:4.0.6-202205270243.rpm.UNTRUSTED" file don't exist (tmp folder do create when command is executed):

```
[user@dom0 ~]$ qvm-template install fedora-36 --enablerepo='qubes-templates-itl-testing' --verbose
Downloading 'qubes-template-fedora-36-0:4.0.6-202205270243'...
qubes-template-fedora-36-0:4.0.6-202205270243:   0%| | 0.00/1.72G [00:00<?, ?B/s Error canonicalizing file: not an RPM package
qubes-template-fedora-36-0:4.0.6-202205270243:   0%| | 0.00/1.72G [00:01<?, ?B/s
ERROR: [Errno 2] No such file or directory: '/home/user/.cache/qvm-template/tmpxqh0rehu/qubes-template-fedora-36-0:4.0.6-202205270243.rpm.UNTRUSTED'
2022-05-27 20:51:23,706 [MainProcess qvm_template.main:1701] app: [Errno 2] No such file or directory: '/home/user/.cache/qvm-template/tmpxqh0rehu/qubes-template-fedora-36-0:4.0.6-202205270243.rpm.UNTRUSTED'
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 897, in download
    qrexec_download(args, app, spec, target_temp,
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 657, in qrexec_download
    raise ConnectionError("rpmcanon failed")
ConnectionError: rpmcanon failed

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 1671, in main
    install(p_args, app)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 933, in wrapper
    return func(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 1072, in install
    package_hdrs = download(args, app,
  File "/usr/lib/python3.8/site-packages/qubesadmin/tools/qvm_template.py", line 902, in download
    os.remove(target_temp)
FileNotFoundError: [Errno 2] No such file or directory: '/home/user/.cache/qvm-template/tmpxqh0rehu/qubes-template-fedora-36-0:4.0.6-202205270243.rpm.UNTRUSTED'
```

**Comment by DemiMarie** [comment]
I believe “Error canonicalizing file: not an RPM package” means that rpmcanon got something that didn’t have the appropriate magic number to be an RPM package.  The most likely reason for this is that the server sent back garbage (such as an error page) instead of a package.

“No such file or directory” comes from qvm-template expecting rpmcanon to have produced an output file and not finding it.  This is normal in the case that rpmcanon fails, but the exception should have been caught.  The exception traceback is not helpful.
