### ISSUE TITLE
Error message when doing fresh 4.1.1 install: "qvm-pool: error: failed to add pool vm-pool: Got empty response from qubesd."

### ISSUE THREAD

**Issue by heinrich-ulbricht** [QubesOS/qubes-issues#7770]
### Qubes OS release
Latest 4.1.1, ISO downloaded today

### Brief summary
I installed Qubes OS 4.1.1 and at the end of the installation got an error message dialog telling me:

```
['/usr/bin/qvm-pool', '--add', 'vm-pool', 'lvm_thin', '-o', 'volume_group=qubes_dom0,thin_pool=vm-pool,revisions_to_keep=2'] failed:
                                     stdout: ""
                                     stderr: "usage: qvm-pool [--verbose] [--quiet] [--help] [-o options]
                                                     [-l | -i POOLNAME | -a NAME DRIVER | -r NAME | -s POOLNAME | --help-drivers]
                                     qvm-pool: error: failed to add pool vm-pool: Got empty response from qubesd. See journalctl in dom0 for details.
```

### Steps to reproduce

(Not sure if this really reproduces the issue but those are the steps that I took:)

* download Qubes 4.1.1 ISO
* `dd` it to a thumb drive
* boot to installation
* install
* reboot
* have Qubes configuration shown (template selection, etc.) - for the **first** time
* do nothing fancy; here are non-default settings I chose:
  * German keyboard layout
  * no default AppVMs
  * sys-usb shall be created
  * I once selected the option "custom pool", but unselected it again (might still have changed something?)

Installation went on for some time. Then a reboot. Then something surprising: the configuration dialog a second time, with the upper part (template selection) grayed out and the other options set back to default...

* in this **second** show of the configuration:
* choose the same settings again
* again choose "Finish configuration" (or whatever that read in the lower right corner)
* wait some time
* get a dialog box showing above error message
* dismiss the dialog
* reboot
* start working with Qubes OS - all seems well

The pool `vm-pool` is present and can be used. So I'm not sure if the error message is just confusing or if something is broken. Doesn't seem so. Nevertheless wanted to report this because currently Google does not produce anything for the error message.

### Expected behavior
No error message dialog.

### Actual behavior

journalctl excerpt containing the error message:
```
Sep 17 14:23:56 dom0 org.fedoraproject.Anaconda.Addons.Baz[2240]: INFO:anaconda.threading:Thread Done: AnaTaskThread-BazInstallationTask-1 (134003002361600)
Sep 17 14:23:56 dom0 org.fedoraproject.Anaconda.Addons.Baz[2240]: INFO:anaconda.threading:Running Thread: AnaTaskThread-BazInstallationTask-1 (134003002361600)
Sep 17 14:23:56 dom0 org.fedoraproject.Anaconda.Boss[2121]: INFO:anaconda.modules.common.task.meta:'Install the system' has started.
Sep 17 14:23:56 dom0 org.fedoraproject.Anaconda.Boss[2121]: DEBUG:dasbus.connection:Publishing an object at /org/fedoraproject/Anaconda/Boss/Task/2.
Sep 17 14:23:56 dom0 org.fedoraproject.Anaconda.Boss[2121]: DEBUG:anaconda.modules.boss.install_manager.install_manager:Getting task /org/fedoraproject/Anaconda/Addons/Baz/Task/1 from module org.fedoraproject.Anaconda.Addons.Baz
Sep 17 14:23:56 dom0 org.fedoraproject.Anaconda.Addons.Baz[2240]: DEBUG:dasbus.connection:Publishing an object at /org/fedoraproject/Anaconda/Addons/Baz/Task/1.
Sep 17 14:23:56 dom0 anaconda[2059]: anaconda: addons: Addon ADDON_placeholder doesn't have execute method!
Sep 17 14:23:56 dom0 anaconda[2059]: anaconda: progress: Executing ADDON_placeholder addon
Sep 17 14:22:55 dom0 kernel: audit: type=1334 audit(1663417375.559:190): prog-id=0 op=UNLOAD
Sep 17 14:22:55 dom0 kernel: audit: type=1334 audit(1663417375.559:189): prog-id=0 op=UNLOAD
Sep 17 14:22:55 dom0 audit: BPF prog-id=0 op=UNLOAD
Sep 17 14:22:55 dom0 audit: BPF prog-id=0 op=UNLOAD
Sep 17 14:22:55 dom0 kernel: audit: type=1131 audit(1663417375.531:188): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:55 dom0 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:55 dom0 systemd[1]: systemd-hostnamed.service: Succeeded.
Sep 17 14:22:54 dom0 kernel: audit: type=1334 audit(1663417374.582:187): prog-id=0 op=UNLOAD
Sep 17 14:22:54 dom0 kernel: audit: type=1334 audit(1663417374.582:186): prog-id=0 op=UNLOAD
Sep 17 14:22:54 dom0 kernel: audit: type=1334 audit(1663417374.582:185): prog-id=0 op=UNLOAD
Sep 17 14:22:54 dom0 audit: BPF prog-id=0 op=UNLOAD
Sep 17 14:22:54 dom0 audit: BPF prog-id=0 op=UNLOAD
Sep 17 14:22:54 dom0 audit: BPF prog-id=0 op=UNLOAD
Sep 17 14:22:54 dom0 audit[1]: SERVICE_STOP pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-localed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:54 dom0 kernel: audit: type=1131 audit(1663417374.555:184): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-localed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:54 dom0 systemd[1]: systemd-localed.service: Succeeded.
Sep 17 14:22:26 dom0 anaconda[2059]: anaconda: misc: Stopping self.
Sep 17 14:22:26 dom0 anaconda[2059]: anaconda: misc: Joining thread.
Sep 17 14:22:26 dom0 anaconda[2059]: anaconda: org_qubes_os_initial_setup.ks.qubes: ['/usr/bin/qvm-pool', '--add', 'vm-pool', 'lvm_thin', '-o', 'volume_group=qubes_dom0,thin_pool=vm-pool,revisions_to_keep=2'] failed:
                                     stdout: ""
                                     stderr: "usage: qvm-pool [--verbose] [--quiet] [--help] [-o options]
                                                     [-l | -i POOLNAME | -a NAME DRIVER | -r NAME | -s POOLNAME | --help-drivers]
                                     qvm-pool: error: failed to add pool vm-pool: Got empty response from qubesd. See journalctl in dom0 for details.
                                     
                                     "
Sep 17 14:22:26 dom0 qubesd[1972]: permission denied for call b'admin.pool.Add'+b'lvm_thin' (b'dom0' → b'dom0') with payload of 75 bytes
Sep 17 14:22:26 dom0 anaconda[2059]: program: Running... /usr/bin/qvm-pool --add vm-pool lvm_thin -o volume_group=qubes_dom0,thin_pool=vm-pool,revisions_to_keep=2
Sep 17 14:22:26 dom0 anaconda[2059]: program: Running... /usr/bin/qubes-prefs default-kernel 5.15.52-1.fc32
Sep 17 14:22:26 dom0 anaconda[2059]: anaconda: progress: Executing org_qubes_os_initial_setup addon
Sep 17 14:22:26 dom0 initial-setup[2059]: executing addons
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Users[2231]: INFO:anaconda.threading:Thread Done: AnaTaskThread-SetRootPasswordTask-1 (126572864472832)
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Users[2231]: DEBUG:program:Return code: 0
Sep 17 14:22:25 dom0 chage[6172]: changed password expiry for root
Sep 17 14:22:25 dom0 kernel: audit: type=1102 audit(1663417345.621:183): pid=6172 uid=0 auid=4294967295 ses=4294967295 msg='op=change-last-change-date id=0 exe="/usr/bin/chage" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:25 dom0 audit[6172]: USER_MGMT pid=6172 uid=0 auid=4294967295 ses=4294967295 msg='op=change-last-change-date id=0 exe="/usr/bin/chage" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Users[2231]: INFO:program:Running... chage -R / -d  root
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Users[2231]: INFO:program:Running... chpasswd -R / -e
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Users[2231]: INFO:anaconda.core.users:user account root locked
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Users[2231]: INFO:anaconda.core.users:user account root setup with no password
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Users[2231]: INFO:anaconda.threading:Running Thread: AnaTaskThread-SetRootPasswordTask-1 (126572864472832)
Sep 17 14:22:25 dom0 initial-setup[2059]: configuring root password via Configure root password task
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Users[2231]: DEBUG:dasbus.connection:Publishing an object at /org/fedoraproject/Anaconda/Modules/Users/Task/1.
Sep 17 14:22:25 dom0 initial-setup[2059]: skipping user configuration - already configured
Sep 17 14:22:25 dom0 kernel: audit: type=1130 audit(1663417345.511:182): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Network[2236]: DEBUG:anaconda.modules.network.network:Current hostname is set to dom0
Sep 17 14:22:25 dom0 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-hostnamed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:25 dom0 systemd[1]: Started Hostname Service.
Sep 17 14:22:25 dom0 systemd[1]: Starting Hostname Service...
Sep 17 14:22:25 dom0 kernel: audit: type=1334 audit(1663417345.436:181): prog-id=43 op=LOAD
Sep 17 14:22:25 dom0 kernel: audit: type=1334 audit(1663417345.436:180): prog-id=42 op=LOAD
Sep 17 14:22:25 dom0 audit: BPF prog-id=43 op=LOAD
Sep 17 14:22:25 dom0 audit: BPF prog-id=42 op=LOAD
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Network[2236]: INFO:anaconda.threading:Thread Done: AnaTaskThread-HostnameConfigurationTask-1 (124495095359232)
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Network[2236]: INFO:anaconda.threading:Running Thread: AnaTaskThread-HostnameConfigurationTask-1 (124495095359232)
Sep 17 14:22:25 dom0 org.fedoraproject.Anaconda.Modules.Network[2236]: DEBUG:dasbus.connection:Publishing an object at /org/fedoraproject/Anaconda/Modules/Network/Task/1.
Sep 17 14:22:24 dom0 org.fedoraproject.Anaconda.Modules.Localization[2239]: INFO:anaconda.threading:Thread Done: AnaTaskThread-KeyboardInstallationTask-1 (135325788878592)
Sep 17 14:22:24 dom0 org.fedoraproject.Anaconda.Modules.Localization[2239]: DEBUG:anaconda.modules.localization.localed:Missing virtual console keymap value de converted from ['de'] X layouts
Sep 17 14:22:24 dom0 kernel: audit: type=1130 audit(1663417344.517:179): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-localed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:24 dom0 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-localed comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:22:24 dom0 systemd[1]: Started Locale Service.
Sep 17 14:22:24 dom0 systemd[1]: Starting Locale Service...
```

**Comment by heinrich-ulbricht** [comment]
Just for completeness, in case it is relevant, and because I won't be able to re-do the installation, here is another (handled?) exception earlier in the logs:

```
Sep 17 14:21:45 dom0 root[5078]: /etc/xen/scripts/block: add XENBUS_PATH=backend/vbd/5/51728
Sep 17 14:21:45 dom0 root[5075]: /etc/xen/scripts/block: add XENBUS_PATH=backend/vbd/5/51712
Sep 17 14:21:43 dom0 lvm[1193]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Sep 17 14:21:43 dom0 lvm[1193]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Sep 17 14:21:43 dom0 lvm[1193]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Sep 17 14:21:43 dom0 lvm[1193]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Sep 17 14:21:43 dom0 kernel: audit: type=1130 audit(1663417303.144:154): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=qubes-vm@sys-net comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:21:43 dom0 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=qubes-vm@sys-net comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:21:43 dom0 systemd[1]: Finished Start Qubes VM sys-net.
Sep 17 14:21:43 dom0 kernel: audit: type=1104 audit(1663417303.119:153): pid=4926 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="user" exe="/usr/sbin/runuser" hostname=? addr=? terminal=? res=success'
Sep 17 14:21:43 dom0 kernel: audit: type=1106 audit(1663417303.118:152): pid=4926 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_unix acct="user" exe="/usr/sbin/runuser" hostname=? addr=? terminal=? re>
Sep 17 14:21:43 dom0 kernel: kauditd_printk_skb: 1 callbacks suppressed
Sep 17 14:21:43 dom0 audit[4926]: CRED_DISP pid=4926 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_rootok acct="user" exe="/usr/sbin/runuser" hostname=? addr=? terminal=? res=success'
Sep 17 14:21:43 dom0 audit[4926]: USER_END pid=4926 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:session_close grantors=pam_keyinit,pam_limits,pam_unix acct="user" exe="/usr/sbin/runuser" hostname=? addr=? terminal=? res=success'
Sep 17 14:21:43 dom0 runuser[4926]: pam_unix(runuser:session): session closed for user user
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: FileNotFoundError: [Errno 2] No such file or directory
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     sock.connect(address)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib64/python3.8/asyncio/selector_events.py", line 501, in _sock_connect
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     return await fut
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib64/python3.8/asyncio/selector_events.py", line 496, in sock_connect
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     await self.sock_connect(sock, path)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib64/python3.8/asyncio/unix_events.py", line 244, in create_unix_connection
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     transport, _ = await loop.create_unix_connection(
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib64/python3.8/asyncio/streams.py", line 111, in open_unix_connection
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     reader, writer = await asyncio.open_unix_connection(path)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib/python3.8/site-packages/qrexec/server.py", line 105, in call_socket_service_local
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     await call_socket_service(guivm, service, source_domain, params)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 151, in notify
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: Traceback (most recent call last):
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: During handling of the above exception, another exception occurred:
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: qrexec.exc.AccessDenied: no matching rule found
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     raise AccessDenied('no matching rule found')
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 1315, in find_matching_rule
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     rule = self.find_matching_rule(request)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib/python3.8/site-packages/qrexec/policy/parser.py", line 1306, in evaluate
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     resolution = policy.evaluate(request)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 273, in handle_request
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: Traceback (most recent call last):
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: error calling qrexec-policy-agent in dom0
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: qrexec: qubes.InputKeyboard: sys-usb -> dom0: denied: no matching rule found
Sep 17 14:21:36 dom0 crond[4942]: (CRON) INFO (running with inotify support)
Sep 17 14:21:36 dom0 crond[4942]: (CRON) INFO (RANDOM_DELAY will be scaled with factor 20% if used.)
Sep 17 14:21:36 dom0 crond[4942]: (CRON) INFO (Syslog will be used instead of sendmail.)
Sep 17 14:21:36 dom0 crond[4942]: (CRON) STARTUP (1.5.5)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: FileNotFoundError: [Errno 2] No such file or directory
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     sock.connect(address)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib64/python3.8/asyncio/selector_events.py", line 501, in _sock_connect
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     return await fut
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib64/python3.8/asyncio/selector_events.py", line 496, in sock_connect
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     await self.sock_connect(sock, path)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib64/python3.8/asyncio/unix_events.py", line 244, in create_unix_connection
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     transport, _ = await loop.create_unix_connection(
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib64/python3.8/asyncio/streams.py", line 111, in open_unix_connection
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     reader, writer = await asyncio.open_unix_connection(path)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib/python3.8/site-packages/qrexec/server.py", line 105, in call_socket_service_local
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     ask_response = await call_socket_service(
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 96, in execute
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     await resolution.execute(caller_ident)
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_exec.py", line 274, in handle_request
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:     result = await handle_request(**args, log=log,
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]:   File "/usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_daemon.py", line 100, in handle_client_connection
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: Traceback (most recent call last):
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: future: <Task finished name='Task-7' coro=<handle_client_connection() done, defined at /usr/lib/python3.8/site-packages/qrexec/tools/qrexec_policy_daemon.py:57> exception=FileNotFoundError(2, 'No such fil>
Sep 17 14:21:36 dom0 qrexec-policy-daemon[2394]: Task exception was never retrieved
Sep 17 14:21:36 dom0 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=crond comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:21:36 dom0 systemd[1]: Started Command Scheduler.
Sep 17 14:21:36 dom0 kernel: audit: type=1130 audit(1663417296.321:150): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-user-sessions comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:21:36 dom0 audit[1]: SERVICE_START pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-user-sessions comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
Sep 17 14:21:36 dom0 systemd[1]: Finished Permit User Sessions.
Sep 17 14:21:36 dom0 systemd[1]: Starting Permit User Sessions...
```
