### ISSUE TITLE
libvirt/libxl refuses 'ich6' sound card model

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#7946]
## Qubes OS release

4.2

## Observation

openQA test in scenario qubesos-4.2-update-x86_64-system_tests_basic_vm_qrexec_gui@64bit fails in
[TC_00_AppVM_debian-11](https://openqa.qubes-os.org/tests/55534/modules/TC_00_AppVM_debian-11/steps/17)

```
# test_223_audio_play_hvm
# error: 

# timestamp 2022-12-12T04:39:28.432749
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 602, in test_223_audio_play_hvm
    self.prepare_audio_vm()
  File "/usr/lib/python3.8/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 442, in prepare_audio_vm
    self.loop.run_until_complete(self.testvm1.start())
  File "/usr/lib64/python3.8/asyncio/base_events.py", line 616, in run_until_complete
    return future.result()
  File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 1210, in start
    raise exc
  File "/usr/lib/python3.8/site-packages/qubes/vm/qubesvm.py", line 1190, in start
    self.libvirt_domain.createWithFlags(
  File "/usr/lib/python3.8/site-packages/qubes/app.py", line 103, in wrapper
    return attr(*args, **kwargs)
  File "/usr/lib64/python3.8/site-packages/libvirt.py", line 1409, in createWithFlags
    raise libvirtError('virDomainCreateWithFlags() failed')
```

libxl-driver.log
```
2022-12-12 04:39:35.897+0000: libxl: libxl_dm.c:1528:libxl__build_device_model_args_new: Domain 68:Unknown soundhw option 'ich6'
```
## Test suite description

Boots with `qvm-features test-vm audio-model ich6`

## Reproducible

Fails since (at least) Build [2022121202-4.2](https://openqa.qubes-os.org/tests/55534) (current job)

## Expected result

Last good: (unknown) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=update&machine=64bit&test=system_tests_basic_vm_qrexec_gui&version=4.2)

**Comment by marmarek** [comment]
It's now called `hda`. I'll add automatic translation.

**Comment by marmarek** [comment]
Hmm, it looks like the simple translation in libvirt xml isn't enough:
```
XML error: Invalid value for attribute 'model' in element 'sound': 'hda'.
```
libvirt patch will be needed
