### ISSUE TITLE
shutdown-idle failed for fedora-37

### ISSUE THREAD

**Issue by lubellier** [QubesOS/qubes-issues#7979]
### Qubes OS release
R4.1

### Brief summary
With the  fedora-37 TemplateVM, the shutdown-idle service doesn't shutdown the AppVM.

### Steps to reproduce
- Install the fedora-37 template from templates-itl-testing.
- Install the `qubes-app-shutdown-idle` package (1.0.8-1.fc37) in the template
- create a fedora-37 based AppVM : test-f37
- activate shutdown-idle service from dom0 : qvm-features test-f37 service.shutdown-idle 1
- start test-f37, run a terminal, close the terminal
- wait 15mn

### Expected behavior
The AppVM shutdowns after 15mn without activities.

### Actual behavior
The AppVM doesn't shutdown after 15mn without activities.

Related to
- [Fedora 37 template #7807](https://github.com/QubesOS/qubes-issues/issues/7807)

**Comment by lubellier** [comment]
I tried to manually launch `qubes-idle-watcher`,  the result is : 
```
[user@test-f37 ~]$ /usr/bin/qubes-idle-watcher
Traceback (most recent call last):
  File "/usr/bin/qubes-idle-watcher", line 33, in <module>
    sys.exit(load_entry_point('qubesidle==1.0.8', 'console_scripts', 'qubes-idle-watcher')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesidle/idleness_monitor.py", line 116, in main
    asyncio.get_event_loop().run_until_complete(monitor.monitor_idleness())
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesidle/idleness_monitor.py", line 86, in monitor_idleness
    done, pending = await wait_for_change_with_timeout
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'IdleWatcher.wait_for_state_change' was never awaited
sys:1: RuntimeWarning: coroutine 'NetworkWatcher.wait_for_state_change' was never awaited

```

**Comment by lubellier** [comment]
@marmarta  I tested the `asyncio.create_task()` change from your pull request. It works well and fixes this issue. 
Thanks.
