### ISSUE TITLE
qubes-global-config crashes due to incorrect permissions on the `/etc/qubes/policy.d` dir

### ISSUE THREAD

**Issue by aronowski** [QubesOS/qubes-issues#8014]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2

### Brief summary

Launching qubes-global-config after a fresh 4.2 installation crashes due to being unable to load non-existent policies. For instance:

```
[user@dom0 ~]$ qubes-global-config 
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubes_config/global_config/policy_manager.py", line 78, in get_rules_from_filename
    rules_text, token = self.policy_client.policy_get(filename)
  File "/usr/lib/python3.8/site-packages/qrexec/policy/admin_client.py", line 49, in policy_get
    token, content = self.call("policy.Get", name).split("\n", 1)
  File "/usr/lib/python3.8/site-packages/qrexec/policy/admin_client.py", line 74, in call
    return call("dom0", service_name, arg, input=payload)
  File "/usr/lib/python3.8/site-packages/qrexec/client.py", line 53, in call
    return subprocess.check_output(
  File "/usr/lib64/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/lib/qubes/qubes-rpc-multiplexer', 'policy.Get+50-config-input', 'dom0']' returned non-zero exit status 1.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/qubes_config/global_config/global_config.py", line 206, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.8/site-packages/qubes_config/global_config/global_config.py", line 274, in perform_setup
    self.handlers['usb'] = DevicesHandler(
  File "/usr/lib/python3.8/site-packages/qubes_config/global_config/usb_devices.py", line 615, in __init__
    self.input_handler = InputDeviceHandler(
  File "/usr/lib/python3.8/site-packages/qubes_config/global_config/usb_devices.py", line 211, in __init__
    self.policy_manager.get_rules_from_filename(
  File "/usr/lib/python3.8/site-packages/qubes_config/global_config/policy_manager.py", line 82, in get_rules_from_filename
    self.policy_client.policy_replace(filename, default_policy)
  File "/usr/lib/python3.8/site-packages/qrexec/policy/admin_client.py", line 57, in policy_replace
    self.call("policy.Replace", name, token + "\n" + content)
  File "/usr/lib/python3.8/site-packages/qrexec/policy/admin_client.py", line 74, in call
    return call("dom0", service_name, arg, input=payload)
  File "/usr/lib/python3.8/site-packages/qrexec/client.py", line 53, in call
    return subprocess.check_output(
  File "/usr/lib64/python3.8/subprocess.py", line 415, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib64/python3.8/subprocess.py", line 516, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/lib/qubes/qubes-rpc-multiplexer', 'policy.Replace+50-config-input', 'dom0']' returned non-zero exit status 2.
```

As we can see, it complains about 50-config-input. Add it manually to `/etc/qubes/policy.d/50-config-input.policy` and it then complains about 50-config-clipboard. Fix this one analogically and it then complains about 50-config-filecopy. I then gave up on testing it further.

### Steps to reproduce

- Download the the 4.2 system from Qubes' OpenQA server:

```
wget https://openqa.qubes-os.org/tests/58993/asset/iso/Qubes-4.2.202301293-x86_64.iso
```

- Install the system as usual and launch qubes-global-config from the commandline.

### Expected behavior

The utility launches correctly.

### Actual behavior

The utility crashes.

**Comment by marmarek** [comment]
It isn't about missing policies, but about wrong permissions on `/etc/qubes/policy.d` dir (should be owned by group `qubes` and be writable by this group). The crash happens when the tool tries to create its policy file.

**Comment by marmarek** [comment]
The issue should be fixed in the next build (specifically when it will contain https://github.com/QubesOS/qubes-qubes-release/commit/b749a75d1fd9bd76265f3bce6c82fbc96c8b2ebe). But I'll add also code to fix this on update.

**Comment by Kenny606** [comment]
I believe this is resolved I also experienced this in RC1, but appears to be working normally in RC2.
While I haven't tried changing every option so far it opens and operates normally from the GUI or command line.

**Comment by andrewdavidwong** [comment]
Closing as resolved. If anyone believes this issue is not yet resolved, or if anyone is still affected by this issue, please leave a comment, and we'll be happy to reopen it. Thank you.

**Comment by kennethrrosen** [comment]
After upgrading-in-place to 4.2, I get this error when using Qubes OS Global Config to set USB devices. I've tried changing ownership to `qubes` and root user to no effect.

**Comment by ben-grande** [comment]
> After upgrading-in-place to 4.2, I get this error when using Qubes OS Global Config to set USB devices. I've tried changing ownership to `qubes` and root user to no effect.

Please share owners and mode of the files:

```
ls -l /etc/qubes/policy.d/*
```
