### ISSUE TITLE
Restoring/verifying a backup in GUI fails with "check extracting process errors"

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8078]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

It's similar to #8047 , after adding some debugging I got (in a child process):
```
Traceback (most recent call last):
  File "/usr/lib64/python3.11/multiprocessing/popen_fork.py", line 71, in _launch
    code = process_obj._bootstrap(parent_sentinel=child_r)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/multiprocessing/process.py", line 332, in _bootstrap
    threading._shutdown()
  File "/usr/lib64/python3.11/threading.py", line 1553, in _shutdown
    assert tlock is not None
           ^^^^^^^^^^^^^^^^^
AssertionError
```

This seems to be a regression between Python 3.11.1 and 3.11.2 (which landed in F37 recently). Upstream bug report will follow.

### Steps to reproduce

Try to verify a backup using GUI tool.

### Expected behavior

Completes successfully

### Actual behavior

https://openqa.qubes-os.org/tests/68374#step/qubesmanager_backuprestore/55

**Comment by marmarek** [comment]
Upstream bug report: https://github.com/python/cpython/issues/102512
