### ISSUE TITLE
U2F proxy fails with an AssertionError with Nitrokey 3A NFC

### ISSUE THREAD

**Issue by t-pa** [QubesOS/qubes-issues#8120]
### Qubes OS release
4.1

### Brief summary
U2F proxy fails with an `AssertionError` in `proto.py` when used with a Nitrokey 3A NFC. When the same key is directly attached as a USB device to the AppVM, everything works fine.

### Steps to reproduce
Follow the instructions in https://www.qubes-os.org/doc/u2f-proxy/. Plug in a Nitrokey 3A NFC and visit a website with U2F (e.g., https://github.com/ or https://u2f.bin.coffee/) in an AppVM (I tried both Fedora-36 and Debian-11). Try to register the key. The key starts blinking, touch it.

### Expected behavior
The key stops blinking and the registration succeeds.

### Actual behavior
The key keeps blinking and the registration process stalls. When the key is touched to confirm the registration, the following error messages are produced:

In sys-usb (prog is the AppVM):
```Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]: Traceback (most recent call last):
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib/python3.10/site-packages/qubesu2f/proto.py", line 147, in __init__
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     self.response_data = self.verify_response_data(
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib/python3.10/site-packages/qubesu2f/proto.py", line 294, in verify_response_data
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     assert key_handle_len <= const.MAX_KH_SIZE
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]: AssertionError
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]: 
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]: During handling of the above exception, another exception occurred:
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]: 
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]: Traceback (most recent call last):
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/bin/qu2f-register", line 5, in <module>
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     sys.exit(main())
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib/python3.10/site-packages/qubesu2f/tools/qu2f_register.py", line 39, in main
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib64/python3.10/asyncio/base_events.py", line 649, in run_until_complete
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     return future.result()
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib/python3.10/site-packages/qubesu2f/tools/__init__.py", line 63, in mux
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     response = await _mux(
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib/python3.10/site-packages/qubesu2f/tools/__init__.py", line 93, in _mux
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     result = fut.result()
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib64/python3.10/concurrent/futures/thread.py", line 58, in run
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     result = self.fn(*self.args, **self.kwargs)
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib/python3.10/site-packages/qubesu2f/tools/__init__.py", line 123, in _mux_device
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     return capdu.APDU_RESPONSE.from_buffer(untrusted_data=rapdu)
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib/python3.10/site-packages/qubesu2f/proto.py", line 217, in from_buffer
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     return cls(
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib/python3.10/site-packages/qubesu2f/proto.py", line 270, in __init__
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     super().__init__(*args, **kwargs)
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:   File "/usr/lib/python3.10/site-packages/qubesu2f/proto.py", line 160, in __init__
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]:     raise APDUWrongDataError()
Mar 24 13:31:51 sys-usb u2f.Register+-prog[7524]: qubesu2f.proto.APDUWrongDataError
```

In the AppVM (prog):
```2023-03-24 13:31:51,938 U2FHIDQrexecDevice.qrexec qrexec_client.returncode=1
2023-03-24 13:31:51,939 U2FHIDQrexecDevice.u2fhid handle_u2fhid_msg(cid=0x1f77d4f) err=APDUExecutionError()
Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qubesu2f/hidemu.py", line 347, in handle_u2fhid_msg
    bytes(await handle(apdu)))
  File "/usr/lib/python3/dist-packages/qubesu2f/tools/qu2f_proxy.py", line 86, in handle_u2f_register
    rapdu = await self.qrexec_transaction(apdu, rpcname='u2f.Register')
  File "/usr/lib/python3/dist-packages/qubesu2f/tools/qu2f_proxy.py", line 77, in qrexec_transaction
    raise proto.APDUExecutionError()
qubesu2f.proto.APDUExecutionError
```

**Comment by marmarek** [comment]
This is fixed with qubes-u2f 2.0 package (now named qubes-ctap).
