### ISSUE TITLE
blueman crashes in fedora-38-xfce template

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8161]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.1

### Brief summary

https://openqa.qubes-os.org/tests/72214/video?filename=video.ogv&t=434.00
```
[2023-04-29 11:34:01] [   34.638232] python3[715]: detected unhandled Python exception in '/usr/bin/blueman-applet'
[2023-04-29 11:34:02] [   35.227066] abrt-server[796]: Deleting problem directory Python3-2023-04-29-11:34:00-715 (dup of Python3-2023-04-29-10:38:49-814)
[2023-04-29 11:34:02] [   35.803849] abrt-notification[816]: Process 814 (blueman-applet) of user 1000 encountered an uncaught gi.repository.GLib.GError exception
```

### Steps to reproduce

Start fedora-38-xfce template

### Expected behavior

No crash, maybe blueman-applet not even started if there are no bluetooth devices.

### Actual behavior

Applet crashes.

BTW, the notification lacks override-redirect flag, so the window has normal decorations, and also grabs focus...

Part of #8069

**Comment by marmarek** [comment]
```
Traceback (most recent call last):
  File "/usr/bin/blueman-applet", line 40, in <module>
    app = BluemanApplet()
          ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/blueman/main/Applet.py", line 44, in __init__
    self.Plugins.load_plugin()
  File "/usr/lib/python3.11/site-packages/blueman/main/PluginManager.py", line 125, in load_plugin
    self.__load_plugin(cls)
  File "/usr/lib/python3.11/site-packages/blueman/main/PluginManager.py", line 163, in __load_plugin
    inst._load()
  File "/usr/lib/python3.11/site-packages/blueman/plugins/AppletPlugin.py", line 51, in _load
    super()._load()
  File "/usr/lib/python3.11/site-packages/blueman/plugins/BasePlugin.py", line 77, in _load
    self.on_load()
  File "/usr/lib/python3.11/site-packages/blueman/plugins/applet/KillSwitch.py", line 61, in on_load
    channel = GLib.IOChannel.new_file("/dev/rfkill", "r")
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
gi.repository.GLib.GError: g-file-error-quark: Permission denied (2)

Local variables in innermost frame:
self: <blueman.plugins.applet.KillSwitch.KillSwitch object at 0x72d71e25dbd0>
```

**Comment by marmarek** [comment]
In fact, the same applies to fedora-37-xfce template.

**Comment by marmarek** [comment]
It seems to be caused by `/dev/rfkill` file existing, but `rfkill` module not actually loaded. This means the kernel doesn't consider device present, so related udev rule did not got applied, so it's left at `0600` and root-owned. Loading `rfkill` module makes `/dev/rfkill` permissions correctly set (0664, plus ACL for the local user).

**Comment by DemiMarie** [comment]
IMO it would be much better for Blueman to not even be started, to save memory.
