### ISSUE TITLE
Qubes Global Config window will not open

### ISSUE THREAD

**Issue by GWeck** [QubesOS/qubes-issues#8238]
### Qubes OS release
R4.2 with current (06/01/2023) patch to dom0

### Brief summary
The `Global Config` button of the Qube Manager as well as the `Qubes Global Config` menu command no longer displays the window with the configuration options. 

### Steps to reproduce
Install the current update containing e.g. `qubes-utils.x86_64` version `4.2.9-1.fc37` and `qubes-manager.noarch` version `4.2.4-1.fc37` to dom0 and then try to set global configuration data via the Qube Manager or the corresponding menu command.

### Expected behavior
A window should open allowing to set global configuration parameters (like it was in previous versions).

### Actual behavior
For a very short time, a window displaying a message like `Loading global settings` is shown which will close immediately.

**Comment by marmarta** [comment]
Hm, looks like something fails at load.. What happens if you try running `qubes-global-config` in command line?

**Comment by GWeck** [comment]
Well, I hoped it would work in this case, but it still shortly shows that small window and displays the following crash information:

~~~
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qubes_config/widgets/gtk_widgets.py", line 69, in set_token
    vm = self.qapp.domains[token_name]
         ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/app.py", line 98, in __getitem__
    raise KeyError(item)
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qubes_config/global_config/global_config.py", line 205, in do_activate
    self.perform_setup()
  File "/usr/lib/python3.11/site-packages/qubes_config/global_config/global_config.py", line 288, in perform_setup
    self.handlers['usb'] = DevicesHandler(
                           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes_config/global_config/usb_devices.py", line 642, in __init__
    self.usbvm_handler = USBVMHandler(self.qapp, gtk_builder)
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes_config/global_config/usb_devices.py", line 135, in __init__
    self.select_widget = VMWidget(
                         ^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes_config/global_config/rule_list_widgets.py", line 113, in __init__
    self.name_widget = TokenName(self.selected_value, self.qapp,
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes_config/widgets/gtk_widgets.py", line 61, in __init__
    self.set_token(token_name)
  File "/usr/lib/python3.11/site-packages/qubes_config/widgets/gtk_widgets.py", line 75, in set_token
    label.set_text(nice_name)
TypeError: Argument 1 does not allow None as a value
~~~

By the way: The updater icon in the taskbar of R4.2 (the black cog-wheel??? - looks rather ugly and even a bit intimidating. In my opinion, the icon in R4.1 - the orange star, which is also used by Debian as its update notifier - is much nicer. Just my 2 cents... :grin:

**Comment by GWeck** [comment]
I updated dom0 again, using today's update. No the global config is working again. Thanks for such a quick remedy!

The new configuration utility is a charm - it gives much more control and helps much better in selecting options.

**Comment by marmarta** [comment]
hahah, I was on my way to write you that this should be fixed by recent updates!
