### ISSUE TITLE
[fedora-37] qrexec-policy-agent TypeError: Passing coroutines is forbidden

### ISSUE THREAD

**Issue by daktak** [QubesOS/qubes-issues#8249]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.1.2 (R4.1)

### Brief summary
qvm-copy gives Request refused

fedora 37 installed from template
python 3.11.3
```
[user@chorus ~]$ qrexec-policy-agent

(qrexec-policy-agent:101433): Gdk-CRITICAL **: 14:27:17.716: gdk_atom_intern: assertion 'atom_name != NULL' failed

(qrexec-policy-agent:101433): Gdk-CRITICAL **: 14:27:17.717: gdk_atom_intern: assertion 'atom_name != NULL' failed
Traceback (most recent call last):
  File "/usr/bin/qrexec-policy-agent", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/qrexec/tools/qrexec_policy_agent.py", line 655, in main
    loop.run_until_complete(asyncio.wait(tasks))
  File "/usr/lib/python3.11/site-packages/gbulb/glib_events.py", line 846, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/asyncio/tasks.py", line 415, in wait
    raise TypeError("Passing coroutines is forbidden, use tasks explicitly.")
TypeError: Passing coroutines is forbidden, use tasks explicitly.
sys:1: RuntimeWarning: coroutine 'SocketService.run' was never awaited
```

### Steps to reproduce
qvm-copy-to-vm vm file

### Expected behavior
copy file to vm

### Actual behavior
Request refused

**Comment by daktak** [comment]
Ok, updated to fedora-38 template,
no error now in qrexec-agent-policy
however "ask" does not work in /etc/qubes/policy.d
added "allow" to qubes.FileCopy and it works, but ask just refuses and does not open a dialog

**Comment by daktak** [comment]
Update: After updating to fedora-38 template, and rebooting, ask does now prompt. 
This can be closed

**Comment by daktak** [comment]
Working as expected after full reboot.
