### ISSUE TITLE
qubes-video-companion-sender missing dependencies in fedora

### ISSUE THREAD

**Issue by Augsch123** [QubesOS/qubes-issues#8453]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2 but R4.1 is probably affected as well

### Brief summary

qubes-video-companion-sender needs libappindicator-gtk3 and notification-daemon on a fedora app qube. Otherwise there are error messages.

### Steps to reproduce

Try to use qubes-video-companion and have a minimal fedora 37 template as the screen-sharing sender.

### Expected behavior

Works

### Actual behavior
Without libappindicator-gtk3:

```
(screenshare.py:1126): Gdk-CRITICAL **: 13:58:53.771: gdk_atom_intern: assertion 'atom_name != NULL' failed

(screenshare.py:1126): Gdk-CRITICAL **: 13:58:53.772: gdk_atom_intern: assertion 'atom_name != NULL' failed
Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/sender/tray_icon.py", line 28, in <module>
    gi.require_version("AyatanaAppIndicator3", "0.1")
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AyatanaAppIndicator3 not available

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/sender/screenshare.py", line 16, in <module>
    from service import Service
  File "/usr/share/qubes-video-companion/sender/service.py", line 24, in <module>
    import tray_icon
  File "/usr/share/qubes-video-companion/sender/tray_icon.py", line 31, in <module>
    gi.require_version("AppIndicator3", "0.1")
  File "/usr/lib64/python3.11/site-packages/gi/__init__.py", line 126, in require_version
    raise ValueError('Namespace %s not available' % namespace)
ValueError: Namespace AppIndicator3 not available
Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 82, in <module>
    main(sys.argv)
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 17, in main
    width, height, fps = read_video_parameters()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 63, in read_video_parameters
    raise RuntimeError("wrong number of bytes read")
```

Without notification-daemon:

```
build qvc.ScreenShare+-disp6823[1491]: Traceback (most recent call last):
build qvc.ScreenShare+-disp6823[1491]:   File "/usr/share/qubes-video-companion/sender/screenshare.py", line 81, in <module>
build qvc.ScreenShare+-disp6823[1491]:     screenshare = ScreenShare()
build qvc.ScreenShare+-disp6823[1491]:                   ^^^^^^^^^^^^^
build qvc.ScreenShare+-disp6823[1491]:   File "/usr/share/qubes-video-companion/sender/screenshare.py", line 24, in __init__
build qvc.ScreenShare+-disp6823[1491]:     self.main(self)
build qvc.ScreenShare+-disp6823[1491]:   File "/usr/share/qubes-video-companion/sender/service.py", line 157, in main
build qvc.ScreenShare+-disp6823[1491]:     self.start_service(target_domain, remote_domain)
build qvc.ScreenShare+-disp6823[1491]:   File "/usr/share/qubes-video-companion/sender/service.py", line 51, in start_service
build qvc.ScreenShare+-disp6823[1491]:     Notify.Notification.new(app, msg, icon).show()
build qvc.ScreenShare+-disp6823[1491]: gi.repository.GLib.GError: g-dbus-error-quark: GDBus.Error:org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable (2)
```

**Comment by pietrushnic** [comment]
I see a similar trace in 4.1.2 using `1.0.5-1+deb12u1`:

```python
work% qubes-video-companion webcam
Cannot open device /dev/video0, exiting.
Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/sender/webcam.py", line 111, in <module>
    webcam = Webcam()
  File "/usr/share/qubes-video-companion/sender/webcam.py", line 19, in __init__
    self.main(self)
  File "/usr/share/qubes-video-companion/sender/service.py", line 158, in main
    self.start_transmission()
  File "/usr/share/qubes-video-companion/sender/service.py", line 124, in start_transmission
    width, height, fps, extra_params = self.parameters()
  File "/usr/share/qubes-video-companion/sender/webcam.py", line 36, in parameters
    proc = subprocess.run(
  File "/usr/lib/python3.9/subprocess.py", line 528, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '('v4l2-ctl', '--list-formats-ext')' returned non-zero exit status 1.
Traceback (most recent call last):
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 82, in <module>
    main(sys.argv)
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 17, in main
    width, height, fps = read_video_parameters()
                         ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/share/qubes-video-companion/receiver/receiver.py", line 63, in read_video_parameters
    raise RuntimeError("wrong number of bytes read")
RuntimeError: wrong number of bytes read
modprobe: FATAL: Module videodev is in use.
Please close any window that has an open video stream so kernel modules can be securely unloaded...
modprobe: FATAL: Module videodev is in use.
Please close any window that has an open video stream so kernel modules can be securely unloaded...
```

`lsmod`;

```bash
work% lsmod |grep video     
uvcvideo              167936  0
videobuf2_vmalloc      20480  1 uvcvideo
videobuf2_memops       20480  1 videobuf2_vmalloc
videobuf2_v4l2         40960  1 uvcvideo
videobuf2_common       86016  4 videobuf2_vmalloc,videobuf2_v4l2,uvcvideo,videobuf2_memops
videodev              323584  3 videobuf2_v4l2,uvcvideo,videobuf2_common
mc                     73728  5 videodev,snd_usb_audio,videobuf2_v4l2,uvcvideo,videobuf2_common
```
