### ISSUE TITLE
Salt error when attempting to install packages on fedora-38-minimal and debian-12-minimal

### ISSUE THREAD

**Issue by Szewcson** [QubesOS/qubes-issues#8488]
### Qubes OS release
4.2-rc2 after in-place upgrade

### Brief summary
When trying to use salt for installing packages on minimal templates salt returning with error:

```
2023-09-04 09:47:50,723 calling 'state.apply fedora-fw-template saltenv=user'...
2023-09-04 09:48:25,123 output: fedora-38-minimal-fw-2:
2023-09-04 09:48:25,124 output:     ----------
2023-09-04 09:48:25,124 output:     _error:
2023-09-04 09:48:25,124 output:         Failed to return clean data
2023-09-04 09:48:25,124 output:     retcode:
2023-09-04 09:48:25,124 output:         1
2023-09-04 09:48:25,124 output:     stderr:
2023-09-04 09:48:25,124 output:         /var/tmp/.root_6b9378_salt/pyall/salt/utils/http.py:8: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
2023-09-04 09:48:25,124 output:           import cgi
2023-09-04 09:48:25,124 output:         Traceback (most recent call last):
2023-09-04 09:48:25,124 output:           File "/var/tmp/.root_6b9378_salt/salt-call", line 27, in <module>
2023-09-04 09:48:25,124 output:             salt_call()
2023-09-04 09:48:25,124 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/scripts.py", line 438, in salt_call
2023-09-04 09:48:25,124 output:             import salt.cli.call
2023-09-04 09:48:25,124 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/cli/call.py", line 3, in <module>
2023-09-04 09:48:25,124 output:             import salt.cli.caller
2023-09-04 09:48:25,124 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/cli/caller.py", line 12, in <module>
2023-09-04 09:48:25,124 output:             import salt.channel.client
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/channel/client.py", line 13, in <module>
2023-09-04 09:48:25,125 output:             import salt.crypt
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/crypt.py", line 26, in <module>
2023-09-04 09:48:25,125 output:             import salt.payload
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/payload.py", line 12, in <module>
2023-09-04 09:48:25,125 output:             import salt.loader.context
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/loader/__init__.py", line 15, in <module>
2023-09-04 09:48:25,125 output:             import salt.config
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/config/__init__.py", line 107, in <module>
2023-09-04 09:48:25,125 output:             _DFLT_IPC_WBUFFER = int(_gather_buffer_space() * 0.5)
2023-09-04 09:48:25,125 output:                                     ^^^^^^^^^^^^^^^^^^^^^^
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/config/__init__.py", line 95, in _gather_buffer_space
2023-09-04 09:48:25,125 output:             import salt.grains.core
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/grains/core.py", line 30, in <module>
2023-09-04 09:48:25,125 output:             import salt.modules.cmdmod
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/modules/cmdmod.py", line 32, in <module>
2023-09-04 09:48:25,125 output:             import salt.utils.templates
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/utils/templates.py", line 21, in <module>
2023-09-04 09:48:25,125 output:             import salt.utils.http
2023-09-04 09:48:25,125 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/utils/http.py", line 27, in <module>
2023-09-04 09:48:25,126 output:             import salt.ext.tornado.simple_httpclient
2023-09-04 09:48:25,126 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/ext/tornado/simple_httpclient.py", line 9, in <module>
2023-09-04 09:48:25,126 output:             from salt.ext.tornado.http1connection import HTTP1Connection, HTTP1ConnectionParameters
2023-09-04 09:48:25,126 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/ext/tornado/http1connection.py", line 31, in <module>
2023-09-04 09:48:25,126 output:             from salt.ext.tornado import iostream
2023-09-04 09:48:25,126 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/ext/tornado/iostream.py", line 42, in <module>
2023-09-04 09:48:25,126 output:             import urllib3.util.ssl_match_hostname
2023-09-04 09:48:25,126 output:         ModuleNotFoundError: No module named 'urllib3'
2023-09-04 09:48:25,126 output:         [ERROR   ] An un-handled exception was caught by Salt's global exception handler:
2023-09-04 09:48:25,126 output:         Traceback (most recent call last):
2023-09-04 09:48:25,126 output:           File "/var/tmp/.root_6b9378_salt/salt-call", line 27, in <module>
2023-09-04 09:48:25,126 output:             salt_call()
2023-09-04 09:48:25,126 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/scripts.py", line 438, in salt_call
2023-09-04 09:48:25,126 output:             import salt.cli.call
2023-09-04 09:48:25,126 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/cli/call.py", line 3, in <module>
2023-09-04 09:48:25,126 output:             import salt.cli.caller
2023-09-04 09:48:25,126 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/cli/caller.py", line 12, in <module>
2023-09-04 09:48:25,126 output:             import salt.channel.client
2023-09-04 09:48:25,126 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/channel/client.py", line 13, in <module>
2023-09-04 09:48:25,127 output:             import salt.crypt
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/crypt.py", line 26, in <module>
2023-09-04 09:48:25,127 output:             import salt.payload
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/payload.py", line 12, in <module>
2023-09-04 09:48:25,127 output:             import salt.loader.context
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/loader/__init__.py", line 15, in <module>
2023-09-04 09:48:25,127 output:             import salt.config
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/config/__init__.py", line 107, in <module>
2023-09-04 09:48:25,127 output:             _DFLT_IPC_WBUFFER = int(_gather_buffer_space() * 0.5)
2023-09-04 09:48:25,127 output:                                     ^^^^^^^^^^^^^^^^^^^^^^
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/config/__init__.py", line 95, in _gather_buffer_space
2023-09-04 09:48:25,127 output:             import salt.grains.core
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/grains/core.py", line 30, in <module>
2023-09-04 09:48:25,127 output:             import salt.modules.cmdmod
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/modules/cmdmod.py", line 32, in <module>
2023-09-04 09:48:25,127 output:             import salt.utils.templates
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/utils/templates.py", line 21, in <module>
2023-09-04 09:48:25,127 output:             import salt.utils.http
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/utils/http.py", line 27, in <module>
2023-09-04 09:48:25,127 output:             import salt.ext.tornado.simple_httpclient
2023-09-04 09:48:25,127 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/ext/tornado/simple_httpclient.py", line 9, in <module>
2023-09-04 09:48:25,128 output:             from salt.ext.tornado.http1connection import HTTP1Connection, HTTP1ConnectionParameters
2023-09-04 09:48:25,128 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/ext/tornado/http1connection.py", line 31, in <module>
2023-09-04 09:48:25,128 output:             from salt.ext.tornado import iostream
2023-09-04 09:48:25,128 output:           File "/var/tmp/.root_6b9378_salt/pyall/salt/ext/tornado/iostream.py", line 42, in <module>
2023-09-04 09:48:25,128 output:             import urllib3.util.ssl_match_hostname
2023-09-04 09:48:25,128 output:         ModuleNotFoundError: No module named 'urllib3'
2023-09-04 09:48:25,128 output:     stdout:
2023-09-04 09:48:25,128 output: /usr/lib/python3.11/site-packages/salt/utils/http.py:8: DeprecationWarning: 'cgi' is deprecated and slated for removal in Python 3.13
2023-09-04 09:48:25,128 output:   import cgi
2023-09-04 09:48:25,128 output: /usr/lib/python3.11/site-packages/salt/utils/jinja.py:9: DeprecationWarning: 'pipes' is deprecated and slated for removal in Python 3.13
2023-09-04 09:48:25,128 output:   import pipes
2023-09-04 09:48:25,128 exit code: 20
```

### Steps to reproduce
Execute salt script that will try to install any package on minimal template.

### Expected behavior
Package will be installed.

### Actual behavior
Salt throwing an error.

**Comment by andrewdavidwong** [comment]
Related to or possible duplicate of: #8440

(@Szewcson, you said debian-12-minimal in https://github.com/QubesOS/qubes-issues/issues/8440#issuecomment-1704330370, but here you're showing fedora-38-minimal.)

**Comment by Szewcson** [comment]
I tested this today also on fedora-38-minimal.

**Comment by ben-grande** [comment]
This issue of missing urllib3 has been fixed.
