### ISSUE TITLE
fedora-38-xfce fails to start with in-vm kernel and HVM virt_mode

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8540]
## Observation

openQA test in scenario qubesos-4.2-update-x86_64-system_tests_pvgrub_salt_storage@64bit fails in
[TC_41_HVMGrub_fedora-38-xfce](https://openqa.qubes-os.org/tests/82379/modules/TC_41_HVMGrub_fedora-38-xfce/steps/1)

```
# test_000_standalone_vm
# error: 

# timestamp 2023-09-19T07:04:30.840577
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 1723, in start_qrexec_daemon
    await self.start_daemon(
  File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 1696, in start_daemon
    raise subprocess.CalledProcessError(p.returncode, command,
subprocess.CalledProcessError: Command '['runuser', '-u', 'user', '--', '/usr/sbin/qrexec-daemon', '-q', '22', 'test-inst-vm1', 'user']' returned non-zero exit status 3.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib64/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/tests/integ/grub.py", line 109, in test_000_standalone_vm
    self.loop.run_until_complete(self.testvm1.start())
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 1253, in start
    await self.start_qrexec_daemon()
  File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 1728, in start_qrexec_daemon
    raise qubes.exc.QubesVMError(
qubes.exc.QubesVMError: Cannot connect to qrexec agent for 120 seconds, see /var/log/xen/console/guest-test-inst-vm1.log for details
```

Similar test using PVH boot mode passes.

## Reproducible

Fails since (at least) Build [2023081504-4.2](https://openqa.qubes-os.org/tests/80082)

## Expected result

Last good: [2023080804-4.2](https://openqa.qubes-os.org/tests/79572) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=update&machine=64bit&test=system_tests_pvgrub_salt_storage&version=4.2)

I suspect it's related to initramfs size - it's 61MB compressed. The difference between PVH and HVM can probably be explained with more memory used for some devices (videoram) and bookkeeping on Xen side - which is subtracted from VM memory.

Similar issue was happening in Debian: https://github.com/QubesOS/qubes-issues/issues/8277

**Comment by marmarek** [comment]
It does _not_ affect fedora-37 on R4.1. I haven't checked fedora-38 on R4.1, so I'm not sure yet whether it's about R4.1 vs R4.2, or fedora-37 vs fedora-38.
