### ISSUE TITLE
Several errors about missing pam_sss in dom0

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8595]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Dom0 log contains several errors about missing pam_sss.so.

### Steps to reproduce

Login, unlock screen or any other action involving PAM

### Expected behavior

No errors

### Actual behavior

```
Oct 10 18:50:30 dom0 xscreensaver-auth[33499]: PAM unable to dlopen(/usr/lib64/security/pam_sss.so): /usr/lib64/security/pam_sss.so: cannot open shared object file: No such file or directory
Oct 10 18:50:30 dom0 xscreensaver-auth[33499]: PAM adding faulty module: /usr/lib64/security/pam_sss.so
```

Setting "minimal" profile of authselect should fix the issue.

**Comment by DemiMarie** [comment]
@deeplow did switching to “minimal” make the problem go away?

**Comment by euidzero** [comment]
@deeplow in dom0 run :  `sudo authselect select minimal`

**Comment by DemiMarie** [comment]
@euidzero This is probably the best answer indeed.  Thanks!

**Comment by jamke** [comment]
I have plenty on these red lines (errors) in `journalctl` on R4.2.4.
From lightdm, systemd, sudo.

**Comment by jamke** [comment]
I run `sudo authselect select minimal` in `dom0`, and after reboot I do not see these errors in log. But I do see exceptions in Python from `qubesd`, which is probably worse. Are those things connected or should I make a separate issue for a bug?

```
Mar 04 04:00:20 dom0 runuser[5406]: pam_unix(runuser:session): session closed for user user
Mar 04 04:00:20 dom0 qubesd[3333]: qubesdb.Error: (2, 'No such file or directory')
Mar 04 04:00:20 dom0 qubesd[3333]:                            ^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 04 04:00:20 dom0 qubesd[3333]:     self._qdb_connection = qubesdb.QubesDB(self.name)
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 871, in untrusted_qdb
Mar 04 04:00:20 dom0 qubesd[3333]:                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 04 04:00:20 dom0 qubesd[3333]:     if not vm.is_running() or not hasattr(vm, 'untrusted_qdb'):
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py", line 527, in on_device_list_usb
Mar 04 04:00:20 dom0 qubesd[3333]:     effects.extend(effect)
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 168, in _fire_event
Mar 04 04:00:20 dom0 qubesd[3333]:                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 04 04:00:20 dom0 qubesd[3333]:     sync_effects, async_effects = self._fire_event(event, kwargs,
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 195, in fire_event
Mar 04 04:00:20 dom0 qubesd[3333]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 04 04:00:20 dom0 qubesd[3333]:     devices = self._vm.fire_event('device-list:' + self._bus)
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubes/devices.py", line 373, in available
Mar 04 04:00:20 dom0 qubesd[3333]:                 ^^^^^^^^^^^^^^^^
Mar 04 04:00:20 dom0 qubesd[3333]:     return iter(self.available())
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubes/devices.py", line 377, in __iter__
Mar 04 04:00:20 dom0 qubesd[3333]:     for dev in vm.devices['usb']:
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py", line 562, in get_all_devices
Mar 04 04:00:20 dom0 qubesd[3333]:     for dev in self.get_all_devices(vm.app):
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py", line 573, in on_device_list_attached
Mar 04 04:00:20 dom0 qubesd[3333]:     effects.extend(effect)
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 168, in _fire_event
Mar 04 04:00:20 dom0 qubesd[3333]:                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 04 04:00:20 dom0 qubesd[3333]:     sync_effects, async_effects = self._fire_event(event, kwargs,
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 195, in fire_event
Mar 04 04:00:20 dom0 qubesd[3333]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Mar 04 04:00:20 dom0 qubesd[3333]:     devices = self._vm.fire_event('device-list-attached:' + self._bus,
Mar 04 04:00:20 dom0 qubesd[3333]:   File "/usr/lib/python3.11/site-packages/qubes/devices.py", line 349, in assignments
Mar 04 04:00:20 dom0 qubesd[3333]: Traceback (most recent call last):
Mar 04 04:00:20 dom0 qubesd[3333]: vm.dom0: Failed to list usb devices
```
