### ISSUE TITLE
Q4.2.0-rc4 Initial Setup is failing to start when /.unconfigured file is there

### ISSUE THREAD

**Issue by John222** [QubesOS/qubes-issues#8682]
### Qubes OS release
Qubes OS 4.2.0-rc4 (R4.2)

### Brief summary

We have written a anaconda addin, therefore we need to touch the /.unconfigured file, to bring up the initial setup at the first start. Unfortunately it anaconda installer fails to start, with the following error:

```** (process:4836): WARNING **: 12:54:16.077: failed to load module nvdimm: libbd_nvdimm.so.2: cannot open shared object file: No such file or directory
INFO initial-setup: Initial Setup 0.3.95
DEBUG initial-setup: running in GUI mode
DEBUG initial-setup: reconfig trigger file found: /.unconfigured
DEBUG initial-setup: running in externally triggered reconfig mode
DEBUG initial-setup: GI overrides imported
INFO initial-setup: found 2 addon modules:
DEBUG initial-setup: spokes
DEBUG initial-setup: categories
DEBUG initial-setup: initializing the Anaconda log
INF initial-setup: using kickstart from previous run for input
INF initial-setup: parsing input kickstart /root/initial-setup-ks.cfg
INF initial-setup: kickstart parsing done
DBG initial-setup: setting up locale
DBG initial-setup: initializing network
DBG initial-setup: trying to import GUI
DBG initial-setup: initializing GUI
DBG initial-setup: setting up the UI
INF initial-setup: starting the UI
ERR initial-setup: Initial Setup crashed due to unhandled exception:
Traceback (most recent call last):
  File "/usr/lib64/python3.11/site-packages/pyanaconda/ui/gui/__init__.py", line 767, in run
    self._currentAction.refresh()
  File "/usr/lib64/python3.11/site-packages/pyanaconda/ui/gui/hubs/__init__.py", line 367, in refresh
    self._createBox()
  File "/usr/lib/python3.11/site-packages/initial_setup/gui/hubs/initial_setup_hub.py", line 33, in _createBox
    Hub._createBox(self)
  File "/usr/lib64/python3.11/site-packages/pyanaconda/ui/gui/hubs/__init__.py", line 176, in _createBox
    spoke.initialize()
  File "/usr/lib64/python3.11/site-packages/pyanaconda/ui/gui/spokes/network.py", line 1561, in initialize
    register_secret_agent(self)
  File "/usr/lib64/python3.11/site-packages/pyanaconda/ui/gui/spokes/lib/network_secret_agent.py", line 294, in register_secret_agent
    proxy.Register("anaconda")
    ^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/proxy.py", line 161, in __getattr__
    member = self._get_member(self._get_interface(name), name)
                              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/proxy.py", line 211, in _get_interface
    self._handler.specification.members
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 206, in specification
    self._specification = self._get_specification()
                          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 326, in _get_specification
    xml = self._call_method(
          ^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 444, in _call_method
    return self._get_method_reply(
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 477, in _get_method_reply
    return self._handle_method_error(error)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/dasbus/client/handler.py", line 497, in _handle_method_error
    raise exception from None
dasbus.error.DBusError: The name is not activatable

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/libexec/initial-setup/initial-setup-graphical", line 10, in <module>
    is_instance.run()
  File "/usr/lib/python3.11/site-packages/initial_setup/__init__.py", line 373, in run
    ret = ui.run()
          ^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/pyanaconda/ui/gui/__init__.py", line 821, in run
    self._gui_lock.release()
    ^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'release'
```

### Steps to reproduce

All the steps have been executed inside the ***dom0***

```bash
sudo touch /.unconfigured
sudo /usr/libexec/initial-setup/initial-setup-graphical
```

### Expected behavior

Anaconda installer gui boots up and shows all the components to configure

### Actual behavior

See supplied error message above.

### Important note

We removed our anaconda addin from the ```/usr/share/anaconda/addons```to ensure it is not caused by our own anaconda addon.

**Comment by John222** [comment]
Hello guys

as soon we gonna remove the line

```python
proxy.Register("anaconda")
``` 
from the ```/usr/lib64/python3.11/site-packages/pyanaconda/ui/gui/spokes/lib/network_secret_agent.py``` file on line ```294```

it is working. I couldn't figure out yet, what the side effect this is.
