### ISSUE TITLE
Test test_223_audio_play_hvm fails on hw2 (MSI, NitroPC Pro) openQA worker

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8711]
## Observation

openQA test in scenario qubesos-4.2-kernel-x86_64-system_tests_basic_vm_qrexec_gui@hw2 fails in
[TC_20_AudioVM_Pulse_debian-12-xfce](https://openqa.qubes-os.org/tests/85679/modules/TC_20_AudioVM_Pulse_debian-12-xfce/steps/4)

```
Traceback (most recent call last):
  File "/usr/lib64/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 311, in test_223_audio_play_hvm
    self.common_audio_playback()
  File "/usr/lib/python3.11/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 170, in common_audio_playback
    self.check_audio_sample(recorded_audio.file.read(), sfreq)
  File "/usr/lib/python3.11/site-packages/qubes/tests/integ/vm_qrexec_gui.py", line 122, in check_audio_sample
    self.fail(f'too short audio, expected 10s, got {rec_size/44100}, saved to {fname}')
AssertionError: too short audio, expected 10s, got 5.285873015873016, saved to /tmp/audio-sample-qubes.tests.integ.vm_qrexec_gui.TC_20_AudioVM_Pulse_debian-12-xfce.test_223_audio_play_hvm.raw
```

When listening to the sample, it indeed is wrong (short beeps, instead of one long one).

## Test suite description

It plays a sound sample over emulated audio card for a HVM domain (`qvm-features vm audio-model ich6`).

## Reproducible

Fails since (at least) Build [2023100700-4.2](https://openqa.qubes-os.org/tests/83468)

It consistently on this runner a few times already, regardless of the template. But the test passes on other workers, including another one with 12th gen CPU, and also one with 13th gen CPU.

## Expected result

Last good: [2023100512-4.2](https://openqa.qubes-os.org/tests/83324) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=kernel&machine=hw2&test=system_tests_basic_vm_qrexec_gui&version=4.2)

**Comment by DemiMarie** [comment]
Do the PipeWire and PulseAudio modules work?  I am trying to figure out if this is a guest-side or host-side problem.

**Comment by marmarek** [comment]
TBH, I have no idea which one is to blame, especially given that exactly the same software (?) passes the test on other (hardware) workers. The test uses paplay to play the sound but I believe goes through pipewire. But since it's using emulated sound card, pacat connects to the stubdomain, not the target domain, so the qubes pipewire module stops at init step.

The specific package versions can be found in "update" jobs for each worker - in the "Logs & Assets" tab (separate file for each template): https://openqa.qubes-os.org/tests/overview?distri=qubesos&version=4.2&build=2023111502-4.2&groupid=12

Maybe it's related to https://github.com/QubesOS/qubes-issues/issues/8590 (which BTW seems to be mostly fixed now) ? But I don't understand why it would be hardware dependent, when it's playing via emulated card...

**Comment by DemiMarie** [comment]
The reason I asked about the PipeWire and PulseAudio modules is that if both of those work, the problem is likely to be in the emulation somewhere, which is a much smaller amount of code to look for bugs in.

**Comment by marmarek** [comment]
It looks like both fedora and debian templates use pipewire (and pipewire-pulse) in those tests.

**Comment by DemiMarie** [comment]
Looks like the Qubes modules are working correctly.  I’m inclined to suspect a problem with the emulated audio device.  Anecdotally those are not very usable (due to performance problems) even without nested virt, and nested virt would just make this worse.

Do the problems go away if PipeWire and interrupt-based scheduling is used in the guest?  That _might_ avoid the xruns.  Otherwise, I would be tempted to dismiss this as a flaky test in an unrealistically bad environment, unless someone observes a similar problem without nested virt.

As an aside, is it possible to run the tests on bare hardware, using piKVM + network boot or (on systems that have it) Intel AMT?

**Comment by DemiMarie** [comment]
Looks like the Qubes modules are working correctly.  I’m inclined to suspect a problem with the emulated audio device.  Anecdotally those are not very usable (due to performance problems) even without nested virt, and nested virt would just make this worse.

Do the problems go away if PipeWire and interrupt-based scheduling is used in the guest?  That _might_ avoid the xruns.  Otherwise, I would be tempted to dismiss this as a flaky test in an unrealistically bad environment, unless someone observes a similar problem without nested virt.

As an aside, is it possible to run the tests on bare hardware, using piKVM + network boot or (on systems that have it) Intel AMT?

**Comment by marmarek** [comment]
> Looks like the Qubes modules are working correctly.

Qubes modules (theoretically) are not involved in this test at all.

> I’m inclined to suspect a problem with the emulated audio device.

Maybe? But I don't think anything changed there since it was working last time. OTOH, I did extended the test (from 1s to 10s), so maybe the issue simply wasn't detected before.

> even without nested virt, and nested virt would just make this worse.

hw* workers are _not_ using nested virt, those are about qubes directly on the hardware. Ironically, this test on a worker with  nested virt is all green.

> Do the problems go away if PipeWire and interrupt-based scheduling is used in the guest?

What specifically you'd like me to test?

**Comment by DemiMarie** [comment]
> > Do the problems go away if PipeWire and interrupt-based scheduling is used in the guest?
> 
> What specifically you'd like me to test?

I will need to do some research here.

**Comment by DemiMarie** [comment]
You will need to set this via WirePlumber; details later.
