### ISSUE TITLE
Qubes 4.2.0-rc5 install of fedora-38-xfce template failed in the 2 stage of the installer

### ISSUE THREAD

**Issue by nestire** [QubesOS/qubes-issues#8735]
### Setup:
Qubes 4.2.0-rc5
Nitropad NS50 with Heads

### Brief summary
fedora-38-xfce fails to install during the setup in the 2. stage of the install.
We use in our oem a kickstarter based install, that forces User Creation also in the 2. Stage. Other then that nothing changed in the image.
When checking the disk after the install  I can see that the volumes are created for the fedora-38 template.
Here the relevant Log.
[fail.log](https://github.com/QubesOS/qubes-issues/files/13501022/fail.log)

The Default Qubes install worked so I suspect the issue has todo something with the kickstarter based install

### Steps to reproduce
1. Use this kickstarter file for the install:
```
#version=DEVEL
%pre
password="PleaseChangeMe"
echo "autopart --type thinp --encrypted --passphrase=\"$password\"" > /tmp/part-include
%end

# Use graphical install
graphical
# clear disk
zerombr
# Keyboard layouts
keyboard --vckeymap=de --xlayouts='de'
# System language
lang de_DE.UTF-8
# Network information
network  --hostname=dom0
# System timezone
timezone Europe/Berlin --utc
# X Window System configuration information
xconfig  --startxonboot
# System bootloader configuration
bootloader --location=mbr --boot-drive=nvme0n1
#Root password
#rootpw --lock
#FIXME for testing
rootpw --plaintext PleaseChangeMe
user --name test --password PleaseChangeMe
# Disk partitioning information
%include /tmp/part-include


# Poweroff after installation
poweroff

%packages
@^qubes-xfce
%end

```
3. in the 2. Stage choose only the fedora-38 template (did not try it yet with debian)

### Expected behavior
- finished clean install

### Actual behavior

- no templates are installed

### Logs
```
Nov 29 13:26:30 dom0 qubesd[1880]: vm.fedora-38-xfce: Creating directory: /var/lib/qubes/vm-templates/fedora-38-xfce
Nov 29 13:26:30 dom0 lvm[1552]: No longer monitoring thin pool qubes_dom0-vm--pool.
Nov 29 13:26:30 dom0 lvm[1552]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Nov 29 13:26:30 dom0 qubesd[1880]: Updating appmenus for 'fedora-38-xfce' in 'dom0'
Nov 29 13:26:30 dom0 qubesd[1880]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Create.TemplateVM' dest=b'dom0' arg=b'' len(untrusted_payload)=31
Nov 29 13:26:30 dom0 qubesd[1880]: Traceback (most recent call last):
Nov 29 13:26:30 dom0 qubesd[1880]:   File "/usr/lib/python3.11/site-packages/qubes/api/__init__.py", line 297, in respond
Nov 29 13:26:30 dom0 qubesd[1880]:     response = await self.mgmt.execute(
Nov 29 13:26:30 dom0 qubesd[1880]:                ^^^^^^^^^^^^^^^^^^^^^^^^
Nov 29 13:26:30 dom0 qubesd[1880]:   File "/usr/lib/python3.11/site-packages/qubes/api/admin.py", line 1129, in _vm_create
Nov 29 13:26:30 dom0 qubesd[1880]:     await vm.create_on_disk(pool=pool, pools=pools)
Nov 29 13:26:30 dom0 qubesd[1880]:   File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 1812, in create_on_disk
Nov 29 13:26:30 dom0 qubesd[1880]:     await self.fire_event_async('domain-create-on-disk')
Nov 29 13:26:30 dom0 qubesd[1880]:   File "/usr/lib/python3.11/site-packages/qubes/events.py", line 234, in fire_event_async
Nov 29 13:26:30 dom0 qubesd[1880]:     effect = task.result()
Nov 29 13:26:30 dom0 qubesd[1880]:              ^^^^^^^^^^^^^
Nov 29 13:26:30 dom0 qubesd[1880]:   File "/usr/lib/python3.11/site-packages/qubesappmenusext/__init__.py", line 112, in create_on_disk
Nov 29 13:26:30 dom0 qubesd[1880]:     await self.update_appmenus(vm)
Nov 29 13:26:30 dom0 qubesd[1880]:   File "/usr/lib/python3.11/site-packages/qubesappmenusext/__init__.py", line 72, in update_appmenus
Nov 29 13:26:30 dom0 qubesd[1880]:     await guivm.run_service_for_stdio("qubes.UpdateAppMenusFor+" + vm.name)
Nov 29 13:26:30 dom0 qubesd[1880]:   File "/usr/lib/python3.11/site-packages/qubes/vm/adminvm.py", line 313, in run_service_for_stdio
Nov 29 13:26:30 dom0 qubesd[1880]:     p = await self.run_service(*args, **kwargs)
Nov 29 13:26:30 dom0 qubesd[1880]:         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Nov 29 13:26:30 dom0 qubesd[1880]:   File "/usr/lib/python3.11/site-packages/qubes/vm/adminvm.py", line 276, in run_service
Nov 29 13:26:30 dom0 qubesd[1880]:     user = qubes_group.gr_mem[0]
Nov 29 13:26:30 dom0 qubesd[1880]:            ~~~~~~~~~~~~~~~~~~^^^
Nov 29 13:26:30 dom0 qubesd[1880]: IndexError: list index out of range
```

**Comment by marmarek** [comment]
Is the user created at this stage? (check earlier in the log)

BTW, you may like this new feature for the OEM install: https://github.com/QubesOS/qubes-lorax-templates/pull/19 (that PR description is the only documentation of it right now...)

**Comment by nestire** [comment]
Ok the Problem happens if there is no user in the group _qubes_ after adding the test user to this group I was able to install the template. 

Since the user creation if not set during the 1. stage seems to happen after the template install this triggers.

**Comment by nestire** [comment]
Uh that is a nice helpful option, thanks for the hint.
