### ISSUE TITLE
Sys-net failed to restart after template update

### ISSUE THREAD

**Issue by deeplow** [QubesOS/qubes-issues#8793]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2

### Brief summary
Sys-net failed to restart on new updater.

### Steps to reproduce
1. I started the computer at around 7h50 AM (things running normally, internet working)
2. I ran the updater (updated non-admin qubes) and select "restart qubes" (sys-net, sys-whonix, sys-usb)
3. At around 7h13m sys-net failed to start with error (details bellow)
4. I manually started sys-net and it worked as usual

### Expected behavior
Updater restarts the sys-net successfully

### Actual behavior
Updater failed to restart sys-net, leaving the system without internet connection

#### `journalctl`

```
Dec 27 08:06:56 dom0 kernel: audit: type=1130 audit(1703664416.659:447): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-tmpfiles-clean comm="systemd" exe="/usr/lib/systemd/systemd">
Dec 27 08:06:56 dom0 kernel: audit: type=1131 audit(1703664416.659:448): pid=1 uid=0 auid=4294967295 ses=4294967295 msg='unit=systemd-tmpfiles-clean comm="systemd" exe="/usr/lib/systemd/systemd">
Dec 27 08:07:11 dom0 lvm[1332]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:12 dom0 lvm[1332]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:13 dom0 lvm[1332]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:13 dom0 lvm[1332]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:14 dom0 libvirtd[1840]: internal error: Unable to reset PCI device 0000:00:0d.0: no FLR, PM reset or bus reset available
Dec 27 08:07:14 dom0 libvirtd[1840]: internal error: Unable to reset PCI device 0000:00:0d.2: internal error: Unable to reset PCI device 0000:00:0d.0: no FLR, PM reset or bus reset available
Dec 27 08:07:14 dom0 libvirtd[1840]: internal error: Unable to reset PCI device 0000:00:14.0: internal error: Unable to reset PCI device 0000:00:0d.2: internal error: Unable to reset PCI device >
Dec 27 08:07:14 dom0 lvm[1332]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:15 dom0 lvm[1332]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:16 dom0 lvm[1332]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:17 dom0 lvm[1332]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:18 dom0 qubesd[3435]: vm.sys-net: Starting sys-net
Dec 27 08:07:18 dom0 qubesd[3435]: socket.send() raised exception.
Dec 27 08:07:18 dom0 qubesd[3435]: socket.send() raised exception.
Dec 27 08:07:18 dom0 lvm[1332]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:18 dom0 lvm[1332]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:18 dom0 lvm[1332]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:18 dom0 lvm[1332]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:19 dom0 kernel: loop0: detected capacity change from 0 to 1045872
Dec 27 08:07:19 dom0 kernel: loop1: detected capacity change from 0 to 1045872
Dec 27 08:07:19 dom0 kernel: pciback 0000:a5:00.0: xen_pciback: vpci: assign to virtual slot 0
Dec 27 08:07:19 dom0 kernel: pciback 0000:a5:00.0: registering for 16
Dec 27 08:07:19 dom0 kernel: xen-blkback: backend/vbd/16/51712: using 1 queues, protocol 1 (x86_64-abi) persistent grants
Dec 27 08:07:19 dom0 kernel: xen-blkback: backend/vbd/16/51728: using 1 queues, protocol 1 (x86_64-abi) persistent grants
Dec 27 08:07:19 dom0 kernel: xen-blkback: backend/vbd/16/51744: using 1 queues, protocol 1 (x86_64-abi) persistent grants
Dec 27 08:07:19 dom0 kernel: xen-blkback: backend/vbd/16/51760: using 1 queues, protocol 1 (x86_64-abi) persistent grants
Dec 27 08:07:40 dom0 libvirtd[1840]: internal error: libxenlight failed to create new domain 'sys-net'
Dec 27 08:07:40 dom0 qubesd[3435]: vm.sys-net: Start failed: internal error: libxenlight failed to create new domain 'sys-net'
Dec 27 08:07:40 dom0 lvm[1332]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:41 dom0 lvm[1332]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:41 dom0 lvm[1332]: No longer monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:41 dom0 lvm[1332]: Monitoring thin pool qubes_dom0-vm--pool-tpool.
Dec 27 08:07:42 dom0 widget-wrapper[6228]: Exception in thread Thread-4 (perform_restart):
Dec 27 08:07:42 dom0 widget-wrapper[6228]: Traceback (most recent call last):
Dec 27 08:07:42 dom0 widget-wrapper[6228]:   File "/usr/lib64/python3.11/threading.py", line 1045, in _bootstrap_inner
Dec 27 08:07:42 dom0 widget-wrapper[6228]:     self.run()
Dec 27 08:07:42 dom0 widget-wrapper[6228]:   File "/usr/lib64/python3.11/threading.py", line 982, in run
Dec 27 08:07:42 dom0 widget-wrapper[6228]:     self._target(*self._args, **self._kwargs)
Dec 27 08:07:42 dom0 widget-wrapper[6228]:   File "/usr/lib/python3.11/site-packages/qui/updater/summary_page.py", line 298, in perform_restart
Dec 27 08:07:42 dom0 widget-wrapper[6228]:     self.restart_vms(to_restart)
Dec 27 08:07:42 dom0 widget-wrapper[6228]:   File "/usr/lib/python3.11/site-packages/qui/updater/summary_page.py", line 334, in restart_vms
Dec 27 08:07:42 dom0 widget-wrapper[6228]:     vm.start()
Dec 27 08:07:42 dom0 widget-wrapper[6228]:   File "/usr/lib/python3.11/site-packages/qubesadmin/vm/__init__.py", line 103, in start
Dec 27 08:07:42 dom0 widget-wrapper[6228]:     self.qubesd_call(self._method_dest, 'admin.vm.Start')
Dec 27 08:07:42 dom0 widget-wrapper[6228]:   File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 76, in qubesd_call
Dec 27 08:07:42 dom0 widget-wrapper[6228]:     return self.app.qubesd_call(dest, method, arg, payload,
Dec 27 08:07:42 dom0 widget-wrapper[6228]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 27 08:07:42 dom0 widget-wrapper[6228]:   File "/usr/lib/python3.11/site-packages/qubesadmin/app.py", line 770, in qubesd_call
Dec 27 08:07:42 dom0 widget-wrapper[6228]:     return self._parse_qubesd_response(return_data)
Dec 27 08:07:42 dom0 widget-wrapper[6228]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Dec 27 08:07:42 dom0 widget-wrapper[6228]:   File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 111, in _parse_qubesd_response
Dec 27 08:07:42 dom0 widget-wrapper[6228]:     raise exc_class(format_string, *args)
Dec 27 08:07:42 dom0 widget-wrapper[6228]: qubesadmin.exc.QubesException: Start failed: internal error: libxenlight failed to create new domain 'sys-net', see /var/log/libvirt/libxl/libxl-driver.>
```

#### `/var/log/libvirt/libxl/libxl-driver.log`

```
2023-12-27 07:51:39.983+0000: libxl: libxl_pci.c:1585:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:0d.0
2023-12-27 07:51:39.988+0000: libxl: libxl_pci.c:1585:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:0d.2
2023-12-27 07:51:39.991+0000: libxl: libxl_pci.c:1585:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:14.0
2023-12-27 08:07:13.671+0000: libxl: libxl_pci.c:1585:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:0d.0
2023-12-27 08:07:13.806+0000: libxl: libxl_pci.c:1585:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:0d.2
2023-12-27 08:07:13.915+0000: libxl: libxl_pci.c:2096:do_pci_remove: Domain 2:xc_physdev_unmap_pirq irq=16: Invalid argument
2023-12-27 08:07:13.915+0000: libxl: libxl_pci.c:1585:libxl__device_pci_reset: The kernel doesn't support reset from sysfs for PCI device 0000:00:14.0
2023-12-27 08:07:20.494+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:20.494+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 1
2023-12-27 08:07:21.561+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:21.562+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 2
2023-12-27 08:07:22.629+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:22.630+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 3
2023-12-27 08:07:23.697+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:23.699+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 4
2023-12-27 08:07:24.765+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:24.766+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 5
2023-12-27 08:07:25.833+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:25.833+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 6
2023-12-27 08:07:26.897+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:26.898+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 7
2023-12-27 08:07:27.965+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:27.966+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 8
2023-12-27 08:07:29.033+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:29.034+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 9
2023-12-27 08:07:30.097+0000: libxl: libxl_qmp.c:1837:qmp_ev_parse_error_messages: Domain 15:Could not open '/sys/bus/pci/devices/0000:00:00.0/config': No such file or directory
2023-12-27 08:07:30.098+0000: libxl: libxl_pci.c:1273:pci_add_qmp_device_add_cb: Domain 15:Retrying PCI add 10
2023-12-27 08:07:30.403+0000: libxl: libxl_pci.c:1862:device_pci_add_done: Domain 15:libxl__device_pci_add failed for PCI device 0:a5:0.0 (rc -9)
2023-12-27 08:07:30.403+0000: libxl: libxl_create.c:2000:domcreate_attach_devices: Domain 15:unable to add pci devices
2023-12-27 08:07:40.576+0000: libxl: libxl_device.c:1489:libxl__wait_for_backend: Backend /local/domain/0/backend/pci/16/0 not ready
```

**Comment by marmarek** [comment]
Have it happened ever again?

**Comment by UndeadDevel** [comment]
FWIW I see failures to restart both `sys-net` and `sys-firewall` occasionally, but don't know how to reliably reproduce so far and it's not only after template update, but also when triggering via the Qube Manager.

**Comment by UndeadDevel** [comment]
I've filed #9078 now that I could reproduce, so that is a different issue than this one.
