### ISSUE TITLE
debian-13 template

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8841]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### The problem you're addressing (if any)

Make it possible to test stuff on Debian testing (trixie).

### The solution you'd like

Prepare packages and (maybe) pre-built template for Debian 13.

### The value to a user, and who that user might be

Make stuff ready well before final Debian 13 release.

**Comment by andrewdavidwong** [comment]
Debian 13 (Trixie) release date has been scheduled for 2025-08-09.

**Comment by ben-grande** [comment]
Systemd unit `efi.mount` is failing on `debian-13-xfce` and `debian-13` but not on `debian-13-minimal`. Just installed them with the template manager. The minimal template says that the unit could not be found, so it was not created, thus not failing. `efi.mount` is created by `efi.automount`, enabled by `systemd-gpt-auto-generator`.

- https://github.com/qubesos/qubes-issues/issues/8954

- debian-13: 0:4.3.0-2025080032011
- debian-13-xfce: 0:4.3.0-202508092358
- debian-13-minimal: 0:4.3.0-2025080032011

- https://bbs.archlinux.org/viewtopic.php?id=287760

Adding to `kernelopts` `systemd.gpt_auto=no` solved the issue. I don't know if it causes other problems.

**Comment by dsg22** [comment]
I tried installing the debian-13 template on R4.2, and it seems qvm-run is broken. Is this a template issue or is there some change that makes R4.3 templates incompatible with R4.2?

```sh
[user@dom0 ~]$ qvm-run -p debian-13 sh
2025-08-16 23:29:27.703 qrexec-client[69650]: qrexec-daemon-common.c:232:connect_unix_socket: connect /var/run/qubes/qrexec.debian-13: No such file or directory
2025-08-16 23:29:27.703 qrexec-client[69650]: qrexec-daemon-common.c:29:negotiate_connection_params: write daemon: Bad file descriptor
```

Also, the debian-13-minimal does not have passwordless sudo, so I could not get a root shell. On the debian-13 template passwordless sudo works.

**Comment by dsg22** [comment]
Built a debian-13 template for R4.2 and qvm-run works fine.

**Comment by marmarek** [comment]
> I tried installing the debian-13 template on R4.2

Templates from R4.3 are not supposed to work on R4.2, so your issue is expected.

**Comment by adrelanos** [comment]
On R4.2, `qvm-template list` shows `debian-13`.

**Comment by marmarek** [comment]
Yes, debian-13 is now built for R4.2 too. Previous comments were before that.

**Comment by marmarek** [comment]
@andrewdavidwong I think it's time to announce Debian 13 template availability for testing (both R4.2 and R4.3)

**Comment by andrewdavidwong** [comment]
Testing announcement:
https://forum.qubes-os.org/t/debian-13-templates-available-for-testing/35868

**Comment by alimirjamali** [comment]
I have received reports [on forum](https://forum.qubes-os.org/t/qubes-os-updates-weekly-review-y2025-w34/35784/4) that `.onion` repos do not contain Debian 13 XFCE testing template. I can confirm this:

Onion:
<img width="826" height="463" alt="Image" src="https://github.com/user-attachments/assets/39ec0b15-6c82-4fc8-834e-0b2deb0a91fc" />

Regular:

<img width="1366" height="768" alt="Image" src="https://github.com/user-attachments/assets/37e281a0-91f9-4749-93af-ccf546555843" />

**Comment by andrewdavidwong** [comment]
> I have received reports [on forum](https://forum.qubes-os.org/t/qubes-os-updates-weekly-review-y2025-w34/35784/4) that `.onion` repos do not contain Debian 13 XFCE testing template.

I think #1352 is the issue for that.

**Comment by qub411** [comment]
Testing the new debian-13-xfce template for r4.2.4 and I am unable to get a salt update working at all. This has been working for r4.3 for some time. I am able to clone the template using salt but then when I run an update salt script I am getting an immediate crash:

```
     _error:
          The command resulted in a non-zero exit code
      parsed:
          None
      retcode:
          1
      stderr:
          Traceback (most recent call last):
            File "/var/tmp/.root_dd8a91_salt/salt-call", line 27, in <module>
              salt_call()
              ~~~~~~~~~^^
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/scripts.py", line 438, in salt_call
              import salt.cli.call
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/call.py", line 3, in <module>
              import salt.cli.caller
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 15, in <module>
              import salt.minion
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/minion.py", line 38, in <module>
              import salt.pillar
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/pillar/__init__.py", line 17, in <module>
              import salt.fileclient
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/fileclient.py", line 30, in <module>
              import salt.utils.http
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/http.py", line 69, in <module>
              import requests
            File "/usr/lib/python3/dist-packages/requests/__init__.py", line 164, in <module>
              from .api import delete, get, head, options, patch, post, put, request
            File "/usr/lib/python3/dist-packages/requests/api.py", line 11, in <module>
              from . import sessions
            File "/usr/lib/python3/dist-packages/requests/sessions.py", line 15, in <module>
              from .adapters import HTTPAdapter
            File "/usr/lib/python3/dist-packages/requests/adapters.py", line 81, in <module>
              _preloaded_ssl_context.load_verify_locations(
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                  extract_zipped_paths(DEFAULT_CA_BUNDLE_PATH)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              )
              ^
          FileNotFoundError: [Errno 2] No such file or directory
          [ERROR   ] An un-handled exception was caught by Salt's global exception handler:
          FileNotFoundError: [Errno 2] No such file or directory
          Traceback (most recent call last):
            File "/var/tmp/.root_dd8a91_salt/salt-call", line 27, in <module>
              salt_call()
              ~~~~~~~~~^^
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/scripts.py", line 438, in salt_call
              import salt.cli.call
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/call.py", line 3, in <module>
              import salt.cli.caller
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/cli/caller.py", line 15, in <module>
              import salt.minion
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/minion.py", line 38, in <module>
              import salt.pillar
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/pillar/__init__.py", line 17, in <module>
              import salt.fileclient
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/fileclient.py", line 30, in <module>
              import salt.utils.http
            File "/var/tmp/.root_dd8a91_salt/pyall/salt/utils/http.py", line 69, in <module>
              import requests
            File "/usr/lib/python3/dist-packages/requests/__init__.py", line 164, in <module>
              from .api import delete, get, head, options, patch, post, put, request
            File "/usr/lib/python3/dist-packages/requests/api.py", line 11, in <module>
              from . import sessions
            File "/usr/lib/python3/dist-packages/requests/sessions.py", line 15, in <module>
              from .adapters import HTTPAdapter
            File "/usr/lib/python3/dist-packages/requests/adapters.py", line 81, in <module>
              _preloaded_ssl_context.load_verify_locations(
              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
                  extract_zipped_paths(DEFAULT_CA_BUNDLE_PATH)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
              )
              ^
          FileNotFoundError: [Errno 2] No such file or directory
```

**Comment by twd64** [comment]
I had the same issue today. After switchting the default-mgmt-dvm template to debian-13 it worked.

```
qvm-prefs -s default-mgmt-dvm -s template debian-13-xfce
```

**Comment by marmarek** [comment]
What was the default-mgmt-dvm template when it didn't work?

**Comment by twd64** [comment]
`fedora-42-xfce`

**Comment by qub411** [comment]
`fedora-42-xfce` here also.

**Comment by marmarek** [comment]
Interestingly, it works with fresh fedora-42-xfce template, but after installing updates there, it breaks.

**Comment by marmarek** [comment]
I think we can declare Debian 13 template stable - for both R4.2 and R4.3. I'll push them to the stable repo in a moment, @andrewdavidwong can you prepare the announcement?
