### ISSUE TITLE
qubes-vm-update exit with code 0 even if updating Debian template fails

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#8898]
## Observation

openQA test in scenario qubesos-4.2-kernel-x86_64-system_tests_network_updates@64bit fails in
[VmUpdates_debian-12-xfce](https://openqa.qubes-os.org/tests/90910/modules/VmUpdates_debian-12-xfce/steps/9)

```
Traceback (most recent call last):
  File "/usr/lib64/python3.11/contextlib.py", line 81, in inner
    return func(*args, **kwds)
           ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/tests/integ/vm_update.py", line 646, in test_131_no_network_qubes_vm_update_cli
    self.update_via_proxy_qubes_vm_update_impl(
  File "/usr/lib/python3.11/site-packages/qubes/tests/integ/vm_update.py", line 532, in update_via_proxy_qubes_vm_update_impl
    self.run_qubes_vm_update_and_assert(
  File "/usr/lib/python3.11/site-packages/qubes/tests/integ/vm_update.py", line 471, in run_qubes_vm_update_and_assert
    self.fail(
AssertionError: qubes-vm-update return unexpected code: 0 in (1, 2)
```

## Test suite description

Tests if update reports failure if update repository is inaccesible

## Reproducible

Fails since (at least) Build [2024012813-4.2](https://openqa.qubes-os.org/tests/90910) (current job)

## Expected result

Last good: [2024012004-4.2](https://openqa.qubes-os.org/tests/90325) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=kernel&machine=64bit&test=system_tests_network_updates&version=4.2)

`test_131_no_network_qubes_vm_update_cli` (`qubes-vm-update --no-progress`) test fails while `test_130_no_network_qubes_vm_update` (just `qubes-vm-update`) passes, and only on Debian template (debian-12-xfce specifically). The failure seems to be reproducible across few test runs already.

My guess is that's caused by recently merged https://github.com/QubesOS/qubes-core-admin-linux/pull/141

**Comment by marmarek** [comment]
cc @piotrbartman
