### ISSUE TITLE
qubes.StartApp choking on Calibre .desktop file

### ISSUE THREAD

**Issue by no-usernames-left** [QubesOS/qubes-issues#8910]
### Qubes OS release
R4.2.0

### Brief summary
Calibre, when installed in an AppVM based on `debian-12-xfce` with Calibre-required packages added, fails to start when its .desktop file is invoked by Qubes.

### Steps to reproduce
1. Install Calibre via `wget -nv -O- https://download.calibre-ebook.com/linux-installer.sh | sh /dev/stdin install_dir=~/calibre-bin isolated=y` in an AppVM based on a clone of `debian-12-xfce` which has had the extra packages required by Calibre installed in it.
2. Add the .desktop file (below) in `.local/share/applications/` and scan for new applications in qube settings
3. Try to launch it

### Expected behavior
Calibre launches.

### Actual behavior
`journalctl` reports:
```
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]: Traceback (most recent call last):
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:   File "/etc/qubes-rpc/qubes.StartApp", line 39, in <module>
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:     main(sys.argv)
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:   File "/etc/qubes-rpc/qubes.StartApp", line 33, in main
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:     launch(os.path.join(raw_volume, f))
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:   File "/usr/lib/python3/dist-packages/qubesagent/xdg.py", line 86, in launch
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:     launcher = make_launcher(filename_or_entry)
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:   File "/usr/lib/python3/dist-packages/qubesagent/xdg.py", line 38, in make_launcher
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:     return Gio.DesktopAppInfo.new_from_filename(filename)
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 03 20:03:20 calibre qubes.StartApp+calibre-gui-dom0[1025]: TypeError: constructor returned NULL
```

The contents of the .desktop file in question (mode 0644, owned by user:user):
```
[Desktop Entry]
Version=1.0
Type=Application
Name=calibre
GenericName=E-book library management
Comment=E-book library management: Convert, view, share, catalogue all your e-books
TryExec=calibre
Exec=/home/user/calibre-bin/calibre/calibre --detach %U
Icon=calibre-gui
Categories=Office;
X-GNOME-UsesNotifications=true
MimeType=application/xhtml+xml;application/x-sony-bbeb;application/x-mobi8-ebook;text/fb2+xml;application/x-cb7;text/rtf;image/vnd.djvu;application/x-cbr;application/pdf;application/vnd.openxmlformats-officedocument.wordprocessingml.document;application/x-mobipocket-subscription;application/x-mobipocket-ebook;application/vnd.ms-word.document.macroenabled.12;application/x-cbc;application/ereader;text/plain;application/oebps-package+xml;application/x-cbz;application/x-ruby;application/epub+zip;text/html;application/vnd.oasis.opendocument.text;text/x-markdown;x-scheme-handler/calibre;
```

**Comment by marmarek** [comment]
The `TryExec=calibre` line looks for `calibre` in `$PATH`. I guess you don't have it there. There are three options:
- add `/home/user/calibre-bin/calibre` to `$PATH` (IMO least preferred)
- change `TryExec=` line to include full path to the executable
- drop `TryExec=`

And independently, complain to Calibre so they fix the desktop file ;)
