### ISSUE TITLE
qrexec-policy-graph has AssertionError when only `--target` is specified without `--source` or `--service`

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#8946]
### Qubes OS release

R4.2

qubes-core-qrexec-4.2.17-1.fc37.x86_64

### Brief summary

Qrexec policy graph breaks unexpectedly. Happens when `--target` is specified but not `--source` or `--service`.

My policy has no syntax errors, as far as I can see from the journal.

Proving with the parser (doesn't cover runtime errors):
```
$ qubes-policy-lint $(find /etc/qubes/policy.d/ -maxdepth 1 -type f -name "*.policy")
WARNING:root:warning: !compat-4.0 directive in file __main__[in-memory] line 1 is transitional and will be deprecated
$ echo $?
0
$ qubes-policy-lint -i $(find /etc/qubes/policy.d/include/ -maxdepth 1 -type f)
$ echo $?
0
```

### Steps to reproduce

I can't share my policy and I understand debugging becomes more difficult.

Occurs with or without `--full-output` or `--include-ask`.

If you specify `--source` or `--service`, it works, but only `--target` doesn't work.

```
$ qrexec-policy-graph --include-ask --full-output --target QUBE
WARNING:root:warning: !compat-4.0 directive in file /etc/qubes/policy.d/35-compat.policy line 16 is transitional and will be deprecated
digraph g {
Traceback (most recent call last):
  File "/usr/bin/qrexec-policy-graph", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/qrexec/tools/qrexec_policy_graph.py", line 186, in main
    action = policy.evaluate(request)
             ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrexec/policy/parser.py", line 1623, in evaluate
    return rule.action.evaluate(request)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrexec/policy/parser.py", line 1115, in evaluate
    return request.ask_resolution_type(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qrexec/policy/parser.py", line 733, in __init__
    assert default_target is None or default_target in targets_for_ask
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```

### Expected behavior

No exception, just the dot output.

### Actual behavior

Python exception.

**Comment by ben-grande** [comment]
Confirmed fixed on R4.3. I have qubes-repo-devel enabled on dom0.
