### ISSUE TITLE
All templates and default qubes missing from fresh installation (only dom0 exists) - pykickstart missing quotes when dir has spaces and quotes

### ISSUE THREAD

**Issue by gianmarco1995** [QubesOS/qubes-issues#8993]
### Qubes OS release
4.2, 4.1, 4.1.1

### Brief summary
Unable to install the needed/default templates and the default Vms. No templates in the additional software page during installation.

### Steps to reproduce
Flash Os iso on usb drive
Install the Os on the target machine
Run the Os

### Expected behavior
All the default templates and Vms are installed.

### Actual behavior
No default templates are available. At the first boot, after the post-installation phase, the system is stuck with dom0 and only dom0.

### Detailed explanation

First of all, I’m sorry for my broken english.
I’m here to address an issue that seems to affect very few people, but also seems to be disruptive and insormontable.

I specify that I’m a Qubes user since 2017: I used this OS during the 2017-2019 period, then back again on it in 2022, and today I’m trying to reinstall it.

The issue is that, doesn’t matter what procedure I follow to flash the iso and install the OS, I’m unable to install the needed templates and the default Vms. I’ll leave you some pics that testify how the issue present itself:

First of all, here are the bios settings on my main machine.
![photo_5980909691494055883_y](https://github.com/QubesOS/qubes-issues/assets/94519738/e2070bdc-f378-4f72-af7c-5d023b6a4f84)
![photo_5980909691494055882_y](https://github.com/QubesOS/qubes-issues/assets/94519738/b6522e86-3920-440d-8f9e-712f18cc59d0)
![photo_5980909691494055881_y](https://github.com/QubesOS/qubes-issues/assets/94519738/e2864a81-1baa-4e04-97fa-33ed94e74927)
![photo_5980909691494055880_y](https://github.com/QubesOS/qubes-issues/assets/94519738/1c96ab49-7fc3-4490-ba24-50121a3bf8b7)

As usual, I flash the iso on the USB drive (tried dd, rufus, etcher: more on that later) and verify the media and the gpg signatures. Then, after the boot, you can see the first symptoms of the issue:
![photo_5980909691494055884_y](https://github.com/QubesOS/qubes-issues/assets/94519738/77f1d195-66bc-4eec-b5a0-f78a312d83bb)

As you can see, in the software selection page, the templates are totally absent. I can only install the Qubes UI.

I also tried to test the installation media, it seems ok.
![photo_5980909691494055886_y](https://github.com/QubesOS/qubes-issues/assets/94519738/e466c45d-0398-45ca-9db1-8455f0761419)

At this point, if I proceed, the installer executes itself and bring me to the reboot. After the reboot, in the post-installation phase, this is the first thing that seems wrong:
![photo_5980909691494055887_y](https://github.com/QubesOS/qubes-issues/assets/94519738/42b3a8d0-a151-4d99-9160-e00a6422762f)

Whonix not available, fedora and debian not even mentioned, and all the options (except the advanced configuration options) are greyed out.

If I go further, in the terminal post-installation phase, the systems gives back this message:
![photo_5980909691494055885_y](https://github.com/QubesOS/qubes-issues/assets/94519738/6d36a614-98ac-430e-a58e-512e9d46802c)

At this point I can boot Qubes and log in, but I’m stuck with Dom0 and only Dom0. No templates at all, and no pre-configured Vms. I know that there is probably some workaround to this issue, like installing the templates after the Os installation, but I’m not an expert user.

On the forum, a guy told me to run this command in the dom0 terminal, so I leave you also this picture.
![photo_5980909691494055888_y](https://github.com/QubesOS/qubes-issues/assets/94519738/1aefa23d-c5d8-45ac-aafc-630f0a426998)

To better address the problem, I tell you that I tried all the possible combinations between the following alternatives (I’ve been on it for the past 3 days):

Downloading the iso:
Tried both from the main qubes website, from the torrent and from multiple mirrors. Tried to flash the 4.2 stable, 4.1 stable and 4.1.1 rc5 (the last time I installed qubes, in 2022, I flashed and installed this last iso and it worked flawlessly). Downloaded the iso both in linux and windows environment.

Flashing the iso:
Tried rufus (both DD and ISO mode), etcher and the dd command in linux environment. Everytime I flashed the iso in a linux environment I did also all the integrity and signature checks, and everytime they passed

Target machine:
The bios settings you see are from the machine with I always used qubes in the past. Anyway, I tried to change the target machine 3 more times:

ASUS UX305UA-FB004T Zenbook, i7-6500U, 8GB Ram
HUAWEI MateBook X Pro, i7-8550U, 8GB Ram
Lenovo IdeaPad S145, i3-8145U, 8GB Ram
Everytime I got the exact same result

Miscellaneous:
Changed 5 different USB drives, also tried a USB 2.0 drive. Tried all the different ports on all the different machines: nothing changed.

Last thing: As you can see here, this isn’t really the first time I encountered this issue. But the last time, in 2022, I was able to resolve it by downloading the 4.1.1 iso (at that time it was a beta version, since the stable was the 4.0). Here you can find the discussion: [All templates MISSING from fresh installation](https://forum.qubes-os.org/t/all-templates-missing-from-fresh-installation/12517)
That brings me to think that there is something wrong with Qubes iso, and not with me.

Link to forum discussion:

https://forum.qubes-os.org/t/are-all-qubes-iso-corrupted-no-additional-software-no-templates-no-default-vms-stuck-with-only-dom0/24722

**Comment by hardcod3dd** [comment]
Any updates on this issue? I am having the exact same issue and only resource i could find is this discussion.

**Comment by gianmarco1995** [comment]
I solved by changing USB drive. I tried something like 6 USB drives, and it
worked on the 7th one.

Il Mer 12 Giu 2024, 14:30 Dogukan ***@***.***> ha scritto:

**Comment by hardcod3dd** [comment]
just tried to flash onto an portable ssd and installed from it. it worked for me too. very weird issue but solved now.

**Comment by ben-grande** [comment]
Please retest on R4.3. Would be nice to have closure of why this happened. If you can't reproduce, please notify so this issue can be closed.

**Comment by rsilvatech** [comment]
I'm having the same issue. I've already installed qubes OS but the setup page never appeared, so I only have dom0. I tried to do "sudo /usr/libexec/initial-setup-graphical" and "sudo /usr/libexec/initial-setup-text" but it only shows errors and traceback calls. I also tried to manually install the templates, but it also breaks. I'm still stuck and without any idea on how to proceed. 

My computer specs: Dell Inspiron 15 with 2 partition tables, one NVME with debian and win11 and a SATA with only QubesOS

**Comment by marmarek** [comment]
> it only shows errors and traceback calls

Please share those messages.

**Comment by technonine** [comment]
Hi, new user here, can confirm this issue still exists. Running the first command from rsilvatech gives me the following terminal output:

> $ sudo /usr/libexec/initial-setup/initial-setup-graphical
> INFO initial-setup: Initial Setup 0.3.101
> DEBUG initial-setup: running in GUI mode
> DEBUG initial-setup: GI overrides imported
> INFO initial-setup: found 2 addon modules:
> DEBUG initial-setup: spokes
> DEBUG initial-setup: categories
> DEBUG initial-setup: initializing the Anaconda log
> INF initial-setup: using kickstart from Anaconda run for input
> INF initial-setup: parsing input kickstart /root/anaconda-ks.cfg
> ERR initial-setup: Initial Setup crashed due to unhandled exception:
> Traceback (most recent call last):
>   File "/usr/libexec/initial-setup/initial-setup-graphical", line 13, in <module>
>     is_instance.run()
>     ~~~~~~~~~~~~~~~^^
>   File "/usr/lib/python3.13/site-packages/initial_setup/__init__.py", line 344, in run
>     self._load_kickstart()
>     ~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/lib/python3.13/site-packages/initial_setup/__init__.py", line 241, in _load_kickstart
>     parser.readKickstart(kickstart_path)
>     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.13/site-packages/pykickstart/parser.py", line 824, in readKickstart
>     self.readKickstartFromString(s, reset=False)
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.13/site-packages/pykickstart/parser.py", line 797, in readKickstartFromString
>     self._stateMachine(i)
>     ~~~~~~~~~~~~~~~~~~^^^
>   File "/usr/lib/python3.13/site-packages/pykickstart/parser.py", line 741, in _stateMachine
>     args = shlex.split(self._line, comments=True)
>   File "/usr/lib64/python3.13/shlex.py", line 313, in split
>     return list(lex)
>   File "/usr/lib64/python3.13/shlex.py", line 300, in __next__
>     token = self.get_token()
>   File "/usr/lib64/python3.13/shlex.py", line 109, in get_token
>     raw = self.read_token()
>   File "/usr/lib64/python3.13/shlex.py", line 191, in read_token
>     raise ValueError("No closing quotation")
> ValueError: No closing quotation

Similarly the second command gives the following terminal output:

> $ sudo /usr/libexec/initial-setup/initial-setup-text 
> INFO initial-setup: Initial Setup 0.3.101
> DEBUG initial-setup: running in TUI mode
> INFO initial-setup: found 2 addon modules:
> DEBUG initial-setup: spokes
> DEBUG initial-setup: categories
> DEBUG initial-setup: initializing the Anaconda log
> INF initial-setup: using kickstart from Anaconda run for input
> INF initial-setup: parsing input kickstart /root/anaconda-ks.cfg
> ERR initial-setup: Initial Setup crashed due to unhandled exception:
> Traceback (most recent call last):
>   File "/usr/libexec/initial-setup/initial-setup-text", line 10, in <module>
>     is_instance.run()
>     ~~~~~~~~~~~~~~~^^
>   File "/usr/lib/python3.13/site-packages/initial_setup/__init__.py", line 344, in run
>     self._load_kickstart()
>     ~~~~~~~~~~~~~~~~~~~~^^
>   File "/usr/lib/python3.13/site-packages/initial_setup/__init__.py", line 241, in _load_kickstart
>     parser.readKickstart(kickstart_path)
>     ~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.13/site-packages/pykickstart/parser.py", line 824, in readKickstart
>     self.readKickstartFromString(s, reset=False)
>     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
>   File "/usr/lib/python3.13/site-packages/pykickstart/parser.py", line 797, in readKickstartFromString
>     self._stateMachine(i)
>     ~~~~~~~~~~~~~~~~~~^^^
>   File "/usr/lib/python3.13/site-packages/pykickstart/parser.py", line 741, in _stateMachine
>     args = shlex.split(self._line, comments=True)
>   File "/usr/lib64/python3.13/shlex.py", line 313, in split
>     return list(lex)
>   File "/usr/lib64/python3.13/shlex.py", line 300, in __next__
>     token = self.get_token()
>   File "/usr/lib64/python3.13/shlex.py", line 109, in get_token
>     raw = self.read_token()
>   File "/usr/lib64/python3.13/shlex.py", line 191, in read_token
>     raise ValueError("No closing quotation")
> ValueError: No closing quotation

**Comment by marmarek** [comment]
Oh, interesting, this looks kinda similar to https://github.com/QubesOS/qubes-issues/issues/10516. Have you chosen maybe filesystem label with a space? Or some other value with a quotation mark? Can you share your kickstart file (`/root/anaconda-ks.cfg`)? Just remove your password hashes.

**Comment by rsilvatech** [comment]
I was going to write the logs but it is exactly the one described above. Thank you for helping Technonine.

Also, I tried to reinstall qubes os using the torrent file instead of the official installation and it almost worked. I got the initial setup screen, configured it and let it install properly. However, after installing the templates for debian, fedora and whonix, it crashes on the networking part. I was able to boot the system and use some offline apps but any of the ones who needed sys-net, sys-firewall or sys-whonix would pop an error (cannot connect to qrexec agent for 60 seconds) on loop. I checked my bootloader, my partitions and tried installing 4.2.4 (it didn't even showed the first installation screen).  Its my 8th time trying to install qubes os today. I'm going to try changing some things to see if it works and share the kickstart file. See y'all soon

**Comment by technonine** [comment]
@marmarek Here is my anaconda-ks.cfg:


```
# Generated by Anaconda 41.28
# Generated by pykickstart v3.58
#version=DEVEL

# Keyboard layouts
keyboard --vckeymap=us-intl --xlayouts='us (intl)'
# System language
lang en_US.UTF-8

# Use hard drive installation media
harddrive --dir=/OS ISO/torrent iso's/Qubes-R4.3.0-x86_64/Qubes-R4.3.0-x86_64.iso --partition=sda2

%packages
@^qubes-xfce
@desktop-accessibility
@qubes-ui
@swaywm-extended

%end

# Run the Setup Agent on first boot
firstboot --enable

# Generated using Blivet version 3.10.1
ignoredisk --only-use=sdb
autopart --encrypted
# Partition clearing information
clearpart --none --initlabel

# System timezone
timezone America/New_York

#Root password
rootpw --lock
user --groups=wheel,qubes --name=technonine --password=[redacted] --iscrypted --gecos="technonine"

```

Seems my harddrive dir for the OS .iso has spaces in it which would mess up the command. (I used ventoy to run the install iso, and the installer seemed to struggle with mounting logical volumes so I gave it the location of the iso on a different system harddrive). This might be a case of user error on my end. No clue what the others did to get this error however. 

Update: editing the harddrive line to add parentheses like below allows me to run the graphical installer succesfully!
```harddrive --dir="/OS ISO/torrent iso's/Qubes-R4.3.0-x86_64/Qubes-R4.3.0-x86_64.iso" --partition=sda2```

**Comment by rsilvatech** [comment]
Sorry for taking so long to answer, but I've successfully installed qubes after many attempts. The directory holding the .iso had spaces in its path, making the inital_setup command fail. And the networking crash only happened when selecting debian-13 as the default system packages, but when installing with fedora selected everithing was fine (i've tested 4 times and fedora worked twice, but debian allways falis the networking part). Maybe its related to debian missing drivers for my notebook's rtl8821ce wifi chip or something. (sorry for my english, its not my first language =)

**Comment by ben-grande** [comment]
There are various reasons why the  installation can fail. In this case, OP stopped replying and we don't know why it failed for them specifically. For the others, I opened a PR upstream to address the issue of missing quotation. This issue may be closed once the new pykickstart reaches dom0 repository.

**Comment by marmarek** [comment]
> we don't know why it failed for them specifically

I think we do in the later case:


> harddrive --dir=/OS ISO/torrent iso's/Qubes-R4.3.0-x86_64/Qubes-R4.3.0-x86_64.iso --partition=sda2

Single quote here confused initial-setup, and if quoted properly it worked:

> Update: editing the harddrive line to add parentheses like below allows me to run the graphical installer succesfully! `harddrive --dir="/OS ISO/torrent iso's/Qubes-R4.3.0-x86_64/Qubes-R4.3.0-x86_64.iso" --partition=sda2`

So, it's (also) pykickstart issue of not adding quotes where necessary, in a different option this time.

**Comment by ben-grande** [comment]
> > we don't know why it failed for them specifically
> 
> I think we do in the later case:

I used them to mean the author of this issue without trying to use her/his.

For the latter case, I opened an issue upstream. It is linked to this thread.

**Comment by ben-grande** [comment]
Upstream did not accept PR with `shlex.quote()` to protect against user controlled path. Here is a backup of that: https://github.com/ben-grande/pykickstart/tree/shlex-quote-dir. Upstream will accept just double quotes, which fixes this case, but will break in the future if the path also contain double quotes.

**Comment by ben-grande** [comment]
PR merged upstream. Requires new version of https://github.com/QubesOS/qubes-pykickstart once upstream releases >3.69.

**Comment by iliacus25** [comment]
I'm having exactly this same issue. Tried a number of different USBs, I'm down to the ratty old ones from the back of the drawer now, since it's failed on all my good new ones. DD mode on Rufus fails the media test every time, trying to proceed without the media test now but still no luck. Balena Etcher usually manages to get dom0 installed but still no templates.

Has anyone had any luck with trying to install them after the install via terminal?

**Comment by ben-grande** [comment]
@iliacus25 I don't know if the cause of your issue is the same. Please share the output of:

```
sudo /usr/libexec/initial-setup/initial-setup-graphical
```

And if it fails loading the config, share the output of:

```
cat -v /root/anaconda-ks.cfg
```

**Comment by iliacus25** [comment]
> [@iliacus25](https://github.com/iliacus25) I don't know if the cause of your issue is the same. Please share the output of:
> 
> ```
> sudo /usr/libexec/initial-setup/initial-setup-graphical
> ```
> 
> And if it fails loading the config, share the output of:
> 
> ```
> cat -v /root/anaconda-ks.cfg
> ```


> [@iliacus25](https://github.com/iliacus25) I don't know if the cause of your issue is the same. Please share the output of:
> 
> ```
> sudo /usr/libexec/initial-setup/initial-setup-graphical
> ```
> 
> And if it fails loading the config, share the output of:
> 
> ```
> cat -v /root/anaconda-ks.cfg
> ```

@ben-grande hi, thanks for getting back to me! I've actually uninstalled dom0 again and formatted the drive to see if that makes a difference, but haven't got around to reinstalling it again yet. But I'll try it again if I get a chance tonight or tomorrow and let you know. 
One thing that occurred to me is that my hardware is very new, and I'm on an AMD processor, so it may be a fundamental hardware incompatibility issue. But I'll try it again and let you know what I get.
