### ISSUE TITLE
rpmcanon fails to build on f40

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9137]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

rpm-oxide / rpmcanon fails to build on Fedora 40

### Steps to reproduce

`./qb -d vm-fc40 -c rpm-oxide package all`

### Expected behavior

Build successfully.

### Actual behavior

```
2024-04-17 20:29:53.540189 +0000 build-fedora43: output: DEBUG: Processing files: qubes-rpm-oxide-0.2.7-1.fc40.x86_64
2024-04-17 20:29:53.558452 +0000 build-fedora43: output: DEBUG: Provides: qubes-rpm-oxide = 0.2.7-1.fc40 qubes-rpm-oxide(x86-64) = 0.2.7-1.fc40
2024-04-17 20:29:53.558541 +0000 build-fedora43: output: DEBUG: Requires(rpmlib): rpmlib(CompressedFileNames) <= 3.0.4-1 rpmlib(FileDigests) <= 4.6.0-1 rpmlib(PayloadFilesHavePrefix) <= 4.0-1
2024-04-17 20:29:53.558825 +0000 build-fedora43: output: DEBUG: Requires: ld-linux-x86-64.so.2()(64bit) ld-linux-x86-64.so.2(GLIBC_2.3)(64bit) libc.so.6()(64bit) libc.so.6(GLIBC_2.14)(64bit) libc.so.6(GLIBC_2.17)(64bit) libc.so.6(GLIBC_2.18)(64bit) libc.so.6(GLIBC_2.2.5)(64bit) libc.so.6(GLIBC_2.28)(64bit) libc.so.6(GLIBC_2.3)(64bit) libc.so.6(GLIBC_2.3.4)(64bit) libc.so.6(GLIBC_2.32)(64bit) libc.so.6(GLIBC_2.33)(64bit) libc.so.6(GLIBC_2.34)(64bit) libc.so.6(GLIBC_2.4)(64bit) libgcc_s.so.1()(64bit) libgcc_s.so.1(GCC_3.0)(64bit) libgcc_s.so.1(GCC_3.3)(64bit) libgcc_s.so.1(GCC_4.2.0)(64bit) librpm.so.10()(64bit) librpmio.so.10()(64bit) rtld(GNU_HASH)
2024-04-17 20:29:53.558956 +0000 build-fedora43: output: DEBUG: Processing files: qubes-rpm-oxide-debugsource-0.2.7-1.fc40.x86_64
2024-04-17 20:29:53.559099 +0000 build-fedora43: output: DEBUG: RPM build errors:
2024-04-17 20:29:53.559249 +0000 build-fedora43: output: DEBUG: error: Empty %files file /builddir/build/BUILD/qubes-rpm-oxide-0.2.7/debugsourcefiles.list
2024-04-17 20:29:53.559430 +0000 build-fedora43: output: DEBUG:     Empty %files file /builddir/build/BUILD/qubes-rpm-oxide-0.2.7/debugsourcefiles.list
2024-04-17 20:29:53.570677 +0000 build-fedora43: output: DEBUG: Child return code was: 1
2024-04-17 20:29:53.571772 +0000 build-fedora43: output: INFO: EXCEPTION: [Error('Command failed: \n # /usr/bin/systemd-nspawn -q -M 760c8e36c1da4a15b51c3c0aea8fa490 -D /builder/build/fedora-40-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.h78zjoh2:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin \'--setenv=PROMPT_COMMAND=printf "\\033]0;<mock-chroot>\\007"\' \'--setenv=PS1=<mock-chroot> \\s-\\v\\$ \' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c \'/usr/bin/rpmbuild -bb --noclean --target x86_64 --nodeps /builddir/build/SPECS/rpm-oxide.spec\'\n', 1)]
2024-04-17 20:29:53.571831 +0000 build-fedora43: output: Traceback (most recent call last):
2024-04-17 20:29:53.571873 +0000 build-fedora43: output:   File "/usr/lib/python3.12/site-packages/mockbuild/trace_decorator.py", line 93, in trace
2024-04-17 20:29:53.571892 +0000 build-fedora43: output:     result = func(*args, **kw)
2024-04-17 20:29:53.571909 +0000 build-fedora43: output:              ^^^^^^^^^^^^^^^^^
2024-04-17 20:29:53.571929 +0000 build-fedora43: output:   File "/usr/lib/python3.12/site-packages/mockbuild/util.py", line 612, in do_with_status
2024-04-17 20:29:53.571952 +0000 build-fedora43: output:     raise exception.Error("Command failed: \n # %s\n%s" % (cmd_pretty(command, env), output), child.returncode)
2024-04-17 20:29:53.571970 +0000 build-fedora43: output: mockbuild.exception.Error: Command failed:
2024-04-17 20:29:53.572075 +0000 build-fedora43: output:  # /usr/bin/systemd-nspawn -q -M 760c8e36c1da4a15b51c3c0aea8fa490 -D /builder/build/fedora-40-x86_64/root -a -u mockbuild --capability=cap_ipc_lock --bind=/tmp/mock-resolv.h78zjoh2:/etc/resolv.conf --bind=/dev/btrfs-control --bind=/dev/mapper/control --bind=/dev/fuse --bind=/dev/loop-control --bind=/dev/loop0 --bind=/dev/loop1 --bind=/dev/loop2 --bind=/dev/loop3 --bind=/dev/loop4 --bind=/dev/loop5 --bind=/dev/loop6 --bind=/dev/loop7 --bind=/dev/loop8 --bind=/dev/loop9 --bind=/dev/loop10 --bind=/dev/loop11 --console=pipe --setenv=TERM=vt100 --setenv=SHELL=/bin/bash --setenv=HOME=/builddir --setenv=HOSTNAME=mock --setenv=PATH=/usr/bin:/bin:/usr/sbin:/sbin '--setenv=PROMPT_COMMAND=printf "\033]0;<mock-chroot>\007"' '--setenv=PS1=<mock-chroot> \s-\v\$ ' --setenv=LANG=C.UTF-8 --resolv-conf=off bash --login -c '/usr/bin/rpmbuild -bb --noclean --target x86_64 --nodeps /builddir/build/SPECS/rpm-oxide.spec'
2024-04-17 20:29:53.572116 +0000 build-fedora43: output: 
```

https://github.com/QubesOS/updates-status/issues/4512
full log: https://github.com/QubesOS/build-logs43/blob/main/build-fedora43/log_2024-04-17_20-12-37

**Comment by marmarek** [comment]
Fixed itself? https://github.com/QubesOS/updates-status/issues/4379
