### ISSUE TITLE
qvm-convert-img fails to convert SVG image

### ISSUE THREAD

**Issue by ben-grande** [QubesOS/qubes-issues#9145]
### Qubes OS release

R4.2

### Brief summary

Try to convert 

### Steps to reproduce

Download [Whonix-logo.svg](https://www.whonix.org/w/images/1/19/Whonix-logo.svg).
```sh
curl -O https://www.whonix.org/w/images/1/19/Whonix-logo.svg
```

Try to convert image:
```sh
qvm-convert-img Whonix-logo.svg Whonix-logo.safe.svg
```

### Expected behavior

Command `qvm-convert-img` converts the image.

### Actual behavior

```sh
gm identify: No decode delegate for this image format (/tmp/qimg-7C8BP9Rv.png).
gm identify: Request did not return an image.
```
```python3
Traceback (most recent call last):
  File "/usr/lib/qubes/qimg-convert-client", line 50, in <module>
    main()
  File "/usr/lib/qubes/qimg-convert-client", line 44, in main
    img = qubesimgconverter.Image.get_through_dvm(args.src)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/qubesimgconverter/__init__.py", line 320, in get_through_dvm
    return cls.get_from_stream(sys.stdin.buffer, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/qubesimgconverter/__init__.py", line 197, in get_from_stream
    raise ValueError('No icon received')
ValueError: No icon received
```

Converting the [qubes-logo-home.svg](https://www.qubes-os.org/attachment/icons/qubes-logo-home.svg) works while the [Whonix-logo.svg](https://www.whonix.org/w/images/1/19/Whonix-logo.svg) fails.

**Comment by alimirjamali** [comment]
> Converting the [qubes-logo-home.svg](https://www.qubes-os.org/attachment/icons/qubes-logo-home.svg) works while the [Whonix-logo.svg](https://www.whonix.org/w/images/1/19/Whonix-logo.svg) fails.

Just wanted to double check. Did you also try to convert `qubes-logo-home.svg`  from svg to svg? Because it should also fail.

**Comment by ben-grande** [comment]
> > Converting the [qubes-logo-home.svg](https://www.qubes-os.org/attachment/icons/qubes-logo-home.svg) works while the [Whonix-logo.svg](https://www.whonix.org/w/images/1/19/Whonix-logo.svg) fails.
> 
> Just wanted to double check. Did you also try to convert `qubes-logo-home.svg` from svg to svg? Because it should also fail.

Although I named the output file `.svg`, the conversion is always from svg to png (I believe, due to rsvg-convert). Yes, converting the Qubes logo from svg to png works, even if the file extension is svg.

**Comment by Jayant-kernel** [comment]
I’d like to work on this.

I opened a PR with a targeted fix: https://github.com/QubesOS/qubes-core-agent-linux/pull/646

Plan/approach is simple: when `gm identify` returns zero/empty dimensions for SVGs, don’t pass `-w 0 -h 0` to `rsvg-convert`; let it pick size from `viewBox`, then keep using the existing post-conversion `gm identify` on the PNG.

This keeps current behavior unchanged for SVGs that already have explicit width/height.
