### ISSUE TITLE
qubes-fwupdmgr refresh broken with Failed to refresh remote 'lvfs'

### ISSUE THREAD

**Issue by kennethrrosen** [QubesOS/qubes-issues#9214]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2.1

### Brief summary

`qubes-fwupdmgr` exits on error.

### Steps to reproduce

1. `qubes-fwupdmgr get-devices`
2. `qubes-fwupdmgr refresh`

### Expected behavior

Devices refresh and `update` updates decides. 

### Actual behavior

`update` hangs, and `qubes-fwupdmgr` exits on error:

```
Traceback (most recent call last):
  File "/usr/bin/qubes-vmexec", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3/dist-packages/qubesagent/vmexec.py", line 55, in main
    os.execvp(command[0], command)
  File "<frozen os>", line 574, in execvp
  File "<frozen os>", line 597, in _execvpe
FileNotFoundError: [Errno 2] No such file or directory
Failed to refresh remote 'lvfs': Metadata download failed.
```

**Comment by marmarek** [comment]
The template you use for updatevm needs to have the `fwupd-qubes-vm` package installed.

**Comment by TNTBOMBOM** [comment]
> Is `fwupd-qubes-vm` a missing dependency of `qubes-core-agent-dom0-updates`? Is there a reason it is not included by default?

Its included by default (full template) in my use case now.

**Comment by Tyr4El** [comment]
Hi,
Sorry I am new to this, so it will probably not be formatted as it should be.
As suggested [here](https://forum.qubes-os.org/t/how-to-do-firmware-updates-with-qubes-os-4-2/23547/7).
it has been appointed to me that it could be a good thing to reopen this ticket.
There might be a need for several tickets for that problem, but you will be the judges of this if you don't mind.

1/ There is nowhere to be found in the UI the fact to know which are the right update qube used ... There are still the update proxy vm mentioned and pointed. But by default that's whonix-gateway or sys-whonix if you prefer. I have seen like 10 threads at least on the forums about this for years apparently and no changes have been done to the UI. 

1bis/ It depends of course if devs want to make qubesOS available to the average people or not. IT can also be a choice to simply be a niche but then journalist, amnesty international and so forth and so forth can continue to complain at privacy camps each year that we don't have the tools to protect against pegasus-like malware etc. 

2/ I had to rely on the actual command line which states verbosely what is the actual updateVM to resolve that  error message. 

3/ As Sean from starlabs systems written to me (and tested before that) and who is one who actually write partly the code of qubes-fwupdmgr, there is still a bug with that piece of software, it can't detect any of the updates for the firmware for starlabs notebooks.

**Comment by andrewdavidwong** [comment]
> 1/ There is nowhere to be found in the UI the fact to know which are the right update qube used ... There are still the update proxy vm mentioned and pointed. But by default that's whonix-gateway or sys-whonix if you prefer. I have seen like 10 threads at least on the forums about this for years apparently and no changes have been done to the UI.
> 
> 1bis/ It depends of course if devs want to make qubesOS available to the average people or not. IT can also be a choice to simply be a niche but then journalist, amnesty international and so forth and so forth can continue to complain at privacy camps each year that we don't have the tools to protect against pegasus-like malware etc.
> 
> 2/ I had to rely on the actual command line which states verbosely what is the actual updateVM to resolve that error message.

Created #10162 for this part.

**Comment by ben-grande** [comment]
> > Is `fwupd-qubes-vm` a missing dependency of `qubes-core-agent-dom0-updates`? Is there a reason it is not included by default?
> 
> Its included by default (full template) in my use case now.

Fixed on R4.3. `rpm -q --whatrequires fwupd-qubes-vm` on Fedora 44 Xfce returns `qubes-vm-recommended`.
