### ISSUE TITLE
qubes-builder creates templates that cannot be installed with qvm-template

### ISSUE THREAD

**Issue by unman** [QubesOS/qubes-issues#9246]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
4.2 with dom0 testing repositories enabled

### Brief summary
As title.
Creating custom templates,(e.g. trixie based), with builderv2, Qubes executor, results in templates that cannot be installed.
(I have not tested building standard templates.)

### Steps to reproduce
1. Build template with builderv2
2. Transfer template to dom0
3. Install template with `qvm-template install...` 

### Expected behavior
Template will be installed.

### Actual behavior
Template fails to install, with this error:

```
Traceback (most recent call last):
  File "/usr/bin/qvm-template-postprocess", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 449, in main
    loop.run_until_complete(post_install(args))
  File "/usr/lib64/python3.11/asyncio/base_events.py", line 653, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 314, in post_install
    import_root_img(vm, args.dir)
  File "/usr/lib/python3.11/site-packages/qubesadmin/tools/qvm_template_postprocess.py", line 102, in import_root_img
    raise qubesadmin.exc.QubesException(
qubesadmin.exc.QubesException: template.rpm symlink not found for multi-part image, using up-to-date `qvm-template install ...` should help

```

There was no sign of error in building the template.
qvm-template provided by qubes-core-admin-client-4.2.12-1

**Comment by marmarek** [comment]
Try calling `qvm-template` with an absolute path to the template rpm. If that helps, I think I know where the issue is.

**Comment by unman** [comment]
As always, a genius level response.
It does help, although I was used to not giving an absolute path.
