### ISSUE TITLE
Cannot create new standalone Qube with UI

### ISSUE THREAD

**Issue by incalzando-a** [QubesOS/qubes-issues#9303]
### Qubes OS release
4.2.1 (R4.2)

When using "Create New Qube" application, to create a standalone Qube, I encounter the error "An error occurred: Got empty response from qubesd. See journalctl in dom0 for details".

journalctl output:
```
Jun 13 10:42:57 dom0 qubesd[40029]: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Create.StandaloneVM' dest=b'dom0' arg=b'' len(untrusted_payload)=31
Jun 13 10:42:57 dom0 qubesd[40029]: Traceback (most recent call last):
Jun 13 10:42:57 dom0 qubesd[40029]:   File "/usr/lib/python3.11/site-packages/qubes/api/__init__.py", line 297, in respond
Jun 13 10:42:57 dom0 qubesd[40029]:     response = await self.mgmt.execute(
Jun 13 10:42:57 dom0 qubesd[40029]:                ^^^^^^^^^^^^^^^^^^^^^^^^
Jun 13 10:42:57 dom0 qubesd[40029]:   File "/usr/lib/python3.11/site-packages/qubes/api/admin.py", line 1077, in _vm_create
Jun 13 10:42:57 dom0 qubesd[40029]:     untrusted_key, untrusted_value = untrusted_param.split('=', 1)
Jun 13 10:42:57 dom0 qubesd[40029]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 13 10:42:57 dom0 qubesd[40029]: ValueError: not enough values to unpack (expected 2, got 1)
```

I've tried with all template and settings, but still receive this error. I think it might be a signing error somewhere.

**Comment by Geblaat** [comment]
Did you by any chance put a space in the name of the new Qube? I got the same output in journalctl, see:
https://github.com/QubesOS/qubes-issues/issues/9558

**Comment by alimirjamali** [comment]
The PR for #9558 should fix this as well. This issue could be closed.
