### ISSUE TITLE
dom0 widget-wrapper error/traceback during dispvm cleanup

### ISSUE THREAD

**Issue by rocodes** [QubesOS/qubes-issues#9358]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

4.2.2

### Brief summary

In the dom0 journal I notice a Python traceback [pointing here](https://github.com/QubesOS/qubes-desktop-linux-manager/blob/66e5cfbc49249159a07cb340c3887e4d52e98e55/qui/tray/updates.py#L173-L175) when dispvms are cleaned up. I initially noticed this when the VM shuts down prematurely (eg, trying to open a file in a dispvm that doesn't have an appropriate mime handler), but this also occurs in normal shutdown of dispvm and I observe it every time.

### Steps to reproduce

Start then shut down a disposable vm while watching dom0 journal

### Expected behavior

Clean shutdown

### Actual behavior

```
Jul 17 16:30:56 dom0 widget-wrapper[15776]: Failed to handle event: None, domain-delete, {'vm': 'disp5303'}
Jul 17 16:30:56 dom0 widget-wrapper[15776]: Traceback (most recent call last):
Jul 17 16:30:56 dom0 widget-wrapper[15776]:   File "/usr/lib/python3.11/site-packages/qubesadmin/events/__init__.py", line 259, in handle
Jul 17 16:30:56 dom0 widget-wrapper[15776]:     handler(subject, event, **kwargs)
Jul 17 16:30:56 dom0 widget-wrapper[15776]:   File "/usr/lib/python3.11/site-packages/qui/tray/updates.py", line 173, in domain_removed
Jul 17 16:30:56 dom0 widget-wrapper[15776]:     if vm.name in self.obsolete_vms:
Jul 17 16:30:56 dom0 widget-wrapper[15776]:        ^^^^^^^
Jul 17 16:30:56 dom0 widget-wrapper[15776]: AttributeError: 'str' object has no attribute 'name'
Jul 17 16:30:56 dom0 qubesd[13154]: Removing appmenus for 'disp5303' in 'dom0'
```

**Comment by marmarek** [comment]
There is already fix for it here: https://github.com/QubesOS/qubes-desktop-linux-manager/pull/210
