### ISSUE TITLE
Cannot shut down template VM; fails with 'Got empty response from qubesd'

### ISSUE THREAD

**Issue by StoicDeveloper** [QubesOS/qubes-issues#9388]
### Qubes OS release

4.2.2

### Brief summary

On a new install of Qubes 4.2.2 on an Acer Switft 3, with temlateVM Debian-Xfce installed, the template VM cannot be shut down. Attempt to do so appear to stall, until a dialog with this message appears:
`The following error occurred while attempting to shut down qube debian-12-xfce: Got empty response from qubesd. See journalctl in dom0 for details.`

### Steps to reproduce

1. New install
2. Open template VM
3. From qubes manager dropdown in the top right, debian-12-xfce -> Shutdown
4. Observe failure

### Expected behavior

Graceful shutdown

### Actual behavior

Ungraceful not shutdown. Template can only be closed by shutting down the computer.

**Comment by StoicDeveloper** [comment]
$ journalctl
Aug 02 11:17:57 localhost kernel: Linux version 6.6.36-1.qubes.fc37.x86_64 (mockbuild@01d867aa44b046b59b72b56f0f81e904) (gcc (GCC) 12.3.1 20230508 (Red Hat 12.3.1-1), GN>
Aug 02 11:17:57 localhost kernel: Command line: placeholder root=/dev/mapper/qubes_dom0-root ro rd.luks.uuid=luks-302a4812-a6b9-40db-bf23-f39e701a8bfa rd.lvm.lv=qubes_do>
Aug 02 11:17:57 localhost kernel: Released 0 page(s)
Aug 02 11:17:57 localhost kernel: BIOS-provided physical RAM map:
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x0000000000000000-0x0000000000057fff] usable
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x0000000000058000-0x0000000000058fff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x0000000000059000-0x000000000007ffff] usable
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x0000000000080000-0x00000000000fffff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x0000000000100000-0x000000007a89ffff] usable
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x000000007a8a0000-0x000000007a8a0fff] ACPI NVS
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x000000007a8a1000-0x000000007a8a1fff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x000000007a8a2000-0x0000000089a62fff] usable
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x0000000089a63000-0x000000008a8fefff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x000000008a8ff000-0x000000008a94efff] ACPI data
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x000000008a94f000-0x000000008a9dbfff] ACPI NVS
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x000000008a9dc000-0x000000008affdfff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x000000008affe000-0x000000008affefff] usable
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x000000008afff000-0x000000008fffffff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x00000000e0000000-0x00000000efffffff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x00000000fe000000-0x00000000fe010fff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x00000000fec00000-0x00000000fec00fff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x00000000fed00000-0x00000000fed00fff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x00000000fed90000-0x00000000fed91fff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x00000000fee00000-0x00000000feefffff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x00000000ff000000-0x00000000ffffffff] reserved
Aug 02 11:17:57 localhost kernel: Xen: [mem 0x0000000100000000-0x000000017661efff] usable
Aug 02 11:17:57 localhost kernel: NX (Execute Disable) protection: active
Aug 02 11:17:57 localhost kernel: APIC: Static calls initialized
Aug 02 11:17:57 localhost kernel: efi: EFI v2.6 by American Megatrends
Aug 02 11:17:57 localhost kernel: efi: TPMFinalLog=0x8a98b000 ACPI 2.0=0x8a90f000 ACPI=0x8a90f000 SMBIOS=0x8ae05000 SMBIOS 3.0=0x8ae04000 ESRT=0x8a90e018 
Aug 02 11:17:57 localhost kernel: SMBIOS 3.1.1 present.
Aug 02 11:17:57 localhost kernel: DMI: Acer Swift SF315-52/Erdinger_KL, BIOS V1.07 09/28/2018
Aug 02 11:17:57 localhost kernel: Hypervisor detected: Xen PV
Aug 02 11:17:57 localhost kernel: tsc: Detected 1991.993 MHz processor
Aug 02 11:17:57 localhost kernel: e820: update [mem 0x00000000-0x00000fff] usable ==> reserved
Aug 02 11:17:57 localhost kernel: e820: remove [mem 0x000a0000-0x000fffff] usable
Aug 02 11:17:57 localhost kernel: last_pfn = 0x17661f max_arch_pfn = 0x400000000
Aug 02 11:17:57 localhost kernel: MTRR map: 1 entries (0 fixed + 1 variable; max 20), built from 10 variable MTRRs
Aug 02 11:17:57 localhost kernel: MTRRs set to read-only
Aug 02 11:17:57 localhost kernel: x86/PAT: Configuration [0-7]: WB  WC  UC- UC  WB  WP  UC- WT  
Aug 02 11:17:57 localhost kernel: last_pfn = 0x8afff max_arch_pfn = 0x400000000
Aug 02 11:17:57 localhost kernel: esrt: Reserving ESRT space from 0x000000008a90e018 to 0x000000008a90e050.
Aug 02 11:17:57 localhost kernel: Kernel/User page tables isolation: disabled on XEN PV.
Aug 02 11:17:57 localhost kernel: Secure boot disabled
Aug 02 11:17:57 localhost kernel: RAMDISK: [mem 0x04000000-0x065fbfff]
Aug 02 11:17:57 localhost kernel: ACPI: Early table checksum verification disabled
Aug 02 11:17:57 localhost kernel: ACPI: RSDP 0x000000008A90F000 000024 (v02 ACRSYS)
Aug 02 11:17:57 localhost kernel: ACPI: XSDT 0x000000008A90F0C8 00010C (v01 ACRSYS ACRPRDCT 01072009 AMI  00010013)
Aug 02 11:17:57 localhost kernel: ACPI: FACP 0x000000008A9413C8 000114 (v06 ACRSYS ACRPRDCT 01072009 AMI  00010013)

**Comment by RandyTheOtter** [comment]
I encounter this problem on occasion. In my case it doesn't seem to be tied to any specific qube (although I might be misremembering this, it happens once in several months). Here's the error it have thrown in journalctl today:
```
unhandled exception while calling src=b'dom0' meth=b'admin.vm.Shutdown' dest=b'win10-testing' arg=b'' len(untrusted_payload)>
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qubes/api/__init__.py", line 297, in respond
    response = await self.mgmt.execute(
               ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/api/admin.py", line 882, in vm_shutdown
    await self.dest.shutdown(force=force, wait=wait)
  File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 1362, in shutdown
    self.libvirt_domain.shutdown()
  File "/usr/lib/python3.11/site-packages/qubes/app.py", line 107, in wrapper
    return getattr(self._vm, attrname)(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib64/python3.11/site-packages/libvirt.py", line 2972, in shutdown
    raise libvirtError('virDomainShutdown() failed')
libvirt.libvirtError: internal error: Failed to shutdown domain '551' with libxenlight
```

I solve it by destroying the domain with virsh.
