### ISSUE TITLE
builerv2-github fails with IndexError

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9437]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release

R4.2

### Brief summary

Failures like in https://github.com/QubesOS/updates-status/issues/5075

### Steps to reproduce

Build a component with several target dists using builderv2-github

### Expected behavior

It builds all targets.

### Actual behavior

First target distribution works, further ones fail with:

```
12:42:34 [qb.fetch.manager] manager: source already fetched. Updating.
12:42:42 [qb.fetch.manager.fetch] copy-in (cmd): /usr/lib/qubes/qrexec-client-vm -- disp331 qubesbuilder.FileCopyIn+-2Fbuilder-2Fmanager /usr/lib/qubes/qfile-agent /home/user/builder-r4.2-dom0/sources/manager
12:42:43 [qb.fetch.manager.fetch] copy-in (cmd): /usr/lib/qubes/qrexec-client-vm -- disp331 qubesbuilder.FileCopyIn+-2Fbuilder-2Fplugins-2Ffetch /usr/lib/qubes/qfile-agent /home/user/qubes-builderv2/qubesbuilder/plugins/fetch
12:42:43 [qb.fetch.manager.fetch] Using executor qubes:disp331.
12:42:43 [qb.fetch.manager.fetch] /usr/bin/qvm-run-vm -- disp331 env -- VERBOSE=1 DEBUG=1 BACKEND_VMM=xen bash -c 'cd /builder && /builder/plugins/fetch/scripts/get-and-verify-source.py https://github.com/QubesOS/qubes-manager.git /builder/manager /builder/keyring /builder/plugins/fetch/keys --git-branch release4.2 --minimum-distinct-maintainers 1 --maintainer 0064428F455451B3EBE78A7F063938BA42CFA724 --maintainer 274E12AB03F2FE293765FC06DA0434BC706E1FCF --fetch-versions-only'
12:42:46 [qb.fetch.manager.fetch] --> Verifying tags...
12:42:46 [qb.fetch.manager.fetch] ---> Good tag 1c94038dce6cba6b4bada8970cfba0433838b4d0.
12:42:46 [qb.fetch.manager.fetch] Enough distinct tag signatures. Found 1, mandatory minimum is 1.
12:42:46 [qb.fetch.manager.fetch] --> Merging...
12:42:46 [qb.fetch.manager.fetch] copy-out (cmd): /usr/lib/qubes/qrexec-client-vm disp331 qubesbuilder.FileCopyOut+-2Fbuilder-2Fmanager /usr/bin/qfile-unpacker 1000 /home/user/builder-r4.2-dom0/sources
12:42:48 [qb.fetch.manager] Log file: /home/user/builder-r4.2-dom0/logs/20240902T124234-manager.log
12:42:48 [qb] > done
Traceback (most recent call last):
  File "/home/user/qubes-builderv2-github/github-action.py", line 1323, in <module>
    main()
  File "/home/user/qubes-builderv2-github/github-action.py", line 1308, in main
    cli.build()
  File "/home/user/qubes-builderv2-github/github-action.py", line 410, in build
    self.make_with_log(
  File "/home/user/qubes-builderv2-github/github-action.py", line 171, in make_with_log
    return self.make_with_log_qrexec(func, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/user/qubes-builderv2-github/github-action.py", line 215, in make_with_log_qrexec
    log_file = log_file_list[0].rstrip("\n")
               ~~~~~~~~~~~~~^^^
IndexError: list index out of range
```

**Comment by fepitre** [comment]
Do you have any RPC issue with `qubesbuilder.BuildLog`?

**Comment by fepitre** [comment]
I don't see anything uploaded to `https://github.com/QubesOS/build-logs42`?

**Comment by marmarek** [comment]
It was indeed a problem with logging vm. Can you improve error message?
