### ISSUE TITLE
untrusted_qdb invoked before qubesdb fully started

### ISSUE THREAD

**Issue by qubest** [QubesOS/qubes-issues#9514]
[How to file a helpful issue](https://www.qubes-os.org/doc/issue-tracking/)

### Qubes OS release
Qubes OS 4.2.0 (R4.2)

### Brief summary
During vm start `sys-gui-gpu` failed to start. After checking journalctl the following error found:
```
vm.sys-gui-gpu: Failed to list usb devices
Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/qubes/devices.py", line 349, in assignments
    devices = self._vm.fire_event('device-list-attached:' + self._bus,
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/events.py", line 195, in fire_event
    sync_effects, async_effects = self._fire_event(event, kwargs,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/events.py", line 168, in _fire_event
    effects.extend(effect)
  File "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py", line 298, in on_device_list_attached
    for dev in self.get_all_devices(vm.app):
  File "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py", line 287, in get_all_devices
    for dev in vm.devices['usb']:
  File "/usr/lib/python3.11/site-packages/qubes/devices.py", line 377, in __iter__
    return iter(self.available())
                ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/devices.py", line 373, in available
    devices = self._vm.fire_event('device-list:' + self._bus)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/events.py", line 195, in fire_event
    sync_effects, async_effects = self._fire_event(event, kwargs,
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/events.py", line 168, in _fire_event
    effects.extend(effect)
  File "/usr/lib/python3.11/site-packages/qubesusbproxy/core3ext.py", line 252, in on_device_list_usb
    if not vm.is_running() or not hasattr(vm, 'untrusted_qdb'):
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubes/vm/qubesvm.py", line 851, in untrusted_qdb
    self._qdb_connection = qubesdb.QubesDB(self.name)
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^
qubesdb.Error: (2, 'No such file or directory')
```

The error causes sys-gui-gpu to restart and get new `xid`. Some vms might start before sys-gui-gpu and uses the old `qubes-gui-domain-xid`. As a result, `qubes-gui-agent` run with unsynced `qubes-gui-domain-xid`.

After tracing the error `untrusted_qdb` is used at [core3ext](https://github.com/QubesOS/qubes-app-linux-usb-proxy/blob/8c67d72f8c6d3df79d477c8a0bf4db819ee1708a/qubesusbproxy/core3ext.py#L527). which might be invoked before starting [`qubesdb`](https://github.com/QubesOS/qubes-core-admin/blob/065c6e4eb6c6eb18c9991d3178c8447100bbe6a4/qubes/vm/qubesvm.py#L1272)

I tried to add a check at [`untrusted_qdb`](https://github.com/QubesOS/qubes-core-admin/blob/065c6e4eb6c6eb18c9991d3178c8447100bbe6a4/qubes/vm/qubesvm.py#L867) for the sock file `/var/run/qubes/qubesdb.sys-gui-gpu.sock` created by `qubesdb` to make sure it started before anyone tries to invoke it. After adding the check the error didn't appear again.

### Steps to reproduce
Occurs randomly 

### Expected behavior
sys-gui-gpu starts normally and gui-agent in appvms run with correct xid

### Actual behavior
sys-gui-gpu restart once which causes gui-agents in appvm to run with wrong gui-domain-xid

**Comment by ben-grande** [comment]
Please retest on R4.3.

**Comment by jeremy-hawkins** [comment]
Affects 4.3. Same root cause, different caller, on Qubes release 4.3.1 (`qubes-core-dom0-4.3.51-1.fc41`).

`qubes/ext/audio.py` `on_domain_start` (line 159) selects consumers with `domain.is_running()`, then calls `attached_vm.untrusted_qdb.write(...)` (line 162). At boot, `sys-audio` (autostart, `default_audiovm`) reached `domain-start` while 12 other autostart qubes were starting in parallel. Several of them were already running to libvirt but had no QubesDB socket yet (yubico's "Starting Qubes DB" is logged 37 ms before the failure). `untrusted_qdb` raised ENOENT, the exception went unhandled in the `domain-start` handler, and qubesd killed `sys-audio`:

```
Sep 22 08:53:53.062732 dom0 qubesd[2137]: INFO: vm.yubico: Starting Qubes DB
Sep 22 08:53:53.099986 dom0 qubesd[2137]: ERROR: vm.sys-audio: Start failed: (2, 'No such file or directory')
Sep 22 08:53:56.104925 dom0 qubesd[2137]: ERROR: unhandled exception while calling src=b'dom0' meth=b'admin.vm.Start' dest=b'sys-audio' arg=b'' len(untrusted_payload)=0
Traceback (most recent call last):
  File "/usr/lib/python3.13/site-packages/qubes/api/__init__.py", line 339, in respond
    response = await self.mgmt.execute(
        untrusted_payload=untrusted_payload
    )
  File "/usr/lib/python3.13/site-packages/qubes/api/admin.py", line 967, in vm_start
    await self.dest.start()
  File "/usr/lib/python3.13/site-packages/qubes/vm/qubesvm.py", line 1564, in start
    await self.fire_event_async(
        "domain-start", start_guid=start_guid
    )
  File "/usr/lib/python3.13/site-packages/qubes/events.py", line 235, in fire_event_async
    sync_effects, async_effects = self._fire_event(
        event, kwargs, pre_event=pre_event
    )
  File "/usr/lib/python3.13/site-packages/qubes/events.py", line 170, in _fire_event
    effect = func(self, event, **kwargs)
  File "/usr/lib/python3.13/site-packages/qubes/ext/audio.py", line 162, in on_domain_start
    attached_vm.untrusted_qdb.write(
  File "/usr/lib/python3.13/site-packages/qubes/vm/qubesvm.py", line 1095, in untrusted_qdb
    self._qdb_connection = qubesdb.QubesDB(self.name)
qubesdb.Error: (2, 'No such file or directory')
```

It is intermittent: it depends on whether a consumer is inside that window when the audiovm finishes starting. Skipping consumers whose QubesDB is not up yet would be safe for the audio case, since `on_domain_qdb_create` (line 139) already writes `/qubes-audio-domain-xid` when the consumer's QubesDB comes up. Guarding centrally in `untrusted_qdb`, as proposed above, would cover both callers.

Workaround: a `Restart=on-failure` / `RestartSec=15` drop-in on `qubes-vm@sys-audio.service`.

**Comment by ben-grande** [comment]
For R4.4, there is a change to avoid it raising `qubesdb.Error` exception, so it will return `None`, and you can skip setting the entry in that case. When the client qube is ready, it will set the qubesdb entry.

- https://github.com/QubesOS/qubes-core-admin/blob/42db306045af848ede9f3c7283ea60e036425b37/qubes/vm/qubesvm.py#L1177
- https://github.com/QubesOS/qubes-core-admin/blob/42db306045af848ede9f3c7283ea60e036425b37/qubes/ext/audio.py#L141

Would you like to submit a PR?
