### ISSUE TITLE
qmemman inflating a qube not in need, starving the system

### ISSUE THREAD

**Issue by ydirson** [QubesOS/qubes-issues#9627]
Qubes OS release: 4.2

### symptoms

After running for "a long time" (more than a week, in this case it happened after 13d uptime), it gets impossible for me to launch any new VM.  When running from the GUI the situation is a bit confusing:

`journalctl` shows:
```
internal error: libxenlight failed to create new domain
```

With additionally various complaints about lack of memory.  The following may be of interest:

```
Dec 05 22:59:53 dom0 libvirtd[47037]: internal error: libxenlight failed to create new domain 'disp6819'
Dec 05 22:59:53 dom0 qubesd[2378]: vm.disp6819: Start failed: internal error: libxenlight failed to create new domain 'disp6819'
Dec 05 22:59:55 dom0 qubesd[2378]: Removing appmenus for 'disp6819' in 'dom0'
Dec 05 22:59:55 dom0 qmemman.systemstate[2375]: Xen free = 515664944 too small for satisfy assignments! assigned_but_unused=520440604, domdict={'0': {'memory_current': 4240236544, 'memory_actual': 4294967296, 'memory_maximum': 4294967296, 'mem_used': 2638827520, 'id': '0', 'last_target': 4294967296, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': False}, '3': {'memory_current': 941056000, 'memory_actual': 1026011383, 'memory_maximum': 4194304000, 'mem_used': 331497472, 'id': '3', 'last_target': 1026011383, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': True}, '5': {'memory_current': 297840640, 'memory_actual': 297840640, 'memory_maximum': 314572800, 'mem_used': None, 'id': '5', 'last_target': 297795584, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': False}, '6': {'memory_current': 150994944, 'memory_actual': 150994944, 'memory_maximum': 150994944, 'mem_used': None, 'id': '6', 'last_target': 150994944, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': False}, '9': {'memory_current': 1379766272, 'memory_actual': 1467832325, 'memory_maximum': 4194304000, 'mem_used': 545517568, 'id': '9', 'last_target': 1467832325, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': True}, '11': {'memory_current': 2856976384, 'memory_actual': 2955095759, 'memory_maximum': 6291456000, 'mem_used': 1265954816, 'id': '11', 'last_target': 2955095759, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': True}, '12': {'memory_current': 4120576000, 'memory_actual': 4227287413, 'memory_maximum': 10485760000, 'mem_used': 1882210304, 'id': '12', 'last_target': 4227287413, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': True}, '51': {'memory_current': 402698240, 'memory_actual': 402698240, 'memory_maximum': 419430400, 'mem_used': None, 'id': '51', 'last_target': 402653184, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': False}, '52': {'memory_current': 150994944, 'memory_actual': 150994944, 'memory_maximum': 150994944, 'mem_used': None, 'id': '52', 'last_target': 150994944, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': False}, '53': {'memory_current': 948469760, 'memory_actual': 1036327388, 'memory_maximum': 4194304000, 'mem_used': 336494592, 'id': '53', 'last_target': 1036327388, 'use_hoplug': False, 'no_progress': False, 'slow_memset_react': False, 'use_hotplug': True}}
```

From the CLI however the user gets more useful feedback clearly pointing to a lack of memory:

```
[dom0 ~]$ qvm-run --dispvm=debian-dvm xterm
Running 'xterm' on $dispvm:debian-dvm
$dispvm:debian-dvm: Start failed: internal error: libxenlight failed to create new domain 'disp8732', see /var/log/libvirt/libxl/libxl-driver.log for details
Traceback (most recent call last):
  File "/usr/bin/qvm-run", line 5, in <module>
    sys.exit(main())
             ^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/tools/qvm_run.py", line 358, in main
    dispvm.cleanup()
  File "/usr/lib/python3.11/site-packages/qubesadmin/vm/__init__.py", line 427, in cleanup
    self.kill()
  File "/usr/lib/python3.11/site-packages/qubesadmin/vm/__init__.py", line 123, in kill
    self.qubesd_call(self._method_dest, 'admin.vm.Kill')
  File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 76, in qubesd_call
    return self.app.qubesd_call(dest, method, arg, payload,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/app.py", line 789, in qubesd_call
    return self._parse_qubesd_response(return_data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/site-packages/qubesadmin/base.py", line 111, in _parse_qubesd_response
    raise exc_class(format_string, *args)
qubesadmin.exc.QubesVMNotFoundError: No such domain: 'disp8732'
```

```
2024-12-05 22:32:17.892+0000: libxl: libxl_create.c:770:libxl__domain_make: domain creation fail: Cannot allocate memory
2024-12-05 22:32:17.892+0000: libxl: libxl_create.c:1372:initiate_domain_create: cannot make domain: -3
```

I can't say for sure this started with the upgrade to 4.2 but this is quite systematic each time I leave the system running for such a long time.

Usually in a hurry to use the computer I only had a reboot to get things straight again.

### investigation

What I see right now is one VM (a HVM one in this case) getting a lot of free RAM, but `qmemman` refuses to reclaim it:

```
[dom0 ~]$ xenstore-ls /local/domain/12/memory
static-max = "4130953"
target = "4114569"
videoram = "0"
meminfo = "1838096"
hotplug-max = "10240000"

guest$ free
               total        used        free      shared  buff/cache   available
Mem:         4051436     1393932     1792600       33256     1181824     2657504
Swap:        1048572      583520      465052
```

If I stop qmemman I can direct the guest's balloon driver to inflate:

```
[dom0 ~]$ systemctl stop qubes-qmemman
[dom0 ~]$ xenstore-write /local/domain/12/memory/target 2000000
[dom0 ~]$ xenstore-ls /local/domain/12/memory
static-max = "4130953"
target = "2000000"
videoram = "0"
meminfo = "1796012"
hotplug-max = "10240000"

guest$ free
               total        used        free      shared  buff/cache   available
Mem:         1936868     1342260      235328       32972      683056      594608
Swap:        1048572      603432      445140
```

But then Qubes won't start a new VM because of qmemman missing, but as soon as I start it again it reflates the balloon again and launching a new VM fails again for lack of memory:

```
[dom0 ~]$ systemctl start qubes-qmemman

guest$ free
               total        used        free      shared  buff/cache   available
Mem:         4011536     1345732     2306120       32972      683288     2665804
Swap:        1048572      603432      445140
```

When memman is running, although I can see the xenstore key keeping the value for ~1sec when I change it, that does not appear to be enough to launch a VM after qmemman sets it back.

**Comment by marmarek** [comment]
Looks very similar to https://github.com/QubesOS/qubes-issues/issues/9431, let me backport the fix.

**Comment by ydirson** [comment]
Thanks, testing this!

**Comment by ydirson** [comment]
Right now, I'm getting `Not enough memory to start domain` while 2 domains have 1GiB free each.

**Comment by marmarek** [comment]
> 1GiB free each.

Also according to meminfo-writer? As in - is "meminfo" xenstore value 1GiB below its current "target"?
Do you see relevant qmemman log lines in dom0? It should print stats what it tried to reclaim.

**Comment by ydirson** [comment]
Current situation:
* largest VM has 2GiB free, and that seems properly reported by `meminfo-writer`:
  ```
user@work-vates:~$ xenstore ls memory
static-max = "9200871"
target = "9184487"
videoram = "0"
meminfo = "7164948"
hotplug-max = "10240000"
user@work-vates:~$ free
               total        used        free      shared  buff/cache   available
Mem:         9121344     6398568     2172556      246636     1107704     2722776
Swap:        1048572     1039388        9184
  ```
* qmemman does not report much things of interest around the time this happens.
* I see yesterday it reported a few lines like this (apparently following a request for dom 9 to inflate the balloon which was not immediately honored):
  ```
Jan 16 19:24:40 dom0 qmemman.systemstate[2799]: Xen free = 183875166 too small for satisfy assignments! assigned_but_unused=160256380, domdict={
    '0': {'memory_current': 4278190080, 'memory_actual': 4294967296, 'memory_maximum': 4294967296, 'mem_used': 2244210688, 'id': '0', 'last_target': 4294967296, 'use_hotplug': False, 'no_progress': False, 'slow_memset_react': False},
    '3': {'memory_current': 612786176, 'memory_actual': 629499634, 'memory_maximum': 4194304000, 'mem_used': 327782400, 'id': '3', 'last_target': 629499634, 'use_hotplug': True, 'no_progress': False, 'slow_memset_react': False},
    '8': {'memory_current': 939393024, 'memory_actual': 975763505, 'memory_maximum': 2097152000, 'mem_used': 520937472, 'id': '8', 'last_target': 975763505, 'use_hotplug': True, 'no_progress': False, 'slow_memset_react': False},
    '9': {'memory_current': 7381528576, 'memory_actual': 7398243498, 'memory_maximum': 10485760000, 'mem_used': 4060315648, 'id': '9', 'last_target': 7398243498, 'use_hotplug': True, 'no_progress': False, 'slow_memset_react': False},
    '11': {'memory_current': 1058623488, 'memory_actual': 1097183854, 'memory_maximum': 4194304000, 'mem_used': 588668928, 'id': '11', 'last_target': 1097183854, 'use_hotplug': True, 'no_progress': False, 'slow_memset_react': False},
    '17': {'memory_current': 402698240, 'memory_actual': 402698240, 'memory_maximum': 419430400, 'mem_used': None, 'id': '17', 'last_target': 402653184, 'use_hotplug': False, 'no_progress': False, 'slow_memset_react': False},
    '18': {'memory_current': 150994944, 'memory_actual': 150994944, 'memory_maximum': 150994944, 'mem_used': None, 'id': '18', 'last_target': 150994944, 'use_hotplug': False, 'no_progress': False, 'slow_memset_react': False},
    '19': {'memory_current': 620666880, 'memory_actual': 655786817, 'memory_maximum': 4194304000, 'mem_used': 342446080, 'id': '19', 'last_target': 655786817, 'use_hotplug': True, 'no_progress': False, 'slow_memset_react': False},
    '22': {'memory_current': 297840640, 'memory_actual': 297840640, 'memory_maximum': 314572800, 'mem_used': None, 'id': '22', 'last_target': 297795584, 'use_hotplug': False, 'no_progress': False, 'slow_memset_react': False},
    '23': {'memory_current': 150994944, 'memory_actual': 150994944, 'memory_maximum': 150994944, 'mem_used': None, 'id': '23', 'last_target': 150994944, 'use_hotplug': False, 'no_progress': False, 'slow_memset_react': False}
}
  ```

It really seems to insist on that guest staying at 2GiB free / 3GiB avail 🤔

**Comment by marmarek** [comment]
So, free memory is distributed among running VMs first to satisfy their used memory (meminfo xenstore key, mem_used in the log), and remaining is distributed proportionally to their maxmem (memory_maximum in the log). So, if you have enough ram, it's expected that large VM (according to maxmem) get more extra RAM.

But that extra RAM should still be reclaimed for starting new VMs...

**Comment by ydirson** [comment]
Current occurrence (system was "behaving badly", after only 3d uptime) I decided to restart `sys-usb` for some reason.  Now the system refuses to launch `sys-usb` again.
- `sys-usb` is configured with 300MB initial RAM
- `xl top` reports 165MB free
- the usual big qube has `free` reporting 632MB free, 1GB available (and only 40% of the 1GB swap used)
- `meminfo-writer` actually reports 5389976 total used with a MemTotal of 6440628: shouldn't that be enough for `qmemman` to deflate that domain a bit and start the new qube?

**Comment by ydirson** [comment]
Here it goes again.
`xentop` sorted for the largest 3 VMs:
```
Mem: 16145912k total, 15964332k used, 181580k free    CPUs: 8 @ 2894MHz
      NAME  STATE   CPU(sec) CPU(%)     MEM(k) MEM(%)  MAXMEM(k) MAXMEM(%) VCPUS NETS NETTX(k) NETRX(k) VBDS   VBD_OO   VBD_RD   VBD_WR  VBD_RSECT  VBD_WSECT SSID
  Domain-0 -----r      56867   11.9    4111540   25.5    4128944      25.6     8    0        0        0    0        0        0        0          0          0    0
         P --b---      61522   12.9    3853900   23.9    3871244      24.0     2    0        0        0    4        0  6460318  2037829  374765303   77586976    0
         W --b---      98337    1.8    2644900   16.4    2662244      16.5     4    0        0        0    4        0  6009888  5160281  375444782  532969984    0
         D -----r      26174    1.7    1886480   11.7    1903824      11.8     8    0        0        0    4        0  7914651  1094099 1105098989   40471528    0
```
in `P`:
```
               total        used        free      shared  buff/cache   available
Mem:         3867236     1907224     1682532      112264      476288     1960012
Swap:        1048572      670608      377964
```
in `W`:
```
               total        used        free      shared  buff/cache   available
Mem:         2549476     1262460      668376       28948      979040     1287016
Swap:        1048572      552368      496204
```
in `D`:
```
               total        used        free      shared  buff/cache   available
Mem:         1803472      801712       79048         332     1004732     1001760
Swap:        1048572      335256      713316
```

Pretty sure it would be possible to deflate those to make room for a new VM :)
All of them do use a bit of swap space, but that does not seem much compared to the free memory.
So it's finally time to make that test @marmarek suggested previously: `swapoff -a` on all three VMs...

... and then all of a sudden there's no problem to start a new qube (even several of them, actually)
