### ISSUE TITLE
[Build 202412140459-4.3] start_standalone_with_cdrom_vm test fails on system installed in legacy boot mode

### ISSUE THREAD

**Issue by marmarek** [QubesOS/qubes-issues#9645]
## Observation

openQA test in scenario qubesos-4.3-kernel-x86_64-system_tests_basic_vm_qrexec_gui@hw6 fails in
[TC_00_Basic](https://openqa.qubes-os.org/tests/122222/modules/TC_00_Basic/steps/4)

```
grub2-mkimage: error: cannot open `/usr/lib/grub/x86_64-efi/moddep.lst': No such file or directory.
...
ERROR: qubes.tests.integ.basic/TC_00_Basic/test_120_start_standalone_with_cdrom_dom0
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python3.13/contextlib.py", line 85, in inner
    return func(*args, **kwds)
  File "/usr/lib/python3.13/site-packages/qubes/tests/integ/basic.py", line 102, in test_120_start_standalone_with_cdrom_dom0
    iso_path = self.create_bootable_iso()
  File "/usr/lib/python3.13/site-packages/qubes/tests/__init__.py", line 1547, in create_bootable_iso
    subprocess.check_call(
    ~~~~~~~~~~~~~~~~~~~~~^
        [
        ^
    ...<11 lines>...
        stdout=v,
        ^^^^^^^^^
    )
    ^
  File "/usr/lib64/python3.13/subprocess.py", line 419, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['grub2-mkimage', '-O', 'x86_64-efi', '-d', '/usr/lib/grub/x86_64-efi', '-p', '/boot/grub2', 'iso9660', 'disk', 'halt']' returned non-zero exit status 1.
```

## Reproducible

Fails since (at least) Build [202412140459-4.3](https://openqa.qubes-os.org/tests/122222) (current job)

## Expected result

Last good: [202411110019-4.3](https://openqa.qubes-os.org/tests/118609) (or more recent)

## Further details

Always latest result in this scenario: [latest](https://openqa.qubes-os.org/tests/latest?arch=x86_64&distri=qubesos&flavor=kernel&machine=hw6&test=system_tests_basic_vm_qrexec_gui&version=4.3)

**Comment by marmarek** [comment]
The `start_standalone_with_cdrom_vm` test tries to boot a VM from a CDROM via SeaBIOS (legacy boot), yet it fails due to not finding grub's efi modules. It shouldn't need them in this test...

The `start_uefi` fails too, but it's kinda expected (relevant grub modules needs to be installed manually).
